### PR TITLE
change(ios): adds null guard within insertText with logs for mystery error

### PR DESCRIPTION
**Pull request by jahorton**
Seeks to prevent outright-crashes of the FV app due to #5300.

While Sentry event logging is included here... note that we don't currently have Sentry integrated within the iOS FV app.  Without that, we're not going to be receiving any additional information about what's causing the underlying errors.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> note that we don't currently have Sentry integrated within the iOS FV app.

Can we add it?

**Comment by jahorton** [comment]
> > note that we don't currently have Sentry integrated within the iOS FV app.
> 
> Can we add it?

Shouldn't be too tricky to do.  Makes me wonder if it not being done was an accidental omission - is it in place for the Android FV app?

**Comment by mcdurdin** [comment]
> is it in place for the Android FV app?

It is. Let's do it for iOS, looks like an accidental omission as you say.

**Comment by mcdurdin** [comment]
Brought up to date with 16.0.1-alpha.

**Comment by mcdurdin** [comment]
Will revisit when we look at errors in the future

**Pull request closed without merging**
