### PR TITLE
chore(developer): change field label to 'Related Package ID' in Related Packages dialog

### LINKED ISSUE #9853: chore(developer): Change field label in Related Packages dialog to `Related Package ID:`
I wonder if it would be better to change the field label to `Related Package ID:`. Initially I thought this is the package id of the package I'm currently editing.

_Originally posted by @ermshiperete in https://github.com/keymanapp/help.keyman.com/pull/843#discussion_r1371333970_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #9853.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by jahorton — COMMENTED** [review]
What's with the changes to the width and left... fields?... here?

**Comment by mcdurdin** [comment]
> What's with the changes to the width and left... fields?... here?

Just moves the element to make room for the longer field description

**Review by rc-swag — APPROVED** [review]
lgtm

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.204-alpha](https://keyman.com/downloads/releases/alpha/17.0.204)

**Pull request merged**
