### PR TITLE
fix(linux): Fix shared keyboard (un-)installation in Bionic

### LINKED ISSUE #6564: bug(linux): TypeError: __init__() got an unexpected keyword argument 'capture_output'
Crash in Bionic because Python 3.6 doesn't support capture_output parameter on `subprocess.run`.

Sentry Issue: [KEYMAN-LINUX-1Z](https://sentry.io/organizations/keyman/issues/3223036278/?referrer=github_integration)

```
TypeError: __init__() got an unexpected keyword argument 'capture_output'
  File "python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "keyman_config/gsettings.py", line 69, in get
    capture_output=True)
  File "keyman_config/gnome_keyboards_util.py", line 13, in read_input_sources
    sources = self.input_sources.get('sources')
  File "keyman_config/install_kmp.py", line 253, in _install_keyboards_to_gnome
    sources = gnomeKeyboardsUtil.read_input_sources()
  File "keyman_config/install_kmp.py", line 233, in install_keyboards
    return self._install_keyboards_to_gnome(keyboards, packageDir, language)
...
(6 additional frame(s) were not displayed)

TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

This happened while running: `/usr/bin/km-package-uninstall -s hieroglyphic`
and `/usr/bin/km-package-install -s -f $HOME/.cache/keyman/hieroglyphic.kmp`.

### PR DESCRIPTION
**Pull request by ermshiperete**
Ubuntu 18.04 Bionic comes with an older Python version (3.6) that
doesn't support the `capture_output` parameter on `subprocess.run`
which leads to a crash when installing or uninstalling keyboads to
the shared area. This change works around the problem by calling
a different method on Bionic.

Fixes #6564.

# User Testing

## Preparations

- The tests should be run on:
  - **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot

- Download `hieroglyphic.kmp` by running `km-package-get hieroglyphic`

## Tests

- **TEST_CLI_INST_SHARED:** Run `sudo km-package-install -s -f ~/.cache/keyman/hieroglyphic.kmp`. Verify that this adds the "Hieroglyphic" keyboard for ancient Egyptian to the keyboard dropdown.
- **TEST_CLI_UNINST_SHARED:** Run `sudo km-package-uninstall -s hieroglyphic`
  - Verify that this removes the "Hieroglyphic" keyboard from the keyboard dropdown
  - Verify that the folder `/usr/local/share/keyman/hieroglyphic` no longer exists

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_CLI_INST_SHARED (FAILED):** Tested this with the attached PR build (Keyman 15.0.240-beta) in Bionic OS and I got a crash after running the mentioned command.

 

* **TEST_CLI_UNINST_SHARED (PASSED):** After running the mentioned command the Hieroglyphic keyboard has been removed from the .local\share\keyman folder. Seems to be working fine.

**Comment by ermshiperete** [comment]
I think the crash reported in the failed test is unrelated. @bharanidharanj Would you please try again?

@keymanapp-test-bot retest TEST_CLI_INST_SHARED

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.241-beta](https://keyman.com/downloads/releases/beta/15.0.241)

**Pull request merged**
