### PR TITLE
chore(common): Bump crowdin github action to 1.3.2

### PR DESCRIPTION
**Pull request by darcywong00**
The crowdin [workflow](https://github.com/keymanapp/keyman/actions/workflows/crowdin.yml) started failing 2 months ago with the error:
> null: Unrecognized field "customSegmentation" (class com.crowdin.client.sourcefiles.model.OtherFileImportOptions), not marked as ignorable (one known property: "contentSegmentation"])

This is fixed by bumping the crowdin GHA which updates crowdin-cli (fixed in version 3.6.4)

See https://github.com/crowdin/crowdin-cli/issues/379

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
Did the workflow raise errors? Wondering why we weren't notified of the error?

**Review by mcdurdin — APPROVED** [review]

**Comment by darcywong00** [comment]
> Did the workflow raise errors? Wondering why we weren't notified of the error?

I don't think the GHA does any notification of pass/fail.

I only realized cause my forked repo (which doesn't have keys) got notified the inactive GHA would be disabled.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.125-alpha](https://keyman.com/downloads/releases/alpha/17.0.125)

**Comment by mcdurdin** [comment]
> I don't think the GHA does any notification of pass/fail.

Is there any way we can raise a notification on failure? It's not good for errors to be silently swallowed.

**Pull request merged**
