### PR TITLE
fix(windows): Improve refresh performance

### PR DESCRIPTION
**Pull request by mcdurdin**
When a keyboard is installed, Keyman will now only refresh its internal state on a given thread when that thread receives focus and/or input, rather than immediately. This will dramatically reduce the chatter caused by Keyman Engine when a keyboard is installed or settings are changed.

# User testing

@MakaraSok, after installing this version, we need to verify that keyboards are correctly activated and usable in a target application after installing the keyboard, or when any settings are changed.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
Trying to download the exe build for this PR, but it is too slow:
image

Is there other way to get the build faster than this? It looks like this is slow only from this particular source, but I can download the beta version with a normal "faster" speed from keyman.com.

**Comment by mcdurdin** [comment]
> Trying to download the exe build for this PR, but it is too slow:

Unfortunately I don't know of any way you can speed this up -- it's related to your local Internet connection and that server not having CDN-style caching. If you like, you can wait for the PR to merge and try again?

**Comment by MakaraSok** [comment]
I suppose this merge will be built tonight, so the test will be done tomorrow morning.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.215-beta](https://keyman.com/downloads/releases/beta/14.0.215)

**Comment by MakaraSok** [comment]
Confirmed it works as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)

**Pull request merged**
