### PR TITLE
fix(windows): Add invalidate context action to non-updatable parse

### LINKED ISSUE #7078: bug(windows): Context is not reset on "Enter/Return"
**Describe the bug**
The `context`  for matching rules is not reset when return is pressed. The result is that if the key pressed on the new line plus the characters and the end of the previous line match the output can remove the CR and move the cursor to the previous line. 

**To Reproduce**

1. Installed Ethiopic - (Language Neutral) keyboard
2. Opened Notepad 
3. Typed: <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd><kbd>Enter</kbd><kbd>a</kbd>
  Received: 
"አስድፍፋ"
  Expected: 
"አስድፍ
አ"

 Windows 15.0.268

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes #7078 

Rename ProcessActionsTestParse to NonUpdatable parse as it does more than just test. Add handling for the invalidate context action to this parse. In the case when an emit keystroke is in the action list it will be emitted and the Updateable round will never occur so we need to invalidate the context now in the non-updatable parse.

# User Testing

Install the keyman for windows build associated with this PR
The key referred to as "enter" also has key cap labelled "return" on many keyboards.
**TEST_ENTER_INVALIDATE**
1. Install gff_ethiopic_7 from Keyman.com [Ethiopic - (Language Neutral)](https://keyman.com/keyboards/gff_ethiopic_7) 
2. Open Notepad
3. Select  Ethiopic - (Language Neutral) as the current keyboard.
4. Type <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd><kbd>Enter</kbd><kbd>a</kbd>

Expected Result: 
"አስድፍ
አ"

Keyboards for the following test are found in the zip file [7077_test_keyboards.zip](https://github.com/keymanapp/keyman/files/9371509/7077_test_keyboards.zip) . Reusing keyboards from PR#7077
**TEST_OUTPUT_KEYSTROKE**
1. Install [043 - output and keystroke.kmx](https://github.com/keymanapp/keyman/files/9371509/7077_test_keyboards.zip)
2. Open Notepad
3. Select  043 - output and keystroke.kmx as the current keyboard.
4. Type <kbd>1</kbd><kbd>2</kbd><kbd>3</kbd>
Expected Result: "abd3"

**TEST_OUTPUT_KEYSTROKE_INVALID_CONTEXT**

1. If not installed from the previous test - Install [043 - output and keystroke.kmx](https://github.com/keymanapp/keyman/files/9371509/7077_test_keyboards.zip)
2. Open Notepad
3. Select  043 - output and keystroke.kmx as the current keyboard.
4. Type <kbd>1</kbd><kbd>2</kbd><kbd>Enter</kbd><kbd>3</kbd>
Expected Result: 
"abc
3"

**TEST_DEADKEY_AND_CONTEXT**
1. Install [045 - deadkey and context.kmx](https://github.com/keymanapp/keyman/files/9371509/7077_test_keyboards.zip)
2. Open Notepad
3. Select  045 - deadkey and context.kmx as the current keyboard.
4. Type <kbd>y</kbd><kbd>z</kbd><kbd>Shift</kbd>+<kbd>/</kbd>
Expected Result: "correct"

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by bharanidharanj** [comment]
* **TEST_ENTER_INVALIDATE (FAILED):** Tested this as per the instructions and it seems that the expected output differs from the actual output. 
   

* **TEST_OUTPUT_KEYSTROKE (PASSED):** Tested this as per the instructions and it is working as expected. 
* **TEST_OUTPUT_KEYSTROKE_INVALID_CONTEXT (PASSED):** Tested this as per the instructions and it is working as expected. 
* **TEST_DEADKEY_AND_CONTEXT (PASSED):** Tested this as per the instructions and it is working as expected.

**Comment by rc-swag** [comment]
My mistake @bharanidharanj  I put in the wrong test keys to type.  I have updated the test input keys.  Please retest

@keymanapp-test-bot retest [TEST_ENTER_INVALIDATE]

**Comment by bharanidharanj** [comment]
> My mistake @bharanidharanj I put in the wrong test keys to type. I have updated the test input keys. Please retest
> 
> @keymanapp-test-bot retest TEST_ENTER_INVALIDATE

@rc-swag Okay. I will retest.

**Comment by bharanidharanj** [comment]
* **TEST_ENTER_INVALIDATE (OPEN):** Retested with the latest Ethiopic Keyboard and it is working as expected. Thanks, Ross!

**Comment by mcdurdin** [comment]
Note: this needs a cherry-pick to `stable-15.0` 🍒

**Pull request merged**
