### PR TITLE
feat(ios):  Deeplink into Keyman settings for system keyboard setup

### PR DESCRIPTION
**Pull request by jahorton**
While investigating a different issue, we recently came across https://developer.apple.com/documentation/uikit/uiapplication/1623042-opensettingsurlstring.  A bit of investigation later, and it turns out that as of iOS 11, it's possible to set Keyman as system keyboard _through_ the Keyman settings submenu - making this a much simpler way to enable the system keyboard for compatible devices.

On older devices, though...

Screen Shot 2020-01-30 at 9 44 39 AM

So, as a result, we maintain the status quo for 10.0 and before:

Screen Shot 2020-01-30 at 9 35 13 AM

Screen Shot 2020-01-30 at 9 35 18 AM

But for 11.0+, we can get fancy:

Screen Shot 2020-01-30 at 9 36 56 AM

Screen Shot 2020-01-30 at 9 37 04 AM

(Please ignore the version string - this was generated outside of our CI pipeline that manages the actual alpha/beta/release versions.)

Screen Shot 2020-01-30 at 9 37 10 AM

While yes, this doesn't suggest that users "Allow Full Access", it doesn't appear to be needed on iOS (11.0+, at least) anyway - our App Groups usage here seems to provide all that's needed, as the system keyboard updates appropriately without it enabled.

------

Of course, if we want to be a little more explicit, we can always do something like seen here: https://www.natashatherobot.com/ios-taking-the-user-to-settings/  

I feel like that's adding an unnecessary extra 'click' though, and it's considerable extra work to add and design such a screen.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> While yes, this doesn't suggest that users "Allow Full Access", it doesn't appear to be needed on iOS (11.0+, at least) anyway - our App Groups usage here seems to provide all that's needed, as the system keyboard updates appropriately without it enabled.

Is this really true? Because it was certainly required in earlier versions. Can we find any reference to this (really great) change in iOS?

**Comment by mcdurdin** [comment]
Note: the docs will be out-of-sync for iOS 11+ users with this change. How can we make this change consistently presented to them without making them needlessly complex?

**Comment by jahorton** [comment]
> > While yes, this doesn't suggest that users "Allow Full Access", it doesn't appear to be needed on iOS (11.0+, at least) anyway - our App Groups usage here seems to provide all that's needed, as the system keyboard updates appropriately without it enabled.
> 
> Is this really true? Because it was certainly required in earlier versions. Can we find any reference to this (really great) change in iOS?

I made sure to double-check that on 11.x and 13.x, though within the Simulator.  From fresh wipes, without ever enabling that setting, the system keyboards had no issues with content synchronization.

**Comment by jahorton** [comment]
> Note: the docs will be out-of-sync for iOS 11+ users with this change. How can we make this change consistently presented to them without making them needlessly complex?

Are we referring to the online docs?  Note that the old way to setup the keyboards is still perfectly valid; the new way is simply shorter and simpler.  If someone follows the existing help.keyman.com notes, that's fine.

**Comment by jahorton** [comment]
> Is this really true? Because it was certainly required in earlier versions. Can we find any reference to this (really great) change in iOS?

I can't really speak to... uh, whatever the old behavior was, but this is what I found after a bit of code & online investigation.

Storage.swift, line 29:
``` 
guard let url = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: groupID),
```
This is the core of KMEI's `Storage.shared`, which houses all app data and settings, with this particular line is used to access the common app-group file storage area.  According to [Apple's documentation](https://developer.apple.com/documentation/foundation/filemanager/1412643-containerurl), this is an iOS 7.0+ method - so it probably got introduced into the codebase when @gabrielwong converted the app from Obj-C to Swift.

Since both the app and the extension are in the same app group, they both have full read-and-write rights to the files contained therein, with no need to "Allow Full Access" to the extension.  It sounds like the App Groups 'capability', along with our settings & file organization scheme, is enough for what the keyboard needs.

**Comment by mcdurdin** [comment]
I found the following:

https://apple.stackexchange.com/a/148104

**Pull request merged**
