### PR TITLE
chore(mac): fix corrupt installer 🍒

### PR DESCRIPTION
**Pull request by mcdurdin**
Cherry-pick of #8565 to stable-16.0.

# User Testing

TEST_INSTALL: Download and attempt to install. It should install.

### CODE REVIEW

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_INSTALL (PASSED):** The app installed successfully.

**Review by rc-swag — APPROVED** [review]
LGTM

**Review by rc-swag — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.141](https://keyman.com/downloads/releases/stable/16.0.141)

**Pull request merged**
