### PR TITLE
fix(web): enhances integrated test stability

### PR DESCRIPTION
**Pull request by jahorton**
This corresponds to an occasionally-seen test failure error from the build logs in which we'd get an error corresponding to this block of code:

https://github.com/keymanapp/keyman/blob/f5b28aa0bfc003d0913e0935f036e37860af13aa/web/src/app/browser/src/contextManager.ts#L533-L536

The error would match line 533, stating an inability to read the `keyboard` field due to `_kmwAttachment` being null / undefined.

The actual trigger:

https://github.com/keymanapp/keyman/blob/f5b28aa0bfc003d0913e0935f036e37860af13aa/web/src/app/browser/src/context/pageIntegrationHandlers.ts#L81-L91

This event handler is called on `page` events, rather than events related to attached elements.  But... on line 87, it calls a method that relates to attached elements... and so a niche case related to management of _recently-attached_ elements had slipped through the cracks until now.

Discovered during work on #9657 and #9690.  I've gone ahead and included its changes there, but this is easy enough to 🍒 out of the feature branch and make its own PR here.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
You need to update your master branch locally... iOS builds failing due to expired certificate.

**Comment by mcdurdin** [comment]
Can you add a link to a build which failed before this fix?

**Comment by jahorton** [comment]
> Can you add a link to a build which failed before this fix?

That would take some hunting.  It's something I've sporadically seen in the past, but I don't remember seeing it within the past week.  If you want me to spend that time, I can... but I figure it's effort best spent elsewhere at this point.

**Comment by mcdurdin** [comment]
> That would take some hunting. It's something I've sporadically seen in the past, but I don't remember seeing it within the past week. If you want me to spend that time, I can... but I figure it's effort best spent elsewhere at this point.

I'd appreciate it because right now I don't know what this is fixing.

**Review by mcdurdin — APPROVED** [review]
LGTM? It's a little hard to be clear on the exact sequence of events and the complex web of event handlers but it's basically a race condition, yeah?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.196-alpha](https://keyman.com/downloads/releases/alpha/17.0.196)

**Pull request merged**
