### PR TITLE
[Developer] Replace ACE editor with Monaco

### PR DESCRIPTION
**Pull request by mcdurdin**
This PR is most easily reviewed commit-by-commit.

* 79d45ef contains the changes to the Delphi source and editor wrapper
* 1e74926 just removes ACE files
* 104a61c just adds Monaco files
* 8706221 and f06e21c together complete the installation wrapper

### CODE REVIEW

**Comment by darcywong00** [comment]
Since installing nodejs is needed for KMW and a prereq for Developer, could we do
```
npm install monaco-editor
```
as an alternative to checking it in?

**Comment by mcdurdin** [comment]
@darcywong00 That's a good idea. Can we do that as a future optimisation PR though? Because I'd like to merge all the editor work in...

But I certainly will investigate using npm for pulling monaco -- I've added it to the card -- there are a couple of tricky things to negotiate path-wise to make debugging work smoothly, but it does give us a nice way forward. Also considering whether we should use TypeScript for editor.js in order to give us cleaner code. Again, another PR.

**Comment by mcdurdin** [comment]
@darcywong00, for some reason, your review comments are not attached to any specific lines of code. Any idea what is going on there?

**Comment by darcywong00** [comment]
Sorry about that - I was reviewing by the individual commits. If you click on commit hash 79d45eff40934ba1d8d4d3da07eae7865d8703ac, I think my comments will show up in context.

**Comment by mcdurdin** [comment]
Ha ha, so you followed my instructions and then I got myself confused. Yay :) Thanks!

**Pull request merged**
