### PR TITLE
feat(core): augment unit tests for ldml 🙀

### PR DESCRIPTION
**Pull request by srl295**
- add 001_tiny to the build, annotate with expected run

This is a little ways from passing, but I wanted to get the test queued up (TDD!)

part of #5015 

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
hooray for total failure

```
				--- command ---
				/var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/keyboardprocessor/arch/release/tests/unit/ldml/ldml /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/keyboardprocessor/arch/release/tests/unit/ldml/k_001_tiny.xml /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/keyboardprocessor/arch/release/tests/unit/ldml/k_001_tiny.kmx
				--- stdout ---
				source file   = /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/keyboardprocessor/arch/release/tests/unit/ldml/k_001_tiny.xml
				compiled file = /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/keyboardprocessor/arch/release/tests/unit/ldml/k_001_tiny.kmx
				expected  : U+0127 U+1790 U+17B6 U+0127  [ħថាħ]
				text store: U+0061 U+0061 U+0061  [aaa]
				context   : U+0061 U+0061 U+0061  [aaa]
				-------

```

**Comment by srl295** [comment]
This is ready for review. The downstream PR #7083 makes it pass.

**Review by mcdurdin — CHANGES_REQUESTED** [review]
001_tiny.kmx seems to be missing?

**Comment by srl295** [comment]
> 001_tiny.kmx seems to be missing?

It and the xml were in the parent pr.  It was the @@ directives that were missing.

**Review by mcdurdin — APPROVED** [review]

**Pull request merged**
