### PR TITLE
fix(android): Update styling and set text to black

### LINKED ISSUE #2236: feat(android): Tweak text color to black in the lists
Can defer to when UI gets updated

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2236 

I've always been bothered by the gray text in the listviews that are hard to see. Also, now that the minimum SDK is 21, the `values/styles.xml` and `values-v21/styles.xml` files can be consolidated.

This also adds the gold color from the [First Peoples' Cultural Center](https://fpcc.ca/) to the OEM FV Android app (in the top status bar and selector).

### Keyman App
get started

picker

keyboard info

language settings

### KMSample1 App
kmsample1 picker

kmsample1 info

### FV App
regions

keyboards

setup

## User Testing
@MakaraSok 
Load the test app and click through all the menus

### CODE REVIEW

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.262-beta](https://keyman.com/downloads/releases/beta/14.0.262)

**Review by mcdurdin — APPROVED** [review]
I think this looks OK. Some changes to code which I am not entirely sure what they are for?

**Comment by darcywong00** [comment]
> Some changes to code which I am not entirely sure what they are for?

For the FV Activities, they were updated to follow the patterns used in KMAPro.
Change from `requestWindowFeature(Window.FEATURE_CUSTOM_TITLE)` to `supportRequestWindowFeature(Window.FEATURE_NO_TITLE);` was need for compilation.

RegionListActivity and KeyboardListActivity now use a simpler `activity_list_layout`.
SetupActivity follows the pattern of KMAPro's GetStartedActivity

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.264-beta](https://keyman.com/downloads/releases/beta/14.0.264)

**Comment by MakaraSok** [comment]
Tested on Android 10 API 29 emulator with the latest build above.

All texts look OK, but one minor thing is with the back arrow on the top left. It looks faint grey still to me comparing with the other arrows, i.e. the forward arrow on the keyboard name right below and on the Dictionary at the bottom of the screen.

image

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)

**Pull request merged**
