### PR TITLE
test(android): Add final keyboard to test K_ENTER rule

### LINKED ISSUE #4645: bug(android/engine): Support emitting carriage return as last character after text
Issue found while testing #4636

>Technically, we don't support emitting text after the carriage return; we support emitting the carriage return as the last character after other text though.
>
>* `+ 'a' > [K_ENTER] 'foo'` should never happen.
>
>But:
>
>* `'bar' + [K_ENTER] > 'foo' [K_ENTER]` could happen (although it will be more [verbose than that in code]
>(https://help.keyman.com/developer/language/guide/groups#:~:text=If%20the%20final%20group%20processed%20is%20a%20context%20and%20keystroke%20group)).
>
>Will that work at present? Do we need to open a separate issue on that?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/4636#discussion_r591818714_

----

I implemented the keyboard from keymanapp/help.keyman.com#346 and found:
| Keystroke: <kbd>s</kbd><kbd>Enter</kbd> | result |
|----------|-------|
| Expected Result | `ς\n` |
| unminified KMW test page | `ς\n` |
| Keyman for Android in-app | `σ\n` |
| Keyman for Android system keyboard (Keep app) | `σ\n` |

### PR DESCRIPTION
**Pull request by darcywong00**
Relates to #4645

Turns out @jahorton had fixed KMW (I think #4498 fixes #4645?)
I repurposed the basic_kbdus keyboard with the following rules to create final.kmp:

```
begin Unicode > use(main)

group(main) using keys

+ 's' > 'σ'
'σ' + [K_ENTER] > 'ς' use(final)

group(final) using keys
c Empty final group causes keystroke to be emitted
```

and added it to the Android KeyboardHarness app.
User testing will show <kbd>s</kbd> followed by <kbd>ENTER</kbd> results in the expected output `ς` with newline.

## User Testing
Setup
On an Android device/emulator, load the PR build of the Test app "Keyboard Harness" - **NOT** Keyman for Android. Note: this isn't normally included in the KMSample artifacts, so I will have to find the CI link
The current install link for [Keyboard Harness](https://build.palaso.org/repository/download/KeymanAndroid_TestSamplesAndTestProjects/338475:id/Tests/KeyboardHarness/app-debug.apk)

* **TEST_FINAL_KEYBOARD** - Verifies #4645 is fixed
1. Launch the "Keyboard Harness" app
2. Long-press the globe button to bring up the keyboard picker menu
3. Select the "final Keyboard" for English (should be the last row)
4. With the final keyboard selected, type <kbd>s</kbd> (lower-case "s")
5. Verify `σ` (sigma) is output
6. With the final keyboard, press <kbd>ENTER</kbd>
7. Verify `σ` changes to `ς` (final letter sigma) followed by newline.

### CODE REVIEW

**Comment by darcywong00** [comment]
CI question - this is probably a 1-off including the Keyboard Harness test app as an artifact on CI.  After this PRI can
1. revert to just keep KMSample apps or
2. Investigate keeping the artifact for keymanapp-test-bot

**Review by mcdurdin — APPROVED** [review]
LGTM. I am ok with keeping final.kmp in the repo for now. One day we will be building them all, I think, but we're not quite ready for that yet.

**Comment by darcywong00** [comment]
We'll keep the CI config to include the Keyboard Harness test app on PR builds

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.67-alpha](https://keyman.com/downloads/releases/alpha/16.0.67)

**Pull request merged**
