### PR TITLE
chore(common): Check in crowdin files for French

### LINKED ISSUE #4415: feat: Import French Localization to KM products
I've completed the CrowdIn for French, can you please add this localization into an alpha or beta build so that I can field-test it?

Notes: 
I can build Android KMPRO locally, but I've never been able to locally build a KMEA that works, and it seems that KMPRO depends on KMEA for its localization choices.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4415 bringing in the French crowdin files.

@MattGyverLee would like to field-test the betas

### CODE REVIEW

**Comment by darcywong00** [comment]
I wonder if the Desktop test build is falling because of the slash

```xml
<string name="ssCancelQuery">Êtes-vous sûr de vouloir annuler l\'installation de $APPNAME?</string>
```

**Comment by darcywong00** [comment]
@mcdurdin I'm stumped getting Delphi to handle the `\'` quotes in the xml files.

I tried to edit AndroidStringToKeymanLocaleString.pas
```
      case text[i] of
        't': Result[j] := #9;
        'n': begin Result[j] := #13; Inc(j); Result[j] := #10; end;
        '''': begin Result[j] := ''''; Inc(j); Result[j] := ''''; end; // Handle single-quote
        else Result[j] := text[i];
      end;
```

but it doesn't seem to help in creating Keyman.Setup.System.Locale.fr.pas (l.12)

```
  #202'tes-vous s'#251'r de vouloir annuler l'installation de $APPNAME?',
```

trying to get `l''`?
```
  #202'tes-vous s'#251'r de vouloir annuler l''installation de $APPNAME?',  
```

**Comment by MattGyverLee** [comment]
I haven't dealt with Pascal in years...but shouldn't  this section start with 3 single quotes or double single double?

To my untrained eye, It looks like you are finding '' and replacing it with '' (no change).

```
'''': begin Result[j] := ''''; Inc(j); Result[j] := ''''; end; // Handle single-quote
        else Result[j] := text[i];
```

**Comment by darcywong00** [comment]
https://github.com/keymanapp/keyman/blob/beta/windows/src/global/delphi/general/Keyman.System.AndroidStringToKeymanLocaleString.pas#L25-L50

Ah, I don't think the quotes are escaped when it gets to step 3. Maybe text needs to call a deprecated WideQuotedStr()?

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.238-beta](https://keyman.com/downloads/releases/beta/14.0.238)

**Comment by darcywong00** [comment]
@MattGyverLee , the beta builds are available for you to field-test
https://keyman.com/downloads/pre-release/

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
