### PR TITLE
chore(developer): add B11 ISO code for ABNT2 keyboard

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Review by jahorton — APPROVED** [review]
Will there need to be adjustments across our various platforms to accommodate this key code?

**Comment by mcdurdin** [comment]
> Will there need to be adjustments across our various platforms to accommodate this key code?

No. It doesn't change the key code, just adds the ISO reference for it, which is used only by the compiler.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.259-beta](https://keyman.com/downloads/releases/beta/14.0.259)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)

**Pull request merged**
