### PR TITLE
feat(core): remove ICU from core under wasm 🙀 

### PR DESCRIPTION
**Pull request by srl295**
The preceding PRs paved the way, now it's time to kick away the scaffolding.

This PR will:
- remove ICU from core, for was
- Note ICU is still used for tests and tooling under wasm, so it will still get built.

See below for metrics, but looks like a 3x improvement in core size.

Fixes: #9467

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
Doesn't seem to change the size in a way that I can measure. Hmm.

**Comment by srl295** [comment]
OK using #11781 numbers:

### Before this PR (and the others in the chain)

```
92K     core/build/wasm/release/tests/unit/ldml/core_ldml_min.js
960K    core/build/wasm/release/tests/unit/ldml/core_ldml_min.wasm
core/build/wasm/release/tests/unit/ldml/core_ldml_min.wasm  :
section        size     addr
TYPE            519       11
IMPORT          624      533
FUNCTION       1621     1160
TABLE             7     2783
MEMORY            6     2792
GLOBAL           13     2800
EXPORT          460     2816
ELEM           1582     3279
CODE         626890     4865
DATA         311320   631759
JS              90462   0
Total           1033504
```

### After this PR (and others in the chain)

```
92K     core/build/wasm/release/tests/unit/ldml/core_ldml_min.js
320K    core/build/wasm/release/tests/unit/ldml/core_ldml_min.wasm
section        size     addr
TYPE            436       11
IMPORT          684      450
FUNCTION        860     1137
TABLE             7     1999
MEMORY            6     2008
GLOBAL           13     2016
EXPORT          326     2032
ELEM            858     2361
CODE         273997     3223
DATA          30282   277224
JS              90960   0
Total           398429
```

**Comment by mcdurdin** [comment]
That's what we were aiming for size-wise with this! I guess we can do some more trimming, e.g. the .js seems pretty big (and is it even needed?) but very glad to see the big drop from 960kb to 320kb.

**Review by jahorton — APPROVED** [review]

**Review by ermshiperete — APPROVED** [review]

**Comment by srl295** [comment]
> That's what we were aiming for size-wise with this! I guess we can do some more trimming, e.g. the .js seems pretty big (and is it even needed?) but very glad to see the big drop from 960kb to 320kb.

the .js is the wrapper, so I think the eventually KMW build would simply have its own .js file. 

I'm surprised the original size isn't larger and the drop more dramatic— the tree shaking and my ICU trimming is already pretty effective.  The usual sizes for ICU are an order of magnitude more. 

```
31M	libicudata.73.0.1.dylib
3.1M	libicui18n.73.0.1.dylib
1.9M	libicuuc.73.0.1.dylib
```

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.57-alpha](https://keyman.com/downloads/releases/alpha/18.0.57)

**Pull request merged**
