### PR TITLE
chore(common): Check in crowdin files for de (German)

### PR DESCRIPTION
**Pull request by darcywong00**
Related to #4228  This PR manually checks in the German strings
```
crowdin.bat download -b master -l de
```

Quick screenie of Android in the German locale

german

### CODE REVIEW

**Review by mcdurdin — CHANGES_REQUESTED** [review]
This results in two German translations for Keyman for Windows -- `de-DE` and `de`. Can you remove the old one please?

**Comment by darcywong00** [comment]
> This results in two German translations for Keyman for Windows -- de-DE and de. Can you remove the old one please?

I updated crowdin.yml so Windows uses `de` instead of `de-DE` for the locale. Is that what you wanted? 

windows/src/desktop/kmshell/locale/de/strings.xml is replaced with the downloaded file.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.226-beta](https://keyman.com/downloads/releases/beta/14.0.226)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)

**Pull request merged**
