### PR TITLE
chore(ios,windows): Update crowdin strings for Azerbaijani 🍒 

### PR DESCRIPTION
**Pull request by darcywong00**
🍒 -pick of #5486 to stable-14.0
This updates 40 crowdin strings for iOS and Windows per one of the translators on translate.keyman.com

The iOS "Get Started" title should also be localized now.

@keymanapp/testers

We generally haven't done any special testing when updating Crowdin strings. You can:

## Test 1 - Keyman for Windows
* Get the test build installer and select "Azerbaycanca" (closest resemblance of typing "Azerbaijani") during Setup
keyman setup - az

* After Setup finishes, open Keyman Configuration --> Display In --> Azerbaijani

* Spot check the Keyman UI

## Test 2 - Keyman for iPhone and iPad
This probably involves building the app from this branch. I'm not familiar with how you'd set the locale for Azerbaijani
- [ ] Check the "Get Started" title on the "Get Started" menu is localized

### CODE REVIEW

**Comment by MakaraSok** [comment]
@darcywong00 Is this ready to be tested? If yes, please provide instructions on steps needed to test this PR. Thanks.

**Comment by darcywong00** [comment]
@MakaraSok We generally haven't done any special testing when updating the Crowdin strings. I'll add some general testing instructions on #5486 (I haven't cherry-picked everything to this PR yet because I'm not sure when the translator is finished).

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.280](https://keyman.com/downloads/releases/stable/14.0.280)

**Comment by MakaraSok** [comment]
# User Testing

## Test 1 - Keyman for Windows

- [x] **PASSED** Spot check and everything looks good as expected.
    image


## Test 2 - Keyman for iPhone and iPad

- [x] **PASSED** Check the "Get Started" title on the "Get Started" menu is localized

### iPhone
image

### iPad
image

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.281](https://keyman.com/downloads/releases/stable/14.0.281)

**Pull request merged**
