### PR TITLE
docs(ios): Add help page for Settings

### LINKED ISSUE #5381: bug(ios): missing help on Settings screen
**Describe the bug**

We do not currently have a help page corresponding to the settings screen, such as we have in Keyman for Android

---

**Keyman for iPhone/iPad/Android:**
 - Keyman version: 14.0

### PR DESCRIPTION
**Pull request by laineyhm**
Fixes #5381

This adds a help page for the Settings menu in Keyman for iPhone and iPad.

## User Testing
Setup: Install the PR build of Keyman for iPhone and iPad
* TEST_HELP_PAGE
1. Launch Keyman
2. From the menu (...), open the Info page.
3. Click 'Using Keyman for iPhone and iPad' > 'Using the Settings Screen' 
4. Verify that the 'Using the Settings Screen' page is displayed.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_HELP_PAGE (FAILED):** Tested with the attached PR build (Keyman 17.0.81-alpha-test-8546) in iPhone and iPad Simulators and here is my observation: 1. Using the Settings Screen option is still missing under the "Using Keyman for iPhone and iPad" help topic. 

..Help page link is missing in iPhone Simulator

   

..Help page link is missing in iPad Simulator

**Comment by jahorton** [comment]
I've created a PR on your repo for the suggested changes: https://github.com/laineyhm/keyman/pull/1.  That should resolve the reported user-testing issue and help us move forward with this.

**Comment by laineyhm** [comment]
Thanks @jahorton, I merged your PR to my fork.

**Comment by jahorton** [comment]
@keymanapp-test-bot retest TEST_HELP_PAGE

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_HELP_PAGE (PASSED):** Tested with the attached PR build (Keyman 17.0.81-alpha-test-8546) in iPhone 14 Pro Max Simulator and I was able to see the 'Using the Settings..." link under the Help topics. By clicking on the link, it opens the relevant help page. Seems to be working fine. Thanks. 

..iPhone 14 Pro Max Simulator

   


..iPad (10th generation) Simulator

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.89-alpha](https://keyman.com/downloads/releases/alpha/17.0.89)

**Pull request merged**
