### PR TITLE
fix(web): unrevert #11258, leaving OSK hidden before instructed to display

### PR DESCRIPTION
**Pull request by jahorton**
#12015 included a reversion to #11258, which was originally a followup that edited the same region as edited by #11174, the focus of #12015.  #11258's changes should be fine to include though, so this PR restores its change.

## User Testing

**TEST_REPRO**:  Attempt to reproduce #11962 using Keyman for Android.

- Install the package provided within that issue.
- Force-quit the app.
- Relaunch the app.
    - If the issue is not properly fixed, an error notification will appear on app-relaunch.

**TEST_ANDROID**:   Do simple general-use testing with Keyman for Android and report back if any odd behaviors occur.

**TEST_IOS**: Do simple general-use testing with Keyman for iOS and report back if any odd behaviors occur.

**TEST_WEB**:  Do simple general-use testing with the "Test unminified Web" test page and report back if any odd behaviors occur.

**TEST_DEV_SERVER**:  Use Keyman Developer's web-keyboard testing page and verify that it still works correctly.  (We're mostly checking to see that this doesn't result in an immediate, obvious break.)

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
RSLGTM, of course pending user test :grin:

**Comment by mcdurdin** [comment]
Can you add a user test for Keyman Developer Server?

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "Keyman 18.0.78-alpha-test-12049" build on the Android 14 & iPhone, web(Chrome & Firefox), and keyboard developer. Here is my observation.

* **TEST_REPRO (passed):** 
1. Install the "Keyman 18.0.78-alpha-test-12049" build.
2. Relaunch the app after force quit.
3. No error notification appears when forced to quit the app.

* **TEST_ANDROID (passed):** 
1. Installed the "Keyman 18.0.78-alpha-test-12049" file and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app. Enable the "Predictions" and install the "Dictionary."
4. Added a sentence to the notepad and Chrome (search).
5. Enter a word and observe that the words are suggested and highlighted on the banner. 
6. The keyboard works on portrait and landscape viewports. Keyboard set as system keyboard.
7. Installed/uninstalled multiple keyboards.
It looks like it was expected.

* **TEST_IOS (passed):**
1. Installed the "Keyman 18.0.78-alpha-test-12049" build from the testflight app and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app. Enable the "Predictions" and install the "Dictionary."
4. Added a sentence to the notepad and Chrome (search).
5. Enter a word. Observe that the words are suggested and highlighted on the banner. 
6. The keyboard works on portrait and landscape viewports. Keyboard set as system keyboard.
7. Installed/uninstalled multiple keyboards.
It looks like it was expected.

* **TEST_WEB (passed):**
1. Navigate to the "Tests unminified Keymanweb" --> "KeymanWeb Sample Page - Unminified Source" pages.
2. "English - English": It works well in the text box and OSK keyboard.
3. "Lao - Lao Basic": It works well in the text box and OSK keyboard.
4. "English - Classic 10-key": OSK board appears but it is blank now. An alert window appears for very few seconds.
5. It works in Khmer and gff_amheric keyboards too. Thank you.

* **TEST_DEV_SERVER (passed):** 
1. Added the Amharic & Cameroon keyboards loaded the .kmn, and pressed F7 to compile.
2. SUITE_DEBUGGER: Test new core-based debugger - Compile and recompile the keyboard. debugger works well.
3. SUITE_SERVER: Test new Keyman Developer Server - Keyboard launched on the browser with OSK.
I tested the above two test suites and work as per expected. Thanks.

**Comment by mcdurdin** [comment]
> 4\. "English - Classic 10-key": OSK board appears but it is blank now. An alert window appears for very few seconds.

Is this reproducible? Could you share a video?

**Comment by jahorton** [comment]
> > 4. "English - Classic 10-key": OSK board appears but it is blank now. An alert window appears for very few seconds.
> 
> Is this reproducible? Could you share a video?

That keyboard was designed for gesture use, rather than standard desktop use.  Assuming he was testing with a 'desktop' form-factor, that completely checks out.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.80-alpha](https://keyman.com/downloads/releases/alpha/18.0.80)

**Pull request merged**
