### PR TITLE
fix(android/app): Track previous device orientation for SystemKeyboard

### LINKED ISSUE #10054: bug(android): sometimes the Android keyboard pops up at wrong size
image

I have not yet been able to figure out exactly what causes this, but sometimes when the OSK pops up on Android, the keyboard shows at the wrong size. Rotating the device seems to be the only way to address this.

Seems like there is probably a race condition somewhere there.

Keyman 17.0.200-alpha-test-9973 (but also seen on 17.0.x-alpha)

### PR DESCRIPTION
**Pull request by darcywong00**
Attempting to fix #10054 (granted hard to have a consistent repro)

This changes SystemKeyboard to track the previous device orientation to get more consistent OSK rotation  via `KMManager.onConfigurationChanged()`.

The InApp keyboard already has similar code in MainActivity

https://github.com/keymanapp/keyman/blob/6db53aee7acfa755a8d0206cf34eeb993a8787de/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java#L237-L250

## User Testing
**Setup** - Install the PR build of Keyman for Android on an Android device/emulator. A physical device is recommended since it's easier to quickly rotate the device

* **TEST_OSK_ROTATION** - Verifies System Keyboard OSK height is correct on device rotations
1. Launch Keyman for Android
2. From the "Get Started" menu, enable and set Keyman as the default system keyboard
3. Launch a separate app (e.g. Google Chrome) where you can type in a text field with the Keyman system keyboard
4. This is the hard part to repro the bug. Repeatedly do the following:
    a. Dismiss the OSK with the back button
    b. rotate the device orientation
    c. Quickly select the text area to bring up the OSK
    d. Verify the keyboard height is a normal height (not squished). During transitions, the OSK may briefly be shorter or skinnier than normal, but it should settle to fill the full width / normal height.
    e. Repeat step 4 several times (~20+) to try to get the issue to repro.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
Changes LGTM in principle. Look forward to testing them on my phone

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_OSK_ROTATION (FAILED):** Retested with the attached PR build (Keyman 17.0.300-beta-test-11134) on an Android 13 Mobile device and here is my observation: 1. Set Keyman as the default system keyboard. 2. Opened Chrome broswer app. 3. Dismissed the OSK with the back button. 4. Rotated the device orientation. (eg.,from portrait to landscape and landscape to portrait) 5. Selected the text area from the Chrome app. Verified the keyboard height was in a normal height. 6. Repeated step 4 several times and I was able to reproduce this issue. 

I have attached the Screenshot for reference.

**Comment by darcywong00** [comment]
sigh - back to draft

**Comment by darcywong00** [comment]
@bharanidharanj - I've merged in some of the KeymanWeb stability PRs.  Can you see if you can still repro the issue?

@keymanapp-test-bot retest

**Comment by mcdurdin** [comment]
@darcywong00 given the screenshot shows the full height of the keyboard area is the landscape height, I don't think the KMW changes are going to fix it. We'd expect to see blank space above the keyboard area if the webview container size was right but the kmw size was wrong.

**Comment by darcywong00** [comment]
I'm just having a really hard time trying to get a repro now. 
That's why I wondered if adding the stability fix in #11108 helps

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_OSK_ROTATION (PASSED):** Retested with the attached PR build (Keyman 17.0.300-beta-test-11134) on an Android 13 Mobile device and here is my observation: 1. Set Keyman as the default system keyboard. 2. Opened Chrome broswer app. 3. Dismissed the OSK with the back button. 4. Rotated the device orientation. (eg.,from portrait to landscape and landscape to portrait) 5. Selected the text area from the Chrome app. Verified the keyboard height was in a normal height. 6. Repeated step 4 several times and this time I was not able to reproduce the above issue. Seems to be a random one. However, I will keep an eye on this issue and will let you know if it is reproducible.

**Comment by darcywong00** [comment]
ok, will go ahead and merge this. and we'll keep an eye if it happens again

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.301-beta](https://keyman.com/downloads/releases/beta/17.0.301)

**Pull request merged**
