### PR TITLE
cherrypick(common): Cleanup Kannada locale 🍒

### PR DESCRIPTION
**Pull request by darcywong00**
🍒 pick of #8182 to stable-16.0

Cleans up Kannada locale
* Use `kn` on Windows instead of `kan-Knda-IN` (pre-Crowdin strings) and `kn-IN` (Crowdin strings). This fixes Kannada from being listed twice on the locale list.
* Updated other Kannada strings noted on Crowdin.

## User Testing
**Setup** - Load the PR build of Keyman for Windows

* **TEST_WINDOWS_KANNADA** - Verifies Kannada is only listed once
1. Start Keyman for Windows
2. Open Keyman Configuration dialog.
3. Click the 'Display in' list box.
4. Scroll down and Select 'Kannada' language.
5. Verify "Kannada" is only listed once
6. Select "Kannada"
7. Verify the UI is in Kannada.

* **TEST_WINDOWS_OLD_TO_NEW_KANNADA** - Test what happens when upgrading to this release when in Kannada locale
1. Install Keyman for Windows release [16.0.138](https://downloads.keyman.com/windows/stable/16.0.138/).
2. In Keyman Configuration, ensure that Kannada locale is selected.
3. Install this test build of Keyman for Windows.
4. Start Keyman Configuration. The locale will probably be back to English -- this is okay. What we want to ensure is that the Configuration doesn't go wrong in other ways (e.g. crash, blank screen, etc.)

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_WINDOWS_KANNADA (PASSED):** Tested this with the attached PR build (16.0.139-test-8189) in Windows 11 OS (VM) and verified that the UI was successfully changed to Kannada without having any problem.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_WINDOWS_OLD_TO_NEW_KANNADA (FAILED):** 1. Installed Keyman 17.0.39-alpha build in the system. 2. Not able to test this part ie., upgrade it to the attached PR build (16.0.139-test-8189) since it is lower version. 

..Keyman UI in 17.0


   


..Upgrade failed since the attached build is 16.0

**Review by ermshiperete — APPROVED** [review]

**Comment by darcywong00** [comment]
@bharanidharanj - I'll modify TEST_WINDOWS_OLD_TO_NEW_KANNADA to use 16.0.138. Hopefully that will let you upgrade to the PR version.

@keymanapp-test-bot retest TEST_WINDOWS_OLD_TO_NEW_KANNADA

**Comment by bharanidharanj** [comment]
> @bharanidharanj - I'll modify TEST_WINDOWS_OLD_TO_NEW_KANNADA to use 16.0.138. Hopefully that will let you upgrade to the PR version.
> 
> @keymanapp-test-bot retest TEST_WINDOWS_OLD_TO_NEW_KANNADA

Okay @darcywong00 . Thanks.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_WINDOWS_OLD_TO_NEW_KANNADA (PASSED):** Retested as per the instructions and here is my observation: 1. Installed Keyman 16.0.138 build. Able to see the Kannada UI name  appears twice in the display list. 2. Upgraded with the attached PR build 16.0.139-test-8189 and now the Kannada name appears once in the display list. Seems to be working fine. 

..Kannada UI before upgrade

   

..Kannada UI after upgrade

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.139](https://keyman.com/downloads/releases/stable/16.0.139)

**Pull request merged**
