### PR TITLE
chore(common): Check in crowdin for Russian

### PR DESCRIPTION
**Pull request by darcywong00**
Adds crowdin strings for Russian for locale ru-RU

## User Testing
This adds the crowdin strings for Russian locale ru-RU

TODO for @sgschantz 
- [x] Run XCode for iOS
- [x] Run XCode for macOS

## User Testing
Load the PR build for each platform and set the UI / Locale to "Pyccĸий (Russian)"

* **TEST_ANDROID** 
1. Load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display Language --> Pyccĸий (Russian)
3. Return to the Keyman app 
4. Verify the UI is in Russian (prompt, Settings strings, etc.).

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Russian
3. Return to the Keyman app
4. Verify the UI is in  Russian

* **TEST_LINUX**
1. Start Keyman configuration with: LANGUAGE=ru-RU km-config
2. Verify Keyman UI is in Russian

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Russian
3. Verify the Keyman UI is in Russian

* **TEST_WINDOWS**
1. Load the PR build of Keyman for Windows
2. Set the UI to Pyccĸий (Russian)
3. Verify the Keyman UI is in Russian

### CODE REVIEW

**Comment by darcywong00** [comment]
It seems the Windows string ssOffline is too long (> 1023 bytes), so I had to truncate at 2 of the 3 sentences.

https://crowdin.com/proofread/keyman/508/en-ru?filter=basic&value=3#q=ssOffline

**Comment by mcdurdin** [comment]
> It seems the Windows string ssOffline is too long (> 1023 bytes), so I had to truncate at 2 of the 3 sentences.

Longer-term, we could fix by having each para a separate string?

**Comment by darcywong00** [comment]
This is going back to draft while we sort out splitting the Offline string into 3 on crowdin.

**Comment by darcywong00** [comment]
OK, the split ssOffline string has been round-tripped to Crowdin, so this PR is ready to review

**Review by rc-swag — APPROVED** [review]
windows LGTM.

**Review by jahorton — APPROVED** [review]

**Comment by darcywong00** [comment]
@bharanidharanj  - please wait on testing iOS until we can resolve why the other localization PRs crash on the iOS emulator (#8095, #8071)

**Comment by mcdurdin** [comment]
> @bharanidharanj - please wait on testing iOS until we can resolve why the other localization PRs crash on the iOS emulator (#8095, #8071)

OK, I think this is now resolved. When the iOS build finishes here, you should be able to test TEST_IOS as well.

**Comment by bharanidharanj** [comment]
> > @bharanidharanj - please wait on testing iOS until we can resolve why the other localization PRs crash on the iOS emulator (#8095, #8071)
> 
> OK, I think this is now resolved. When the iOS build finishes here, you should be able to test TEST_IOS as well.

@mcdurdin Okay, Thanks.

**Comment by bharanidharanj** [comment]
* **TEST_LINUX (PASSED):** Tested with the attached PR build (16.0.134-beta (package version 16.0.134-1~PR-8072+focal12) )in Ubuntu 20.04 Focal Linux OS (VM) and I am able to change the UI into Russian in Keyman Config dialog. 

..Russian UI1:

   

..Russian UI2:

   

..Russian UI3:

**Comment by bharanidharanj** [comment]
* **TEST_ANDROID (PASSED):** Tested with the attached PR build (16.0.134-beta-test-8072) in Android 12 / API 31 emulator and I was able to change the UI into Russian in Keyman app.

**Comment by bharanidharanj** [comment]
* **TEST_MACOS (PASSED):** Tested with the attached PR build in macMini Monterey 12.6 OS and I was able to change the UI in to Russian in Keyman app. 

..Russian UI1:

   

..Russian UI2:

**Comment by mcdurdin** [comment]
I manually triggered a new iOS test build which should pull in the fixed sil_euro_latin.kmp 2.0.3.

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_IOS (PASSED):** Everything seems to be shown in Russian, but the word "Done" in multiple places. This could well be a system thing. Hence, PASSED for now.

| 1 | 2 |
| --- | --- |
| image | image |

**Comment by bharanidharanj** [comment]
@mcdurdin  Tested with the attached PR build (keyman 16.0.134-beta-test-8072) in iOS 15.0 / iPhone 12 Pro Max Simulator and I was able to change the UI into Russian without having any problem.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.136-beta](https://keyman.com/downloads/releases/beta/16.0.136)

**Pull request merged**
