### PR TITLE
feat(developer): Rework Touch Layout Editor to support flick and multitap 🙊

### PR DESCRIPTION
**Pull request by mcdurdin**
~~**Blocked:** this is blocked by #6918, will want to run the regression test before this lands, so once #6918 chain hits master, we should rebase/merge master.~~ DONE.

---

This is a significant rework of the Touch Layout Editor. I started by refactoring the code into multiple units with minimal code changes -- you can see these changes in the following commits:

* e6a321d0b - chore(developer): refactor builder.js
* 2743574aa - chore(developer): refactor undo actions out of builder.js
* f6974e064 - chore(developer): refactor 'constants' out of builder.js
* 84d8f2662 - chore(developer): refactor subkeys out of builder.js
* 4578742c8 - chore(developer): update jquery-ui version to 1.13.1

I did make some more minor further refactoring changes in subsequent commits, but did not separate them out quite as much. However, first reviewing the above commits separately, and then reviewing the remaining commits in a block should make it easier to see what's going on.

This PR includes the following feature work and bug fixes:

* Restructure touch layout editor to make space for additional gesture types:
   * Move control bar to right hand side
   * Move key cap edit controls to control bar (instead of being on the key)
* Adds support for flick and multitap gestures.
* New types of buttons to add longpress keys, flicks or multitaps (removing all gestures of a given type deletes the entire gesture object in the JSON).
   * Note that the 'wedge' style of adding keys is still available on longpress and on multitap
* Adds Unicode value boxes which mirror the key cap text box.
* Maintain selected key as far as possible across layer switch, platform switch and presentation view switch.
* Split 'special' key cap icons from normal key caps in the controls, so users can pick them visually.
* Updates key width values in real time when resizing.
* Fixes selection of last active element with undo

And finally, also updated relevant Delphi code to allow the new fields to validate successfully.

image

There are a number of changes to the UX. First, it has been significantly rearranged to simplify editing different gesture types. These rearrangements should also improve the editing experience for any touch keyboard, even if new gesture types are not used.

## Controls for editing

The controls for editing key metadata are all to the right of the keyboard view -- even the key cap is edited here now:

image

There are a few new fields here:

### Keycap Value

This allows the user to choose keycap images visually rather than by using the previous `*<name>*` pattern which was a little obtuse (and was hard to work with in the keycap text field as the names didn't really fit):

image

Note that when a 'special' key cap is selected, the Text and Unicode fields are hidden:

image

### Unicode

The Unicode field lets the user see and/or enter Unicode values directly for the key Text.

image

### Gesture Type

This field is read-only but correlates to the selected key area (the same information is available visually by the location of the key).

image

## Gesture indicators

The slash on the top right of a key that indicated the presence of a longpress menu is gone. In its place we have the following indicators that indicate the presence of a gesture on the key, located in rough association with the direction of the gesture (where appropriate):

* Longpress: an icon at the top of the key:
  image

* Flicks: one icon for each flick direction defined for the key:
  image

* Multitaps: an icon to the bottom right of the key:
  image

Note: these icons are only visible in the designer -- not in the running keyboard. We are still planning to introduce 'hints' for key caps; when we implement this, it may impact these icons.

# User Testing

In all your testing, it will be valuable to have the F12 Developer Tools window open to verify that there are no errors raised.

For every test, we want to make sure that (a) no errors occur, and (b) the result is what you would expect to have happen.

## SUITE_BASIC

Here, we aim to test that touch layout designer functionality available in earlier versions still works in the new version.

* **TEST_ADD_KEY:** Add a key to an existing row of the keyboard (with the green 'wedge').
* **TEST_ADD_ROW:** Add a new row to an existing layer on the keyboard (with the green 'wedge').
* **TEST_ADD_LAYER:** Add a new layer to a keyboard (Layer/Add button)
* **TEST_DEL_KEY:** Delete a key from the keybaord (Red x button on the selected key)
* **TEST_DEL_ROW:** Delete a row from the keyboard by deleting all keys in the row.
* **TEST_DEL_LAYER:** Delete a layer from the keyboard (Layer/Del button).
* **TEST_ADD_PLATFORM:** Add either tablet or phone platform.
* **TEST_DEL_PLATFORM:** Delete either tablet or phone platform from the keyboard.
* **TEST_TEMPLATE:** Import from On Screen, then use the Template button to select the Basic layout, and verify that this generates a 'basic' layout -- mobile-optimised, fewer keys than a desktop layout.
* **TEST_SWITCH_LAYER:** Select an alternative layer from the Layer menu. Then double-click on the Shift key to switch layers another way.
* **TEST_PRESENTATIONS:** Switch between the landscape/portrait orientation and verify correct.

## SUITE_EDIT_KEY_DATA

Next, we'll want to test the key cap editing behaviour. 

* **TEST_EDIT_TEXT:** Select a key and change its key cap value in the Text field.
* **TEST_EDIT_UNICODE:** Select a key and change its key cap value in the Unicode field.
* **TEST_EDIT_ID:** Select a key and change its ID.
* **TEST_EDIT_PAD:** Select a key and change the padding to a value such as 30. Verify that the padding left of the key grows.
* **TEST_EDIT_WIDTH:** Select a key and change its width to the value 200. Verify that the key is twice as wide as normal.

## SUITE_EDIT_GESTURE_DATA:

* **TEST_ADD_LONGPRESS:** For a selected base key, add a longpress by clicking the [+] button in the Longpress area. Verify that the longpress icon appears on the base key.
* **TEST_DEL_LONGPRESS:** For a selected base key, delete a longpress key by clicking the red (x) button on the longpress key.
* **TEST_ADD_FLICK:** For a selected base key, add a flick by clicking any [+] button in the Flick area. Verify that the coresponding Flick icon appears on the base key.
* **TEST_DEL_FLICK:** For a selected base key, delete a flick key by clicking the red (x) button on the flick key.
* **TEST_ADD_MULTITAP:** For a selected base key, add a multitap by clicking the [+] button in the Multitap area. Verify that the multitap icon appears on the base key.
* **TEST_DEL_MULTITAP:** For a selected base key, delete a multitap key by clicking the red (x) button on the multitap key.

## SUITE_CHAR_MAP

* **TEST_CHAR_DROP:** Drag a character from character map and drop it onto a key. The new character should replace the character on the key.
* **TEST_CHAR_DROP_ADD:** Drag a character from character map and drop it onto a key while holding Shift. The new character should be added to the key.
* **TEST_CHAR_DROP_TEXT:** Drag a character from character map and drop it onto the Text field. The new character should replace the character on the key.
* **TEST_CHAR_DROP_TEXT_ADD:** Drag a character from character map and drop it onto the Text field while holding Shift. The new character should be added to the key.

## SUITE_USAGE

* **TEST_GENERAL_USE:** It would be valuable to just give the touch layout editor some general use, playing around with it, and verifying that it behaves as you expect, as well as all the above tests. Any behaviour that doesn't "make sense" or causes an error would be a reason to fail this test.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
## SUITE_EDIT_KEY_DATA: 

* **TEST_EDIT_TEXT (PASSED):** Able to change the Key cap value in the Text field. 

   

* **TEST_EDIT_UNICODE (PASSED):** Able to change the Key cap value in the Unicode field.
   


* **TEST_EDIT_ID (PASSED):** Able to change the Key's ID. 

   


* **TEST_EDIT_PAD (PASSED):** Able to see the paddinf left of the key grows. 

   


* **TEST_EDIT_WIDTH (PASSED):** Able to see the key is twice as wide as normal after changing the value of the width to 200.

**Comment by bharanidharanj** [comment]
## SUITE_EDIT_GESTURE_DATA: 

* **TEST_ADD_LONGPRESS (PASSED):** Verified that the Longpress icon appears on the base key. 
LongPressKey1


* **TEST_DEL_LONGPRESS (PASSED):** Verified that the longpress icone has been removed from the base key after clicking the red (x) button on the longpress key. 

DelLongpress


* **TEST_ADD_FLICK (PASSED):** Verified that the corresponding Flick icon appears onthe base key. 


AddFlick

* **TEST_DEL_FLICK (PASSED):** Verified that the Flick key has been removed from the base key after clicking the red (x) button on the Flick key.

DelFlickKey

* **TEST_ADD_MULTITAP (FAILED):** Noticed that the multitap icon does not appear on the base key. 

AddMultitap


* **TEST_DEL_MULTITAP (FAILED):** Noticed that the this functionality is not working as expected. 

DelMultitap

**Comment by bharanidharanj** [comment]
## SUITE_CHAR_MAP: 

* **TEST_CHAR_DROP (PASSED):** Verified that the new character was replaced the character on the key. 

Drag1

* **TEST_CHAR_DROP_ADD (PASSED):** Verified that the new character was added to the key. 

Drag2


* **TEST_CHAR_DROP_TEXT (PASSED):** Verified that the new character was replaced the character on the key. 

Drag3


* **TEST_CHAR_DROP_TEXT_ADD (PASSED):** Verified that the new character was added to the key. 

Drag4

**Comment by mcdurdin** [comment]
> * **TEST_ADD_MULTITAP (FAILED):** Noticed that the multitap icon does not appear on the base key.

I think the multitap icon is present, perhaps not visible enough?

image

> * **TEST_DEL_MULTITAP (FAILED):** Noticed that the this functionality is not working as expected.

Can you let me know what is not working as you expected? Is it just related to the multitap icon from the previous test?

**Review by jahorton — COMMENTED** [review]
Does this PR include code to actively check against the new schema(s), even if only for linting purposes?

**Comment by MakaraSok** [comment]
@mcdurdin After playing with SUITE_BASIC I've noticed one thing that I expect to see. 

When delete something from Touch Layout tab, i.e. a layer or a platform, I expect a warning pop-up message telling what's gonna happen. Otherwise, the current layer would just disappear as soon as the `Del` button is pressed. I know the undo key could help getting the deleted layer back, but it would be nice to give a warning message. :)

**Comment by bharanidharanj** [comment]
> > * **TEST_ADD_MULTITAP (FAILED):** Noticed that the multitap icon does not appear on the base key.
> 
> I think the multitap icon is present, perhaps not visible enough?
> 
> image
> 
> > * **TEST_DEL_MULTITAP (FAILED):** Noticed that the this functionality is not working as expected.
> 
> Can you let me know what is not working as you expected? Is it just related to the multitap icon from the previous test?
> 
> @keymanapp-test-bot retest SUITE_EDIT_GESTURE_DATA TEST_ADD_MULTITAP TEST_DEL_MULTITAP

@mcdurdin I thought since Multitap feature is not working, so that I failed this test too. Anyhow, I will re-test and add my comment. Thanks.

**Comment by bharanidharanj** [comment]
## SUITE_EDIT_GESTURE_DATA: 

* **TEST_ADD_MULTITAP (PASSED):** Retested this as per Mar'c suggestion and yes, I was able to see the Multitap icon appears on the Key. (but partially visible)
AddMultitap


* **TEST_DEL_MULTITAP (PASSED):** Retested this and I noticed that after deleting the Multitap key, the corresponding icon has been removed from the Key. 
DelMultitap

**Comment by bharanidharanj** [comment]
## SUITE_USAGE: 

* **TEST_GENERAL_USE (PASSED):** I have done some general testing in the Touch Layout editor with all the options that are available in the Touch layout window. Seems to be working fine. However, I noticed that I got an compilation error message after adding a 'LongPress' feature to a base Key. 

 

Note: I did not see any error message while adding Flicks Key or Multitap key after compilation.

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_BASIC: 

* ** TEST_TEMPLATE (FAILED):** I observe that this `TEST_TEMPLATE` is weird when you change the template to `template-basic.keyman-touch-layout`. The keyboard layout gets replaced by the English layout instead of simplifying the current layout. To make the matter worse, the action cannot be reversed. The "undo" button is grayed out.

https://user-images.githubusercontent.com/28331388/177499402-4e311bf1-982a-473f-a82f-c683d8718134.mov

When change the template on the existing layout, the template replace the layout nicely. See below.


https://user-images.githubusercontent.com/28331388/177504337-edcd9751-60cc-4dae-adca-c6d5b4158395.mov


---


## Other observations:

1. There is ZWSP in the `Keycap Value`, but there are several `ZWNJ`.

image

2. Can we have a consistent measure of font size everywhere, i.e. OSK, TLP, TLT and TLD? What would be more familiar to me personally is `pt` instead of `em`. 3. See the screenshot below.

image

**Comment by mcdurdin** [comment]
> When delete something from Touch Layout tab, i.e. a layer or a platform, I expect a warning pop-up message telling what's gonna happen. Otherwise, the current layer would just disappear as soon as the `Del` button is pressed. I know the undo key could help getting the deleted layer back, but it would be nice to give a warning message. :)

As we discussed, we're sticking with the modern style of undo rather than confirmation, because it's less painful for the user for normal use.

**Comment by mcdurdin** [comment]
> * TEST_TEMPLATE (FAILED):

@MakaraSok thank you for this feedback. Can you test this in 16.0-alpha and see if you have the same outcome?

**Comment by mcdurdin** [comment]
> Note: I did not see any error message while adding Flicks Key or Multitap key after compilation.

* [ ] Compiler needs update here to get same behaviour.

**Comment by mcdurdin** [comment]
> > * TEST_TEMPLATE (FAILED):
> 
> @MakaraSok thank you for this feedback. Can you test this in 16.0-alpha and see if you have the same outcome?

I tested this against `master` and had the same issue. So this is not new to this PR. That said, I'll try and fix it here. Two issues, both relatively minor and hopefully easy to fix:

1. After clicking `Import from On Screen`, the presentation is not correctly selected.
2. After clicking `Import from On Screen`, changing the template type fails _if_ you don't first save.

**Comment by mcdurdin** [comment]
Latest commit fixes the two issues with the template function that you found, @MakaraSok. Please retest this functionality with the latest build, thank you 😄 (I might run the test myself if you are unavailable)

@keymanapp-test-bot retest SUITE_BASIC  TEST_TEMPLATE

**Comment by mcdurdin** [comment]
# Test Results

## SUITE_BASIC: 

* **TEST_TEMPLATE (PASSED):** I ran through this test myself and am confident it is working correctly now.

**Pull request merged**
