### PR TITLE
fix(developer): validate keyboard_info should give info on non-canonical bcp47

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Review by darcywong00 — CHANGES_REQUESTED** [review]
test build failed

**Comment by mcdurdin** [comment]
Ref #4425

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.263-beta](https://keyman.com/downloads/releases/beta/14.0.263)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)

**Pull request merged**
