### PR TITLE
fix(ios): fixes installation of default resources and updates them

### LINKED ISSUE #2512: [iOS] Default resource updates
**Describe the bug**
Currently, KMEI packages `nrc.en.mtnt-0.1.2.model.kmp`.  We have a more up-to-date version available, so we should package that instead.

Past that, however, there's an issue with how KMEI ensures that its resources are installed.  I've yet to double-check this for keyboards (SIL EuroLatin), but I've noticed that KMEI will automatically reinstall the MTNT model every time the app restarts - possibly undoing downloaded updates to the resource!

**To Reproduce**
1. Install and open the Keyman app (Simulator use is fine, and actually recommended here)
2. Terminate the app
3. Set a breakpoint at some stage of the lexical model installation process
4. Re-run the app

The breakpoint will be reached, with the app paused during lexical model installation - despite the fact that the first installation already installed MTNT!

**Expected behavior**
I would expect KMEI to note that:

1.  MTNT has already been installed
2.  The installed version either matches or is greater than the pre-packaged version

Based on these two factors, I would then expect it to bypass installation of the model.

**iPhone/iPad/Android (please complete the following information):**
 - Keyman version: 12.0 and 13.0
- iOS version, device, etc doesn't matter - it's an app control-flow logic issue.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2512.

Previously, the app would always reinstall the default keyboard and lexical model files on _every_ startup.  If someone deliberately uninstalled the MTNT lexical model, for example, they'd find it reinstalled whenever the app restarted; not the greatest user experience.

This was occurring because of the design of the method responsible for the installation.  `Storage.copyKMWFiles` always re-copies the base KMW resources because it excludes them from being backed up for a user's device.  Since the files exist as part of the app's bundle, they can always be renewed; why require a second copy?  The issue there - because they're not backed up, we can't assume that the keyboard and lexical model files actually exist whenever we reload the app unless we re-copy (and thus, reinstall) them.

This PR changes this so that the default language resources are:
- not excluded from backups, so that we're guaranteed that the files are persistent after their installation
- only installed on app upgrades (between major-minor versions) and on the first load after initial installation (which uses the same control-flow path as upgrades)
  - Note that as a result, `Migrations.engineVersion` acts as a 'flag' that indicates whether this check triggers.  (For comparison to how the Android app handles it.)

This way, the resources are installed exactly once; any changes a user makes on their local device will no longer be overturned. by default-resource management code.  In effect, the default resources are now "installed from the app" itself and are otherwise treated exactly like cloud-installed resources.  This also prevents any possible attempt for an accidental "downgrade" of a default resource if it is updated from the cloud.  (Well, unless we forget to update it accordingly for the new release - and even then, it's a one-off until the user re-updates the resource.)

### CODE REVIEW

**Comment by mcdurdin** [comment]
Question: what happens on existing installs? Is it possible for them to fall into a gap where the files are not restored but not backed up either?

**Comment by jahorton** [comment]
> Question: what happens on existing installs? Is it possible for them to fall into a gap where the files are not restored but not backed up either?

Have we ever seen this for resources installed from the cloud - where the keyboard supposedly is installed but the local files are missing?

That said, I'll see if there's a simple-enough way to add a failsafe when the app is looking for the files.  It may be possible for those who have already updated to the current beta to have this problem in the future, since the version check would assume the backup logic already ran.  (Or I could just slip the build number into `Version.current` for the check?)

**Comment by mcdurdin** [comment]
> Have we ever seen this for resources installed from the cloud - where the keyboard supposedly is installed but the local files are missing?

Okay, maybe I'm misunderstanding... The only time this could happen from my current understanding was if the user restored their device from a backup, and then Keyman needed to reinstall certain files. Is that right?

> That said, I'll see if there's a simple-enough way to add a failsafe when the app is looking for the files. It may be possible for those who have already updated to the current beta to have this problem in the future, since the version check would assume the backup logic already ran. (Or I could just slip the build number into `Version.current` for the check?)

Somewhat confused here ... Not sure what this means :(

**Comment by jahorton** [comment]
To prevent any issues with the storage/backup change, a new control path has been added that conditions on version `13.0.65`, the likely beta version this PR will drop within.  (Absolute precision isn't necessary, fortunately.)  In previous installations of the app (which will have `13.0` or less), one final reinstallation occurs (see Migration.swift) so that the default resource files become marked for backup, unlike with prior installations.

This also pre-emptively fixes a bug with updating from versions without an explicit entry in the resource set history, which triggered while making this change.

**Pull request merged**
