### PR TITLE
chore: consolidate script helper functions

### PR DESCRIPTION
**Pull request by mcdurdin**
@keymanapp-test-bot skip

Refactors the following helper functions in shellHelperFunctions.sh:

* `log_error` --> remove, unused
* `log_warning` --> `builder_warn`
* `echo_heading` --> `builder_heading`
* `fail` --> `builder_die`
* `die` --> `builder_die`
* `warn` --> `builder_warn`

It may be easier to review this PR commit-by-commit.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Review by jahorton — APPROVED** [review]
The main concern I have here at the moment is that this is propagating `builder_` functions to non-builder-based scripts.

The color setting, in particular, is configured with the expectation of builder-style parameters... which are likely to be unsupported by such non-builder-based scripts.  Granted, this _is_ just a color thing, but might this have any ramifications for our CI builds or other parts of our tooling?  Just wondering, since we do have explicit logic and handling to ensure we can disable color-coding as part of `builder`.

Granted, a lot of the functions that are being merged into the newer `builder_` functions never did have an off-switch for their color... so maybe that's not actually an issue, then.  On further inspection... yeah, all of the previously-used functions never did have an "off".

----

So... tl;dr:  LGTM, I guess.  Still, I wanted to voice the concerns in case this might highlight a possible issue for not-yet-builder-based scripts.

**Comment by mcdurdin** [comment]
> So... tl;dr: LGTM, I guess. Still, I wanted to voice the concerns in case this might highlight a possible issue for not-yet-builder-based scripts.

All our scripts reference build-utils.sh, even if they are not yet builder-based, so it should be fine. Also, the color variables have all been defined in builder.inc.sh for some time, so this just completes that consolidation :grin:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.52-alpha](https://keyman.com/downloads/releases/alpha/17.0.52)

**Pull request merged**
