### PR TITLE
Update to Unicode 10.0

### PR DESCRIPTION
**Pull request by darcywong00**
Downloaded from ftp://ftp.unicode.org/Public/10.0.0/ucd/

### CODE REVIEW

**Comment by darcywong00** [comment]
@mcdurdin 
1. Does Unihan.txt and ethnologue.txt also need to be updated?
2. Where can we document how the Unicode characters get updated?

**Comment by darcywong00** [comment]
re: question 1, no action needed

**Comment by mcdurdin** [comment]
Document the unicodedata.txt update stuff in the keymanapp/keyman public wiki I guess?

**Comment by darcywong00** [comment]
Documented on the wiki

**Pull request merged**
