### PR TITLE
fix(android/engine): Display longpress keys during a Move gesture

### PR DESCRIPTION
**Pull request by darcywong00**
Addresses #5301 

~This PR is initially in Draft for @MakaraSok to characterize the behavior of 14.0 compared to this one.~
Currently, if a user starts a longpress gesture but moves off the initial base key, the longpress (subkeys) never show.
This is because the Keyman Engine for Android's use of GestureDetector isn't handling ACTION_MOVE when it interrupts ACTION_LONGPRESS.

This PR handles ACTION_MOVE during a longpress gesture to display subkeys (if available).

In talking with @mcdurdin , he said once longpress keys are displayed, it's ok to keep displaying the initial keys while the longpress is held. (We currently don't need to refresh to other longpress keys as the user drags to other keys)

KeymanWeb is also changed so the base key isn't updated if there's subkeys are being displayed. 
Previously, moving during the longpress would cause to longpress keys to update for the the final base key.
With this change, the longpress keys are locked into the original base key.

## User Testing
This needs to be tested on more than one device type

### Device Types
* **GROUP_WEB:** - Tests KeymanWeb desktop in mobile view
1. Load the PR build of KeymanWeb Test Home --> Manual Test pages --> Unminified KeymanWeb
2. Set the browser page to mobile viewport and hard refresh the page
3. Click the globe button on the keyboard and switch to Swedish (uses sil_euro_latin)
* **GROUP_ANDROID:** - Tests Android app
* **GROUP_IOS:** - Tests iOS app

### Tests
* **TEST_TOUCH_KEYS** - Tests the behavior of popup and longpress keys
1. Load the corresponding Keyman PR build of the group being tested
4. Enable Keyman as a system keyboard
5. Launch a separate app (e.g. Chrome or Safari) and select a field to start typing
6. With the default sil_euro_latin keyboard, select the symbolic layer
7. Short press a normal key <kbd>(</kbd>and release - verify `(` is output
8. Longpress a normal key <kbd>(</kbd>release - verify `(` is output
9. Longpress a key that contains longpress keys, and when the longpress keys display, move to an available longpress key and release - verify the selected longpress key is output
10. Longpress and move - Case 1:
    a. Longpress a key, but immediately move off the base key before the longpress registers. 
    b. While holding the longpress, verify longpress keys for the original base key are displayed
    c. Move to an available longpress key and release - verify the selected longpress key is output
11. Longpress and move - Case 2:
    a. Longpress a key, but immediately move off the base key before the longpress registers. 
    b. While holding the longpress, hold on a separate base key for a few seconds - verify longpress keys for the original base key are displayed
    c. Move to an available longpress key and release - verify the selected longpress key is output
12. Longpress and move - Case 3:
    a. Longpress a key, but immediately move off the base key before the longpress registers. 
    b. While holding the longpress, hold on a separate base key for a few seconds - verify longpress keys for the original base key are displayed
    c. Hold on the separate base key and release - verify nothing is output (only the longpress keys are eligible selections)

### CODE REVIEW

**Comment by darcywong00** [comment]
Initial feedback from @MakaraSok is that a key should immediately show preview before waiting a slight delay for longpress

**Comment by mcdurdin** [comment]
> Initial feedback from @MakaraSok is that a key should immediately show preview before waiting a slight delay for longpress

Correct. The key preview should always be instantaneous.

**Comment by MayuraVerma** [comment]
do we have longpress gesture in v15?
can output a character with longpress gesture without selecting the popup key?

**Comment by mcdurdin** [comment]
> do we have longpress gesture in v15?

What do you mean by a longpress gesture? Just a longpress on a key without movement? At present that is still the base key. We will be doing a lot more with gestures in 16.0, and that will be the appropriate time to review this.

**Comment by MayuraVerma** [comment]
With longpress, we are seeing the popup keys. Is it possible for longpress to output shift layer as output instead of popup keys?

**Comment by mcdurdin** [comment]
> With longpress, we are seeing the popup keys. Is it possible for longpress to output shift layer as output instead of popup keys?

This can be part of our 16.0 gesture work; see #6138; I will make note of this there.

**Comment by darcywong00** [comment]
I think this is ready to test and review

**Review by mcdurdin — APPROVED** [review]
LGTM!

**Comment by bharanidharanj** [comment]
### GROUP_WEB: - Tests KeymanWeb desktop in mobile view

* **TEST_TOUCH_KEYS (FAILED):** Tested this on Chrome Mobile emulator in Unminified Web page and this is working is fine except Case 3. Because, Hold on the Separate Key then release, Outputs the letter on the Text Area. 

Case 1: 
 

Case1C:
 

Case2C:
 

Case2LongPress:
 

Case3:

**Comment by bharanidharanj** [comment]
### GROUP_IOS: - Tests iOS app

* **TEST_TOUCH_KEYS (FAILED):** Tested this on iPhone 12 Pro (iOS 15.2) (on Safari browser) and it is failed due to the Original base key is missing while holding the key for few seconds.  (longpress). Also, Hold on the base key then release it would show the Output on the text area. 

Case1B:
 

Case2B:


Case3C: Hold on the separate key then release would outputs the letter on the text area

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: - Tests Android app

* **TEST_TOUCH_KEYS (PASSED):** Tested this issue in Android emulator API 30 and it is working as expected. 

Longpress and move - Case 1:


Longpress and move - Case 2:


Longpress and move - Case 3:

**Comment by bharanidharanj** [comment]
> @bharanidharanj Regarding GROUP_IOS, this doesn't address any iOS popup issues. Those are handled separately in #6383.
> 
> Do the iOS steps work as written? Holding on a base key and releasing should output the base key.
> 
> For GROUP_WEB, I cannot reproduce your Case 3 If I longpress y and quickly move to t and hold on t. Release on t and no character is output.

@darcywong00 Here, What I did is Hold on a separate base key for some time then release would show the base key letter on the text area. Okay, I will re-test this as per your suggestion in both Group_Web and Group-iOS and will post my result.

**Comment by bharanidharanj** [comment]
> @bharanidharanj Regarding GROUP_IOS, this doesn't address any iOS popup issues. Those are handled separately in #6383.
> 
> Do the iOS steps work as written? Holding on a base key and releasing should output the base key.
> 
> For GROUP_WEB, I cannot reproduce your Case 3 If I longpress y and quickly move to t and hold on t. Release on t and no character is output.

@darcywong00 On iOS, Holding on a base key then quickly move to some other key will not show any output.

**Comment by bharanidharanj** [comment]
### GROUP_WEB: - Tests KeymanWeb desktop in mobile view

* **TEST_TOUCH_KEYS (PASSED):** Re-tested this as per Darcy's instructions, Case 3 (Hold on the separate base key and release - verify nothing is output). ie., Hold on the separate base key then quickly move to some other key then release would show nothing as output in the text area.

**Comment by darcywong00** [comment]
I'll go ahead and merge this. The iOS popup key alignment is handled in separate PR.

**Comment by jahorton** [comment]
In post-mortem, this broke our "roaming touch" behavior on all mobile platforms - the behavior where key previews are shown for the key underneath the user's finger as they move it about the keyboard.  (So long as they wouldn't have triggered a longpress by that point, anyway.)

**Pull request merged**
