### PR TITLE
fix(windows): help links updated

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes:#12463

The help link passed to the opening of the keyman help(CHM) on windows was broken for a number of the help links. This updates them.
Note: no help exists for apEntryHelper so it was set to the main `index` instead

### CODE REVIEW

**Comment by mcdurdin** [comment]
> Note: no help exists for apEntryHelper so it was set to the main `index` instead

Was reserved for a feature that has never been implemented (requested recently again in #12562)

**Comment by rc-swag** [comment]
# User Testing
(taken from the original issue steps to reproduce)
Install Keyman from the PR build
TEST_ONSCREEN_KBD_1
1. Open the Keyman configuration app.
2. Navigate to the "Keyboard Layouts" tab.
3. Install one or two keyboards (e.g. Khmer Angkor, Imperial Aramaic)
4. Navigate to the systems page. Click the "Install Keyboard or Dictionary"
5. Open the OSK and then select the keyboard.
6. Click the help icon on the OSK window.
7. The "Keyman Help" dialog appears and click the "Help Contents" link button.
8. Expected Results: The Keyman for Windows User guide help appears here, and text on the right is Keyman Toolbox - On Screen Keyboard


TEST_FONT_HELPER
1. Open the OSK and then select the keyboard.
2. Click the font helper icon on the tool bar (has a "T" on it)
3. Click the help icon on the OSK window.
4. The "Keyman Help" dialog appears and click the "Help Contents" link button.
5. Expected Results: The Keyman for Windows User guide help appears here, and text on the right is Keyman Toolbox - Font Helper

TEST_CHARACTER_MAP

1. Open the OSK and then select the keyboard.
2. Click the character map icon on the tool bar (has a grid with letters)
3. Click the help icon on the OSK window.
4. The "Keyman Help" dialog appears and click the "Help Contents" link button.
5. Expected Results: The Keyman for Windows User guide help appears here, and text on the right is Keyman Toolbox - Character Map

**Comment by rc-swag** [comment]
> Was reserved for a feature that has never been implemented (requested recently again in #12562)

Thank you for the info. Otherwise I was going to raise an issue to remove it.

**Review by mcdurdin — APPROVED** [review]

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "18.0.137-alpha-test-12646" build on the Windows 10 and 11 OS. Here is my observation.

* **TEST_ONSCREEN_KBD_1 (Passed):** 
1. Installed the "keyman-18.0.137.exe" file. 
2. Keyman keyboard added in the system tray.
3. Open the keyman "Configuration" window.
4. Navigate to the "Keyboard Layouts" tab. 
5. Installed the "Khmer Angkor, Imperial Aramaic" keyboards by clicking the "Download keyboard" button.
6. Navigate to the systems page. Click "Install Keyboard or Dictionary."
7. Open the OSK and then select the keyboard.
8. Click the help icon on the OSK window.
9. The "Keyman Help" dialog appears, and click the "Help Contents" link button.

Verified that the "Keyman for Windows User Guide" help appeared. Focus appeared on the Keyman Toolbox—On-Screen Keyboard and help content displayed.
It works well.

* **TEST_FONT_HELPER (Failed):** 
1. Installed the "keyman-18.0.137.exe" file. 
2. Keyman keyboard added in the system tray.
3. Open the keyman "Configuration" window.
4. Navigate to the "Keyboard Layouts" tab. 
5. Installed the "Khmer Angkor, Imperial Aramaic" keyboards by clicking the "Download keyboard" button.
6. Navigate to the systems page. Click "Install Keyboard or Dictionary."
7. Open the OSK and then select the keyboard.
8. Click the font(T- view point helper) icon on the toolbar.
9. Click the help(?) icon on the OSK window.
10. The "Keyman Help" dialog appears and click the "Help Contents" link button.

Verified that the "Keyman for Windows User Guide" help appeared. Focus did not appear on the Keyman Toolbox—Font Helper and Help content displayed for OSK. It seems to not be correct.
The focus needs to be on an appropriate topic. 

* **TEST_CHARACTER_MAP (Failed):** 
1. Installed the "keyman-18.0.137.exe" file. 
2. Keyman keyboard added in the system tray.
3. Open the keyman "Configuration" window.
4. Navigate to the "Keyboard Layouts" tab. 
5. Installed the "Khmer Angkor, Imperial Aramaic" keyboards by clicking the "Download keyboard" button.
6. Navigate to the systems page. Click "Install Keyboard or Dictionary."
7. Open the OSK and then select the keyboard.
8. Click the font (grid, character map) icon on the toolbar.
9. Click the help(?) icon on the OSK window.
10. The "Keyman Help" dialog appears and click the "Help Contents" link button.

Verified that the "Keyman for Windows User Guide" help appeared. Focus did not appear on the Keyman Toolbox—Character Map and Help content displayed for OSK. It seems to not be correct.
The focus needs to be on an appropriate topic. 
I am seeing this behavior on window 10 and window 11 OS

**Comment by rc-swag** [comment]
Thank you @dinakaranr I have fixed this once the build is complete please retest
@keymanapp-test-bot retest TEST_FONT_HELPER TEST_CHARACTER_MAP

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "18.0.137-alpha-test-12646" build on the Windows 10 OS. I'm sharing my observation here.

* **TEST_FONT_HELPER (Passed):** 
1. Installed the "keyman-18.0.137.exe" file. 
2. Keyman keyboard added in the system tray.
3. Open the keyman "Configuration" window.
4. Navigate to the "Keyboard Layouts" tab. 
5. Installed the "Khmer Angkor, Imperial Aramaic" keyboards by clicking the "Download keyboard" button.
6. Navigate to the systems page. Click "Install Keyboard or Dictionary."
7. Open the OSK and then select the keyboard.
8. Click the font(T- viewpoint helper) icon on the toolbar.
9. Click the help(?) icon on the OSK window.
10. The "Keyman Help" dialog appears and click the "Help Contents" link button.
Verified that the "Keyman for Windows User Guide" help appeared. Focus appeared on the Keyman Toolbox—Font Helper and Help content displayed for "Font Helper". It seems to be correct now.

* **TEST_CHARACTER_MAP (Passed):**
1. Installed the "keyman-18.0.137.exe" file. 
2. Keyman keyboard added in the system tray.
3. Open the keyman "Configuration" window.
4. Navigate to the "Keyboard Layouts" tab. 
5. Installed the "Khmer Angkor, Imperial Aramaic" keyboards by clicking the "Download keyboard" button.
6. Navigate to the systems page. Click "Install Keyboard or Dictionary."
7. Open the OSK and then select the keyboard.
8. Click the font (grid, character map) icon on the toolbar.
9. Click the help(?) icon on the OSK window.
10. The "Keyman Help" dialog appears and click the "Help Contents" link button.
Verified that the "Keyman for Windows User Guide" help appeared. Focus appeared on the Keyman Toolbox—Character Map and Help content displayed for Character Map. It seems to be correct.
It works well. Thank you for fixing this behavior.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.139-alpha](https://keyman.com/downloads/releases/alpha/18.0.139)

**Pull request merged**
