### PR TITLE
fix(ios): resolves rough edges with installation view transitions

### PR DESCRIPTION
**Pull request by jahorton**
While #4332 resolves the worst-looking UI aspect of package installation, I noticed another rough edge during testing that fix.  In particular, the keyboard was displaying over the Settings menu after using "Install From File", instead of only once the settings menu was dismissed.

Took a little digging, hence newly written documentation and a field-name change or two for clarity, but I was able to resolve this through a new closure, allowing us to properly configure when the keyboard is displayed toward the end of the installation process.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.229-beta](https://keyman.com/downloads/releases/beta/14.0.229)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.230-beta](https://keyman.com/downloads/releases/beta/14.0.230)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
