### PR TITLE
fix(windows): ensure profiles are reinstalled during setup

### LINKED ISSUE #4725: bug(windows): Keyman setup is not reinstalling user language profiles during upgrade
**Describe the bug**

The installer runs a process in `TImportOlderVersionKeyboards11To13` where it removes existing profiles installed by Keyman 11, 12 or 13, and reinstalls them. It does this because the earlier profiles are 'enable by default' while we need them to be enabled separately in Keyman 14. 

However, due to a logical error, the 'reinstall' (`TImportOlderVersionKeyboards11To13.ImportCurrentUser`) never runs because the `TImportOlderVersionKeyboards11To13.ShouldRun` returns `False`, as the transient profiles that it tests for are installed in the previous step.

See description of symptoms in https://github.com/keymanapp/keyman/pull/4649#issuecomment-801759538

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 20H2 
 - Keyman version: 14.0.264-beta

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4725.

### CODE REVIEW

**Comment by mcdurdin** [comment]
# User Testing

Please re-run the upgrade procedure with this version to see that language profiles are installed successfully (per #4724 and https://github.com/keymanapp/keyman/pull/4649#issuecomment-801759538)

@MakaraSok

**Review by jahorton — APPROVED** [review]

**Comment by MakaraSok** [comment]
The upgrade from 12 stable to 14.0.266-beta-test-4727 went well and the existing keyboards in the older version are well populated in the keyboard menu.

image

Testing for 13 stable is pending...

**Comment by MakaraSok** [comment]
Upgrading from 13 stable is the same as that of 12 stable. No error experienced. The existing keyboards are also populated well after the upgrade.

image

**Comment by mcdurdin** [comment]
Thank you @MakaraSok you are so awesome!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.266-beta](https://keyman.com/downloads/releases/beta/14.0.266)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)

**Pull request merged**
