### PR TITLE
chore: bugfix cherrypick (#4208, #4210)

### PR DESCRIPTION
**Pull request by jahorton**
#4208 and #4210 were meant to be applied against the `beta` branch, but it appears they were merged with `master` instead.

### CODE REVIEW

**Comment by darcywong00** [comment]
Can you update the PR description to include the original PR numbers? (For the entry that gets added to history.md)

**Review by darcywong00 — APPROVED** [review]
lgtm (please update the PR title)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.219-beta](https://keyman.com/downloads/releases/beta/14.0.219)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)

**Pull request merged**
