### PR TITLE
fix(web): ios popup positioning and style

### LINKED ISSUE #5929: bug(web): longpress menus blend into underlying keyboard
The longpress menus do not look OK, esp. the ones with two rows of keys. The subkeys pop up under or right on the base instead of above.
   System keyboardː
   image

   In-app keyboardː
   image

Contrast with KeymanWeb: unlike the system and in-app keyboards, the subkeys look a lot better.
   image

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/5915#issuecomment-971404829_

### LINKED ISSUE #6381: bug(web): longpress popup has incorrect shape
**Describe the bug**

The longpress popup should be a single row of three keys in this example. However, it is showing on two rows.

image

**To Reproduce**

1. Using Keyman Developer Server, test Khmer Angkor on iPhone
2. Long press almost any key
3. See error

---

**KeymanWeb:**
 - OS: Windows 10 
 - Browser: Chrome 99 
 - KeymanWeb Version: 15.0.206-beta

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5929.
Fixes #6381.

This fixes four separate issues with the longpress popups and key previews:

1. The key preview was offset by a couple of pixels (unreported issue).
2. The background 'shim' did not cover the key caps, which caused them to look startlingly white when the rest of the background greyed down (#5929).
3. The popup menu was incorrectly wrapping to two rows due to sizing model mismatches (#6381).
4. The popup menu would be realigned incorrectly for the in-app keyboard, when moving it to keep it in the keyboard area (#5929).

Longpress iOS (Chrome simulation):

image

Key preview iOS (Chrome simulation): 

image

# User Testing

* We need to verify the behaviour of the longpress menu and the key preview. If possible, capture screenshots of both of these elements when running the tests, so we can compare.

* Suggest using sil_euro_latin keyboard for this test, as it has many big longpress menus.

* Test single-row long presses, such as long-press <kbd>m</kbd>, and multi-row, such as long-press <kbd>g</kbd> or <kbd>e</kbd>.

**TEST_IOS:** Verify that the in-app keyboard and system keyboard both display longpress menus and key previews correctly. Note that the longpress menu will be constrained to fit within the keyboard area on iOS, due to limitations with iOS system keyboards. Please test on iPhone 13 Pro and iPhone SE. Consider other devices also. Please test with 4 and 5 row keyboards.
**TEST_ANDROID:** Verify that the in-app keyboard and system keyboard both display longpress menus and key previews correctly.
**TEST_WEB_IOS:** Verify that the web keyboard in unminified/testing, on an iOS simulator or device, displays longpress menus and key previews correctly. Please test on iPhone 13 Pro and iPhone SE. Consider other devices also. Please test with 4 and 5 row keyboards.
**TEST_WEB_ANDROID:** Verify that the web keyboard in unminified/testing, on an Android emulator or device, displays longpress menus and key previews correctly.

### CODE REVIEW

**Comment by darcywong00** [comment]
# Test Results

* **TEST_ANDROID (PASSED):** Popup and longpress keys appear normal

In-app popup key
inapp-popup

In-app longpress keys
inapp-longpress

System popup key
system-popup

System longpress keys
system-longpress

**Comment by bharanidharanj** [comment]
* **TEST_IOS (PASSED):** Tested on iOS 15.2 Simulator and it is working as expected. 

In-App Key Preview
 

System Keyboard Key Preview

 

In-App Key Long Press (single row)

 

In-App Key Long Press (multiple rows)



System Keyboard Long Press (single row)



System Keyboard Long Press (multiple rows)

**Comment by bharanidharanj** [comment]
* **TEST_WEB_ANDROID (PASSED):** Tested this on Android Emulator (API 29 - Version 10.0) and it is working as expected. 

Key Preview - Unminfied Page
 

Long Press Single Row - Unminified Page
 

Long Press Multiple Rows - Unminified Page

**Comment by bharanidharanj** [comment]
* **TEST_WEB_IOS (PASSED):** Tested this on iOS 15.2 Simulator in the Keyman Web page and it is working as expected. 

Key Preview - Unminified Page


Long Press - Single row -Unminified Page 


Long Press - Multiple rows - Unminified Page

**Review by ermshiperete — APPROVED** [review]

**Comment by mcdurdin** [comment]
Hmm, the positioning is certainly better than before. But it doesn't look quite right on KeymanWeb in iOS and Keyman for iOS. So will have another round.

## Key Preview, Keyman for iOS

image

image

## Longpress, Keyman for iOS

image

## Key Preview, KeymanWeb on Safari / iOS

image

## Longpress, KeymanWeb on Safari / iOS

image

**Comment by mcdurdin** [comment]
So I've done another round of tweaks to the positioning to try and get it working better. I have tested locally on my test build with Chrome on Windows (emulation and in developer frame), and in Safari on iOS, but not yet in iOS app.

But this sadly means retesting everything, so sorry @bharanidharanj and @darcywong00! The screenshots were very helpful, please keep them coming.

@keymanapp-test-bot retest all

**Comment by darcywong00** [comment]
* **TEST_ANDROID (PASSED):** Round 2 passed on Pixel 2 emulator with Android API 29

inapp keyboard - popup
inapp-popup

inapp keyboard - longpress
inapp-longpress

system keyboard - popup
system-popup

system keyboard - longpress
system-longpress

**Comment by bharanidharanj** [comment]
* **TEST_WEB_ANDROID (PASSED):** Re-tested this on Android emulator (API 30) in Unminified Page and it seems to be working as expected. 

Unminified Page - Popup
 


Unminified Page - Long Press

**Comment by bharanidharanj** [comment]
* **TEST_IOS (PASSED):** Tested this on iPhone 13 Pro (iOS 15.2) Simulator and the long press functionality seems to be deviated from the alignment. I don't know whether my assumption is right or wrong.

In-App - Popup
 

In-App - Long Press
 

System Keyboard - Popup
 

System Keyboard - Long Press

**Comment by bharanidharanj** [comment]
* **TEST_WEB_IOS (PASSED):** Tested this on iPhone 13 Pro Simulator (iOS 15.2) in Unminified Page and it seems to be working as expected. 

System Keyboard - Popup
 

System Keyboard - Long Press (Single row)
 

System Keyboard - Long Press (Multiple row)

**Comment by mcdurdin** [comment]
> * **TEST_IOS (PASSED):** Tested this on iPhone 13 Pro (iOS 15.2) Simulator and the long press functionality seems to be deviated from the alignment. I don't know whether my assumption is right or wrong.

Yes, this doesn't look right... 😢 

TEST_IOS FAILED

**Comment by mcdurdin** [comment]
Okay, I've fixed up the issues with the callout positioning on iOS.

@keymanapp-test-bot retest TEST_IOS

**Comment by MakaraSok** [comment]
TEST_IOS (FAILED): the alignment on the key when long pressed looks better, but the visible border between the base key and the subkey is still seen on the first row, i.e. key <kbd>q</kbd>, <kbd>w</kbd>, <kbd>r</kbd>, <kbd>t</kbd>, <kbd>y</kbd> and <kbd>p</kbd>. 

### in both in-app and system
The visible border between the preview key and its base key is seen on all rows. The preview key doesn't seen to be fully aligned center. The right part of the key looks longer than that of the left.
1st row
visible border - 1st row

2nd row
visible border - 2nd row

3 row
visible border - 3rd row

The visible border between the subkey and its base is seen on the 1st row only, but not the 2nd and 3rd. No alignment issue seen though, AFA I can tell.
1st row
visible border - 1st - sub:base


2nd row
no visble border - 2nd row - sub:base


3rd row
no visble border - 3rd - sub:base

---

### Bonus screen recording if they help in anyway.

in-app

https://user-images.githubusercontent.com/28331388/159399066-a35bad9a-4ff5-4255-94eb-9828dda5ad73.mov



system


https://user-images.githubusercontent.com/28331388/159399095-4aa55f5e-121c-44c8-a810-057567c38c01.mov

**Comment by mcdurdin** [comment]
Okay, I've tweaked the positions slightly with the latest commit. Can you check these again per spec?

Sample key preview from Safari on iOS (zoomed):

image

@keymanapp-test-bot retest TEST_IOS TEST_WEB_IOS

**Comment by bharanidharanj** [comment]
* **TEST_IOS (PASSED):** Re-tested this in iPhone 13 Pro (iOS 15.2)  Simulator with the new PR (iOS) and it seems to be working as  expected. 

In-App - Popup:


In-App - LongPress (Single row):
 

In-App LongPress (Multiple rows):
 

System Keyboard - popup:
 

System Keyboard - Long Press (Single row):
 

System Keyboard - Long Press (Multiple rows):

**Comment by bharanidharanj** [comment]
* **TEST_WEB_IOS (PASSED):** Tested this in Unminified page on iPhone 13 Pro Simulator and it seems to be working fine. 
Note: It is also working fine even in the Caps Lock is one. 

Unminified Page : Popup


Unminified Page : Long Press (Single row)


Unminified Page : Long Press (Multiple rows)

**Comment by mcdurdin** [comment]
Okay, I've tried again and tested locally on both iPhone SE 3rd gen and iPhone 13 Pro to cater to the different resolutions. We should probably test against both those devices and with more than one keyboard -- the subpixel calculations can mask issues on different resolutions.

@keymanapp-test-bot retest TEST_IOS TEST_WEB_IOS

**Comment by bharanidharanj** [comment]
> Okay, I've tried again and tested locally on both iPhone SE 3rd gen and iPhone 13 Pro to cater to the different resolutions. We should probably test against both those devices and with more than one keyboard -- the subpixel calculations can mask issues on different resolutions.
> 
> @keymanapp-test-bot retest TEST_IOS TEST_WEB_IOS

@mcdurdin Okay.

**Comment by bharanidharanj** [comment]
* **TEST_IOS (FAILED):** Re-tested this in iPhone 13 Pro (iOS 15.2)  Simulator with the updated PR (iOS) and I noticed that while long pressing the top row buttons the key tip has wrong bottom alignment as mentioned by Marc. (in his previous comments)

In-App - Popup:
 

In-App - LongPress (Single row):
 

In-App - LongPress (Multiple rows):


System Keyboard - popup:
 

System Keyboard - Long Press (Single row):
 

System Keyboard - Long Press (Multiple rows):

**Comment by bharanidharanj** [comment]
* **TEST_WEB_IOS (PASSED):** Tested this in Unminified page on iPhone 13 Pro Simulator and it seems to be working as expected.

Unminified Page : Popup
 

Unminified Page : Single row
 

Unminified Page : Multiple rows

**Comment by mcdurdin** [comment]
> * **TEST_IOS (FAILED):** Re-tested this in iPhone 13 Pro (iOS 15.2)  Simulator with the updated PR (iOS) and I noticed that while long pressing the top row buttons the key tip has wrong bottom alignment as mentioned by Marc.

Good catch! I missed that when I was re-testing. Okay, I have put in a fix for that, can you retest please?

@keymanapp-test-bot retest TEST_IOS

**Comment by bharanidharanj** [comment]
> > * **TEST_IOS (FAILED):** Re-tested this in iPhone 13 Pro (iOS 15.2)  Simulator with the updated PR (iOS) and I noticed that while long pressing the top row buttons the key tip has wrong bottom alignment as mentioned by Marc.
> 
> Good catch! I missed that when I was re-testing. Okay, I have put in a fix for that, can you retest please?
> 
> @keymanapp-test-bot retest TEST_IOS

@mcdurdin Okay. I will re-test it. Thanks.

**Comment by bharanidharanj** [comment]
* **TEST_IOS (FAILED):** Retested this with the attached PR build (Keyman 15.0.211-beta-6383) in iPhone SE and the key tip has wrong bottom alignment in Longpress (Multiple rows). I am seeing the same result in iPhone 13 Pro Simulator too. 

In-App (Popup)
 

In-App - Long Press (Single row)


In-App - Long Press (Multiple rows)


System Keyboard - Popup


System Keyboard - Long Press (Single row)


System Keyboard - Long Press (Multiple rows)

**Comment by mcdurdin** [comment]
> * **TEST_IOS (FAILED):** Retested this with the attached PR build (Keyman 15.0.211-beta-6383) in iPhone SE and the key tip has wrong bottom alignment in Longpress (Multiple rows). I am seeing the same result in iPhone 13 Pro Simulator too.

TEST_IOS (PASSED): I am comfortable with going ahead with that very minor artifact. Thank you for your attention to detail :grin:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.223-beta](https://keyman.com/downloads/releases/beta/15.0.223)

**Pull request merged**
