### PR TITLE
feat(windows): emit keystrokes for imx keydown/up actions 🥑

### LINKED ISSUE #6099: feat(windows):  Emit keystrokes from IMX dll call backs - keystroke processing optimization  🥑
The Simplified Chinese Keyboard wants to generate an "Enter" key using KEY_DOWN and KEY_UP actions, to work with the core integration we need to convert this to an emit keystroke action. 
This however is hard to do with the IMX dll (3rd party library) and the way the windows API works. Windows wants to know on the first test of keystroke if the Keyman will consume the keystroke or not. Currently, we can't know this without actually calling back to the IMX dll. However, we can't do that twice.  -- Essentially we will use this to make an optimisation in which the core processing of each keystroke will only be done once and cache the result. Actions will be applied on the second pass off the keystroke.

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes #6099

Moving this testing to #5936  As that branch needs this work merged to proceed.

@keymanapp-test-bot skip

# Needs CapsTest User Testing

SUITE_SIMPLIFIED_CHINESE:
This keyboard will display the IMX window as soon as a string that matches the pinyin for one or more characters are typed.
For all these tests install the Simplified Chinese Keyboard cs-pinyin.cmp

TEST_SIMPLIFIED_ENTER_KEY:
Using Notepad or equivalent.
Type h a n z i - The IMX window will appear and in the top left the letters hanzi will be present
Choose the 5th option
Expected result: 汉字变换
Type `Enter`
The cursor should be on a new line.
Type `hanzi` and press Enter
Expected Result:
汉字变换
汉子

### CODE REVIEW

**Comment by mcdurdin** [comment]
This is currently failing to build on most platforms. Some suggestions:

* **Test-14.0 (Keyman - Windows (Desktop/Developer))**

  1. Build failure is fixed by a workaround for a bug in npm that has recently been merged to master.
  2. Update your local master
  3. `git merge master`
  4. Push 

* **Test-14.0 (Keyman - Linux)**
* **Test-14.0: Keyman Core - Linux (Common)**
* **Test-14.0: Keyman Core - macOS (Common)**

    All three of these have the same root cause.

    ```
    [15:36:38][Step 2/4] [3/57] Compiling C++ object 'src/kmnkbp0@sha/km_kbp_keyboard_api.cpp.o'.
    [15:36:38][Step 2/4] FAILED: src/kmnkbp0@sha/km_kbp_keyboard_api.cpp.o 
    [15:36:38][Step 2/4] c++  -Isrc/kmnkbp0@sha -Isrc -I../../../../common/core/desktop/src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++14 -O3 -fPIC -isystem ../../../../common/core/desktop/include -isystem include -DKMN_KBP_EXPORTING -Wall -Wctor-dtor-privacy -Wdouble-promotion -Wendif-labels -Wextra -Wno-unknown-pragmas -Wno-missing-field-initializers -Wnon-virtual-dtor -Wshadow -fvisibility=hidden -fvisibility-inlines-hidden -MD -MQ 'src/kmnkbp0@sha/km_kbp_keyboard_api.cpp.o' -MF 'src/kmnkbp0@sha/km_kbp_keyboard_api.cpp.o.d' -o 'src/kmnkbp0@sha/km_kbp_keyboard_api.cpp.o' -c ../../../../common/core/desktop/src/km_kbp_keyboard_api.cpp
    [15:36:38][Step 2/4] In file included from ../../../../common/core/desktop/src/km_kbp_keyboard_api.cpp:16:0:
    [15:36:38][Step 2/4] ../../../../common/core/desktop/src/kmx/kmx_processor.hpp:64:5: error: extra qualification ‘km::kbp::kmx_processor::’ on member ‘queue_action’ [-fpermissive]
    [15:36:38][Step 2/4]      kmx_processor::queue_action(
    [15:36:38][Step 2/4]      ^~~~~~~~~~~~~
    ```

**Comment by mcdurdin** [comment]
This seems to extend feat/windows/imx-support-common-core but is not currently based on it, meaning we'd have to review a lot of code twice. Can you rebase?

**Comment by rc-swag** [comment]
> This seems to extend feat/windows/imx-support-common-core but is not currently based on it, meaning we'd have to review a lot of code twice. Can you rebase?

It is cut feat/windows/imx-support-common-core from so should not need rebasing.  It had the wrong target for merge it was for master instead of the `feat/windows/imx-support-common-core`. I will fix that.

**Comment by rc-swag** [comment]
> This is currently failing to build on most platforms. Some suggestions:
> 
> * **Test-14.0 (Keyman - Windows (Desktop/Developer))**
>   
>   1. Build failure is fixed by a workaround for a bug in npm that has recently been merged to master.
>   2. Update your local master
>   3. `git merge master`
>   4. Push

I fixed the linux / macos comments. I will hold off merging master untill you have a chance to review as it will show the differences between `feat/windows/imx-support-common-core` and master which you don't want to see in the initial review

**Review by mcdurdin — APPROVED** [review]

**Pull request merged**
