### PR TITLE
feat(android): Spacebar text controls

### PR DESCRIPTION
**Pull request by mcdurdin**
Relates to #949.

* Adds setSpacebarText() API to Keyman Engine for Android
* Adds displayName API to Keyman Engine for Android
* Adds Preference for spacebar text to Keyman for Android
* Sets default spacebar text to keyboard name for FirstVoices Keyboards

New settings preference:
image

Touching that preference shows:
image

Result:
image

### CODE REVIEW

**Comment by darcywong00** [comment]
When I use the "Spacebar caption" menu, I see the change in the spacebar (From default "English - EuroLatin (SIL)" to something else).

But when I enter the globe button and exit out, I see the keyboard refresh and revert to "English - EuroLatin(SIL)"

**Comment by mcdurdin** [comment]
> But when I enter the globe button and exit out, I see the keyboard refresh and revert to "English - EuroLatin(SIL)"

I believe fixed now (along with a couple of other things).

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.80-alpha](https://keyman.com/downloads/releases/alpha/15.0.80)

**Pull request merged**
