### PR TITLE
fix(developer): two small issues in kmdecomp

### PR DESCRIPTION
**Pull request by mcdurdin**
1. build paths when loaded as part of solution were incorrect
2. decompiling `if` statements did not work for `!=`

### CODE REVIEW

**Comment by darcywong00** [comment]
Side question - how does kmdecomp handle syntax added in 14.0?  (e.g. cased keys, `..`)?

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
> Side question - how does kmdecomp handle syntax added in 14.0? (e.g. cased keys, `..`)?

- `&CasedKeys` was added to kmdecomp in 14.0.
- `..` is expanded at compile time, so this source `'a' .. 'f'` would be expanded in the .kmx, then decompiled to `'abcdef'`.

**Comment by mcdurdin** [comment]
I won't cherry-pick this to stable-14.0 as it is a low-priority fix.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.44-alpha](https://keyman.com/downloads/releases/alpha/15.0.44)

**Pull request merged**
