### PR TITLE
[Web] SuggestionBanner touch support, test page

### PR DESCRIPTION
**Pull request by jahorton**
Based on #1704.

This PR duplicates existing OSK touch handlers for use with the SuggestionBanner, but then refactors and redesigns the whole thing into something more abstract and OO-friendly.  While this won't be immediately tied back into the OSK itself, the design should hold up and be useful there when we have time to merge that.

Of course, the current priority is predictive text support, and so that's what received the focus here.  As we're not yet doing longpress menus but have plans in that direction, related methods have been designed and written, but left with minimal/'stub' implementations for the time being.

In-browser testing in Chrome (for Android/iOS modes) shows that this properly highlights the expected Suggestion and will trigger application of the Suggestion when an appropriate touch is released.  The issue at this point:  having fully-formed Suggestions to apply.

---

For in-browser testing, please direct your attention to the new **web/testing/prediction-ui/index.html**.  This provides us the first fully-linked testing platform for the predictive text feature.

To enable this, the page makes use of the prototype English wordlist resource from the LMLayer's unit test for now.  Very basic, but it's enough to get us something presentable and easily usable.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148982:id/kvk/index.html)

**Comment by mcdurdin** [comment]
In testing, mostly looks good (although I cannot tell which suggestion was unable to be applied from the error message), except when dragging off suggestion 2 or 3, and down into the keyboard in which case the first suggestion gets highlighted (and subsequently applied when I 'lift' my finger).

If I drag up into the content area, the first suggestion is not highlighted, but a suggestion is still applied when my finger is 'lifted'.

What should happen is that the highlight disappears and the suggestion is cancelled, once we move outside the boundaries of the target.

**Comment by jahorton** [comment]
Good points.  I've taken another look at the relevant sections and patched things up; things should be more intuitive in that regard now, though there is a minor fudge factor so that average users don't have to be exacting with their inputs.  (I used the analogous existing fudge factor from the OSK's check, which seems pretty reasonable.)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/149090:id/kvk/index.html)

**Comment by jahorton** [comment]
Turns out that very little needed fixing to get a first viable testing page up and working, so I merged that feature into this branch directly.

**Comment by darcywong00** [comment]
I think if you update your npm version, then there won't be changes to package-lock.json

**Comment by eddieantonio** [comment]
Good PR! I like seeing the suggestion banners with actual suggestions! Dumb question: are the touch events supposed to apply the suggestions in this PR? It doesn't seem to be work for me, despite enabling `touchstart` event listeners. I even tried this on my actual, honest-to-goodness smartphone!

**Comment by mcdurdin** [comment]
> are the touch events supposed to apply the suggestions in this PR? It doesn't seem to be work for me, despite enabling `touchstart` event listeners. I even tried this on my actual, honest-to-goodness smartphone!

I believe @jahorton is looking into this; it is supposed to be working; this may be related to another PR merged for Android support.

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/149361:id/kvk/index.html)

**Comment by jahorton** [comment]
I just identified a kludge workaround for the Android touch event issues - there's some weirdness around old `devicePixelRatio` code that was causing those touch events to be blocked by the keyboard's (key input) handlers.

**Comment by eddieantonio** [comment]
Huzzah! It works for me on Android and Chrome (with 2x displayPixelRatio).

:shipit:

**Pull request merged**
