### PR TITLE
fix(web): popupBaseKey null check

### LINKED ISSUE #5912: bug(web): TypeError: undefined is not an object (evaluating 'this.popupBaseKey.id')
Sentry Issue: [KEYMAN-WEB-M](https://sentry.io/organizations/keyman/issues/2788919663/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'this.popupBaseKey.id')
  at None (/keyman.js:811:401)
  at None ([native code])
```

Corresponds to line 1221 below:

https://github.com/keymanapp/keyman/blob/a7580a2fdfe92a4f8a013c363c1dfc67acbd9167/web/source/osk/visualKeyboard.ts#L1207-L1227

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5912.

Corresponds loosely to #5949.

# User Testing

* TEST_ANDROID: Verify that popup keys work correctly on Keyman for Android. Try various ways of using them and sliding on/off them
* TEST_IOS: Verify that popup keys work correctly on Keyman for iPhone and iPad. Try various ways of using them and sliding on/off them
* TEST_WEB: Verify that popup keys work correctly on KeymanWeb in touch mode (Chrome emulation okay). Try various ways of using them and sliding on/off them. Use the testing/unminified page.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
* **TEST_ANDROID: FAILED?** It's impossible to roll back to the base key and use it. When rolling back to the base key, the first subkey is selected and output instead.

   image

* **TEST_IOS: FAILED?** It's impossible to roll back to the base key and use it. When rolling back to the base key, the first subkey is selected and output instead.

   image


* **TEST_WEB: FAILED?** (tested in Chrome on Windows and macOS) It is impossible to roll back to the base key and output the character on the base key after the subkeys appears. The first subkey on the list was triggered instead.

   On Windows:
   image

   On macOS:
   image

**If these are by designed, please considered all tests as PASSED.**

**Comment by mcdurdin** [comment]
> * It is impossible to roll back to the base key and output the character on the base key after the subkeys appears. The first subkey on the list was triggered instead.

This is not correct, but this issues is also present in `stable-14.0`, so I think that this fix is still good. Note that 15.0 has resolved the reported issue.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.284](https://keyman.com/downloads/releases/stable/14.0.284)

**Pull request merged**
