### PR TITLE
chore: merge beta to master (A15S1)

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Comment by darcywong00** [comment]
This is missing the auto-generated HISTORY.md update

**Comment by mcdurdin** [comment]
> This is missing the auto-generated HISTORY.md update

It will resolve with time; I'm not bothered 😁

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.21-alpha](https://keyman.com/downloads/releases/alpha/15.0.21)

**Pull request merged**
