### PR TITLE
fix(web): Don't configure if banner is undefined

### LINKED ISSUE #4794: bug(web): postConfigure on undefined
Sentry Issue: [KEYMAN-ANDROID-RQ](https://sentry.keyman.com/organizations/keyman/issues/4233/?referrer=github_integration)

```
sendKMWError
```

More info from the Sentry error

KMKeyboard.sendKMWError
packageID: indonesia
keyboardID: indonesia
keyboardType: SYSTEM
cm_message: Could not load model 'benny_lin.id.kamus_indonesia': Cannot read property 'postConfigure' of undefined
cm_sourceID: file:///data/data/com.tavultesoft.kmapro.debug/app_data/keyman-sentry.js
keyboardName: Indonesia
cm_lineNumber: 208

### PR DESCRIPTION
**Pull request by darcywong00**
This fixes #4794 where a Sentry error was happening while toggling from **sil_euro_latin** (predictions enabled) with **indonesia** (predictions disabled)

### CODE REVIEW

**Review by jahorton — CHANGES_REQUESTED** [review]
If `state` == 'configured', something is _very_ wrong if `suggestionBanner` is not defined.  Honestly... it's pretty 'wrong' to even need the currently-existing check.

We should investigate how the erroneous scenario is arising.

**Comment by darcywong00** [comment]
If the banner is disabled due to override, wouldn't it be `undefined`?

**Comment by jahorton** [comment]
> due to override

... I'm missing something here.  Overridden _how_?  I'm pretty sure the value should _always_ hold a banner type - "blank", "image", or "suggestion".  I don't recall there being any sort of overriding mechanism.

**Comment by darcywong00** [comment]
> ... I'm missing something here. Overridden how? I'm pretty sure the value should always hold a banner type - "blank", "image", or "suggestion". I don't recall there being any sort of overriding mechanism.

I mean when the "Enable predictions" override is off (e.g. predictions disabled).

The keyboard swap triggers a model swap, right? What behavior do you see on iOS?

**Comment by jahorton** [comment]
> > ... I'm missing something here. Overridden how? I'm pretty sure the value should always hold a banner type - "blank", "image", or "suggestion". I don't recall there being any sort of overriding mechanism.
> 
> I mean when the "Enable predictions" override is off (e.g. predictions disabled).
> 
> The keyboard swap triggers a model swap, right? What behavior do you see on iOS?

It swaps cleanly between the `BlankBanner` and `SuggestionBanner` (both from `banner.ts`).  No issues, error messages, or anything of the sort.

**Comment by darcywong00** [comment]
It's possible this was also fixed by #4840. Will continue to monitor Sentry...

**Comment by jahorton** [comment]
Looks like the underlying issue isn't fixed yet, based on [Sentry issue `KEYMAN-ANDROID-QZ`](https://sentry.keyman.com/share/issue/e5f14b653a25419d81557e88dc7bb688/).

**Comment by darcywong00** [comment]
Abandoning this for #4961

**Pull request closed without merging**
