### PR TITLE
fix: remove saving and restoring context kbd options

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes: #7074

This PR removes the saving of context and keyboard options
on the non-updateable call to process hook when using the core processor.

The windows Text Input Processor calls twice for each keystroke the first call is not updatable. With the core integration we run
the processor only once - the actions and the context are available to be applied on the updatable call.
Saving and restoring the options meant that the stores values were overwritten and seeing as the process event call was not called again the stores changed value was lost.

### CODE REVIEW

**Comment by rc-swag** [comment]
# User Testing

Install the keyman for windows build associated with this PR
**TEST_21_OPTION:**
1. Install [021 - options.zip](https://github.com/keymanapp/keyman/files/9356095/021.-.options.zip)
2. Open Notepad
3. Select  021-options.kmx as the current keyboard.
4. Type <kbd>a</kbd><kbd>1</kbd><kbd>a</kbd><kbd>0</kbd><kbd>a</kbd>

Expected Result: "no foo.foo.no foo"

**TEST_COMMUNITY_KBD:**
1. Install [test.kmx.zip](https://github.com/keymanapp/keyman/files/9356082/test.kmx.zip)
2. Open Notepad
3. Select  test.kmx as the current keyboard.
4. Type <kbd>a</kbd><kbd>a</kbd><kbd>a</kbd><kbd>=</kbd><kbd>=</kbd><kbd>a</kbd><kbd>a</kbd><kbd>a</kbd><kbd>=</kbd><kbd>=</kbd><kbd>a</kbd><kbd>a</kbd><kbd>a</kbd><kbd>=</kbd><kbd>=</kbd><kbd>a</kbd><kbd>a</kbd><kbd>a</kbd>

Expected Result: "aaaAAAaaaAAA"

**Comment by mcdurdin** [comment]
Looks good, I love the simplification of the code! I would like to see some user tests about context checks given this also changes the way we handle context.

**Comment by mcdurdin** [comment]
Once we approve and merge this, we need a cherry-pick to stable-15.0

**Review by mcdurdin — APPROVED** [review]
Approving this, but please do add the extra user test for context changes!

**Comment by rc-swag** [comment]
> extra user test for context changes!

Absolutely see this - issue https://github.com/keymanapp/keyman/issues/7078. I went back to versions where process_event at the core level was called both times [!Updateable/Updateable] and it still had this issue. 
Feel free to comment on some context test cases I may miss.

**Comment by bharanidharanj** [comment]
* **TEST_21_OPTION (PASSED):** Tested this as per the instructions and it is working as expected. 

   

* **TEST_COMMUNITY_KBD (PASSED):** Tested this as per the instructions and it is working as expected.

**Comment by mcdurdin** [comment]
> Feel free to comment on some context test cases I may miss.

I think we need some more user tests in this PR for context changes, if that's ok.

**Comment by bharanidharanj** [comment]
* **TEST_OUTPUT_KEYSTROKE (PASSED):** Downloaded the Corresponding Keyboard and tested as per the instructions. It is working as expected. 
* **TEST_IF_AND_CONTEXT (PASSED):** Downloaded the Corresponding Keyboard and tested as per the instructions. It is working as expected. 
* **TEST_DEADKEY_AND_CONTEXT (PASSED):** Downloaded the Corresponding Keyboard and tested as per the instructions. It is working as expected. 
* **TEST_DEADKEY_AND_CONTEXT_EX (PASSED):** Downloaded the Corresponding Keyboard and tested as per the instructions. It is working as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.49-alpha](https://keyman.com/downloads/releases/alpha/16.0.49)

**Pull request merged**
