### PR TITLE
chore(common): support forked repos when triggering test builds

### PR DESCRIPTION
**Pull request by mcdurdin**
This change allows branches from forked repos to trigger test builds.

Note: this will not be run automatically, but only when we manually tell it to run in TeamCity.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by jahorton — COMMENTED** [review]
> Note: this will not be run automatically, but only when we manually tell it to run in TeamCity.

Where's the mechanism that handles this logic?

**Comment by mcdurdin** [comment]
> > Note: this will not be run automatically, but only when we manually tell it to run in TeamCity.
> 
> Where's the mechanism that handles this logic?

In the TeamCity build configuration (can't be in-repo!)

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.119-alpha](https://keyman.com/downloads/releases/alpha/15.0.119)

**Pull request merged**
