### PR TITLE
fix(web): font size was not consistently set

### LINKED ISSUE #5731: bug(web): `getIdealFontSize` is slow
The call to `getComputedStyle` is very expensive; it [forces a reflow](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing?utm_source=devtools#avoid-forced-synchronous-layouts) for every key on the layout.

https://github.com/keymanapp/keyman/blob/dd15e68a0ea5954317f36b1b024d1c06a3ab2e9c/web/source/osk/oskKey.ts#L304

For example, on my machine with khmer_angkor, this one call costs 25% of the total time for `refreshLayout()`; an additional 25% is spent with a similar style recalculation at:

https://github.com/keymanapp/keyman/blob/dd15e68a0ea5954317f36b1b024d1c06a3ab2e9c/web/source/osk/oskRow.ts#L75

This also seems much slower on desktop osk presentation than on mobile osk presentation.

### LINKED ISSUE #5779: bug(web): some keys are not fully visible when testing OSK in Chrome emulator
**Describe the bug**

When tested `khmer_angkor` keyboard on Chrome emulator, some keys on the Shift layer are cropped off.

Windows/macOS/Linux desktop

No touch device has this issue.

**Expected behavior**

The character on each cap should be readability, nothing is cropped off.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman Developer version: 15.0.113.0 from the build of this PR https://github.com/keymanapp/keyman/pull/5723

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5779.
Fixes #5731 (I believe mitigation is sufficient to close this issue).

A variety of interrelated font and font size display issues resolved:
1. KVK font was not applied early enough for size calculations, which meant that we were calculating font scaling per key based on a default font when transforming from the KVK data for desktop devices (defaultLayout.ts)
2. Font scaling for non-default layers was calculated when elements were not visible and had no size information, giving incorrect values. To resolve this, font scaling is now calculated when a layer is made visible, which had performance impacts; resolved by reducing unnecessary `layer.refreshLayout()` calls; see performance point 1 below (oskView.ts:layerChangeHandler())
3. `getViewportScale()` would return an incorrect scaled value when emulating touch devices on a desktop browser (kmwutils.ts)
4. After switching keyboards, the device-specific scaling factor was not maintained (oskView.ts:refreshLayout())

Related performance improvements:
1. Multiple calls to `layer.refreshLayout()` in `refreshLayout()` have been eliminated, and only the currently visible layer is now refreshed. This dramatically reduces the number of calls to `getIdealFontSize()` which was the primary concern of #5731. (visualKeyboards.ts)
2. Unnecessary use of `innerHTML` replaced with `innerText` (oskBaseKey.ts)

Minor Keyman Developer performance improvement:
1. The web debugger no longer recalculates the OSK twice (test.js)

image

# User Testing

I am sorry that we need to run these tests across so many devices. However, there have been repeated issues with font scaling and there is special-case code for each platform, so we do need to do these tests.

## SUITE_DEVELOPER: Test the web debugger in Keyman Developer

The web debugger in Developer currently runs only on desktop devices (see #5905). We need to test that the presentation of various Keyman keyboards is still working correctly here. You should not need to use Chrome Developer Tools to run these tests.

* TEST_KHMER_ANGKOR: Test that the Khmer Angkor keyboard renders correctly in the web debugger in each of the available device views. Check multiple layers, not just the default layer.
* TEST_OTHER_KEYBOARDS: Select a variety of keyboards - your choice - and verify that they display correctly in the web debugger. Note the keyboards that you test.

## SUITE_COMPAT: Test that these changes are compatible across a range of devices

Here we want to check that KeymanWeb now displays the on screen keyboard correctly in a variety of contexts. For these groups, use KeymanWeb Unminified test page:

* GROUP_WINDOWS_CHROME: KeymanWeb in Chrome on Windows
* GROUP_WINDOWS_FIREFOX: Firefox on Windows
* GROUP_MACOS_CHROME: Chrome on macOS
* GROUP_LINUX_FIREFOX: Firefox on Linux

* GROUP_IPAD_SAFARI: Safari on iPad (not Chrome emulation; iOS simulator okay)
* GROUP_IPHONE_SAFARI: Safari on iPhone (not Chrome emulation; iOS simulator okay)
* GROUP_ANDROIDPHONE_CHROME: Chrome on Android phone
* GROUP_ANDROIDTABLET_CHROME: Chrome on Android tablet

The tests:

* **TEST_BASELINE:** Check each of the keyboard in the unminified test page; make sure that different layers render correctly.
* **TEST_KHMER_ANGKOR:** Load the Khmer Angkor keyboard by entering 'khmer_angkor' into the "Add a keyboard by keyboard name" field and clicking Add. Verify that it too displays correctly.
* **TEST_CHOICE:** Choose a keyboard of your own liking to test -- this helps to verify that keyboards I haven't considered are also working correctly.

## SUITE_APPS: Test that these changes are compatible in Keyman apps on Android and iOS

For these groups, use the Keyman app on each device:

* GROUP_IPAD_NATIVE: Keyman 15.0 on iPad (not Chrome emulation, but simulator okay)
* GROUP_IPHONE_NATIVE: Keyman 15.0 on iPhone (not Chrome emulation, but simulator okay)
* GROUP_ANDROIDPHONE_NATIVE: Keyman 15.0 on Android phone (not Chrome emulation, but simulator okay)
* GROUP_ANDROIDTABLET_NATIVE: Keyman 15.0 on Android tablet (not Chrome emulation, but simulator okay)

The tests:

* **TEST_BASELINE:** Check the SIL Euro Latin keyboard displays correctly
* **TEST_KHMER_ANGKOR:** Install the Khmer Angkor keyboard. Verify that it too displays correctly.
* **TEST_CHOICE:** Choose a keyboard of your own liking to test -- this helps to verify that keyboards I haven't considered are also working correctly.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
# User Test Results

## SUITE_DEVELOPER: Test the web debugger in Keyman Developer
- **TEST_KHMER_ANGKOR: PASSED** The letters on keycaps all look good and nothing is cropped off.
   

   One thing though that the OSK preview within Keyman Developer does not look great when it comes to two-character combination on a key. See below.
   
   
- **TEST_OTHER_KEYBOARDS: PASSED** The letters on keycaps all look good and nothing is cropped off. But there is something I would like to report here while testing various keyboards.

   The top part of subkeys is cropped off in iPhone and .
   gff_amharic - iPhone
   
   
   gff_amhaic - Samsung Galaxy S5  
   
   
   sil_euro_latin - iPhone

**Comment by MakaraSok** [comment]
## SUITE_DEVELOPER: Test the web debugger in Keyman Developer
- **TEST_KHMER_ANGKOR: PASSED** The letters on keycaps all look good and nothing is cropped off.
   

   One thing though that the OSK preview within Keyman Developer does not look great when it comes to two-character combination on a key. See below.
   
   
- **TEST_OTHER_KEYBOARDS: PASSED** The letters on keycaps all look good and nothing is cropped off. But there is something I would like to report here while testing various keyboards.

   The top part of subkeys is cropped off in iPhone and .
   gff_amharic - iPhone
   
   
   gff_amhaic - Samsung Galaxy S5  
   
   
   sil_euro_latin - iPhone

**Comment by mcdurdin** [comment]
> * One thing though that the OSK preview within Keyman Developer does not look great when it comes to two-character combination on a key. See below.

This is a font and renderer issue which is not trivial to solve. See for example how we fixed this for Lao: https://marc.durdin.net/2015/01/how-to-rendering-combining-marks-consistently-across-platforms-a-long-story/

**Comment by mcdurdin** [comment]
> * But there is something I would like to report here while testing various keyboards.
>   The top part of subkeys is cropped off in iPhone and [Android].

Tracking this in #5926.

**Comment by MakaraSok** [comment]
## SUITE_COMPAT: Test that these changes are compatible across a range of devices
* GROUP_WINDOWS_CHROME: KeymanWeb in Chrome on Windows
  - **TEST_BASELINE: PASSED** Different layers of each keyboard in the test page are rendered correctly.
  - **TEST_KHMER_ANGKOR: PASSED** Nothing is too critical on each layer.
      One thing with the Khmer Angkor where the dotted circles are not shown for three of all the diacritics. 
      

  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_WINDOWS_FIREFOX: Firefox on Windows
  - **TEST_BASELINE: PASSED** Different layers of each keyboard in the test page are rendered correctly.
  - **TEST_KHMER_ANGKOR: PASSED** Nothing is too critical on each layer.
     One thing though with this vowel ឿ. Its top part is not fully visible, on FireFox and Chrome on Windows and on FireFox on Linux.
     

     It looks OK on Chrome on macOS.
     
 
  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_MACOS_CHROME: Chrome on macOS _**It looks like the texts on keycaps are bold which is different from those on Windows.**_
  - **TEST_BASELINE: PASSED**  Different layers of each keyboard in the test page are rendered correctly.
  - **TEST_KHMER_ANGKOR: PASSED** OK.
  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_LINUX_FIREFOX: Firefox on Linux
  - **TEST_BASELINE: PASSED** Different layers of each keyboard in the test page are rendered correctly.
  - **TEST_KHMER_ANGKOR: PASSED** OK
  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_IPAD_SAFARI: Safari on iPad (not Chrome emulation; iOS simulator okay)
  - **TEST_BASELINE: PASSED** OK
  - **TEST_KHMER_ANGKOR: FAILED** Two keys on the shift layer are not fully visible. Also, the keycaps with two characters on them are not nicely merged as those on the computer.
      

  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_IPHONE_SAFARI: Safari on iPhone (not Chrome emulation; iOS simulator okay)
  - **TEST_BASELINE: PASSED** OK
  - **TEST_KHMER_ANGKOR: FAILED** One of the subway on <kbd> ោ</kbd> is not fully visible. It's a two-character vowel, i.e. ោះ.
     
  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_ANDROIDPHONE_CHROME: Chrome on Android phone
  - **TEST_BASELINE: FAILED** The shift layer of Dzongkha keyboard has keys without two characters on the keycaps which are not rendered correctly. They look OK though on iOS.
    

  - **TEST_KHMER_ANGKOR: PASSED** OK. Plus all two-character vowels are nicely rendered together.
  - **TEST_CHOICE: PASSED** `sil_myanmar_my3` keyboard is rendered correctly.

* GROUP_ANDROIDTABLET_CHROME: Chrome on Android tablet
  - **TEST_BASELINE: FAILED** Similar to the issue above for Dzongkha keyboard.
     

     Also, characters on keycaps are too small to see on the spacious keyboard layout. See the Lao characters below.
      


  - **TEST_KHMER_ANGKOR: PASSED** It would be better though if each character on the keycaps are bigger. They look awkward to have big keycaps with small texts.
  - **TEST_CHOICE: PASSED** It would be better though if each character on the keycaps are bigger. They look awkward to have big keycaps with small texts.

**Comment by MakaraSok** [comment]
## SUITE_APPS: Test that these changes are compatible in Keyman apps on Android and iOS
* GROUP_IPAD_NATIVE: Keyman 15.0 on iPad (not Chrome emulation, but simulator okay)
  - **TEST_BASELINE: PASSED** The EuroLatin keyboard displays correctly.
  - **TEST_KHMER_ANGKOR: PASSED** Khmer Angkor keyboard displays correctly. One thing with the two-character vowels though. They should be merged and nicely rendered as those on Android. 
  
  
  - **TEST_CHOICE: PASSED** Myanmar3 (SIL) keyboard displays correctly.

* GROUP_IPHONE_NATIVE: Keyman 15.0 on iPhone (not Chrome emulation, but simulator okay)
  - **TEST_BASELINE: PASSED** The EuroLatin keyboard displays correctly.
  - **TEST_KHMER_ANGKOR: FAILED** One of the subkeys on <kbd> ោ</kbd> is not fully visible. It's a two-character vowel, i.e. ោះ.
     

     It looks better on Android:
     
  
  - **TEST_CHOICE: PASSED** Myanmar3 (SIL) keyboard displays correctly.

* GROUP_ANDROIDPHONE_NATIVE: Keyman 15.0 on Android phone (not Chrome emulation, but simulator okay)
  - **TEST_BASELINE: PASSED** The EuroLatin keyboard displays correctly.
  - **TEST_KHMER_ANGKOR: PASSED** Khmer Angkor keyboard displays correctly. One thing is with the font of the text on subkeys. They seems to be different from that of the base keys'.
  - **TEST_CHOICE: PASSED** Myanmar3 (SIL) keyboard displays correctly.

* GROUP_ANDROIDTABLET_NATIVE: Keyman 15.0 on Android tablet (not Chrome emulation, but simulator okay)
  - **TEST_BASELINE: PASSED** The EuroLatin keyboard displays correctly.
  - **TEST_KHMER_ANGKOR: PASSED** Khmer Angkor keyboard displays correctly. One thing is with the font size of text on each key, they should be bigger.
  - **TEST_CHOICE: PASSED** Myanmar3 (SIL) keyboard displays correctly. One thing is with the font size of text on each key, they should be bigger.

**Comment by mcdurdin** [comment]
I have adjusted the font scaling for Android tablet devices. Can we retest Android devices?

The issues with scaling around specific two-part characters such as ោះ is a separate thing to resolve. This is really tricky. I have reviewed those tests where there are multiple dotted circles and PASSED them for this issue; feel free to open a new issue for us to track this as a general problem -- and as you noted the behaviour is different on each platform as well!

SUITE_COMPAT

* GROUP_IPAD_SAFARI
  * TEST_KHMER_ANGKOR: PASSED (note multiple dotted circles breaking scaling as a separate problem)

* GROUP_IPHONE_SAFARI
  * TEST_KHMER_ANGKOR: PASSED (note multiple dotted circles breaking scaling as a separate problem)

* GROUP_ANDROIDPHONE_CHROME
  * TEST_BASELINE: OPEN _please retest_
  * TEST_KHMER_ANGKOR: OPEN _please retest_
  * TEST_CHOICE: OPEN _please retest_

* GROUP_ANDROIDTABLET_CHROME
  * TEST_BASELINE: OPEN _please retest_
  * TEST_KHMER_ANGKOR: OPEN _please retest_
  * TEST_CHOICE: OPEN _please retest_

SUITE_APPS

* GROUP_IPHONE_NATIVE
  * TEST_KHMER_ANGKOR: PASSED (note multiple dotted circles breaking scaling as a separate problem)

* GROUP_ANDROIDPHONE_NATIVE
  * TEST_BASELINE: OPEN _please retest_
  * TEST_KHMER_ANGKOR: OPEN _please retest_
  * TEST_CHOICE: OPEN _please retest_

* GROUP_ANDROIDTABLET_NATIVE
  * TEST_BASELINE: OPEN _please retest_
  * TEST_KHMER_ANGKOR: OPEN _please retest_
  * TEST_CHOICE: OPEN _please retest_

**Comment by MakaraSok** [comment]
## SUITE_COMPAT: Test that these changes are compatible across a range of devices
* GROUP_ANDROIDPHONE_CHROME: Chrome on Android phone
   * **TEST_BASELINE: FAILED** The character on each keycap become to big and for the Lao keyboard, some parts of some keys are cropped off or spilled over.
      
   
   * **TEST_KHMER_ANGKOR: FAILED** The character on each keycap become to big and for the Lao keyboard, some parts of some keys are cropped off or spilled over.
      
      
   * **TEST_CHOICE: FAILED** The character on each keycap become to big and for the Lao keyboard, some parts of some keys are cropped off or spilled over.
      
   
* GROUP_ANDROIDTABLET_CHROME: Chrome on Android tablet
   * **TEST_BASELINE: PASSED** Nothing is cropped off and the characters are visibly bigger, but the characters on keycaps are still not satisfactorily big enough comparing with the key size.
      image

   * **TEST_KHMER_ANGKOR: PASSED** The characters on keycaps are visibly bigger now.
      image
      
   * **TEST_CHOICE: PASSED** The characters on keycaps are visibly bigger now.
      image

Note that on both Android phone and table, the shift layer of Dzongkha keyboard looks ugly.
Screen Shot 2021-11-30 at 10 55 38 AM

**Comment by MakaraSok** [comment]
## SUITE_APPS: Test that these changes are compatible in Keyman apps on Android and iOS
* GROUP_ANDROIDPHONE_NATIVE: Keyman 15.0 on Android phone (not Chrome emulation, but simulator okay)
  * **TEST_BASELINE: PASSED** The EuroLatin (SIL) keyboard displays correctly on all layers including the subkeys.
     image

  * **TEST_KHMER_ANGKOR: PASSED** The OSK looks great. Nothing is cropped off or spilled over.
     image

     But the font of the text on subkeys seems to be different from that of the base keys'.
     image
  
  * **TEST_CHOICE: PASSED** The OSK looks great. Nothing is cropped off or spilled over.
     image

* GROUP_ANDROIDTABLET_NATIVE: Keyman 15.0 on Android tablet (not Chrome emulation, but simulator okay)
  * **TEST_BASELINE: PASSED** The EuroLatin (SIL) keyboard displays correctly.
  * **TEST_KHMER_ANGKOR: PASSED** Khmer Angkor displays correctly, but there is a separate issue (https://github.com/keymanapp/keyman/issues/5986).
  * **TEST_CHOICE: PASSED** The Myanmar3 (SIL) keyboard displays correctly.

**Comment by mcdurdin** [comment]
Latest push should resolve the tablet detection, I hope. Please retest the relevant 

@keymanapp-test-bot retest SUITE_COMPAT GROUP_ANDROIDPHONE_CHROME SUITE_COMPAT GROUP_ANDROIDTABLET_CHROME

**Comment by MakaraSok** [comment]
SUITE_COMPAT 
GROUP_ANDROIDPHONE_CHROME 
* **TEST_BASELINE: PASSED** the font size is now back to normal, not too big any longer.
   image

* **TEST_KHMER_ANGKOR: PASSED** the font size is now back to normal, not too big any longer.
   image

* **TEST_CHOICE: PASSED** the font size is now back to normal, not too big any longer.
    image


Note that there is a weird behavior noted before and had been investigated with @darcywong00. I would like to show it here for our record. 

https://user-images.githubusercontent.com/28331388/144836458-5898f3ac-e754-49a5-88a5-cba5d00aa6ec.mov


GROUP_ANDROIDTABLET_CHROME
* **TEST_BASELINE: PASSED** no issue
* **TEST_KHMER_ANGKOR: PASSED** no issue
* **TEST_CHOICE: PASSED** no issue

One thing that stays the same is that the shift layer of Dzongkha keyboard is not shown correctly. No double dotted circle should be shown.

image

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.165-alpha](https://keyman.com/downloads/releases/alpha/15.0.165)

**Comment by mcdurdin** [comment]
See https://community.software.sil.org/t/feedback-on-keyman-15-0-alpha/5405/34 for details on regression introduced by this PR.

**Pull request merged**
