### PR TITLE
refactor(web): OSK modularization - view components, layout cleanup ✂️

### PR DESCRIPTION
**Pull request by jahorton**
This relatively lightweight PR adds an abstraction for use by the OSK and its subcomponents.  By having each subcomponent implement a common interface, this increases nomenclature consistency and should facilitate code readability and maintenance.

Follows #5530.  (The 👆 set.)

This PR also polishes up some of the internal layout calculations, using thematically-named fields and methods that better describe the purpose of the values being used.  There _is_ a mild shift in the values' source when it comes to `.computedWidth` and `.computedHeight`, which are intended to serve as the "master" layout value for active OSKs and are recalculated during layout-refreshes.  (Refer to changes made in https://github.com/keymanapp/keyman/pull/5462.)
- These changes also include fixes for desktop OSK `.computed__` value calculations; these were previously incorrect.
- **CHANGE**:  `setSize` now sets the size of the full OSK, _including the 'frame'_ - the header and footer components.
    - That is, it sets the size of the `kmw-osk-frame` element, rather than a select subset of the inner components.
        - Does **_not_** affect help-page keyboards like `sil_euro_latin`; `setSize` will _continue_ to have no effect on them.
            - Is pre-existing behavior.  I'm not claiming that this is _ideal_ behavior... just that it's the same behavior as before.
    - Before, the header and footer bars were ignored!
        - If an OSK-sizing cookie exists from a prior version of KMW, the desktop OSK will appear somewhat squashed (compared to before) until resized.
        - APIs that set the OSK's size will now function more precisely as a result.  (Unless showing a help-page keyboard.)
            - While technically **BREAKING**, this should be a net plus to site developers.
            - Only affects the OSK's display / layout calculations, not its functionality.

# User Testing

This PR's user tests will be delegated to #5620, as the combined number of changes is going to require a significant amount of testing.

### CODE REVIEW

**Comment by jahorton** [comment]
As user-testing is intentionally delegated to #5620...

@keymanapp-test-bot skip

**Comment by jahorton** [comment]
Delayed, I know, but I just added a fix for the OSK's default height after the page's cookie has been cleared.

**Comment by mcdurdin** [comment]
> I... uh... we _could_. Feels like a pretty low ROI, though. It only affects people who:
> 
> * previously used a site using KMW

Thousands of people a day use KMW...

**Comment by jahorton** [comment]
> > ... It only affects people who:
> > 
> > * previously used a site using KMW
> 
> Thousands of people a day use KMW...

And after these changes, it literally affects those people _once_ each.  Just _once_ per site.  The last commit I made ensures it's just the 'once'; cache-clearing previously caused a similar issue that could happen more frequently.

If you still strongly want some sort of versioning here, what design for that would you propose?

**Comment by mcdurdin** [comment]
I'm just not clear on how it's only once. If it's only once, why can't it be never? What automatic handling are you doing to ensure that it doesn't recur the next time they load the site?

**Comment by jahorton** [comment]
> I'm just not clear on how it's only once. If it's only once, why can't it be never? What automatic handling are you doing to ensure that it doesn't recur the next time they load the site?

Before:
- height:  the height of _just_ the `VisualKeyboard` portion of the OSK.
    - does not include the title bar or resize bar.

After:
- height:  the height of the full `_Box` of the OSK.
    - includes the `VisualKeyboard`
    - _and_ the title & resize bars.

The distinction between these two states - the purpose of / paradigm for the stored height value is different.

----

Potential scenarios:
1.  A user loads a KMW-enabled for the first time after it's been updated.  (A prior, pre-change cookie exists)
    - The OSK looks "off" - it's "flat", as the previously-saved height value did not include the title bar or resize bar's space.
    - Here, the user has one of two options:
        1. "Eh, it's okay."  They don't fix it.
        2. "It shouldn't be that flat" - and they correct it.
    - In either case, the final cookie for this visit will be set to the final, post-fix version of height - the full height of the page's displayed OSK.
2.  The user has a repeat visit.  (A prior, but post-change cookie exists)
    - Here, the previous cookie was saved under the same assumptions about height - the title bar and resize bar height's are included in the stored value.  (See previous point.)
    - If they left the "flat" scale as it was, that "flat" scale does remain.
        - KMW infers a "this is fine" reaction from the user, since it's a customizable aspect of the OSK.
        - In this context, this behavior is correct for the OSK - to use the same width and height from the previous visit.  (Even if those values themselves may not have been ideal.)
3.  The user visits for the first time after clearing the cache.  (No cookie exists)
    - There is no "previous" value available, so KMW just uses its default height calculations instead.

**Comment by mcdurdin** [comment]
Yes, so my concern is with:

> "Eh, it's okay." They don't fix it.

Which for many users *will* be:

> "Eh, that looks weird. Wish they could fix that." They don't fix it -- because they don't know how.

Anything which depends on the user to resolve it is really a non-starter.

So I would like to get this resolved.

For versioning a cookie, I'd be happier with the positioning info in the cookie being dropped if it's a v14 cookie, than having a weird view that may persist for the life of the cookie for users moving from v14 to v15. 

Of course, my ideal would be for KMW to look at the cookie, go 'oh that's a v14 cookie, I need to do a transform', and then store a v15 cookie in its place (I don't care about the downgrade scenario -- that's a vanishingly small proportion of users).

**Comment by jahorton** [comment]
> Yes, so my concern is with:
> 
> > "Eh, it's okay." They don't fix it.
> 
> Which for many users _will_ be:
> 
> > "Eh, that looks weird. Wish they could fix that." They don't fix it -- because they don't know how.

In that case, would it be reasonable to say 'oh that's a v14 cookie, I should just throw it out' instead?
- If a user "doesn't know how to fix it" when we preserve the cookie, this will reset the OSK to use default dimensions.
- If a user had a customized OSK size, then they _do_ know how, so throwing out the old preference isn't a big problem because they've proven they "know how to fix it."

**Comment by mcdurdin** [comment]
> In that case, would it be reasonable to say 'oh that's a v14 cookie, I should just throw it out' instead?
> 
> * If a user "doesn't know how to fix it" when we preserve the cookie, this will reset the OSK to use default dimensions.
> * If a user had a customized OSK size, then throwing out the old preference isn't a big problem because they've proven they "know how to fix it."

That sounds acceptable -- so worst case scenario is a single session with wonky aspect ratio. (Ideal would be to make the additional tweak when loading the cookie, given we now know its version, to fixup the aspect ratio...)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.113-alpha](https://keyman.com/downloads/releases/alpha/15.0.113)

**Pull request merged**
