### PR TITLE
change(web): more prep for better async prediction handling 🕐

### PR DESCRIPTION
**Pull request by jahorton**
This is another aspect toward resolving #3580.  With this change, we will be able to use `await` within the `getBestMatches()` method in order to yield to the JS microtask queue, allowing us a way to receive new messages _during_ an active prediction phase - the most significant of which may indicate new prediction requests that should supersede the current one.  That part of the work will be left to another PR.

----

If desired, we probably can _find a way_ to do this without async generator functions, but it's not going to be pretty.   Async generator support will do a _lot_ of heavy lifting for us here.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by jahorton** [comment]
Man, changing just two lines of TS results in 3.6 kb of changes when minified.  That's downcompilation for you; this causes less tslib downcompile helpers to treeshake out.

**Review by mcdurdin — APPROVED** [review]

**Comment by jahorton** [comment]
It's been a while since I originally put this PR together, and we've since had a discussion at one point in regard to dependency updates.  This PR seeks to update Web's use of `esbuild` to at least `0.18.8` in order to leverage newer JS features for predictive text.  `kmc` stuff is fine with the old `esbuild`, though.

Should `kmc`'s `esbuild` be updated to match versions, or should we leave it using the older version of `esbuild` for now?

**Comment by mcdurdin** [comment]
> Should `kmc`'s `esbuild` be updated to match versions, or should we leave it using the older version of `esbuild` for now?

Yes, and if possible the esbuild update should be a separate PR which is just about updating that dependency. We want to try and avoid divergence on our dependencies.

**Comment by mcdurdin** [comment]
@jahorton says:

> we need that async-generator downcompilation support for the ES6 target.

https://github.com/evanw/esbuild/releases/tag/v0.18.8 says:

> I have never used this feature myself and code that uses this feature is hard to come by, so this transformation has not yet been tested on real-world code. If you do write code that uses this feature, please let me know if esbuild's async generator transformation doesn't work with your code.

This worries me. Is it possible to avoid using generators? How much does our design depend on this rarely-used feature?

**Comment by jahorton** [comment]
> This worries me. Is it possible to avoid using generators? How much does our design depend on this rarely-used feature?

It does a _lot_ of heavy lifting for us.

Our correction-search algorithm searches for the "best" corrections possible given the current context.  As we get new potential corrections, we then check them against the lexical model for viable predictions based on those corrections.  Naturally, not all possible corrections make sense - correcting 'car' to 'xar' (or worse, 'cqr') won't turn up anything in English, and so we often need to 'find more'.  The generator setup allows us to pause and resume our search for corrections and then simply abandon the paused search once we no longer need to search for more possibilities.  That may be due to having already found enough high-quality suggestions... or due to hitting our prediction-engine's timeout.

The original aim of this PR series (🕐) is to allow us to terminate an ongoing search early by allowing it to be interrupted.  For it to be interruptible, we must be able to yield periodically to the JS microtask/macrotask queues.

I believe that dumping the generator setup is theoretically possible, but the most straightforward way to do that would reduce the responsiveness of predictive text - we'd no longer be able to tell if we could stop the correction-searching process early, and the time spent converting corrections to predictions would no longer be included within the standard timeout.  A more significant rework could probably avoid these issues, though it'd take some redesign for the core methods involved and would likely result in overall less-clear code.

> > If you do write code that uses this feature, please let me know if esbuild's async generator transformation doesn't work with your code.
> 
> This worries me.

I would like to point out that this code-path has been out in the wild for about a year now.  Based on what I can see in the release notes, there's been one fix since... within the very next version.
- https://github.com/evanw/esbuild/releases/tag/v0.18.9

I'm not familiar with `await using` and how it's used, but clearly others out there are using this transform, and _this_ is the one issue they appear to have run into.

The next-closest issue I can find in the release notes is in regard to use of `for...await`: https://github.com/evanw/esbuild/releases/tag/v0.21.4, which landed in the literal most-recent version... and only appears to matter if using `for...await` with `try...catch` statements _with_ labels present.

**Comment by jahorton** [comment]
Found a decent resource about that `await using` thing, in case of interest.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.56-alpha](https://keyman.com/downloads/releases/alpha/18.0.56)

**Pull request merged**
