### PR TITLE
chore(common): Check in crowdin strings for Spanish (Latin America)

### PR DESCRIPTION
**Pull request by darcywong00**
Checks in localization files for Spanish (Latin America) - `es-419`.

## User Testing
@MakaraSok - With the PR test builds, check that the strings switch. (We're not sure all the platforms handle the language tag `es-419`)

### Android
1. Start Keyman (assuming you're in either English or Khmer system locale)
2. Settings --> Change Display Language --> Espanol (Spanish - Latin America)
Screenshot_1623371912
3. Settings --> Change Display Language --> Default Locale ("Variedad predeterminada" in Spanish)
4. Verify Keyman strings are in the default locale
4. From the Androi System settings, change the locale to Espanol (Estados Unidos)
5. Verify Keyman strings are in Spanish
 
### Windows
1. Change the Display Language to Espanol

TODO
- [x] @jahorton to run the iOS files through Xcode

### CODE REVIEW

**Comment by mcdurdin** [comment]
I really don't understand why the Jenkins build is failing:

```
12:48:11  [0m[0mengine.c: In function ‘ibus_keyman_engine_process_key_event’:
12:48:11  [0m[0mengine.c:682:25: error: ‘KM_KBP_MODIFIER_CAPS’ undeclared (first use in this function); did you mean ‘KM_KBP_MODIFIER_ALT’?
12:48:11  [0m[0m         km_mod_state |= KM_KBP_MODIFIER_CAPS;
12:48:11  [0m[0m                         ^~~~~~~~~~~~~~~~~~~~
12:48:11  [0m[0m                         KM_KBP_MODIFIER_ALT
12:48:11  [0m[0mengine.c:682:25: note: each undeclared identifier is reported only once for each function it appears in
```

`KM_KBP_MODIFIER_CAPS` is right there in keyboardprocessor_vkeys.h alongside `KM_KBP_MODIFIER_ALT`, in the tip of this branch:

https://github.com/keymanapp/keyman/blob/941088b83edf47752d067aa9b0eb3fb9adb347f8/common/core/desktop/include/keyman/keyboardprocessor_vkeys.h#L21-L30

**Comment by MakaraSok** [comment]
On Android, at step 2, after switching to the `Spanish - Latin America`, the tooltip on the globe key is shown in Khmer which is the previously set language (it's also the system's UI language).

Screenshot_1623395435

Everything else is working as expected. Changing the system language to Spanish does change the Keyman UI language to Spanish.

---

On Windows, everything is OK.

**Comment by MakaraSok** [comment]
Just tested this [build](https://build.palaso.org/buildConfiguration/KeymanAndroid_TestPullRequests/274056?buildTab=artifacts#%2Frelease) again and it shows the tooltip on the globe key is not consistent with the language being selected, but the language set prior to the one currently selected.

The screenshot shows the tooltip in Spanish while the currently language is set to EN. Note that right before this the UI language was set to Spanish.
Screenshot_1623634562

Now when switching the language to KM, the tooltip changes to EN.
Screenshot_1623634590

**Comment by darcywong00** [comment]
The globe button string is probably related to #4875

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.68-alpha](https://keyman.com/downloads/releases/alpha/15.0.68)

**Pull request merged**
