### PR TITLE
fix(web): osk responsiveness to held modifiers on legacy kbds 🧓

### LINKED ISSUE #10224: bug(web): modifier keys on OSK don't track correctly for armenian keyboard
The armenian keyboard is a legacy keyboard, but the modifier keys _should_ track. However, holding <kbd>Shift</kbd> seems to have no effect, and pressing and releasing <Ctrl> leaves the Ctrl key/layer depressed on the OSK.

The <Kbd>Ctrl</kbd> behaviour is similar for the <kbd>Alt</kbd> key. Using combinations results in other stuck layers but no more than one layer remains stuck.

Hard to see here, but Shift pressed (and released) around 4 second mark; Ctrl pressed at 5 seconds and released at 6 seconds:

https://github.com/keymanapp/keyman/assets/4498365/df115d43-ab0c-4b86-9d74-0a6df87250d0

Repro on various versions:
* https://keymanweb.com/?version=17.0.228#hy,Keyboard_armenian
* https://keymanweb.com/?version=16.0.144#hy,Keyboard_armenian
* https://keymanweb.com/?version=12.0.106#hy,Keyboard_armenian

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10224.

I'm not 100% sure I have the fully-intended legacy keyboard behavior right for cases with a held CTRL or ALT modifier, but it's what I inferred as the pre-existing code's most likely intent.  I added a lot of relevant detail re: this inference in the comments of #10224 for those curious.

## User Testing

TEST_ARMENIAN:  Using the "Test unminified KeymanWeb" test page on a desktop form-factor device, verify that the OSK responds properly to hardware keystrokes.

1. Once on the page, in the "Add a keyboard by keyboard name" input field, type `armenian`, then click Add.
2. Swap to the "Armenian - Armenian Unicode" keyboard.
3. Use the key equivalent to a QWERTY layout's `a` key - a `ա` should result.
4. Press and hold the SHIFT key - the OSK's layer should change.
5. With the SHIFT key still held, use the key equivalent to a QWERTY layout's `a` key - a `Ա` should result.
6. Release the SHIFT key - the OSK's layer should return to the original layer, with a `ա` in the same position the `Ա` was in.
7. Press and hold the CTRL key - the OSK's layer should change to one with blank keys.
8. Use the key equivalent to a QWERTY layout's `a` key - the text area's text should all be selected, with no new text output.
9. Release the CTRL key - the OSK's layer should return to the one with a `ա` key.
10. Press and hold the ALT key - the OSK's layer should change to one with blank keys.
11. Use the key equivalent to a QWERTY layout's `a` key - there should be no effect.
12. Release the ALT key - the OSK's layer should return to the one with a `ա` key.
13. Press both the CTRL and ALT key - the OSK's layer should change to one with blank keys, with both CTRL and ALT highlighted.
14. Release both CTRL and ALT - the OSK's layer should return to the one with a `ա` key.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM. I think this makes sense. If neither positional nor mnemonic is defined, that indicates a legacy 1.0 keyboard, right? So this change should only impact those keyboards anyway.

**Comment by jahorton** [comment]
> LGTM. I think this makes sense. If neither positional nor mnemonic is defined, that indicates a legacy 1.0 keyboard, right? So this change should only impact those keyboards anyway.

That is correct.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ARMENIAN (PASSED):** Tested with the "Test unminified KeymanWeb" test page and here is my observation: 1. Added "Armenian - Armenian Unicode" keyboard. 2. Pressed 'a' letter from the keyboard. Verified it showed 'ա' on the screen. 3. Verified that the OSK's layer changed, after pressing and holding the SHIFT key. 3. With the SHIFT key still held, I pressed 'a' from the physical keyboard. It showed 'Ա' in the text input screen. 4. Verified that the blank keys appeared after pressing and holding the CTRL key. 5. Pressed 'a' key, all texts were selected, and no new text outputs on the screen. 6. Verified that the OSK's layer appeared with blank keys after pressing and holding the ALT key. 7. Pressed 'a' key and there was no effect on the OSK. 8. Released the ALT key and noticed that it returns to the default layer. 9. Pressing both CTRL and ALT keys showed blank keys on the OSK with both CTRL and ALT keys highlighted. 10. Released both CTRL and ALT keys and noticed that it returned to the default layer. 


..after pressing 'a' key (with SHIFT key pressed and hold) for the second time it shows the following result


   

..All texts were selected by pressing CTRL+A

   


..CTRL+ALK keys were highlighted on the OSK

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.250-alpha](https://keyman.com/downloads/releases/alpha/17.0.250)

**Pull request merged**
