### PR TITLE
chore(common): Add crowdin strings for Dutch

### PR DESCRIPTION
**Pull request by darcywong00**
This adds the crowdin strings for Nederlands (Dutch) - locale nl-NL

TODO for @sgschantz 
- [x] Run XCode for iOS
- [x] Run XCode for macOS

## User Testing
Load the PR build for each platform and set the UI / Locale to Dutch
There may be a handful of strings still in English, but most are in Dutch

* **TEST_ANDROID** 
1. Load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display Language --> Nederlands (Dutch)
3. Return to the Keyman app 
4. Verify the UI is in Dutch (prompt, Settings strings, etc.). 

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Dutch
3. Return to the Keyman app
4. Verify the UI is in  Dutch

* **TEST_LINUX**
1. Start Keyman configuration with: LANGUAGE=nl_NL km-config
2. Verify Keyman UI is in Dutch

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Dutch
3. Verify the Keyman UI is in Dutch

* **TEST_WINDOWS**
1. Load the PR build of Keyman for Windows
2. Set the UI to Nederlands
3. Verify the Keyman UI is in Dutch

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

**Review by mcdurdin — APPROVED** [review]

**Comment by darcywong00** [comment]
Commit https://github.com/keymanapp/keyman/pull/7498/commits/5b59cca37ba916b219214eab120215ef5d052409 adds the newest mac string for privacy-alert-text

**Comment by bharanidharanj** [comment]
* **TEST_ANDROID (PASSED):** Tested this PR with the attached build (Keyman 16.0.85-alpha-test-7498) in API 26 / Android 8.0 emulator and verified that the Keyman Config has been changed to Dutch UI.

**Comment by bharanidharanj** [comment]
* **TEST_IOS (PASSED):** Tested this PR in iOS 16 / iPhone 14 Pro Max Simulator and verified that the Dutch UI is in Keyman App. 

   

* **TEST_MACOS (PASSED):** Tested this in macMini M1 12.6 Monterey OS and verified that the Dutch UI is in Keyman dialog.

**Comment by bharanidharanj** [comment]
* **TEST_WINDOWS (FAILED):** Tested this PR in Windows 10 (Native Machine) OS and noticed that there is no Nederlands UI / Dutch UI appear in the UI drop down list box.

**Comment by darcywong00** [comment]
@bharanidharanj - 
In Keyman Setup - "Nederlands" is an available option. But you're right about it not being an option in Keyman Configuration.
I found a language code the translator should have kept as `en` and fixed it. That should fix "English" from showing twice in the UI list.

@keymanapp-test-bot retest TEST_WINDOWS

**Comment by bharanidharanj** [comment]
> @bharanidharanj - In Keyman Setup - "Nederlands" is an available option. But you're right about it not being an option in Keyman Configuration. I found a language code the translator should have kept as `en` and fixed it. That should fix "English" from showing twice in the UI list.
> 
> @keymanapp-test-bot retest TEST_WINDOWS

@darcywong00 Oh Okay. Sorry, I just added an issue about the English UI name appears twice in the list box. #7559

**Comment by bharanidharanj** [comment]
* **TEST_WINDOWS (PASSED):** Retested this with the update PR build and verified that the Dutch UI is in the Keyman Configuration dialogue.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.90-alpha](https://keyman.com/downloads/releases/alpha/16.0.90)

**Pull request merged**
