### PR TITLE
feat(web): prediction casing follows current layer

### LINKED ISSUE #6455: feat(common): model should suggest according to current layer
> * Lexical model should suggest words according to the current layer even before the user starts typing. For example, when kb is in default layer, all suggestions should be in lower case; in shift layer, all suggestions should be in Initial Caps; in caps layer, all suggestions should be in ALL CAPS.

https://community.software.sil.org/t/keyman-15-beta-feedback/5755/21

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/6005#issuecomment-1079779690_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6455.

This involved adding an extra hint to the data passed into the lexical model layer, being the CasingForm that the current layer wants to use.

Given there are several entry points to the lexical model layer, this meant a few places where we needed to check the current layer.

I refactored the very long function `InputProcessor.processKeyEvent` to extract out the `buildAlternates` function. There should be no functional changes to the `buildAlternates` code. But it makes `processKeyEvent` significantly easier to read.

# User Testing

For all these tests, use the page **web/testing/prediction-ui**, and keyboard **obolo_chwerty_6351** under English.

Ensure that you are using the mobile emulation mode in Chrome by pressing F12, selecting image in the Developer Tools toolbar, and selecting iPhone SE in the Device toolbar. Reload the page to ensure that it is in proper mobile mode.

**TEST_CAPITALS_AND_PREDICTIONS:** Verify that suggestions match the selected case for the current word.

1. Focus the text area. The three suggestions offered on an empty text box should be in Title Case (as the keyboard should be on `shift` layer).
2. Press the <kbd>Shift</kbd> key. The suggestions should switch to lower case (and the keyboard should be on the `default` layer).
3. Press the <kbd>Shift</kbd> key again. The suggestions should switch to Title Case (and the keyboard should be back on the `shift` layer).
4. Double-click the <kbd>Shift</kbd> key. The suggestions should switch to ALL CAPS (and the keyboard should be on the `caps` layer).

**TEST_APPLYING_SUGGESTIONS:** Verify that when suggestions are applied, casing is tracked correctly

1. Focus the text area. Click a suggestion to insert it. The keyboard should return to the `default` layer, and the inserted word should be Title Case. The new suggestions offered should be lower case.
2. Type <kbd>.</kbd> <kbd>spacebar</kbd>. The keyboard should switch to the `shift` layer, and the suggestions should be Title Case.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_CAPITALS_AND_PREDICTIONS (FAILED):** notes

**Comment by bharanidharanj** [comment]
* **TEST_APPLYING_SUGGESTIONS (PASSED):** Tested this in the web/testing/prediction-ui, along with the obolo_chwerty_6351keyboard and it seems to be working as expected.

**Review by ermshiperete — APPROVED** [review]

**Comment by mcdurdin** [comment]
Apologies @bharanidharanj I did not specify that we needed to test this in mobile emulation mode. The desktop mode is a separate issue which we should address but is not required for 15.0 😁 

I have updated the test instructions accordingly:

> Ensure that you are using the mobile emulation mode in Chrome by pressing F12, selecting image in the Developer Tools toolbar, and selecting iPhone SE in the Device toolbar. Reload the page to ensure that it is in proper mobile mode.

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
> Apologies @bharanidharanj I did not specify that we needed to test this in mobile emulation mode. The desktop mode is a separate issue which we should address but is not required for 15.0 😁
> 
> I have updated the test instructions accordingly:
> 
> > Ensure that you are using the mobile emulation mode in Chrome by pressing F12, selecting image in the Developer Tools toolbar, and selecting iPhone SE in the Device toolbar. Reload the page to ensure that it is in proper mobile mode.
> 
> @keymanapp-test-bot retest

Okay, Thanks @mcdurdin for the Clarification. I will retest it in mobile emulation mode.

**Comment by bharanidharanj** [comment]
* **TEST_CAPITALS_AND_PREDICTIONS (PASSED):** Tested this as per Marc's instructions in mobile emulator (iPhone SE) and it seems to be working as expected. 

Test 1:
 

Test 2:
 

Test 3:
 

Test 4:

**Comment by bharanidharanj** [comment]
* **TEST_APPLYING_SUGGESTIONS (PASSED):** Tested this as per Marc's instructions in Chrome Mobile emulator (iPhone SE) and it seems to be working as expected. 

Test Suggestion 1:


Test Suggestion 2:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.228-beta](https://keyman.com/downloads/releases/beta/15.0.228)

**Pull request merged**
