### PR TITLE
fix(ios): reloads keyboard after package updates

### LINKED ISSUE #2757: bug(ios): Keyman (and possibly Developer) cache files leading to difficulty repeating test installs
**Describe the bug**
When installing a package from a developer web host, recompiling the package and reinstalling it should be sufficient to retrieve updates. However, the keyboard must be installed, and Keyman must be forcibly quit, before reinstalling the keyboard, in order for the updates to actually surface.

---

**iPhone/iPad/Android:**
 - Device: iPhone 7
 - OS: iOS 12
 - Keyman version 13.0.100

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2757.

- Re-installing a package that has already been previously installed will automatically load the newly re-installed version, regardless of identical package filenames, relative package versions, etc.

----

With the first commit, the severity of the bug is downgraded for both cases:

> If I take care to ensure no automatic [package filename] renaming occurs behind the scenes, this does reproduce exactly. It gets tricky though, as various ways of importing .kmp files for testing will result in automatic `-1`, `-2`, etc renaming by iOS / Simulator / whatever.

- Now only requires swapping in and out of the keyboard.  There's no need to force-close & restart the app.

> If I slip up and let automatic renaming occur, merely swapping in and out of the keyboard is sufficient for a refresh; force-closing the app is not required. It is still required if system-level automatic renaming is prevented.

- Now 100% fixed; the keyboard will auto-refresh without issue so long as the actual package filename is different, even if only due to automatic iOS renaming.

----

The second commit fully resolves the bug, even for the first case.  As it turns out, the actual `reload()` method was never called until the keyboard picker was dismissed - the problem being that this required _summoning_ the picker, which isn't part of the package install pipeline.

It did make one assumption:  _the keyboard must always be hidden during a package install & redisplayed after it's fully complete_.  As the install process now always sets `shouldReloadKeyboard`, the keyboard's `viewWillAppear` method is sufficient for detecting that for needed reloads.

Unfortunately, attempting to immediately reload the keyboard (instead of using `shouldReloadKeyboard` to defer the reload until keyboard re-display) is prone to causing a blank keyboard bug.  As a result, I think it's safer to rely upon the assumption above for now; that assumption _is_ the "correct" control flow for the app, after all.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM. I am approving now and will test with the beta rather than with a local build.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.229-beta](https://keyman.com/downloads/releases/beta/14.0.229)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.230-beta](https://keyman.com/downloads/releases/beta/14.0.230)

**Comment by jahorton** [comment]
> LGTM. I am approving now and will test with the beta rather than with a local build.

@mcdurdin - just a reminder to give it a try, as it's landed on the beta.

**Comment by mcdurdin** [comment]
This also looks like it is working correctly now on my test iPhone. Thank you!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
