### PR TITLE
chore(common): Check in crowdin for Ukrainian

### PR DESCRIPTION
**Pull request by darcywong00**
Adds crowdin strings for Ukrainian for locale uk-UA

## User Testing
This adds the crowdin strings for Ukrainian locale uk-UA

TODO for @sgschantz 
- [x] Run XCode for iOS
- [x] Run XCode for macOS

## User Testing
Load the PR build for each platform and set the UI / Locale to "Українська (Ukrainian)"

* **TEST_ANDROID** 
1. Load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display Language --> Українська (Ukrainian)
3. Return to the Keyman app 
4. Verify the UI is in Ukrainian (prompt, Settings strings, etc.).

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Ukrainian
3. Return to the Keyman app
4. Verify the UI is in  Ukrainian

* **TEST_LINUX**
1. Start Keyman configuration with: LANGUAGE=uk-UA km-config
2. Verify Keyman UI is in Ukrainian

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Ukrainian
3. Verify the Keyman UI is in Ukrainian

* **TEST_WINDOWS**
1. Load the PR build of Keyman for Windows
2. Set the UI to Українська (Ukrainian)
3. Verify the Keyman UI is in Ukrainian

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID (PASSED):** Tested with the attached PR build (keyman 16.0.134-beta-test-8073) in Android 12 / API 31 emulator and I am able to change Ukrainian UI in the Keyman App.

**Comment by bharanidharanj** [comment]
* **TEST_LINUX (PASSED):** Tested with the attached PR build (keyman 16.0.134-beta (package version 16.0.134-1~PR-8073+focal6) in Ubuntu 20.04 Focal Linux OS (VM) and I am able to change the UI into Ukrainian in Keyman Configuration dialog.

**Comment by bharanidharanj** [comment]
* **TEST_WINDOWS (PASSED):** Tested with the attached PR build (keyman 16.0.134-beta-test-8073) in Windows 11 OS (VM) and I am able to change Ukrainian UI in the Keyman App.

**Comment by bharanidharanj** [comment]
* **TEST_MACOS (PASSED):** Tested with the attached PR build in MacMini Monterey 12.6 OS and I am able to change the UI into Ukrainian in the Keyman app. 

..Ukrainian UI1:

   

..Ukrainian UI2:

**Comment by mcdurdin** [comment]
I manually triggered a new iOS test build which should pull in the fixed sil_euro_latin.kmp 2.0.3.

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_IOS (PASSED):** "Done" is found to still be in English (1 and 2) and "Keyboard" is also seen in English under the menu for keyboard caption (3). PASSED for now as it doesn't prove to be a blocking issue that prevent users from accessing the app.

| (1) | (2) | (3) |
| --- | --- | --- |
| image | image | image |

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.136-beta](https://keyman.com/downloads/releases/beta/16.0.136)

**Pull request merged**
