### PR TITLE
fix(linux): Replace deprecated `pkg_resources` module with `packaging.version`

### LINKED ISSUE #10850: bug(linux): Deprecation warning when running `km-package-install`
When running `km-package-install` on Ubuntu 24.04 Noble a deprecation warning is shown:

```bash
$ km-package-install -p sil_el_ethiopian_latin --bcp47 ssy-latn
/usr/bin/km-package-install:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
```

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #10850.

# User Testing

## Preparations

- The tests should be run on these Linux platforms:
  - **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
  - **GROUP_JAMMY**: Ubuntu 22.04 Jammy with Gnome Shell and X11 or Wayland
  - **GROUP_NOBLE**: Ubuntu 24.04 Noble with Gnome Shell and X11 or Wayland

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot

## Tests

**TEST_NO_WARNING**: 

- run `km-package-install --version`
- verify that the version is output, but no warning

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_NO_WARNING (PASSED):** Tested with the attached PR build on Ubuntu 20.04 Focal Linux OS (VM) and here is my observation: 1. Run km-package-install --version on the terminal and verified that it is showing the version as output without showing any warning message.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_NOBLE: Ubuntu 24.04 Noble with Gnome Shell and X11 or Wayland

* **TEST_NO_WARNING (FAILED):** Tested with the attached PR build on Ubuntu 24.04 Noble Linux OS (wayland) (VM) and here is my observation: 1. Run km-package-install --version on the terminal and verified that it is showing the version with a warning message. Seems to be an issue.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_JAMMY: Ubuntu 22.04 Jammy with Gnome Shell and X11 or Wayland

* **TEST_NO_WARNING (PASSED):** Tested with the attached PR build (17.0.277-beta (package version 17..277-1~PR-10860-2445.1+jammy1) on Ubuntu 22.004 Jammy Linux OS (X11) (Virtual Box) and here is my observation: 1. It is showing the version number without any warning message after running the above command.

**Comment by ermshiperete** [comment]
GROUP_NOBLE: TEST_NO_WARNING(PASSED)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.291-beta](https://keyman.com/downloads/releases/beta/17.0.291)

**Pull request merged**
