### PR TITLE
chore(developer): upgrade ngrok to v3

### LINKED ISSUE #10357: chore(developer): upgrade ngrok to v3
Keyman Developer currently only downloads version 2.3 of ngrok. However,

> all ngrok agents version 3.1 and older will stop working on January 15th, 2024 for all free users. 

So we need to update the URL where we download ngrok.zip.

This needs to be done for v16 and v17.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10357.

# User Testing

TEST_NGROK_UPGRADE: In Keyman Developer, Tools|Options|Server, Configure Server, click `Download or update ngrok`. Once the download completes, the label to the right of the button should show "ngrok version 3.5.0" or similar (it must be version 3.2 or later to pass).

TEST_NGROK_WORKING: In Keyman Developer, verify that you have enabled ngrok in Keyman Developer Server Options. Open a keyboard, and test it on web. Verify that a URL appears in the list of server web addresses, and that when you select it to Open in browser, the test web site works correctly.

Note: your ngrok entry will look different to this but will be a public website:
image

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NGROK_UPGRADE (PASSED):** Tested with the attached PR build Keyman 17.0.242-alpha-test-10359 on Windows 10 OS (Native machine) and here is my observation: 1. Able to upgrade ngrok version into 3.5 in Configure Server dialog. Verified that the version number 3.5.0 appeared with ngrok label name. 

   


* **TEST_NGROK_WORKING (FAILED):** 1. Verified that the option "Use ngrok to provide public URL for Server" was enabled. 2. Verified that the copy of the token has been pasted in the Authentication token text box. 3. Opened a keyboard project. Compiled keyboard. 4. Clicked the Build tab. 5. Clicked the "Test Keyboard on web" button. Here, I noticed that there is no URL (link with ngrok-free.pp name) appearing in the list of web addresses pane. Seems to be an issue.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NGROK_WORKING (FAILED):** Retested with the attached PR build  Keyman 17.0.242-alpha-test-10359 on Windows 10 OS (Native machine) and here is my observation: 1. I got an error message in the Node window. 

..on Windows 10

   

..on Windows 11 (VM)

**Comment by mcdurdin** [comment]
@bharanidharanj can you try the following for me please and report on the results:

* Open a command prompt and type the following commands:

  ```
  cd "%appdata%\keyman\Keyman Developer\Server\bin"
  .\ngrok.exe --version
  .\ngrok.exe http 80
  ```

Thank you!

**Comment by bharanidharanj** [comment]
> @bharanidharanj can you try the following for me please and report on the results:
> 
>     * Open a command prompt and type the following commands:
>       ```
>       cd "%appdata%\keyman\Keyman Developer\Server\bin"
>       .\ngrok.exe --version
>       .\ngrok.exe http 80
>       ```
> 
> 
> Thank you!

@mcdurdin I am getting the following message after running the command lines,

**Comment by mcdurdin** [comment]
Okay, I am a little bit stumped. Not sure what is causing the problem, perhaps we will need to do a remote desktop session on Monday?

**Comment by bharanidharanj** [comment]
> Okay, I am a little bit stumped. Not sure what is causing the problem, perhaps we will need to do a remote desktop session on Monday?

@mcdurdin Okay, Thanks.

**Comment by mcdurdin** [comment]
@bharanidharanj I have put in a fix to remove the region parameter. Can you retest once the build completes?

Thank you!

@keymanapp-test-bot skip

**Comment by bharanidharanj** [comment]
> @bharanidharanj I have put in a fix to remove the region parameter. Can you retest once the build completes?
> 
> Thank you!
> 
> @keymanapp-test-bot retest

@mcdurdin Sure. I will do it.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NGROK_UPGRADE (PASSED):** Retested with updated PR build (Keyman 17.0.242-alpha-test-10359) on Windows 11 OS (VM) and here is my observation: 1 . Able to update ngrok version to 3.5. Verified that the label name appeared with the version in the Keyman Developer Server Options window. It seems to be working fine. 


   


* **TEST_NGROK_WORKING (PASSED):** 1. After pasting the token key in Authentication token link, I restarted Keyman Developer build. 2. Opened an existing keyboard project. 3. Compiled it. Verified that a URL appeared in the list of server web address in the 'Build' view. 4. Clicked the ngrok-free.app link then clicked the Open in browser button. 5. It opened ngrok web site page with the 'VisitSite' button. 6. Verified that the test website is working correctly after clicking the 'VisitSite' button. It seems to be working fine. 

..ngrok website link
  
   

..ngrok test web page1

    
   


..ngrok test web page2

**Comment by mcdurdin** [comment]
TODO: remove the region parameter entirely now that we have verified that this works.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.251-alpha](https://keyman.com/downloads/releases/alpha/17.0.251)

**Pull request merged**
