### PR TITLE
fix(common/core/web): error from early fat-finger termination due to OS interruptions 🍒

### PR DESCRIPTION
**Pull request by jahorton**
A 🍒-pick of #5479.

## User Testing
@keymanapp/testers 

It's literally the same set of tests that was used for #5479.

Much of this is taken from standard KMW acceptance testing and adapted toward the aspects of KMW modified by this PR, though we'll only worry about testing against a single platform here.

**Platform**:  Chrome emulation / Android

Ensure that you see the "Console" tab while performing these tests.
  - [ ] TEST_CRITICAL:  If any errors (red text entries in the "Console" area) or warnings appear during these tests, fail this test entry and report a screenshot of them.
      - Ignore anything seen elsewhere mentioning "Issues" or within a small "Issues" tab - there are a few entries we know about, but they're not affected by this PR.  I'm looking for "Console" log messages.

Console tab:

image

It should resemble Windows' `CMD` prompt and the macOS Terminal.

Utilize the "Test unminified Keymanweb" testing page to ensure the following:
  - [ ] TEST_1: KMW properly handles input to the controls.
  - **Attempt to add the following keyboards**:
    - [ ] TEST_2: Using "Add a keyboard by keyboard name", add: `sil_ipa`.  (For our currently-deprecated IPA keyboard.)
      - [ ] TEST_3: `ŋ` should be a subkey of `n` - ensure it works.
    - [ ] TEST_4: Using "Add a keyboard by keyboard name", add: `khmer_angkor`
      - [ ] TEST_5: Type in the following sequence:  ស, ុ, ្រ (subkey of រ), ក.  You should see ស្រុក.
      - [ ] TEST_6:  Continuing from the last test, hit backspace in sequence.  As this is a reorder (keyboard) rule test, you should see:
        - ស្រុ
        - ស្រ
        - ស
    - [ ] TEST_7:  Using "Add a keyboard by language name(s)", add: `spanish`.

Utilize the "Prediction - robust testing" testing page for the following:
  - Swap to the "English - EuroLatin (SIL)" keyboard.
    - [ ] TEST_8:  Use long-press `.` to output `'` and then press `e`.  The two characters should not combine.
    - [ ] TEST_9:  Ensure that long-press `p` and SHIFT + long-press `g` displays properly and that the subkeys produce the expected output.
    - [ ] TEST_10:  Type the following sequence, pressing near the center of the key each time:
      - `L` (shift layer)
      - `k` (default layer)
      - `v` (default layer)
      - Expected result:  you should see suggestions for `Love` and `Live`, along with one other random suggestion.

### CODE REVIEW

**Comment by jahorton** [comment]
Huh... GitHub didn't auto-cherry the documentation comment that was applied by code suggestion.  Odd.

**Review by mcdurdin — APPROVED** [review]
LGTM. Any sanity user testing we can do?

**Comment by jahorton** [comment]
> LGTM. Any sanity user testing we can do?

"Can do?"  We can always run the same tests from the PR against `master`.  There's no reliable way to set up an actual repro to test, though.

**Comment by mcdurdin** [comment]
> There's no reliable way to set up an actual repro to test, though.

I'm looking more for regression tests -- make sure nothing else gets broken. I'm fairly confident that this is true, but can you add a user test for Makara similar to the one we did for master?

**Comment by jahorton** [comment]
> ... but can you add a user test for Makara similar to the one we did for master?

Gave it the ol' `CTRL+C` -> `CTRL+V` sequence.

**Comment by MakaraSok** [comment]
## User Testing
@keymanapp/testers 

**Platform**:  Chrome emulation / Android

_Build and test on Windows 10 Pro 21H1, Chrome 92.0.4515.107 (x64) - Pixel 2_

  - [ ] TEST_CRITICAL: **FAILED** - No errors (red text entries in the "Console" area) or warnings appear during "Test unminified Keymanweb". There is one thing though during "Prediction - robust testing".

This shows up when switching the keyboard to EuroLatin (SIL).
image

      
Utilize the "Test unminified Keymanweb" testing page to ensure the following:
  - [x] TEST_1: **PASSED** - the OSK can be used as usual
  - **Attempt to add the following keyboards**:
    - [x] TEST_2: **PASSED** - no issue when adding `sil_ipa` using "Add a keyboard by keyboard name".
      - [x] TEST_3: **PASSED** - `ŋ` is one of the subkeys of `n` - it works as intended.
    - [x] TEST_4: **PASSED** - no issue when adding `khmer_angkor` using "Add a keyboard by keyboard name".
      - [x] TEST_5: **PASSED** - type in  <kbd>ស</kbd> <kbd> ុ</kbd><kbd> ្រ </kbd>(subkey of <kbd>រ</kbd>) <kbd>ក</kbd> and the output indeed is ស្រុក.
      - [x] TEST_6: **PASSED** - Continuing from the last test, hit backspace in sequence.  As this is a reorder (keyboard) rule test, each backspace indeed shows:
        - ស្រុ
        - ស្រ
        - ស
    - [x] TEST_7: **PASSED** - Using "Add a keyboard by language name(s)", add: `spanish` and a Spanish keyboard shows up on the keyboard menu off of the globe key

Utilize the "Prediction - robust testing" testing page for the following:
  - Swap to the "English - EuroLatin (SIL)" keyboard.
    - [x] TEST_8: **PASSED** - Use long-press `.` to output `'` and then press `e`.  The two characters do not combine per expectation.
    - [x] TEST_9: **PASSED** - long-press `p` and SHIFT + long-press `g` displays properly and that the subkeys produce the expected output.
    - [x] TEST_10: **PASSED** - Type the following sequence, pressing near the center of the key each time:
      - `L` (shift layer)
      - `k` (default layer)
      - `v` (default layer)
      - Expected result:  the expected suggestions for `Love` and `Live`, along with one other random suggestion are shown.

**Comment by jahorton** [comment]
Eh, that's fine.  (The `outputContext missing` message.  Not _ideal_, but it's definitely not branch-local.)  And it's "yellow," not red, so it's not worth blocking on.

**Comment by MakaraSok** [comment]
## User Testing [retest on Android for good measure]
@keymanapp/testers 
@darcywong00 @mcdurdin 

**Platform**:  Android 6.0.1 emulated on Nexus 5

_**Test build [#14.0.280-test at 2 Aug 01:52](https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/283153:id/release/kMAPro-debug.apk)**_

~~Utilize the "Test unminified Keymanweb" testing page to ensure the following:~~     
  - [x] TEST_1: **PASSED** - the OSK can be used as usual
  - **Attempt to add the following keyboards**:
    - [x] TEST_2: **PASSED** - no issue when adding `sil_ipa` using "Add a keyboard by keyboard name".
    > successfully installed this from Settings > Install Keyboard or Dictionary > Install from keyman.com > `sil_ipa`
      - [x] TEST_3: **PASSED** - `ŋ` is one of the subkeys of `n` - it works as intended.
    - [x] TEST_4: **PASSED** - no issue when adding `khmer_angkor` using "Add a keyboard by keyboard name".
    > successfully installed this from Settings > Install Keyboard or Dictionary > Install from keyman.com > `khmer_angkor`
      - [x] TEST_5: **PASSED** - type in  <kbd>ស</kbd> <kbd> ុ</kbd><kbd> ្រ </kbd>(subkey of <kbd>រ</kbd>) <kbd>ក</kbd> and the output indeed is ស្រុក.
      - [x] TEST_6: **PASSED** - Continuing from the last test, hit backspace in sequence.  As this is a reorder (keyboard) rule test, each backspace indeed shows:
        - ស្រុ
        - ស្រ
        - ស
    - [x] TEST_7: **PASSED** - Using "Add a keyboard by language name(s)", add: `spanish` and a Spanish keyboard shows up on the keyboard menu off of the globe key
    > Tap on the plus sign in `Installed Languages`>type in the search box `Spanish`>tap to install EuroLatin (SIL) keyboard for Spanish language>successfully installed.

~~Utilize the "Prediction - robust testing" testing page for the following:~~
  - Swap to the "English - EuroLatin (SIL)" keyboard.
    - [x] TEST_8: **PASSED** - Use long-press `.` to output `'` and then press `e`.  The two characters do not combine per expectation.
    - [x] TEST_9: **PASSED** - long-press `p` and SHIFT + long-press `g` displays properly and that the subkeys produce the expected output.
    - [ ] TEST_10: **FAILED** - Type the following sequence, pressing near the center of the key each time:
      - `L` (shift layer)
      - `k` (default layer)
      - `v` (default layer)
      - Expected result:  the expected suggestions for `Love` and `Live`, along with one other random suggestion are shown.
      - Actual result: no suggestion given in the banner. See the screenshot below.
      image

**Comment by MakaraSok** [comment]
Retested for good measure using the stable build [#14.0.280-test at 2 Aug 01:52](https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/283155?buildTab=overview).

Confirm that all tests have PASSED. Things are working as expected.

**Pull request merged**
