### PR TITLE
chore(common): Update localization for Greek Polytonic

### PR DESCRIPTION
**Pull request by darcywong00**
This pulls in the rest of the Greek Polytonic localization strings requested by community site user
https://community.software.sil.org/t/request-for-polytonic-greek-localization/8851

Follows #11877 which added strings for Android and iOS

@sgschantz - Can you add the Greek locale for mac? You previously had "el" for iOS.

## User Testing
**Setup** - Install the PR build of Keyman on the corresponding desktop platforms

* **TEST_WINDOWS** - Verifies Greek Polytonic UI on Windows
1. Install Keyman for Windows
2. Choose "Greek Polytonic" for the UI language
3. Verify UI strings appear in Greek

* **TEST_MAC** - Verifies Greek Polytonic UI on macOS
1. Install Keyman for macOS
2. Choose "Greek Polytonic" for the UI language
3. Verify UI strings appear in Greek

* **TEST_LINUX** - Verifies Greek Polytonic UI on Linux
1. Install Keyman for Linux
2. Start Keyman configuration with: LANGUAGE=el_polyton km-config
3. Verify UI strings appear in Greek

### CODE REVIEW

**Comment by sgschantz** [comment]
I've updated the project settings for macOS to include the Greek localization.

**Review by ermshiperete — APPROVED** [review]
RSLGTM

**Comment by dinakaranr** [comment]
# Test Results

I tested this issue with the attached "Keyman 18.0.84-alpha-test-12112" build on the Windows 10, Ubuntu 22.04 Jammy and MAC OS. Here is my observation.

* **TEST_WINDOWS (Passed):** 
1. Installed the "Keyman-18.0.84" build on the Windows 10.
2. Open the Configuration window by clicking the keyman icon from tray.
3. Click on the English link button and then the list box appears with various languages.
4. Select the "Greek Polytonic" language.
I observed the Polytonic UI language reflected in various places.(Keyboard Layouts, Options, support, and Keyman menu from Windows tray) 

* **TEST_MAC (Passed):** 
1. Installed the "Keyman-18.0.84" build on the macOS.
2. Change the system UI to "Greek Polytonic" language.
3. Open the Configuration dialog by clicking the keyman icon.
I observed the Polytonic UI language reflected in various places. (Keyboard Layouts, Options, and Keyman menu from tray)

* **TEST_LINUX (Passed):** 
1. Installed the "Keyman-18.0.84" build on the Ubuntu 22.04 Jammy.
2. Open the Configuration dialog by giving a command in the terminal. (LANGUAGE=el_polyton km-config)
Observed the Polytonic UI language reflected in various places. (Keyboard Layouts, Options, uninstall, about, and Keyman menu from tray)
It works well. Thank you.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.86-alpha](https://keyman.com/downloads/releases/alpha/18.0.86)

**Pull request merged**
