### PR TITLE
chore: Revert "feat(web): prediction casing follows current layer"

### PR DESCRIPTION
**Pull request by mcdurdin**
Reverts keymanapp/keyman#6459, because of #6507.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
Will we need to re-open #6455 which #6459 closed?

**Comment by mcdurdin** [comment]
> Will we need to re-open #6455 which #6459 closed?

No, we'll go with the new issue #6507 and work from there.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.230-beta](https://keyman.com/downloads/releases/beta/15.0.230)

**Pull request merged**
