### PR TITLE
fix(core): set mac build version for meson cli build to 10.13

### PR DESCRIPTION
**Pull request by srl295**
- add as option to compiler
- Match version in #11302

Fixes: #11423

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
@sgschantz This doesn't seem to have an effect locally, but let's see if it works in ci.

**Comment by srl295** [comment]
@sgschantz seems promising

**Comment by srl295** [comment]
OK as far as I can tell this seems to remove the warning.

**Review by sgschantz — APPROVED** [review]
absolute perfection

**Comment by sgschantz** [comment]
I guess we probably need to cherry-pick to 17 stable also.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.93-alpha](https://keyman.com/downloads/releases/alpha/18.0.93)

**Comment by mcdurdin** [comment]
Cherry-picked to #12246

**Pull request merged**
