### PR TITLE
fix(windows): Show balloon when Keyman is already running

### LINKED ISSUE #4192: bug(windows): Attempting to restart Keyman when already running does not show the balloon notification
**Is your feature request related to a problem? Please describe.**

When pressing the Keyman shortcut on the desktop, nothing appears. It was confusing for me at first why the shortcut does not do anything, but then I notice that Keyman is already running. The thing is that it's buried under the 'Show hidden icon' on the Window taskbar.

**Describe the solution you'd like**

A dialog box should be shown telling the user that Keyman is already running and they can access it from the 
Windows taskbar.

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.214-beta
 - Target Application: Keyman shortcut

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4192.

If Keyman is already running, and the user attempts to start Keyman again, a balloon will be shown to direct the user to the right place on the screen.

Note: this worked in earlier versions of Keyman but stopped working due to name changes for windows in the app.

I have also added a new string for balloon that will need translation.

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

**Comment by mcdurdin** [comment]
@MakaraSok would you like to check that this works for you?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.235-beta](https://keyman.com/downloads/releases/beta/14.0.235)

**Comment by MakaraSok** [comment]
Tested and confirm the balloon does appear when Keyman is opened while it's already opened.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
