### PR TITLE
fix(oem/fv/ios): build configuration for 14.0's test-oriented simulator artifact

### PR DESCRIPTION
**Pull request by jahorton**

### CODE REVIEW

**Comment by darcywong00** [comment]
Is this similar to the pbxproj file changes in #4094 ?

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by jahorton** [comment]
> Is this similar to the pbxproj file changes in #4094 ?

Yep.  They were never made for the FV app.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.281](https://keyman.com/downloads/releases/stable/14.0.281)

**Pull request merged**
