### PR TITLE
fix(web): blocks nextLayer for keys quickly typed when multitapping to new layer when final tap is held

### LINKED ISSUE #11187: bug(web): modipress held from multitapping releases early if first key from new layer is pressed too early
Does reproduce:

1. With `sil_euro_latin` 3.0+...
2. Triple tap the numeric key, holding the final tap instead of releasing it.
3. _Quickly_ tap any non-frame key.

Result:  the key produces its text and you are _immediately_ returned to the default layer.

Does _not_ reproduce:

1. With `sil_euro_latin` 3.0+...
2. Triple tap the numeric key, holding the final tap instead of releasing it.
3. Wait ~0.5 seconds.
4. Tap any non-frame key.

You will remain on the same layer until the held, layer-swapping finger is lifted.

Does _not_ reproduce:

1. With `sil_euro_latin` 3.0+...
2. Press and hold the numeric key.
3. _Quickly_ tap any key from the second or third row aside from the key in `s` position.

You will remain on the numeric layer.

Thus, this only triggers for modipresses reached by multitaps, and only if the first key that would normally trigger a layer swap happens before the multitap timer completes.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11187.

This fixes an issue where a held layer-swap was being cancelled incorrectly upon use of an output key.  Conditions needed for the error to trigger:
- the output key's layer was reached by multitap + hold, not a single tap + hold
- the output key was tapped before the current layer would otherwise be "locked in" due to time held.  (That is, tapping the layer-change key again, rather than the output key, would continue the layer-changing multitap.)

To be clear, if there's a pause before keys are tapped (enough to wait out that "lock in" timer) but the scenario is otherwise the same, that is working already.  

Turns out that I missed something small in #10838, with its changes being why this specific behavior broke.  The efforts to avoid an asynchronous infinite loop, as implemented, caused the ongoing gesture to self-cancel at the exact point when it should have transitioned to the "locked-in modipress" state.  With a small tweak to the logic, we can allow post-init model rejection to still trigger replacement while ensuring init-time model rejection still auto-cancels, which preserves #10838's fix while fixing #11187 as well.

## User Testing

TEST_NUMERIC_MULTITAP:   Using Keyman for Android and `sil_euro_latin`...

1. Triple-tap the numeric key, holding it down on the final tap.
2. Tap any key that produces text, still holding down the finger that tapped the numeric key.
3. Verify that the layer does _not_ change when text is output.
4. End all ongoing touches and gestures.
5. Verify that the layer changes afterward.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NUMERIC_MULTITAP (FAILED):** Tested with the attached PR build (17.0.303-beta-test-11189) on an Android 13 mobile device and here is my observation: 1. Triple tapped the number key the holding the key on the final tap. 2. Tapped some other key from the keyboard leads to Keyboard error message. I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/933a697d-f39e-47e4-a295-43c46227b1a1

**Comment by jahorton** [comment]
The keyboard error detected corresponds to #11165, the fix for which (#11178) only just merged in.

The Sentry event: https://keyman.sentry.io/share/issue/799c39d76ad541c9b9ed7d65aac52ce1/  (Confirmed by matching release: `release@17.0.303-beta-test-11189`)

While I could override... this is also based directly on `beta`, so how about I just merge that fix in and we do a quick retest, eh?  (And... merge done.)  I couldn't help but notice that the sequence actually executed correctly... aside from signalling that error.

@keymanapp-test-bot retest ALL

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NUMERIC_MULTITAP (PASSED):** Retested with the attached PR build (Keyman 17.0.305-beta-test-11189) on an Android 13 Mobile device and here is my observation: 1. Tripple tapped the numeric key, holding it down on the final tap. 2. Tapped some other keys that produce text and verified that the tapped keys showed the outputs on the screen. 3. Completed all ongoing touches and gestures, then released the Number key instead of holding it. Verified that the layer changed afterward.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.305-beta](https://keyman.com/downloads/releases/beta/17.0.305)

**Pull request merged**
