### PR TITLE
feat(developer): touch layout testing 🎩

### PR DESCRIPTION
**Pull request by mcdurdin**
Adds support for testing touch layouts without requiring use of device emulation. Uses new `InlinedOSKView`.

Does not yet add a view within Keyman Developer; this will come in a separate PR.

## Windows

image

## iPhone

image

## Device Menu

image

## Keyboard Menu

image

# User Testing

All this testing should run from Keyman Developer, web test view. You no longer need to use the Chrome Developer Tools to test mobile (touch) keyboards.

These tests should be run on various devices; on smaller devices it is expected that it may be difficult to use the test page, but it shouldn't functionally fail.

GROUP_CHROME: Test in Chrome
GROUP_FIREFOX: Test in Firefox
GROUP_IPAD: Test on an iPad, in Safari
GROUP_IPHONE: Test on an iPhone, in Safari
GROUP_ANDROID: Test on a modern Android device (tablet or phone), in Chrome

* **TEST_DESKTOP:** Load a keyboard, e.g. khmer_angkor, and check that it works correctly in web (desktop) view.
* **TEST_MOBILE:** Load a keyboard, e.g. khmer_angkor, and check that it works correctly in iPhone view. Test longpress, key preview, layers. Note that the globe key deliberately does not work.
* **TEST_MULTI:** Verify that loading and testing multiple keyboards and swapping between them works.
* **TEST_MODEL:** Verify that loading a keyboard and a model in the debugger works, and that the predictions are working and can be used in the various touch modes.
* **TEST_PACKAGE:** Verify that selecting a package for 'Test Package Online' in the Package Editor works, and that you can install it on your device.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Note: kmw.keyboardchange does not seem to always be called after a keyboard is selected. Are there circumstances in which it is not called?

**Comment by mcdurdin** [comment]
Issues:

* preview is offset vertically slightly
image

* longpress is offset horizontally
image

**Comment by jahorton** [comment]
For bookkeeping:  fully replaces what #2876 originally sought to achieve.

**Comment by MakaraSok** [comment]
> GROUP_IPAD: Test on an iPad, in Safari

How to test this on iPad. Should the web build from this PR be used to test on Safari in iPad simulator? The same question for Android.

> These tests should be run on various devices; on smaller devices it is expected that it may be difficult to use the test page, but it shouldn't functionally fail.

What should be used to run on these [emulated] devices? Please provide the detailed instructions. This seems to be very new. Thanks.

**Comment by mcdurdin** [comment]
> How to test this on iPad. Should the web build from this PR be used to test on Safari in iPad simulator? The same question for Android.

This uses Keyman Developer's existing web server functionality. Start Keyman Developer and click the "Test Keyboard on web" button for a keyboard. Then, you will see a list of web site addresses for the test server. Usually, the best one to use will start with something like `http://192.168.` or `http://10.`. You can click on one of those addresses and scan the QR Code on a device (must be on same network) to load the test site on that device, or you can type the address directly into browser bar on the device.

image

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
* GROUP_CHROME: Test in Chrome
  - **TEST_DESKTOP: FAILED** This is probably only applicable with Khmer  Angkor, but when the size of the key caps are smaller than the character on the caps, they are not fully shown.
    On the bottom row the forth key from the right and the fifth key from the left have their other half cropped off. The same for the second from the left and third from the right on the third row.

    
  - **TEST_MOBILE: FAILED** The subkeys pop up to the far right of the OSK and not directly on the key pressed. See the screenshot.
    

  - **TEST_MULTI: PASSED** Switching between the system and Khmer Angkor keyboard does work without any issue. (No instructions given on how to add more than one keyboard to the tool. This is a new tool which is not familiar to the tester. Specific instructions needed to add more than one keyboard. Currently, from within DK, only one keyboard can be viewed at a time.)
  - **TEST_MODEL: FAILED** The model can't be used and the font selected for the keyboard doesn't get applied here. Nothing happens when tapping on the word suggestion.

    


  - **TEST_PACKAGE: BLOCKED** No instructions given on how to get to "Package Editor" in KD. It seems like this feature is not yet available.

* GROUP_FIREFOX: Test in Firefox **(Please note that the result in here is exactly like that of Chrome.)**
  - **TEST_DESKTOP: FAILED** This is probably only applicable with Khmer  Angkor, but when the size of the key caps are smaller than the character on the caps, they are not fully shown.
    On the bottom row the forth key from the right and the fifth key from the left have their other half cropped off. The same for the second from the left and third from the right on the third row.

    
  - **TEST_MOBILE: FAILED** The subkeys pop up to the far right of the OSK and not directly on the key pressed. See the screenshot.
    

  - **TEST_MULTI: PASSED** Switching between the system and Khmer Angkor keyboard does work without any issue. (No instructions given on how to add more than one keyboard to the tool. This is a new tool which is not familiar to the tester. Specific instructions needed to add more than one keyboard. Currently, from within DK, only one keyboard can be viewed at a time.)
  - **TEST_MODEL: FAILED** The model can't be used and the font selected for the keyboard doesn't get applied here. Nothing happens when tapping on the word suggestion.

    


  - **TEST_PACKAGE: BLOCKED** No instructions given on how to get to "Package Editor" in KD. It seems like this feature is not yet available.

**Comment by MakaraSok** [comment]
* GROUP_IPAD: Test on an iPad, in Safari
  - **TEST_DESKTOP: BLOCKED** This test and all below are BLOCKED because the QR code to `http://10.*.*.**:8008 and the rest are not accessible to a physical Android device nor iOS emulators.
  - **TEST_MOBILE: BLOCKED**
  - **TEST_MULTI: BLOCKED**
  - **TEST_MODEL: BLOCKED**
  - **TEST_PACKAGE: BLOCKED**

* GROUP_IPHONE: Test on an iPhone, in Safari
  - **TEST_DESKTOP: BLOCKED**
  - **TEST_MOBILE: BLOCKED**
  - **TEST_MULTI: BLOCKED**
  - **TEST_MODEL: BLOCKED**
  - **TEST_PACKAGE: BLOCKED**

* GROUP_ANDROID: Test on a modern Android device (tablet or phone), in Chrome
  - **TEST_DESKTOP: BLOCKED**
  - **TEST_MOBILE: BLOCKED**
  - **TEST_MULTI: BLOCKED**
  - **TEST_MODEL: BLOCKED**
  - **TEST_PACKAGE: BLOCKED**

**Comment by mcdurdin** [comment]
> * This test and all below are BLOCKED because the QR code to `http://10.*.*.**:8008 and the rest are not accessible to a physical Android device nor iOS emulators.

Perhaps we should rubber-ducky 🦆 to sort this out?

**Comment by mcdurdin** [comment]
> TEST_DESKTOP * This is probably only applicable with Khmer  Angkor, but when the size of the key caps are smaller than the character on the caps, they are not fully shown.
>   On the bottom row the forth key from the right and the fifth key from the left have their other half cropped off. The same for the second from the left and third from the right on the third row.

> TEST_MOBILE: FAILED The subkeys pop up to the far right of the OSK and not directly on the key pressed. See the screenshot.

I think this is unrelated to this code, but is rather a display issue for KeymanWeb and Khmer. If you want to pursue this, please open a separate issue and mark this as passed.

> * **TEST_PACKAGE ([BLOCKED](https://github.com/keymanapp/keyman/pull/5723#issuecomment-928974865))**: No instructions given on how to get to "Package Editor" in KD. It seems like this feature is not yet available.

For example: in Keyman Developer, load the khmer_angkor project, build the keyboard and then open the khmer_angkor.kps from the package tab in the Project view. 

image

In the package editor, go to the Compile tab, and click Test Package Online:

image

Then visit the web page as given in the browser on your test device, and click on the Install Packages link, in the test view in the web browser, and then you can click the link to install the package on the test device:

image

**Comment by MakaraSok** [comment]
* GROUP_CHROME: Test in Chrome

  * **TEST_DESKTOP: PASSED** the keyboards do work, but there is a separate issue with how the OSK is shown.

    bug report: https://github.com/keymanapp/keyman/issues/5779

  * **TEST_MOBILE: PASSED** all keys, key preview and longpress work as expected, but there is a separate issue when longpressing on a keyboard on touch devices, the subkeys are shown further away to the right of the screen instead of right on the base key.

    bug report: https://github.com/keymanapp/keyman/issues/5780

  * **TEST_MULTI: PASSED** the keyboards swap seamlessly.

  * **TEST_MODEL: FAILED** word suggestions are shown contextually on the banner, but it doesn't output when tapped on off of the banner.

  * **TEST_PACKAGE: PASSED** the built packages are shown and can be downloaded to install.


* GROUP_FIREFOX: Test in Firefox

  * **TEST_DESKTOP: PASSED** the keyboards do work, but there is a separate issue with how the OSK is shown.

    bug report: https://github.com/keymanapp/keyman/issues/5779

  * **TEST_MOBILE: PASSED** all keys, key preview and longpress work as expected, but there is a separate issue when longpressing on a keyboard on touch devices, the subkeys are shown further away to the right of the screen instead of right on the base key.

    bug report: https://github.com/keymanapp/keyman/issues/5780

  * **TEST_MULTI: PASSED** the keyboards swap seamlessly.

  * **TEST_MODEL: FAILED** word suggestions are shown contextually on the banner, but it doesn't output the word when tapped on off of the banner.

  * **TEST_PACKAGE: PASSED** the built packages are shown and can be downloaded to install.


* GROUP_IPAD: Test on an iPad, in Safari

  * **TEST_DESKTOP: PASSED** but unlike the desktop view, one has to tap in the text area to start typing, otherwise the OSK will not automatically detect/output anything at all.

  There also is a separate issue with how the OSK is shown.

  bug report: https://github.com/keymanapp/keyman/issues/5779
  
  * **TEST_MOBILE: PASSED** all keys works but the OSK jumps up making the top part of the OSK goes out of sight. Subkeys are also popped away to the right of the OSK, just like what's seen in iPhone on Chrome emulator.

  * **TEST_MULTI: PASSED** Keyboards swap seamlessly.

  * **TEST_MODEL: PASSED** The word suggestions shown on the banner and work as expected, but once picked a suggestion, the OSK moves up and has the banner gone out of sight.

  * **TEST_PACKAGE: PASSED** the built packages can be downloaded and installed on the device, but this issue (https://github.com/keymanapp/keyman/issues/5704) gets in the way. However the package installed and the keyboard is usable. _Note that the predictive text available will not be installed together with the keyboard automatically._


* GROUP_IPHONE: Test on an iPhone, in Safari

  * **TEST_DESKTOP: PASSED** but unlike the desktop view, one has to tap in the text area to start typing, otherwise the OSK will not automatically detect/output anything at all.

  There also is a separate issue with how the OSK is shown.

  bug report: https://github.com/keymanapp/keyman/issues/5779

  * **TEST_MOBILE: PASSED** all keys works but the OSK jumps up making the top half of the OSK goes out of sight. Subkeys are also popped away to the right of the OSK, just like what's seen in iPhone on Chrome emulator.

  * **TEST_MULTI: PASSED** Keyboards swap seamlessly.

  * **TEST_MODEL: PASSED** The word suggestions shown on the banner and work as expected.

  * **TEST_PACKAGE: PASSED** the built packages can be downloaded and installed on the device, but this issue (https://github.com/keymanapp/keyman/issues/5704) gets in the way. However the package installed and the keyboard is usable. _Note that the predictive text available will not be installed together with the keyboard automatically._


* GROUP_ANDROID: Test on a modern Android device (phone), in Chrome

  * **TEST_DESKTOP: PASSED** but unlike the desktop view, one has to tap in the text area to start typing, otherwise the OSK will not automatically detect/output anything at all.

    There also is a separate issue with how the OSK is shown.

    bug report: https://github.com/keymanapp/keyman/issues/5779

  * **TEST_MOBILE: PASSED** all keys works but the subkeys are popped away to the right of the base key and there is a black thing popped on the top left of the OSK.

    

  * **TEST_MULTI: PASSED** Keyboards swap seamlessly.

  * **TEST_MODEL: PASSED** The word suggestions shown on the banner, but it doesn't work as expected. Nothing is output when the suggestion is tapped on.

  * **TEST_PACKAGE: PASSED** the built packages can be downloaded and installed on the device and the package installed and the keyboard is usable.

**Comment by mcdurdin** [comment]
> * (GROUP_CHROME) **TEST_MODEL: FAILED** word suggestions are shown contextually on the banner, but it doesn't output when tapped on off of the banner.

This is certainly an issue but I will make sure it hasn't been fixed in another branch, and if so will open a new issue to address this so we don't block this particular branch any longer. (Support for predictive text in desktop modes is extremely limited in any case at present so am comfortable with this not being fixed in the short-term.)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.125-alpha](https://keyman.com/downloads/releases/alpha/15.0.125)

**Comment by mcdurdin** [comment]
> This is certainly an issue but I will make sure it hasn't been fixed in another branch, and if so will open a new issue to address this so we don't block this particular branch any longer. (Support for predictive text in desktop modes is extremely limited in any case at present so am comfortable with this not being fixed in the short-term.)

Testing against 15.0.125-alpha shows that this issue is resolved.

**Pull request merged**
