### PR TITLE
fix(web): Solving kmwosk color inconsistency

### PR DESCRIPTION
**Pull request by MattGyverLee**
This pull request attempts to solve the issues mentioned in https://github.com/keymanapp/keyman/issues/4153

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by mcdurdin** [comment]
Thank you for this pull request. These changes look really good. We don't have any automated regression tests for styling -- it's kinda hard to achieve in any case. I've asked @jahorton and @darcywong00 to review the changes on iOS and Android respectively and give any feedback needed.

Unlike iOS, where there is a clear delineation between phone and tablet, this is really fuzzy on Android. Is a phablet a tablet or a phone? We have found that they are kinda hard to detect web-side, because the only real difference is in screen size -- and given that information has in the past not been reliably available (and of course, resolution != size). From my fuzzy memory, I think that Keyman for Android has some additional sensing it passes through to KeymanWeb to give a more reliable answer (is that right @darcywong00?). We haven't looked at this in some time, however, so there may be some more reliable signals available now.

@jahorton once this passes testing, we should cherry-pick to `beta`.

**Comment by mcdurdin** [comment]
Unfortunately we probably won't get to merging this until after Christmas as things are pretty hectic just now with the beta release. I don't like delaying pull requests 😢 but unless other things fall into place very quickly we just won't get to it. Please bear with us 😃

**Comment by MattGyverLee** [comment]
No problem on the timing. I hard-coded similar style workarounds into my keyboards, so I won't see the result of this work much anyway.

**Comment by darcywong00** [comment]
> I think that Keyman for Android has some additional sensing it passes through to KeymanWeb to give a more reliable answer

The distinction between phone and tablet on Keyman for Android is based on dp of the device.
The default value of [device_type](https://github.com/keymanapp/keyman/blob/master/android/KMEA/app/src/main/res/values/strings.xml#L5) in strings.xml is `AndroidMobile`. Starting at 600dp, [device_type](https://github.com/keymanapp/keyman/blob/master/android/KMEA/app/src/main/res/values-sw600dp/strings.xml#L5) is set to `AndroidTablet`.

**Review by jahorton — COMMENTED** [review]
Seems pretty reasonable for iOS.

Here's how it looks with the "French Basic" keyboard (`basic_kbdfr`).  It uses a desktop-like layout that was compiled into the keyboard.  (It's not a run-time generated layout, despite using five rows.  It's just not 'optimized'.)

Screen Shot 2020-12-21 at 9 13 17 AM

Note the second-to-last key on the second row - it's a deadkey on both the 'default' (`^`) and 'shift' (`¨`) layers.

**Review by mcdurdin — APPROVED** [review]
I am happy to approve this now and will cherry-pick this to beta. Looks great, and thank you again for your contribution!

**Pull request merged**
