### PR TITLE
change(ios/engine):  Removes unused, deprecated JS/JSON-based adhoc install code

### PR DESCRIPTION
**Pull request by jahorton**
Since we'll be removing cloud-JS based keyboard installation within the iOS engine and app outright in the near future, I figured now's as good a time as any to remove the extreme-legacy adhoc code that's somehow survived until now within the iOS code base.  It'll make the path forward for KMP-only installs a little easier to see.

Just to be safe, I did test a direct KMP download of a lexical model from a webpage, just to confirm that the removed lexical model code was indeed unused.  Went off without a hitch.

### CODE REVIEW

**Comment by darcywong00** [comment]
> Just to be safe, I did test a direct KMP download of a lexical model from a webpage, just to confirm that the removed lexical model code was indeed unused. Went off without a hitch.

Did you also try to download a lexical models from the cloud? (e.g. after installing fv_sencoten keyboard)

**Comment by jahorton** [comment]
> Did you also try to download a lexical models from the cloud? (e.g. after installing fv_sencoten keyboard)

Not at first.  It was very easy to tell that the removed code had nothing to do with that pathway.  There's a bit of instability there, but it already existed.

**Comment by darcywong00** [comment]
I suggest opening an issue on keymanapp/help.keyman.com to keep track of KMManager() changes.

e.g. https://help.keyman.com/developer/engine/iphone-and-ipad/13.0/Manager/downloadLexicalModel

**Comment by jahorton** [comment]
> I suggest opening an issue on keymanapp/help.keyman.com to keep track of KMManager() changes.
> 
> e.g. https://help.keyman.com/developer/engine/iphone-and-ipad/13.0/Manager/downloadLexicalModel

https://github.com/keymanapp/help.keyman.com/issues/183

**Pull request merged**
