### PR TITLE
fix(linux): Improve fix for #3399

### LINKED ISSUE #3399: bug(linux): Downloading/installing the euro_latin_sil keyboard for Jola-Fonyi doesn't show up in Linux keyboards list
**Describe the bug**
When searching for Jola-Fonyi and installing the euro_latin_sil keyboard for that language it'll install the keyboard and add an entry to the Gnome Input Sources list. However, it won't show in the keyboard selection list.

When I add the keyboard for Jola-Fonyi in the Input Sources section of the Gnome Settings dialog it will show up correctly.

**To Reproduce**
1. in km-config, click on Download and search for `l:id:dyo-latn`
2. Install the keyboard

**Actual behavior**

Keyboard shows up as `dyo:..sil_euro_latin.kmx` in Gnome Settings dialog, but doesn't show up in list of keyboards.

Screenshot from 2020-07-23 18-57-44

**Expected behavior**

Keyboard appears as `Other (EuroLatin (SIL) - Jola-Fonyi)` in both Gnome Settings dialog and the list of keyboards.

Screenshot from 2020-07-23 19-00-31

This is the case if the keyboard gets added in the Gnome Settings dialog.

### PR DESCRIPTION
**Pull request by ermshiperete**
This improves the implementation for normalizing language tags when installing a keyboard. Based on the Windows implementation in `Keyman.System.CanonicalLanguageCodeUtils.pas`.

One difference to the Windows implementation is that the mapping of 3- to 2-letter tags is based on `langtags.json` instead of
`iso639-3.tab`.

Closes #3399.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> One difference to the Windows implementation is that the mapping of 3- to 2-letter tags is based on `langtags.json` instead of
> `iso639-3.tab`.

Nice! I didn't quite get to doing that refactor on Windows... 😁

**Review by mcdurdin — APPROVED** [review]
LGTM. Looks like the BCP47Tag.pas unit translated pretty well to Python!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.236-beta](https://keyman.com/downloads/releases/beta/14.0.236)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
