### PR TITLE
fix(developer): correct handling of trailing spaces by GetDelimitedString() in kmcmplib compiler

### PR DESCRIPTION
**Pull request by markcsinclair**
Fix `GetDelimitedString()` to correctly handle trailing spaces

Fixes: [#11937](https://github.com/keymanapp/keyman/issues/11937)

Tests for `GetDelimitedString()` in `gtest-compiler-test.cpp`

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by markcsinclair** [comment]
Ready for review.

Once merged, this should fix four commented-out test cases in [#11663](https://github.com/keymanapp/keyman/pull/11663)

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by markcsinclair** [comment]
An additional bug in the handling of spaces, but no argument, in the delimited string was identified in using test cases that had been previously commented out in [#11663](https://github.com/keymanapp/keyman/pull/11663).  This has required an additional one-line fix, and eight supporting test cases.

**Comment by mcdurdin** [comment]
> An additional bug in the handling of spaces, but no argument, in the delimited string was identified in using test cases that had been previously commented out in [#11663](https://github.com/keymanapp/keyman/pull/11663). This has required an additional one-line fix, and eight supporting test cases.

Process note: generally, if you make significant changes to a PR following a review, it should either be re-reviewed or the changes should be added to a follow-up PR. We try to keep changes post-approval of a PR to nits only.

**Comment by markcsinclair** [comment]
It's a fair cop, Your Honour!  I had hoped to get these interlinked PRs merged in the short gap between your return and my departure to holiday, and so pushed past what I know to be good practice - sorry.

**Comment by mcdurdin** [comment]
No worries mate, all good 😁

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.74-alpha](https://keyman.com/downloads/releases/alpha/18.0.74)

**Pull request merged**
