### PR TITLE
feat(android/engine): Single tap globe switch to previous system IME

### LINKED ISSUE #6175: feat(android): Android Globe icon: single tap behavior with only one Keyman Keyboard
**Is your feature request related to a problem? Please describe.**
Android Globe icon "single tap behavior" with only one Keyman Keyboard installed, needs to be relooked into

Current scenario, with only one Keyman Keyboard installed, single tap on globe icon presents list of all system keyboards along with Keyman similar to long press on Globe Icon.

with more than one Keyman Keyboard installed, single tap on globe icon presents toggles between keyman keyboards

**Describe the solution you'd like**
with only one Keyman Keyboard installed, single tap on globe icon can switch to previously used system keyboard.

image

**Keyman for Android:**
 - Device: Samsung
 - OS: Andriod 11
 - Keyman version: 15.0.186-alpha
 - Target application: Notes, Keyman

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #6175 ; Follow-on to #1887, #5834

Change to Keyman Engine for Android API
* Add enum `GlobeKeyAction.GLOBE_KEY_ACTION_ADVANCE_TO_PREVIOUS_SYSTEM_KEYBOARD`

This way, when only 1 Keyman keyboard is installed as a system IME, the user can tap the globe key to revert to the previous system IME.

### Keyman IME Globe Key in System keyboard
| Duration | # Keyman Keyboards Installed | Behavior |
|-----------|----------------------------------|------------|
| Short       | 1                                              | Switch to previous IME |
| Short       |  2+                                           | Switch to next Keyman keyboard |
| Long        |  1                                             | Keyboard picker menu |
| Long        |  2+                                          | Keyboard picker menu |

No change to globe-key for In-app keyboards
Also no change  to globe key behavior on the lock screen

## User Testing
Because the Android SDK call to switch to last (previous) keyboard changes at Android API 28, the test cases are broken into
* Number of Keyman keyboards installed
* Short vs long-press on globe key
* Android SDK level
* In-app vs System Keyboard
For each test, do a clean installation of Keyman (only 1 keyboard loaded)
Note, the globe key action triggers when the key is released

**SUITE_API_21**

* **TEST_INAPP_KEYBOARD_21** - Tests globe key in the Keyman in-app keyboard
1. Install and launch Keyman on Android API 21 emulator
2. With the default sil_euro_latin keyboard, short-press the globe key
3. Verify the Keyboard picker menu appears
4. Dismiss the menu
5. Long-press the globe key
6. Verify the keyboard picker menu appears
7. Dismiss the menu
8. From the "Settings" menu, search for another Keyman keyboard and install
9. After the keyboard installs, short-press the globe key
10. Verify the keyboard switches to the next Keyman keyboard
11. Long-press the globe key
12. Verify the keyboard picker menu appears

* **TEST_SYSTEM_KEYBOARD_21** - Tests globe key in Keyman system IME
1. Before installing Keyman, install and enable additional system IME's until there's two non-Keyman IME's (e.g. Gboard and FirstVoices)
2. Install and launch Keyman 
3. On the "Getting Started" menu, set Keyman as a default system keyboard
4. Dismiss the "Getting Started" menu and launch a separate app to type in (e.g. Chrome browser)
5. Switch to a non-Keyman system IME (e.g. Gboard)
6. Switch to the Keyman system IME
7. On the Keyman keyboard, short-press the globe key
8. Verify the system IME switches back to the previous IME
9. Switch to the Keyman system IME
10. On the Keyman keyboard, long-press the globe key
11. Verify the keyboard picker menu appears
12. Dismiss the keyboard picker menu
9. Go back to the Keyman app
10. From the "Settings" menu, search for another Keyman keyboard and install
11. After the keyboard installs, switch back to the separate app (e.g. Chrome browser)
12. Switch to a non-Keyman system IME (e.g. Gboard)
13. Switch to the Keyman system IME
14. On the Keyman keyboard, short-press the globe key
15. Verify the keyboard switches to the next Keyman keyboard
16. Switch to a non-Keyman system IME (e.g. Gboard)
17. Switch to the Keyman system IME
18. On the Keyman keyboard, long-press the globe key
19. Verify the keyboard picker menu appears (with other system IME's listed on the bottom)
20. Dismiss the keyboard picker menu

* **TEST_LOCK_SCREEN_21** - Tests globe key in Keyman system IME on lock screen
1. Before installing Keyman, on the Android device set a simple lock screen password (e.g. `1234`). If using an actual device, recommend having an additional unlock set up (e.g. fingerprint).
2. Install and launch Keyman
3. On the "Getting Started" menu, set Keyman as a default system keyboard
4. Dismiss the "Getting Started" menu and launch a separate app to type in (e.g. Chrome browser)
5. Lock the device
6. Start unlocking the device
7. With the Keyman IME, short-press the globe key button
8. Verify the keyboard switches to another system IME

**SUITE_API_29**
Repeat all the test cases from SUITE_API_21 using an Android 29+ emulator

* **TEST_INAPP_KEYBOARD_29** - Tests globe key in the Keyman in-app keyboard

* **TEST_SYSTEM_KEYBOARD_29** - Tests globe key in Keyman system IME

* **TEST_LOCK_SCREEN_29** - Tests globe key in Keyman system IME on lock screen

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
## SUITE_API_21:

- **TEST_INAPP_KEYBOARD_21: PASSED** The globe key works as indicated.
- **TEST_SYSTEM_KEYBOARD_21: PASSED** The globe key works as indicated.
- **TEST_LOCK_SCREEN_21: PASSED** The globe key on the lock screen does switch to the next IME.

**Comment by bharanidharanj** [comment]
## SUITE_API_29: 

* **TEST_INAPP_KEYBOARD_29 : PASSED**  Tested this issue with the latest Keyman Installed 15.0.192-alpha-test-6206 in Android Emulator API 29 and the globe key is working as expected.
* **TEST_SYSTEM_KEYBOARD_29: PASSED** Tested this issue with the latest Keyman Installed 15.0.192-alpha-test-6206 in Android Emulator API 29 and the globe key is working as expected.
* **TEST_LOCK_SCREEN_21: PASSED** Tested this issue with the latest Keyman Installed 15.0.192-alpha-test-6206 in Android Emulator API 29 and noticed that clicking on the globe key switch to next IME in the Lock Screen mode.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.194-alpha](https://keyman.com/downloads/releases/alpha/15.0.194)

**Pull request merged**
