### PR TITLE
chore(common): Add crowdin strings for Kannada

### LINKED ISSUE #7952: chore(common): Request Kannada localization
### Describe the bug

Kannada localization is completed in crowdin.

Please pull it into all apps. I would like to test it.

### Reproduce the bug

_No response_

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [x] Keyman for Android
- [x] Keyman for iPhone and iPad
- [x] Keyman for Linux
- [x] Keyman for macOS
- [x] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

_No response_

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

Kannada

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #7952 

This adds the crowdin strings for Kannada - locale kn-IN

TODO for @sgschantz 
- [x] Run XCode for iOS
- [x] Run XCode for macOS

## User Testing
Load the PR build for each platform and set the UI / Locale to "ಕನ್ನಡ" (and/or Kannada)

* **TEST_ANDROID** 
1. Load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display Language --> ಕನ್ನಡ (Kannada)
3. Return to the Keyman app 
4. Verify the UI is in Kannada (prompt, Settings strings, etc.). Note, the globe tip string stays in English and is a separate issue #7975

kannada android menu

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Kannada
3. Return to the Keyman app
4. Verify the UI is in  Kannada

* **TEST_LINUX**
1. Start Keyman configuration with: LANGUAGE=kn_IN km-config
2. Verify Keyman UI is in Kannada

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Kannada
3. Verify the Keyman UI is in Kannada

* **TEST_WINDOWS**
1. Load the PR build of Keyman for Windows
2. Set the UI to Kannada
3. Verify the Keyman UI is in Kannada

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID (PASSED):** Tested with the attached PR build (16.0.126-beta-test-7970) in my Android Mobile device (Ver 11.0) and verified that the changed Kannada UI is showing everywhere instead of English UI. Seems to be working as expected.

**Comment by bharanidharanj** [comment]
* **TEST_WINDOWS (PASSED):** Tested with the attached PR build in Windows 11 OS (VM) and the Kannada UI language is working fine in Keyman dialog. 


..Kannada UI1:

   


..Kannada UI2:

   

..Kannada UI3:

**Comment by bharanidharanj** [comment]
* **TEST_LINUX (PASSED):** Tested with the attached PR build (keyman 16.0.134-beta (package version 16.0.134-1~PR-7970+focal13) in Ubuntu 20.04 Focal Linux OS (VM) and I am able to see the Kannada UI in the Keyamn Configuration dialog.

**Comment by bharanidharanj** [comment]
* **TEST_MACOS (PASSED):** Tested with the attached PR build in mac Mini (Monterey 12.6) OS and I was able to see the Kannada UI appears in the Keyman App. 


..Kannada UI1:
   

..Kannada UI2:

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (PASSED):** Tested with the attached PR build in iPhone and iPad (iOS 15.0) Simulators and I was able to change the Kannada UI in the Keyman App. 


..Kannada UI in iPhone Simulator (iOS 15.0):

   


..Kannada UI in iPad Simulator (iOS 15.0):

**Review by rc-swag — APPROVED** [review]
lgtm

**Pull request merged**
