### PR TITLE
chore(common): Check in crowdin strings for Kibaku 📜

### PR DESCRIPTION
**Pull request by darcywong00**
This checks in the crowdin strings for the locale `ckl` for Kibaku. Does not include macOS.

- [x] TODO: @sgschantz to check on adding ckl (ckl-NG?) locale in XCode

## User Testing
For the listed platforms:
1. Load the PR build
2. Set the UI/locale to Kibaku
3. Verify the UI is Kibaku
Note: The crowdin translator left some strings in English, so that's out of our control

* **TEST_ANDROID**
1. Verify Kibaku strings are like the screenshot
kibaku

* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing

* **TEST_LINUX**
1. start Keyman configuration with: `LANGUAGE=ckl_NG km-config`

* **TEST_WINDOWS**
1. start Keyman configuration and select UI language 'Nya Nasara'

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
There are a handful of advanced strings in English -- probably not enough to worry about? LGTM

**Comment by sgschantz** [comment]
Kibaku is not yet supported on iOS as of version 15.1

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: PASSED** The UI language does switch to Kibaku when the language is selected from the list.
- **TEST_IOS: BLOCKED** (language not available per Shawn's comment.)
- **TEST_LINUX: BLOCKED** The language is not seen in the dropdown menu. See the screenshot below.

    image

- **TEST_WINDOWS: BLOCKED** The language is not seen in the dropdown menu. See the screenshot below.

    image

**Comment by darcywong00** [comment]
> * **TEST_WINDOWS: BLOCKED** The language is not seen in the dropdown menu. See the screenshot below.
>     image

@MakaraSok - It appears the translator used the string "Nya Nasara" for the language, which appears in the list between "Bura-Pabir" and "Deutch".

See https://github.com/keymanapp/keyman/blob/06835125e6324b67160504fb8a6c1d0780328ef2/windows/src/desktop/kmshell/locale/ckl-NG/strings.xml#L649

I'm not sure if that's correct...

**Comment by MakaraSok** [comment]
I was not looking for "... Nasara". I thought Nasara was for a [separate keyboard](https://github.com/keymanapp/keyman/pull/6047#issuecomment-1007043064). On Android, it's shown as "Kanuri".

image


Anyway, the language does switch to "Nya Nasara".
image

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.179-alpha](https://keyman.com/downloads/releases/alpha/15.0.179)

**Pull request merged**
