### PR TITLE
chore(developer): seed epic/ldml-editor 🗼

### PR DESCRIPTION
**Pull request by mcdurdin**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
From the commit:

> seed epic/ldml-editor � 

hmm my console wasn't handling this very well. Such is life

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by srl295** [comment]
> > seed epic/ldml-editor �

image

I decided against _that_ one!

**Comment by mcdurdin** [comment]
> > > seed epic/ldml-editor �
> 
> I decided against _that_ one!

I typed the emoji in a `git commit -m "... 🗼"` command and due to wrong encoding it got corrupted without me noticing. I don't think it's worth fixing :grin:

**Pull request merged**
