### PR TITLE
fix(web): forgot to target es5 when minifying polyfilled worker

### LINKED ISSUE #9401: bug(android): Keyboard error message appear on the screen after installing Keyman 17.0.150 build in Android Lollipop OS
### Describe the bug

I noticed that after installing Keyman 17.0.150 alpha build in Android Lollipop OS, it is showing keyboard error message on the screen. 

### Reproduce the bug

1. Install Keyman 17.0.150-alpha build.
2. Open Keyman-InApp. 

Here, I noticed that an error message flashes on the screen. Seems to be an issue. 

Note: This error message always appear on the scree whenever a new keyboard is installed. 

..Error in default keyboard after opening keyman In-App

   

..After installing a keyboard
   

### Expected behavior

The default keyboard should appear without showing any error message. 

### Related issues

#7613

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.15-alpha

### Operating system

Android 5.1 Lollipop OS

### Device

API 22 Android Simulator

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### LINKED ISSUE #9408: bug(web): esbuild minification introduces Android API-incompatible arrow funcs
Sentry Issue: [KEYMAN-WEB-DS](https://keyman.sentry.io/issues/4362964860/?referrer=github_integration)

```
SyntaxError: Unexpected token =>
  at None (blob:null/d8970687-38d9-4657-a356-c4a0824632fd:1:41)
```

@jahorton here.

From `common/web/lm-worker/build/lib/worker-main.polyfilled.min.js`:

```javascript
var ae=Object.defineProperty;var v=(r,e)=>ae(r,"name",{value:e,configurable:!0});/* ...
```

Contrast with `common/web/lm-worker/build/lib/worker-main.polyfilled.js`:

```javascript
if (defineProperty) {
	defineProperty(String.prototype, 'codePointAt', {
		'value': codePointAt,
		'configurable': true,
		'writable': true
	});
}
```

That's _definitely_ minification, but it went too far by adding in the arrow func.  Is there a way we can turn off arrow funcs in `esbuild` minification?

... turns out there is.  Turns out I forgot to mark es5-mode during the polyfilled-worker minification step, so esbuild thought ES6 arrow funcs were fine.  Oops.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #9401.
Fixes #9408.
Fixes Sentry issue: [KEYMAN-WEB-DS](https://keyman.sentry.io/issues/4362964860/?referrer=github_integration).

## User Testing

TEST_ANDROID_5:  Using an Android 5.0 (Lollipop) device with its originally-installed version of Chrome...

1. Install and launch the Keyman app for Android
2. Verify that no errors happen on startup
3. Swap to `sil_euro_latin` for English if it is not already the active keyboard/language combination.
4. Type `app`.
5. Verify that the predictive-text banner is visible and shows reasonable suggestions.

This may be easiest to do through Android Studio emulation.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

Is this the only minify that needed to specify the es5 target?

**Comment by jahorton** [comment]
> lgtm
> 
> Is this the only minify that needed to specify the es5 target?

The standard `esbuild` config setting already includes it; this lm-worker specific one doesn't reference that default, though.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID_5 (PASSED):** Tested with the attached PR build (Keyman 17.0.152-alpha-test-9409) in Android 5.1 Lollipop OS / API 22 Simulator and here is my observation: 1. I did not see the keyboard error message after opening the Keyman In-App. 2. Installed another keyboard using Settings option and I noticed that there is no keyboard error message after the new installation. Seems to be fixed and working fine. Thanks.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.154-alpha](https://keyman.com/downloads/releases/alpha/17.0.154)

**Pull request merged**
