### PR TITLE
fix(developer): remove keymanengine.msm

### LINKED ISSUE #6028: chore(developer): remove keyman engine msm from kmdev.wxs
**Describe the bug**

Keyman Developer no longer has a dependency on Keyman Engine, but it still includes keymanengine.msm in the installer. This should be removed.

---

**Keyman Developer:**
 - Keyman Developer version: 15.0.165-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6028.

As of Keyman Developer 15, we no longer need to install keymanengine.msm, so it should be able to co-exist with any version of Keyman for Windows. Remove the .msm to make this so!

# User Testing

**TEST_BASELINE:** Make sure Keyman Developer still installs and runs

1. On a brand new virtual machine, which has never had either Keyman or Keyman Developer installed, install this version of Keyman Developer.
2. Start Keyman Developer, and run through a few standard tasks, e.g. open and compile keyboard, etc.
3. There should be no crashes.
4. Attempt to install a keyboard or package through Keyman Developer. It should show an error "Keyman for Windows is not installed.  You must install Keyman to complete this action." but should not crash.

**TEST_INSTALL_KEYBOARD:** Ensure that a tested keyboard can still be installed in Keyman

1. Ensure that Keyman and Keyman Developer are both installed.
2. Attempt to install a keyboard from the Keyboard Editor in Keyman Developer. It should install and be available for testing.

**TEST_INSTALL_PACKAGE:** Ensure that a tested package can still be installed in Keyman

1. Ensure that Keyman and Keyman Developer are both installed.
2. Attempt to install a package from the Package Editor in Keyman Developer. It should install and be available for testing.

**TEST_UNINSTALL_KEYBOARD:** Ensure that a tested keyboard can still be uninstalled from Keyman

1. Ensure that Keyman and Keyman Developer are both installed.
2. Attempt to uninstall a keyboard from the Keyboard Editor in Keyman Developer. It should uninstall cleanly.

**TEST_UNINSTALL_PACKAGE:** Ensure that a tested package can still be uninstalled from Keyman

1. Ensure that Keyman and Keyman Developer are both installed.
2. Attempt to uninstall a package from the Package Editor in Keyman Developer. It should uninstall cleanly.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
* **TEST_BASELINE: PASSED** There is a little hiccup after double clicking on the project file of a keyboard.



But then the Developer starts without any issue after clicking OK on the error window. No error experiences when performing basic editing/compiling of the keyboard and its package.

**Comment by mcdurdin** [comment]
> * There is a little hiccup after double clicking on the project file of a keyboard.

Thank you for testing. I think this should have failed the test -- it's a new error that should not be occurring, and is a direct result of this change.

* TEST_BASELINE: FAILED An error message appears when starting Keyman Developer, although it isn't fatal.

**Comment by mcdurdin** [comment]
Okay, new build should resolve the error. As a result, I've added a few new tests, sorry!

@keymanapp-test-bot retest TEST_BASELINE

**Comment by MakaraSok** [comment]
* **TEST_BASELINE: PASSED** No crash with Keyman Developer and Keyman for Windows.

**Comment by MakaraSok** [comment]
* **TEST_BASELINE: PASSED** No crash with Keyman Developer and Keyman for Windows.


* **TEST_INSTALL_KEYBOARD: PASSED?** The keyboard installs without any issue, but to install it from the .kps and .kmn registered two separate keyboard layouts even though they are of the same keyboard project. The one above (with EN lang tag) is from the .kmn.



No issue with testing the keyboard though.

* **TEST_INSTALL_PACKAGE: PASSED?** The keyboard installs without any issue, but to install it from the .kps and .kmn registered two separate keyboard layouts even though they are of the same keyboard project. The one below (with the appropriate lang tag) is from the .kps.



No issue with testing the keyboard though.

* **TEST_UNINSTALL_KEYBOARD: FAILED** unable to uninstall a keyboard from within the .kmn, but after clicking on OK button of the error window, a popup message says "Uninstall successfully.". However, the keyboard stays.



image


* **TEST_UNINSTALL_PACKAGE: FAILED** unable to uninstall the package from within in the .kps. Nothing happens after clicking on the OK button of the window.

**Comment by mcdurdin** [comment]
> The keyboard installs without any issue, but to install it from the .kps and .kmn registered two separate keyboard layouts even though they are of the same keyboard project.

This happens because the keyboard install does not have any language metadata, so it registers against the default language (US English in this case). When installing the package, it replaces the keyboard installation (not removing it altogether) and adds the language from the package. So then we see the keyboard registered twice. This is perhaps not ideal but I don't think it's worth worrying about.

I've fixed the issues with uninstalling.

@keymanapp-test-bot retest TEST_UNINSTALL_KEYBOARD TEST_UNINSTALL_PACKAGE

**Comment by bharanidharanj** [comment]
- **TEST_UNINSTALL_KEYBOARD: PASSED**  The Keyman Keyboard in Keyman developer has been uninstalled cleanly.

- **TEST_UNINSTALL_PACKAGE: PASSED**  The Keyman Package in Keyman developer has been uninstalled cleanly.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.191-alpha](https://keyman.com/downloads/releases/alpha/15.0.191)

**Pull request merged**
