### PR TITLE
chore(common): Check in crowdin strings for Waha 📜

### PR DESCRIPTION
**Pull request by darcywong00**
This checks in the crowdin strings for the locale `hia` for Waha

- [x] TODO: @sgschantz to check on adding hia (hia-NG?) locale in XCode

## User Testing
For the listed platforms:
1. Load the PR build
2. Set the UI/locale to Waha
3. Verify the UI is Waha
Note: The crowdin translator left some strings in English, so that's out of our control

* **TEST_ANDROID**
1. Verify Waha strings are like the screenshot
waha

* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing

* **TEST_LINUX**
1. start Keyman configuration with: `LANGUAGE=hia_NG km-config`

* **TEST_MAC**

* **TEST_WINDOWS**

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by sgschantz** [comment]
I do not see Waha listed as an available language in iOS 15.1

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: PASSED** The UI language does switch to Waha when selected from the Display Language menu.

- **TEST_IOS: BLOCKED** The language cannot be found in this OS.

    image


- **TEST_LINUX: BLOCKED** The language cannot be found in this OS.

    image

- **TEST_MAC: BLOCKED** The language cannot be found in this OS.

    image


- **TEST_WINDOWS: PASSED** but some strings are still in English. See the screenshot below.

    Screen Shot 2021-12-21 at 2 55 38 PM

**Comment by darcywong00** [comment]
iOS and macOS will be tracked in #6104

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.178-alpha](https://keyman.com/downloads/releases/alpha/15.0.178)

**Pull request merged**
