### PR TITLE
fix(android/engine): register lexical model in switchToNextKeyboard

### PR DESCRIPTION
**Pull request by darcywong00**
Split out from #5437 and follow-on #5438

This fixes the following in switchToNextKeyboard
* Check for valid keyboard index
* register associated lexical model

Note: This contains temporary globe action `GlobeKeyAction.GLOBE_KEY_ACTION_SWITCH_TO_NEXT_KEYBOARD` which  must be reverted before merging.

## User Testing
@keymanapp/testers 
1. Load the PR build
2. Install the following keyboards: khmer_angkor, gff_amharic, sil_cameroon_qwerty
3. Wait for the keyboards to install and the associated dictioanry for gff_amharic
4. In the Keyman app press the globe key several times (switches to next keyboard w/o KeyboardPicker)
* Verify sil_euro_latin shows suggestions
* Verify khmer_angkor does not show suggestions
* Verify gff_amharic shows suggestions
* Verify sil_cameroon_qwerty does not show suggestions

### CODE REVIEW

**Comment by mcdurdin** [comment]
Are there any situations where this could have been broken in stable-14.0?

**Comment by darcywong00** [comment]
> Are there any situations where this could have been broken in stable-14.0?

I ran a test build of stable-14.0 and this needs to be 🍒 picked to it too

**Comment by MakaraSok** [comment]
Tested on Emulator Pixel_2_API_29 (Android 10), all tests pass. The switch is not very smooth comparing with Gboard and Samsung keyboard, but it is not related to this PR.

One thing from the users point of view, is it possible to double tap or longpress to bring up the keyboard picker. It is a little painful to have to cycle through to the last keyboard on the list, i.e. while on EuroLatin (SIL), it takes at least 3 keypresses on the globe key to get to a Cameroon keyboard.

**Comment by MakaraSok** [comment]
Also, "Afade" language was selected to install for "Cameroon QWERTY". After the installation was finished, "Baka" was shown before "Afade". When cycle through the list by repeatedly pressing on the globe key, you'll see "Baka - Cameroon QWERTY" and then "Afade - Cameroon QWERTY" ...etc.

Note that "Baka" was not selected during the keyboard installation.

Screenshot_1625717233
Screenshot_1625717219

**Comment by darcywong00** [comment]
> One thing from the users point of view, is it possible to double tap or longpress to bring up the keyboard picker

Yes, that's what #5437 will do to change 
* shortpress globe to switch keyboard
* longpress globe to bring up keyboard picker

**Comment by MakaraSok** [comment]
It seems like the "Baka" one has been preselected because that's what I see when searching for "Cameroon".

Screenshot_1625722510

Now in the installation process, I'm supposed to select a language, so "Afade" it is. Now by the end of the installation both "Baka" and "Afade" are installed.

This doesn't happen though when tested using the way method on 14.0.277.

**Comment by darcywong00** [comment]
>This doesn't happen though when tested using the way method on 14.0.277.

Ah, the alpha builds search the keyboards from keyman-staging.com. Maybe it's providing a default language tag for the keyboard. Anyways, that's separate from this PR

**Review by mcdurdin — APPROVED** [review]
LGTM. Don't forget to remove the test code before merge.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.84-alpha](https://keyman.com/downloads/releases/alpha/15.0.84)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.89-alpha](https://keyman.com/downloads/releases/alpha/15.0.89)

**Pull request merged**
