### PR TITLE
refactor(mac): pass kmx data blob to keyman core instead of file path

### PR DESCRIPTION
**Pull request by sgschantz**
To load a keyboard using Keyman Core, call `km_core_keyboard_load_from_blob instead` of `km_core_keyboard_load`. This allows for the removal of platform file access from within Core.

Fixes: #12499

# User Testing

* **TEST_LOAD_KEYBOARD**: keyboards load and are usable

1. Install this version of Keyman and switch to the Khmer Angkor keyboard
1. Verify that typing produces Khmer characters

### CODE REVIEW

**Comment by SabineSIL** [comment]
lgtm

**Review by SabineSIL — APPROVED** [review]
lgtm

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached Keyman 18.0.150-alpha-local build in the macOS environment. Here is my observation.

* **TEST_LOAD_KEYBOARD (Passed):**
1. Installed the Keyman package version keyman-18.0.150.dmg
2. Open the configuration dialog.
3. "Download Keyman keyboards" dialog by clicking the "Download keyboard" button.
4. Installed the "Khmer Angkor" keyboard.(search a keyboard in the search box)(Khmer, gff_Amheric, Hindi, EuroLatin)
5. Verified that the installed keyboard appears on the configuration dialog.
6. Open the Note editor & Libre Office application.
7. Switch the keyboard from English to Khmer.
8. Enter some words in the application.
9. Verified that the "Khmer" letters appeared
10. Open the Stickes & Note application.
11. Switch the keyboard from Khmer to IPA.
12. Enter some words in the application.
13. Verified that the "IPA" letters appeared
It works well. Thank you.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.152-alpha](https://keyman.com/downloads/releases/alpha/18.0.152)

**Pull request merged**
