### PR TITLE
fix(linux): test fileVersion during package install

### LINKED ISSUE #6256: bug(linux): test fileVersion during package install
> @mcdurdin I built a test keyboard with Developer 15 that has a longpress of U_xxxx_yyyy on a key. kmp.json has
> 
> ```
>     "fileVersion": "7.0"
> ```
> 
> Should fileVersion be 15.0 for Keyman 15 features?

Yes, with #6145, the `fileVersion` will be `"15.0"`. From the testing in that PR, we can see that we have to fix several platforms:

5. Linux - Unknown? (@ermshiperete)

I think we should try and fix this in 15.0 for better file safety going forward. Linux and macOS *should* test the .kmx version anyway at runtime, but it really should be blocked at install time.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/5992#issuecomment-1037584657_

Note: The testing was inconclusive for Linux, so if this is already correct, then all good, just go ahead and close this issue!

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #6256.

# User Testing

## Preparations

- The tests can be run on any Linux platforms

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot

- Download the [the_99.kmp](https://build.palaso.org/repository/download/KeymanDesktop_TestPullRequests/315373:id/keyboards/index.html) keyboard package

- Download the [u_xxxx_yyyy_2858.kmp](https://build.palaso.org/repository/download/KeymanDesktop_TestPullRequests/315373:id/keyboards/u_xxxx_yyyy_2858/build/u_xxxx_yyyy_2858.kmp) keyboard package

## Tests

**TEST_INST_CLI_NEW**: `km-package-install` refuses to install a keyboard for a newer Keyman version

- Run `km-package-install -f the_99.kmp` (in the directory where you downloaded `the_99.kmp`
- This should output an error: `ERROR:the_99.kmp requires Keyman 99.0 or higher`
- Run `km-package-list-installed` and verify that `the_99` doesn't show up in the list

**TEST_INST_CLI_OK**: `km-package-install` still can install keyboards for current and older Keyman versions

- Run `km-package-install -p basic_kbdal`
- Succeeds without error
- Run `km-package-list-installed` and verify that "Albanian Basic" keyboard (`basic_kbdal`) got installed

**TEST_INST_GUI_NEW**: `km-config` refuses to install a keyboard for a newer Keyman version

- open `km-config` ("Keyman Configuration"), click the "Install" button and install `the_99.kmp`
- This should pop up a message that this requires Keyman 99.0 or higher
- Verify that the `the_99` does not appear in the list of installed keyboards

**TEST_INST_GUI_OK**: `km-config` still can install keyboards for current and older Keyman versions

- open `km-config` ("Keyman Configuration"), click the "Install" button and install `u_xxxx_yyyy_2858.kmp`
- This should succeed without error message
- Verify that the `U_xxxx_yyyy_2858` appears in the list of installed keyboards

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Review by darcywong00 — CHANGES_REQUESTED** [review]
oops, the CI build failed

**Comment by bharanidharanj** [comment]
* **TEST_INST_CLI_NEW (PASSED):** Tested this in Bionic 18.04 as per the instructions and it is working as expected.
  


* **TEST_INST_CLI_OK (PASSED):** Tested this in Bionic 18.04 as per the instructions and it is working as expected. 
 



* **TEST_INST_GUI_NEW (PASSED):** Tested this in Bionic 18.04 as per the instructions and it is working as expected. 
Test 1:
 

Test 2:
 


* **TEST_INST_GUI_OK (PASSED):** Tested this in Bionic 18.04 as per the instructions and it is working as expected.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.233-beta](https://keyman.com/downloads/releases/beta/15.0.233)

**Pull request merged**
