### PR TITLE
feat(developer): add unit tests for meta compiler 🙀

### PR DESCRIPTION
**Pull request by mcdurdin**
First, a little bit of refactoring to make it cleaner to do unit test for each section.

Then add some global error values.

Throw in a helper function or two.

Dust off the edges of the CompilerCallbacks object.

Duct tape together validation of the normalization attribute.

And ... eventually we get a nice clean-like unit test for the meta compiler, with three pretty little fixtures and as-neat-as-you-like-it assertions.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
I only looked at https://github.com/keymanapp/keyman/pull/7154/commits/995d731ccbbc178aebc67164416acc53d53e0c0c (the rest of the commits seem to be from master?)

lgtm

**Comment by mcdurdin** [comment]
> I only looked at [995d731](https://github.com/keymanapp/keyman/commit/995d731ccbbc178aebc67164416acc53d53e0c0c) (the rest of the commits seem to be from master?)

Yes, sorry, I merged chore/merge-master-into-feature-ldml into this...

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
@mcdurdin  i reviewed these two:
- 995d731
- 8fc7921

rest seem to be merge errs

**Comment by srl295** [comment]
Does have some odd commits. Will review on the morrow.

**Pull request merged**
