### PR TITLE
feat(core): ldml tertiary reordering 🙀 

### PR DESCRIPTION
**Pull request by srl295**
- implemented tertiary reordering
- reinstated bengali reordering!
- fixed reordering to be longest-first (by sorting the list before applying)
- updated debug logging

Fixes: #9707

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by ermshiperete** [comment]
I'm not sure why this build failed to trigger all builds (or rather why it worked for the other PRs). Anyways, a fix is in `master`, so if you merge you should get a complete set of builds.

**Comment by srl295** [comment]
> I'm not sure why this build failed to trigger all builds (or rather why it worked for the other PRs). Anyways, a fix is in `master`, so if you merge you should get a complete set of builds.

thank you, i have updated it now

**Comment by mcdurdin** [comment]
[Keyman Core - macOS](https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_macOS/422600?buildTab=log&focusLine=3153&linesState=84&logView=flowAware):

```
84/84 keyman_core:ldml / test_transforms                       FAIL            0.63s   killed by signal 6 SIGABRT
```

[Keyman Core - WASM](https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_WASM/422603?buildTab=log&focusLine=1761&linesState=84&logView=flowAware):

```
84/84 keyman_core:ldml / test_transforms                       FAIL            0.18s   exit status 7
```

[Keyman Core - Linux](https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_Linux/422598?buildTab=log&focusLine=1317&linesState=82&logView=flowAware):

```
84/84 keyman_core:ldml / test_transforms                       FAIL            0.46s   killed by signal 6 SIGABRT
```

[Keyman Core - Windows](https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_Windows/422606?buildTab=log&focusLine=1383&linesState=86&logView=flowAware):

```
03:47:15   ../../../src/debuglog.cpp(467): error C2220: the following warning is treated as an error
03:47:15   ../../../src/debuglog.cpp(467): warning C4477: 'snprintf' : format string '%4.6X' requires an argument of type 'unsigned int', but variadic argument 1 has type 'char32_t'
```

Keyman - Windows and Keyman - Developer are probably same as above.

Hesitant to start review with so many build errors

**Comment by mcdurdin** [comment]
Hope you don't mind, will return this to draft while we wait for parent branches to stabilize and builds to pass, so it exits the review queue.

**Comment by srl295** [comment]
rebased

**Review by mcdurdin — APPROVED** [review]
LGTM as far as I can tell! Tertiary reorders are fun I think?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.215-alpha](https://keyman.com/downloads/releases/alpha/17.0.215)

**Pull request merged**
