### PR TITLE
chore(android/engine): Fix dictionary selector and back arrow styling

### LINKED ISSUE #4715: chore(android/app): Dictionary selector and back arrow styling
Found during Keyman for Android acceptance testing (#4712) with 14.0.264 beta 

The styling update in #4662 missed the Dictionary Settings menu selector (it needs a transparent background)

### Steps to repro:
1. Settings --> Installed languages --> English --> Dictionary --> English dictionary (MTNT)
2. The selector appears like the screenshot

dictionary

Possibly also affects other places like:
* Keyboard Settings help link
* Keyboard Info help link

### PR DESCRIPTION
**Pull request by darcywong00**
Follow-on to #4662 and fixes #4715

This fixes the Dictionary Settings menu selector to have a transparent instead of gray background.

Also fixes the back arrow button to be black instead of gray in the titlebars. Note, the Keyman "Settings" menu uses a different layout, so that's not updated.

## User Testing
Setup: Install the test app

* **TEST_STYLING** Test the styling on dictionary settings menu
1. Load the Keyman app
2. Go to the "Settings" menu --> Installed Languages --> English
3. Verify on the "English Settings" menu that the back arrow is styled black
Screenshot_1630554169

4. Click the bottom menu "Dictionary" to access Dictionary Settings
5. On the "Dictionary Settings" menu, hold on "English dictionary (MTNT)"
6. Verify the entire selection has the same color styling (checkbox and  forward arrow don't have a gray background)
dictionary settings
7. Click around other menus and verify other styling is consistent.

### CODE REVIEW

**Comment by MakaraSok** [comment]
* **TEST_STYLING: FAILED** Not completely failed, but marked as failed for now. Please see the details below.

On Android 5.0 and 5.1, there is an error after tapping on `English`.

Android 5.0, API 21, phone:


Android 5.1, API 22, tablet:


---

On Android 6-11, everything is shown in style set, but one thing might be worth checking to see if the style has been applied consistently.

It looks like the arrow to the left of `Settings` is grey comparing with the one to the right of `Installed languages`.

image

**Comment by darcywong00** [comment]
> It looks like the arrow to the left of `Settings` is grey comparing with the one to the right of `Installed languages`.

Yep, I did note in the PR description that the "Settings" menu uses a different layout, so I didn't update that.

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by darcywong00** [comment]
@MakaraSok can you retest on Android 5.0 or 5.1? I consolidated the item fields and it works on my emulator.

**Comment by MakaraSok** [comment]
* **TEST_STYLING: PASSED** Retested and it works fine on both 5.0 and 5.1.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.111-alpha](https://keyman.com/downloads/releases/alpha/15.0.111)

**Pull request merged**
