### PR TITLE
fix(web): Fixes mnemonic code handling issues

### LINKED ISSUE #2209: [Web] SIL IPA Keyboard deletes multiple characters on bksp (relates to mnemonic layout)
There seem to be a bug in [SIL IPA keyboard](https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_ipa#sil-ipa-keyboard-keyboard) on Keymanweb. The `Backspace` deletes multiple characters when it is triggered.

To test:

- https://keymanweb.com/#und-fonipa,Keyboard_sil_ipa
- https://keymanweb.com/#und-fonipa,Keyboard_ipauni11 _(deprecated?)_

**Recommended font: [Charis SIL](https://software.sil.org/charis/) or [Doulos SIL](https://software.sil.org/doulos/)**

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2209.

OK, this one was a bit fun.

We had a similar error before with non-mnemonic layouts that was fixed, but I forgot about the "other" backspace handler in `defaultKeyOutput`.  Easy enough to fix... though it turns out that this was triggered in combination with another bug.  (It took two things going wrong to occur.)

In v12, `defaultKeyOutput` gained an extra purpose when compared to prior versions - it's now used to lookup mnemonic keystroke codes _in addition to_ handling default output.  The "disableDOM" bit indicates that it's functioning in "lookup" mode, so no change should happen to the DOM when `true`.

That "another bug"?  Try hitting the "Delete" key with the sil_ipa keyboard active on the current version of KeymanWeb - it outputs periods instead!  The code we use for Delete is the same as the ASCII code for period... turns out that mnemonic's use of `.vkCode` as a backup (to avoid triggering rules exactly here) was been forgotten during the v12 refactor and placed within `.lCode` instead, which erroneously triggers the output mentioned above.  I had the mnemonic `.lCode` logic all wrong.

Fixing this `.lCode`/`.vkCode` bug is _also_ enough to correct the originally-reported bug while also fixing a highly-related secondary bug, so it's the main fix that should be added.  Never hurts to have a failsafe though, especially for high-impact backspace issues, so I added fixes to both places for robustness.

## Testing

* Clone this repo if you haven't already
* Build this branch
  * Go to /web/source
  * Run .build.sh
* Go to web/testing/unminified.html.
* "Add a keyboard by keyboard name" > `sil_ipa` > Add
* Select the sil_ipa keyboard, test with a standard desktop form factor (not touch)
  * In particular, ensure that Backspace behaves normally.
  * The Delete key should also behave normally, now that it's not erroneously triggering any keyboard rules.
* Feel free to reload the page in touch mode (Chrome emulation) and ensure that backspace still works correctly.
* It wouldn't hurt to test a "normal" keyboard like sil_eurolatin or one of the EuroLatin 2 variants.

### CODE REVIEW

**Comment by darcywong00** [comment]
One of the LMLayer tests failed on the PR build. (browserstack?)

**Comment by darcywong00** [comment]
Maybe add this test case of SIL IPA to **User Tests**?

> One test sequenceː type zo=i= to produce zɒɪ then follow that by backspace.
With Keyman Desktop result is (as expected) zɒ
With KeymanWeb result is z 

KeymanWeb should now match zɒ

**Comment by mcdurdin** [comment]
I receive the following error when I try to load sil_ipa in testing/unminified.html (do I need to run it in a local web server, because that's not specified in the testing notes?):

```
kmwutils.ts:176 TypeError: Cannot read property 'getElem' of null
    at Object.ui.updateMenu (kmwuitoggle.ts:611)
    at kmwuitoggle.ts:542
    at Util.callEvent (kmwutils.ts:174)
    at KeyboardManager.doKeyboardChange (kmwkeyboards.ts:1514)
    at KeyboardManager.mergeStub (kmwkeyboards.ts:329)
    at KeyboardManager.addStub (kmwkeyboards.ts:229)
    at KeyboardManager.addKeyboardArray (kmwkeyboards.ts:985)
    at KeyboardManager.registerDeferredStubs (kmwkeyboards.ts:174)
    at DOMManager.<anonymous> (kmwdom.ts:1485)
    at KeymanBase.init (kmwbase.ts:422)
```

**Comment by mcdurdin** [comment]
The same error occurs when running on http://localhost instead of file://...

**Comment by mcdurdin** [comment]
Testing passed (I was able to load sil_ipa on the second go -- so not sure what is causing that error; it results in a 'could not connect to cloud server' visible KMW toast). Looking good.

**Pull request merged**
