### PR TITLE
[Mac] #994 - Use keyboard names w/ native script from KMX instead of inf

### LINKED ISSUE #994: [Mac] Make info display handle UTF-8 text
The Keyman for macOS display for keyboard information (i) appears not to handle UTF-8 text (v10.0.46). It may be that it does, but uses a limited font. Note the "?"s next to “(Amharic)”, the copyright symbol is then a black diamond with a “?” inside.
c70cbc54991e200cdefd2947c3e4d7101e85f78e

### PR DESCRIPTION
**Pull request by tombogle**
Fixes #994 
It seems the *.inf files are not UTF-8, so any non-Roman characters used in keyboard names turn into question marks. The native script name is stored in the kmx file, so getting it from there seems to work.

### CODE REVIEW

**Comment by darcywong00** [comment]
The KMP metadata file `kmp.json` files should be UTF-8.

I recommend parsing the keyboard name from: `"keyboards" : "name"` like the mobile apps.

**Comment by mcdurdin** [comment]
The .kmx is the correct source for the keyboard name in the macOS app. kmp.json will only be available for a small percentage of keyboards at this time.

**Comment by mcdurdin** [comment]
Note: Windows does the following for reading metadata during keyboard install:

1. Load kmp.json if present
2. Load kmp.inf otherwise

The data from kmp.json/kmp.inf is presented just during keyboard installation. After installation, the .kmx file is read for keyboard name.

**Comment by tombogle** [comment]
The current (somewhat sad perhaps) state of affairs is that Keyman for macOS does not attempt to unzip the amp file at all in order to get at the json or inf files during installation, so for now this is only an issue *after* installation. @mcdurdin, do you think I should rip out the fallback code I left in?

**Comment by mcdurdin** [comment]
I think it's okay for now. In future, we should be presenting the Readme file if present in the .kmp, before installation. But that's a project for another day.

**Pull request merged**
