### PR TITLE
chore(web): move web-environment to common/web 🎡

### PR DESCRIPTION
**Pull request by mcdurdin**
@keymanapp-test-bot skip

### CODE REVIEW

**Review by jahorton — CHANGES_REQUESTED** [review]
Personally, this is needlessly WET; consider #6625 my review of this one.

**Comment by mcdurdin** [comment]
> Personally, this is needlessly WET; consider #6625 my review of this one.

My aim here in this PR chain is to avoid changing functionality as far as humanly possible. The goals of this chain were deep enough:

* remove lerna dependency
* move to using TypeScript Projects and NPM Workspaces
* get files into consistent locations
* make build scripts and processes more consistent.

That means that _of course_ this PR is WET, but the code is no WETter than it was before -- so refactoring to DRY it out is just not a goal of this PR chain.

Yes, #6625 is a good follow-up, but introduces additional risk and test requirements by changing functionality, even if, in this case, it may seem to be relatively minor. I think we've already covered some of that in discussion off GH. So: can we park #6625 until this PR chain is complete, and _then_ revisit it and apply it?

**Comment by jahorton** [comment]
> That means that _of course_ this PR is WET, but the code is no WETter than it was before -- so refactoring to DRY it out is just not a goal of this PR chain.
> 
> Yes, #6625 is a good follow-up, but introduces additional risk and test requirements by changing functionality...

... you lost me on both counts.  What functionality was changed there?  And, while _this_ PR is no WETter, the net results from the 🎡 certainly are.

**Review by jahorton — APPROVED** [review]
Since #6625 exists and is promising, I'll go ahead and give this the LGTM for now.

**Pull request merged**
