### PR TITLE
chore: Xcode 14.2 update

### PR DESCRIPTION
**Pull request by sgschantz**
When moving from Xcode 13.4 to 14.2, Keyman for Mac builds successfully, but this is not the case for Keyman for iOS.
Two changes generated warnings and caused the build to fail. These changes are described in the Xcode 14 [release notes](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes):

1) increase the iOS target version from 9 to 11

>The Xcode 14 release supports on-device debugging in iOS 11 and later, tvOS 11 and later, and watchOS 4 and later. Xcode 14 requires a Mac running macOS Monterey 12.5 or later.

2) disable bit code

The xcode 14 release notes describe the deprecation of bit code:

>Deprecations
Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode. The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download. (86118779)

With the change of the iOS target version to 11, some code written for older versions of iOS could be removed from  KeyboardCalibrator.

Heads up to @chrisvire @rpmargetts @davidmoore1 that we are making these changes for Keyman for iOS. This PR is in place of #7433.

## User Testing
A basic smoke test is needed for Keyman for macOS and Keyman for iOS

* **TEST_MAC** 
1. Verify that Keyman for macOS is operating as expected.

* **TEST_IOS**
1. Verify that Keyman for iOS is operating as expected.

### CODE REVIEW

**Comment by darcywong00** [comment]
> increase the iOS target version from 9 to 11

The [system requirement for Keyman 15](https://help.keyman.com/products/iphone-and-ipad/current-version/about/system-requirements) says the minimum version of iOS is 12.1. Should we target 12?

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_MAC (PASSED):** Tested with the attached PR build (keyman 17.0.17-alpha-test-8015) in macmini 12.6 Monterey OS and verified that the Keyman keyboard is working as expected.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (PASSED):** Tested with the attached PR build (keyman 17.0.17-alpha-test-8015) in iPhone 12 Pro Max / iOS 15 Simulator and verified that it is working as expected.

**Comment by chrisvire** [comment]
> The [system requirement for Keyman 15](https://help.keyman.com/products/iphone-and-ipad/current-version/about/system-requirements) says the minimum version of iOS is 12.1. Should we target 12?

FYI, Scripture App Builder has move to require 12.2 so that the Swift system libraries do not need to be included. They started being included in the OS with 12.2+. That significantly slimmed down the template app.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.33-alpha](https://keyman.com/downloads/releases/alpha/17.0.33)

**Pull request merged**
