### PR TITLE
[ios] slimmed down keyboard picker

### PR DESCRIPTION
**Pull request by rfaramir**
A first pass at a slimmed down keyboard picker launched from the globe icon.

I haven't tested the case where we call the KeyboardPickerViewController with true for shouldAddKeyboard (which immediately launched the add view). But that should still work as before. (See the minor change in Manager).

### CODE REVIEW

**Comment by rfaramir** [comment]
> I'm pretty sure the `shouldAddKeyboard` case should just be rerouted to the equivalent handlers in the settings UI now. Rather than subclass, why not just root out those parts from the base KeyboardPickerViewController entirely?
> 
> That said... where are updates being handled / checked for with this in place? I don't seem to be prompted with an update check when I enter the "Installed Languages" menu.

In this code, no updates are done. The code is still in the superclass, but without the UI (and the checkUpdate override), they can't be hit. It was just a quick way to do it without rebuilding everything.

In the new Settings code, I haven't gotten a handle on where (or whether) it is handled... I think lexical models don't update (yet), but keyboards may still, when needed.

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/157996:id/kvk/index.html)

**Comment by rfaramir** [comment]
> Architecturally, we need to be subclassing the other way -- add functionality in the subclass, don't remove it. This is actually fairly important because when it comes to maintenance or addition of new features, having the subclassing upside down (a) is different to everywhere else and (b) means if we want to add functionality to the parent class, we'll also need to update the subclass to undo that functionality again (and the maintenance programmer will probably tear their hair out until they figure that out).

I would normally agree, but sometimes it is better upsidedown: CFString is the mutuable superclass while the Immutable variant is the subclass, removing the editability. But I agree it *is* unexpected. I was trying to do it quickly as well as trying to retain the ability to go back to the way it was if users demanded. All that would have to be done is stick the old class on an icon or menu (or back on the globe, or as a preference for the globe: switch-only vs do-everything-old-style).

**Comment by mcdurdin** [comment]
Okay. I understand the doing it quickly bit :) But we shouldn't be architecting our app to allow us to quickly undo a design change: that builds us very quickly into a corner.

We'll need to refactor this to flip the hierarchy, sorry.

**Comment by rfaramir** [comment]
> Architecturally, we need to be subclassing the other way -- add functionality in the subclass

Done. The switcher is the superclass, and the picker--with add/delete capability--is the subclass.

**Comment by rfaramir** [comment]
> just root out those parts from the base KeyboardPickerViewController entirely

There is one case where the Picker is called: in the Get Started view, the Add a keyboard option calls it with shouldAddKeyboard: true. So, while I have reversed the subclassing, the Picker still exists and is used in that one case.

And that change is done and working, now. Both the Picker works with addingj/deleting capability, and the Switcher works to switch keyboards.

**Comment by mcdurdin** [comment]
> does this require use of the old Picker via Get Started? If it's the latter, that should be a blocker.

I don't think we need to block beta on this though :)

**Comment by jahorton** [comment]
> > does this require use of the old Picker via Get Started? If it's the latter, that should be a blocker.
> 
> I don't think we need to block beta on this though :)

Really?  I find that surprising, but if you say so...

**Comment by mcdurdin** [comment]
Keyboard updates are relatively infrequent. The whole update mechanism needs a rewrite anyway. So I am comfortable going into beta with it being a little buried.

**Pull request merged**
