### PR TITLE
[LMLayer] Remove obsoleted wordlist model.

### PR DESCRIPTION
**Pull request by eddieantonio**
This removes the old wordlist model, that has been completely obsoleted by the
trie model. Might as well get rid of this now, before having to maintain it in
beta!

**EDIT**: I tested this with the current lexical-models and it works! But now, `trie-1.0` and `trie-2.0` are the exact same implementation. So those models should all use `trie-1.0` instead, which is backed by a genuine trie.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/152558:id/kvk/index.html)

**Comment by eddieantonio** [comment]
@jahorton Anything blocking this one from being merged?

**Comment by eddieantonio** [comment]
Note: checked the build and it is a GENUINE failure that occurs due to me forgetting that IE 11 does not have `String.prototype.normalize()` 😭

I will address that in a new PR!

**Comment by jahorton** [comment]
I've gone ahead and added a commit to adjust KMW's test page to use the trie version as well, as that was otherwise overlooked.

**Comment by eddieantonio** [comment]
> How often do you anticipate these getting updated? It might be manageable for future diffs to have the .js files pretty-print.

Not often. Files like common/predictive-text/unit_tests/in_browser/resources/models/simple-wordlist.js, web/testing/prediction-ui/simple-en-wordlist.js and common/predictive-text/unit_tests/in_browser/json/wordlists/english-1000.json are automatically generated by the lexical models compiler, so these are not maintained by hand.

The rest are all deletions (the entire file was deleted).

**Pull request merged**
