### PR TITLE
chore(common): Check in crowdin strings for Marghi 📜

### PR DESCRIPTION
**Pull request by darcywong00**
This checks in the crowdin strings for the locale `mrt` for Marghi. Does not include macOS.

- [x] TODO: @sgschantz to check on adding mrt (mrt-NG?) locale in XCode

## User Testing
For the listed platforms:
1. Load the PR build
2. Set the UI/locale to Marghi
3. Verify the UI is Marghi
Note: The crowdin translator left some strings in English, so that's out of our control

* **TEST_ANDROID**
1. Verify Marghi strings are like the screenshot
marghi

* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing

* **TEST_LINUX**
1. start Keyman configuration with: `LANGUAGE=mrt_NG km-config`

* **TEST_WINDOWS**

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by sgschantz** [comment]
Marghi is not yet supported on iOS as of version 15.1

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: PASSED** The display language does switch to Marghi after it's chosen from the list.

- **TEST_IOS: BLOCKED** The language is not yet available on this OS.
- **TEST_LINUX: BLOCKED** The language is not yet available on this OS.

    image


- **TEST_WINDOWS: PASSED** Some strings are still in English, but the UI language does switch to Marghi when it is selected from the dropdown menu.

    image

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.177-alpha](https://keyman.com/downloads/releases/alpha/15.0.177)

**Pull request merged**
