### PR TITLE
chore: update history for stable 🏠

### PR DESCRIPTION
**Pull request by mcdurdin**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
Why is the 18.0 history going into stable-17.0?

**Comment by mcdurdin** [comment]
> Why is the 18.0 history going into stable-17.0?

It doesn't hurt

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.325](https://keyman.com/downloads/releases/stable/17.0.325)

**Pull request merged**
