### PR TITLE
refactor(ios/engine): Language resource + keying polymorphism

### PR DESCRIPTION
**Pull request by jahorton**
Swift generics are... really weird and cumbersome.  Especially once `protocol`s get involved.

Most of the changes contained in this PR are to approximate Java-style generic polymorphism regarding language resources and how we key them.  Alas, Swift lacks the ability to "wildcard" its generics, so "type erasure" is necessary - note the `Any*` classes.

Some "fun" Swift reading along those lines:  https://medium.com/@bobgodwinx/swift-associated-type-design-patterns-6c56c5b0a73a
- I followed the "Shadow Type Erasure" strategy where possible.

All of this is to allow a few things:
- `KeymanKeyboardPackage.installables` is of type `[[InstallableKeyboards]]` - something reasonably clear (though I could improve its docs) and exposable as an API on packages.
    - Likewise, `KeymanLexicalModelPackage` is of type `[[InstallableLexicalModels]]`.
    - The base, type-erased `KeymanPackage` exports `installableResourceSets: [[LanguageResource]]`.  
        - It was impossible to fully do "shadow type erasure" here so that the same name was used for all cases.
    - One of my big goals - the `KMPMetadata` classes will _not_ be exposed as API - they'll be internal-only.
- `FullKeyboardID` and `FullLexicalModelID` are now related via `Protocol` while maintaining their original type signatures and accessibility.
    - As a result, `fullID` is now exposed as a property on `AnyLanguageResource` (and its implementing classes).
    - Existing uses of `InstallableKeyboard` and `InstallableLexicalModel` are practically unaffected despite the shifts in its type hierarchy.
    - Great pains were taken to avoid breaking anything with the changes involved.

This allows us to easily get the unique keying information for any installed resources so that we can use it to find "matches" within a KMP as part of the cloud -> KMP migration process.

-----

Other notes:
- This is designed to further enhance #3207 along the lines of our recent offline discussions - that bit about using the "unique keying information" will now be far more possible.
    - In fact, this started off on that branch until I realized how complex things were becoming and that a separate, focused review would be far better.
- Noting the comment on #3212 [here](https://github.com/keymanapp/keyman/pull/3212#discussion_r437146769), this same pattern provides a more "Swift-like" solution to that problem; we'll be able to constrain the `init` method such that nothing unexpected can be passed in.

### CODE REVIEW

**Comment by mcdurdin** [comment]
This seems to add a fair bit of complexity to the design and I'm afraid the in-code comments aren't really helpful in understanding the 'why' we are architecting in this way -- I understand the limitations you are running into with Swift but I'm not really understanding why you are needing to work in this architecture. I don't mind comments on workarounds for language/library limitations but I really appreciate comments on the deeper 'why' for design decisions too.

What are we gaining with this change? Can you document the changes to public APIs that you anticipate providing as a result of these changes so I can understand them?

**Comment by jahorton** [comment]
Effective changes to API:  **__none__**.  Check the list of changed files - not a single file in the Keyman app project was changed in any way, shape, or form.  Just within KMEI.  I didn't even touch the samples or the FV app, all of which also passed their build tests.  (Of course, I do want to more thoroughly validate things before merging.)

That said:
- There may be some shifts in parameter types accessible outside KMEI, using (for example, without loss of generality) `AnyLanguageResource` over `LanguageResource`.
    - In these cases, existing assignments were still legal.  Continuing the example, note that `LanguageResource` is (in effect) derived from its `Any` variant.
    - `AnyLanguageResource` _is_ what `LanguageResource` _was_.
- Admittedly, a few shifts in return type (`LanguageResource` -> `AnyLanguageResource`) do occur; these are currently covered by `let`-assignment that auto-infers the type.
    - This is the one detail I could see affecting 3rd-party apps, but even then... the only real change needed would be adding the `Any` prefix.

Past that...
- Continuing the example again, `LanguageResource` now provides more specific type information to the compiler, allowing useful type guarantees.
    - For this _specific_ case, this "more specific type information" allows us to guarantee that we did not break the existing `fullID` property/API when we made it more accessible.
        - The existing type guarantees were the trickiest part to work around.
        - Otherwise, a _lot_ of methods (in both KeymanEngine and the Keyman app) would have been broken due to their reliance on specific "full ID" types.
        - A quick CTRL-F shows "68 [references] in 15 files" to `fullID`, and I think about half of them broke in my other approaches that led to this PR.  The work quickly grew out of control with my attempts at adjusting these references.

I know how we are about breaking API changes, so preventing them was my top priority.

This also allows the following benefits:
- `ResourceFileManager.install` (in #3207) can use unique-key lookups for installation from packages.
    - Additionally, it can be written with better type-checking guarantees.
- `KMPResource`'s changes in #3212 can be done more cleanly.
- For the future:
    - `ResourceInfoViewController` could more cleanly serve as a common base class for `LanguageResource` types.
        - That is, should we ever extend it and/or have type-specific info to display, a bit of templating could outright prevent the need for typecasting checks.

I've also been aiming to set up `KeymanKeyboardPackage` and `KeymanLexicalModelPackage` as API-friendly classes, starting with the work in #3205.  Ideally, those classes will gain data about any available help files, keyboard options, etc contained within their KMPs.  These changes should make the new related APIs a friendlier to work with.
- Big selling point:  a 3rd party app could ask for a KMP to be parsed, check its type (keyboard/lexical-model), and then work on it without any further typecast shenanigans.  The one, top-level typecast will remove all subsequent ambiguities.  Much cleaner.

Alternative approaches:  
- Having some seriously ugly WETness regarding `fullID` - I'd have to write a second version of the type from scratch that worked with both `LanguageResource` types, with its own separate copy of the properties... that would only work with `KeymanPackage` instances.
    - Again, note that CTRL-F above.  The second type would be incompatible with those references, while the current `Full*ID` types mentioned below would be incompatible with `KeymanPackage` and its derived classes.
    - It's probably the _simplest_, but the resulting WETness feels _wrong_.
- Seriously breaking the API and migration code to outright replace `FullKeyboardID` and `FullLexicalModelID` with that "second version"... which would lead to significantly more changes than seen here.  Again, note that CTRL-F.

I tried those two alternatives _first_.  Despite the complexity this PR's changes bring... it's less ugly than either of those two alternatives.

- third alternative: just hardcoding against the old `Full*ID` types, causing moderate WET-ness within `KeymanPackage` and some 'fun' type cast management in the key-based-lookup code.
    - 2 full-ID types x 2 package types = 4 cases / 4x code repetition.
        - So, serious WETness, though in a confined area of code.
    - Also maintains the ugliness you noted by (this #3212 comment](https://github.com/keymanapp/keyman/pull/3212#discussion_r437146769).

- fourth alternative: if we drop the push to provide clean, proper unique-key-based installs from KMPs.

**Comment by jahorton** [comment]
Also, note that so far as I can tell, this _is_ the Swift way of "doing things".  Yeah, it's verbose.

Like with certificates, profiles, and notarization, Apple really likes trying to pin things down to force developers to follow their approaches and mindset.  If nothing else, I'm glad I tried doing this (despite the time it took) just to learn how Swift generics + 'generic' protocols actually work.

**Comment by jahorton** [comment]
Tested the FV app / system keyboard as well as the Keyman app; all seems good.  Merging.

**Pull request merged**
