### PR TITLE
refactor(linux): Use `km_core_state_context_set_if_needed`

### LINKED ISSUE #10212: refactor(linux): ibus: use `km_core_state_context_set_if_needed`

### PR DESCRIPTION
**Pull request by ermshiperete**
Also update comment on `km_core_state_context_set_if_needed` to make it clearer that it's expecting a UTF-16 string.

Closes #10212.

# User Testing

## Preparations

- The tests can be run on any Linux platform

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot

### Tests

- **TEST_IPA_WRITER:** Open LibreOffice Writer. Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_IPA_GEDIT:** Open gedit. Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_KO_WRITER:** Open LibreOffice Writer. Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_KO_GEDIT:** Open gedit. Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_KM_WRITER:** Open LibreOffice Writer. Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_KM_GEDIT:** Open gedit. Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_CONTEXT:**
  - Open gedit
  - Switch to "IPA (SIL)" keyboard.
  - Type
    ```
    an
    m
    ```
  - click after `n`
  - type `>`
  - verify that the output is
    ```
    aŋ
    m
    ```

### CODE REVIEW

**Review by mcdurdin — COMMENTED** [review]
With non-compliant apps, how do we reset the context when the user switches focus?

**Comment by ermshiperete** [comment]
> With non-compliant apps, how do we reset the context when the user switches focus?

We call `km_core_context_clear`.

Which raises another question: should we rename this to `km_core_state_context_clear` (or rather add a new method with that name so that we can deprecate the old one)?

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IPA_WRITER (PASSED):** 1. Installed the attached PR build keyman 17.0.241-alpha-local (package version 17.0.241-1~PR-10354-1978.1+lunar1) on Ubuntu 23.10 Mantic Minotaur Linux OS (VM) and here is my observation: 1. Opened Libreoffice Writer. 2. Switched to "IPA (SIL)" keyboard. 3. Verified the result was ŋ, after typing "n>". 

   

* **TEST_IPA_GEDIT (PASSED):** 1. Opened the Text Editor. 2. Switched to "IPA (SIL)" keyboard. Verified the result was ŋ in the notepad.

   


* **TEST_KO_WRITER (PASSED):** 1. Opened LibreOffice Writer. 2. Switched to "Korean KORDA Jamo (SIL)" keyboard. 3. Verified the expected result "한글" appeared on the document. 


* **TEST_KO_GEDIT (PASSED):** 1. Opened the Text Editor. 2. Switched to "Korean KORDA Jamo (SIL)" keyboard. 3. Verified the expected result "한글" appeared on the text editor. 


* **TEST_KM_WRITER (PASSED):** 1. Opened LibreOffice Writer. 2. Switched to "Khmer Angkor" keyboard. 3. Typed xEjmr. Verified the output was ខ្មែរ on the document. 


* **TEST_KM_GEDIT (PASSED):** 1. Opened the Text Editor. 2. Switched to "Khmer Angkor" keyboard. 3. Typed xEjmr. Verified the output was ខ្មែរ on the text editor. 


* **TEST_CONTEXT (PASSED):** 1. Verified the expected output appeared on the text editor.

**Comment by mcdurdin** [comment]
> Which raises another question: should we rename this to `km_core_state_context_clear` (or rather add a new method with that name so that we can deprecate the old one)?

We can let this wait until 18.0.

> Another option instead of calling `km_core_context_clear` would be to pass an empty string to `km_core_state_context_set_if_needed`

I'm not 100% sure that will be correct with #10100. I think the explicit clear of context is safer.

**Review by mcdurdin — APPROVED** [review]
LGTM

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
> > Which raises another question: should we rename this to `km_core_state_context_clear` (or rather add a new method with that name so that we can deprecate the old one)?
> 
> We can let this wait until 18.0.

Turns out it already exists! I added it not long ago. See #10370.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.243-alpha](https://keyman.com/downloads/releases/alpha/17.0.243)

**Pull request merged**
