### PR TITLE
feat(windows): kmdevlink app

### PR DESCRIPTION
**Pull request by mcdurdin**
Internal app for opening shortcuts to Keyman repos and Character Identifier.

Stripped down version of the old 'tscrmlink' app which was used in Tavultesoft era. Hence why it is written in Delphi...

image

image

image

@keymanapp-test-bot skip

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm
Couple of questions:
1. Is this intended to be locally built as-needed by developers that want to use it?
2. Could you add a short README of what this tool is for / how to build it?
3. Are the copyrights in the code still under Tavultesoft vs SIL Global? (Falls under the MIT license of the whole repo?)

**Comment by mcdurdin** [comment]
This will be the binary version of kmdevlink for now:
[kmdevlink.zip](https://github.com/user-attachments/files/17566880/kmdevlink.zip)

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.132-alpha](https://keyman.com/downloads/releases/alpha/18.0.132)

**Pull request merged**
