### PR TITLE
fix(ios): properly handle selection 🎢

### PR DESCRIPTION
**Pull request by keyman-server**
Relates to #5853
~~Fixes 6041~~ Looks like this is still a separate issue (per discussion with @sgschantz)

This deals with deleting the selection with the new interface for KeymanWeb. It also ensures that the selection is always correctly sent to KeymanWeb.

# User Testing

(Note: these tests are very good candidates for general acceptance tests!)

Where requested, these tests should be run using the attached [web_context_tests keyboard](https://drive.google.com/file/d/1C1I39AxR9egfuQKXRbwwyK4T9YBw6Ji-/view?usp=sharing).

* **GROUP_IOS_INAPP:** Test on Keyman for iPhone and iPad, in-app
* **GROUP_IOS_SYSTEM:** Test on Keyman for iPhone and iPad, system keyboard

**TEST_BASELINE:** Using a keyboard with some complex behaviours, such as Khmer Angkor, verify that input sequences are correct. For example, type <kbd>x</kbd><kbd>E</kbd><kbd>j</kbd><kbd>m</kbd><kbd>r</kbd> (desktop: <kbd>ខ</kbd><kbd>ែ</kbd><kbd>្</kbd><kbd>ម</kbd><kbd>រ</kbd> touch: <kbd>ខ</kbd><kbd>ែ (longpress េ)</kbd><kbd>្ម (longpress ម)</kbd><kbd>រ</kbd>) and verify that the emitted output is actually `ខ្មែរ` (you may need to use a tool to view the Unicode values, which should be as in the image below).

image

**TEST_SELECTION:** Using the web_context_tests keyboard, type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select `bc` and type <kbd>q</kbd>. The output after the final key should be `aqx`. (This is testing selection replacement with no matching keyboard rule.)

**TEST_SELECTION_2:** Using the web_context_tests keyboard, type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select `bc` and type <kbd>p</kbd>. The output after the final key should be `aqx`. (This is testing selection replacement with a matching keyboard rule.)

**TEST_CONTEXT_BASE:** Using the web_context_tests keyboard, type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>d</kbd>. The output after the final key should be `!`.

**TEST_CONTEXT_SELECTION:** Using the attached web_context_tests keyboard, type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `x` character, and type <kbd>d</kbd>. The output after the final key should be `abcd`.

**TEST_CONTEXT_SELECTION_2:** Using the attached web_context_tests keyboard, type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `x` character, and delete it with <kbd>Backspace</kbd>. Type <kbd>d</kbd>. The output after the final key should be `!`.

**TEST_CONTEXT_SELECTION_3:** Using the attached web_context_tests keyboard, type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `x` character, and type <kbd>y</kbd>. Press <kbd>Backspace</kbd>, and type <kbd>d</kbd>. The output after the final key should be `!`.

**TEST_CONTEXT_SELECTION_4:** Using the attached web_context_tests keyboard, type <kbd>x</kbd><kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `abc` characters, and type <kbd>d</kbd>. The output after the final key should be `xdx`.

## SMP Tests

**TEST_SELECTION_SMP:** Using the web_context_tests keyboard, type <kbd>f</kbd><kbd>g</kbd><kbd>h</kbd><kbd>j</kbd>. Select `𐌁𐌂` and type <kbd>o</kbd>. The output after the final key should be `𐌀𐍈𐌈`.

**TEST_CONTEXT_BASE_SMP:** Using the web_context_tests keyboard, type <kbd>f</kbd><kbd>g</kbd><kbd>h</kbd><kbd>i</kbd>. The output after the final key should be `𐌙`.

**TEST_CONTEXT_SELECTION_SMP:** Using the attached web_context_tests keyboard, type <kbd>f</kbd><kbd>g</kbd><kbd>h</kbd><kbd>j</kbd>. Select the `𐌈` character, and type <kbd>i</kbd>. The output after the final key should be `𐌀𐌁𐌂i`.

**TEST_CONTEXT_SELECTION_SMP_2:** Using the attached web_context_tests keyboard, type <kbd>f</kbd><kbd>g</kbd><kbd>h</kbd><kbd>j</kbd>. Select the `𐌈` character, and delete it with <kbd>Backspace</kbd>. Type <kbd>i</kbd>. The output after the final key should be `𐌙`.

**TEST_CONTEXT_SELECTION_SMP_3:** Using the attached web_context_tests keyboard, type <kbd>f</kbd><kbd>g</kbd><kbd>h</kbd><kbd>j</kbd>. Select the `𐌈` character, and type <kbd>k</kbd>. Press <kbd>Backspace</kbd>, and type <kbd>i</kbd>. The output after the final key should be `𐌙`.

**TEST_CONTEXT_SELECTION_SMP_4:** Using the attached web_context_tests keyboard, type <kbd>k</kbd><kbd>f</kbd><kbd>g</kbd><kbd>h</kbd><kbd>k</kbd>. Select the `𐌀𐌁𐌂` characters, and type <kbd>i</kbd>. The output after the final key should be `𐌰i𐌰`.

## ~~Multi-line backspace Crash Test~~

~~TEST_MULTI_LINE_BACKSPACE: (following the steps from #6041, using the [start_of_sentence_3621.kmp](https://drive.google.com/uc?id=1WbiesUOgI5Nby8xJM_vSy-Ip_-98nLCf&export=download)) Type <kbd>S</kbd><kbd>Return</kbd><kbd>S</kbd><kbd>Return</kbd><kbd>S</kbd><kbd>Return</kbd>, then use the OSK backspace key to delete all content. Keyman should no longer crash.~~

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **GROUP_IOS_INAPP**: **Test on Keyman for iPhone and iPad, in-app**

   * **TEST_BASELINE (OPEN):** 
   * **TEST_SELECTION (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing aqx after the final key q. 
   * **TEST_CONTEXT_BASE (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing ! after typing d key.
   * **TEST_CONTEXT_SELECTION (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing abcd after typing d
   * **TEST_CONTEXT_SELECTION_2 (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing ! after typing d key.
   * **TEST_CONTEXT_SELECTION_3 (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it shoing ! after typing d.
   * **TEST_CONTEXT_SELECTION_4 (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it is showing xdx after typing d. 
   * **TEST_CONTEXT_BASE_SMP (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing 𐌙 after typing fghi
   * **TEST_CONTEXT_SELECTION_SMP (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing 𐌀𐍈𐌈 after typing o
   * **TEST_CONTEXT_SELECTION_SMP_2 (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing 𐌙 after typing fghi
   * **TEST_CONTEXT_SELECTION_SMP_3 (PASSED):**  Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing 𐌙 after typing i
   * **TEST_CONTEXT_SELECTION_SMP_4 (PASSED):** Tested with the latest Keyman 15.0.202 alpha build along with web_context_tests keyboard and it showing 𐌰i𐌰 after typing i

**Comment by MakaraSok** [comment]
All tests were done on iOS 15.2 simulator.

* GROUP_IOS_INAPP: Test on Keyman for iPhone and iPad, in-app
  - **TEST_SELECTION_2 (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_SELECTION_SMP_2 (FAILED)** The output is `𐌀𐌁𐌂i` (instead of the expected `𐌙`) as shown in the screenshot below. 
  image<br/>

**Comment by mcdurdin** [comment]
I've just pushed a fix which should resolve the failing test. But for safety I would like to retest everything...

@keymanapp-test-bot retest

**Comment by MakaraSok** [comment]
All tests were done on iOS 15.2 simulator.

* GROUP_IOS_SYSTEM: Test on Keyman for iPhone and iPad, system keyboard
  - **TEST_BASELINE (PASSED)** The output is indeed shown as indicated.
  - **TEST_SELECTION (PASSED)** The output is indeed shown as indicated.
  - **TEST_SELECTION_2 (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_BASE (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_SELECTION (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_SELECTION_2 (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_SELECTION_3 (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_SELECTION_4 (PASSED)** The output is indeed shown as indicated.
  - **TEST_SELECTION_SMP (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_BASE_SMP (PASSED)** The output is indeed shown as indicated.
  - **TEST_CONTEXT_SELECTION_SMP (PASSED)** The output is indeed shown as indicated.
  Note that the last character on the string of the final output of this test cannot be removed as normal. One has to select it to delete it. See the screen recording below:

https://user-images.githubusercontent.com/28331388/155662550-e107c203-baf8-4f55-9e41-86154dbc90d9.mov

  - **TEST_CONTEXT_SELECTION_SMP_2 (FAILED)** The output is not what's indicated. The final output is `𐌀𐌁𐌂i` instead of the expected `𐌙`. <br/>

https://user-images.githubusercontent.com/28331388/155662888-388e409c-570d-4cc6-885d-296b8d081173.mov

  - **TEST_CONTEXT_SELECTION_SMP_3 (FAILED)** The output is not what's indicated. The final output is `𐌀𐌁𐌂i` instead of the expected `𐌙`.

https://user-images.githubusercontent.com/28331388/155663228-8af243d7-5e02-47c9-b4a6-1bde9dc52f34.mov

  - **TEST_CONTEXT_SELECTION_SMP_4 (PASSED)** The output is indeed shown as indicated.

**Comment by bharanidharanj** [comment]
* **GROUP_IOS_INAPP**: **Test o Keyman for iPhone and iPad, in-app**

   * **TEST_SELECTION_SMP (PASSED):** The output is showing 𐌀𐍈𐌈.
   * **TEST_CONTEXT_BASE_SMP (PASSED):** The output is showing 𐌙 after typing fghi 
   * **TEST_CONTEXT_SELECTION_SMP (PASSED):** The output is showing 𐌀𐌁𐌂i after typing i.
   * **TEST_CONTEXT_SELECTION_SMP_2 (PASSED):** The output is showing 𐌙 after typing i
   * **TEST_CONTEXT_SELECTION_SMP_3 (PASSED):** The output is showing 𐌙 after typing i.
   * **TEST_CONTEXT_SELECTION_SMP_4 (PASSED):** The output is showing 𐌰i𐌰 after typing i.

**Comment by bharanidharanj** [comment]
* **GROUP_IOS_INAPP**: **Test o Keyman for iPhone and iPad, in-app**

   * **TEST_BASELINE (PASSED):** The output is showing ខ្មែរ
   * **TEST_SELECTION (PASSED):** The output is showing aqx. 
   * **TEST_SELECTION_2 (FAILED):** The output is showing apx instead of aqx
   * **TEST_CONTEXT_BASE (PASSED):** The output is showing !
   * **TEST_CONTEXT_SELECTION (PASSED):** The output is showing abcd
   * **TEST_CONTEXT_SELECTION_2 (PASSED):** The output is showing !.
   * **TEST_CONTEXT_SELECTION_3 (PASSED):** The output is showing !.
   * **TEST_CONTEXT_SELECTION_4 (PASSED):** The output is showing xdx.

**Comment by mcdurdin** [comment]
> GROUP_IOS_INAPP: Test o Keyman for iPhone and iPad, in-app
> * TEST_SELECTION_2 (FAILED): The output is showing apx instead of aqx

Can you make sure you are using the latest version of the test keyboard, @bharanidharanj? The transform from 'p' to 'q' was only added in the most recent version. I was not able to reproduce this when I was testing.

@keymanapp-test-bot retest GROUP_IOS_INAPP TEST_SELECTION_2

**Comment by mcdurdin** [comment]
> GROUP_IOS_SYSTEM 
> * TEST_CONTEXT_SELECTION_SMP_2 FAILED
> * TEST_CONTEXT_SELECTION_SMP_3 FAILED

@MakaraSok, I was not able to reproduce this problem, no matter how I tried. Can you verify that you were trying with the latest version, with a clean install? Are there any other steps you took beforehand that may have caused this?

@keymanapp-test-bot retest GROUP_IOS_SYSTEM TEST_CONTEXT_SELECTION_SMP_2 TEST_CONTEXT_SELECTION_SMP_3

**Review by sgschantz — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
After setting Keyman as a system keyboard on iPhone 8 Plus (fresh), Keyman crashes right away when the globe key was pressed on.

image

Bharani was testing this on iPhone 13 Pro Max (fresh), Keyman doesn't crash visually, but it doesn't show up at all when selected from the globe key. Please see the video attached in the next comment.

* GROUP_IOS_SYSTEM: Test on Keyman for iPhone and iPad, system keyboard
   - **TEST_CONTEXT_SELECTION_SMP_2 (BLOCKED)**
   - **TEST_CONTEXT_SELECTION_SMP_3 (BLOCKED)**

**Comment by bharanidharanj** [comment]
@mcdurdin After setting Keyman 15.0.202-alpha-test-6280 Keyboard as the System Keyboard, it does not work after clicking the globe key. 
Note : Tested it in iPhone 13 Pro Max. I have attached the Video file for reference. Thanks.

https://user-images.githubusercontent.com/19683143/155964389-8a2f66f9-e5c8-42f7-bdbc-4b334f724e83.mp4

**Comment by mcdurdin** [comment]
> After setting Keyman as a system keyboard on iPhone 8 Plus (fresh), Keyman crashes right away when the globe key was pressed on.

@MakaraSok: Are you able to consistently reproduce this? Which version of iOS are you running in the Simulator?

> After setting Keyman 15.0.202-alpha-test-6280 Keyboard as the System Keyboard, it does not work after clicking the globe key.

@bharanidharanj I believe this is a problem I also encountered with iOS Simulator on M1 mac. The workaround for now is to launch an older version of iOS, e.g. 13.7, instead of most recent. It is due, I believe, to the iOS simulator build of Keyman system keyboard not containing the correct architecture run on M1. (Tracking this in #6306)

**Comment by mcdurdin** [comment]
Tested on iPhone 8 plus, iOS 13.7 (as later versions currently blocked on M1, see #6306).

GROUP_IOS_SYSTEM: Test on Keyman for iPhone and iPad, system keyboard
* **TEST_CONTEXT_SELECTION_SMP_2 (PASSED):** Tested in Messages app, no issues encountered
* **TEST_CONTEXT_SELECTION_SMP_3 (PASSED):** Tested in Messages app, no issues encountered

**Comment by MakaraSok** [comment]
> Are you able to consistently reproduce this? Which version of iOS are you running in the Simulator?

It happened the first time I installed. When trying it again today, no error experienced.

**Comment by bharanidharanj** [comment]
@MakaraSok  @mcdurdin Tested this issue with Keyman 15.0.205 ( downloaded it from #6317) Keyboard in iOS 13.7 also in iOS 14.0 and here is my observation:
The Keyman Keyboard is working fine as a System Keyboard in both iOS 13.7 and 14.0 Simulators in M1 Mac.

**Comment by mcdurdin** [comment]
> The Keyman Keyboard is working fine as a System Keyboard in both iOS 13.7 and 14.0 Simulators in M1 Mac.

Excellent, thank you!

**Pull request merged**
