### PR TITLE
docs(android): update-image-enabling-system-keyboard.md

### PR DESCRIPTION
**Pull request by bravogeorge**
docs(android): help-docs polish needed #4733

suggestion of @jahorton that image in f keyboard icon the image of help article should pop more.

https://help.keyman-staging.com/products/android/current-version/start/enabling-system-keyboard

CTRL+F: "you'll see a keyboard icon at the bottom right"

Edited image to add red circle to highlight the keyboard icon more effectively.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by mcdurdin — CHANGES_REQUESTED** [review]
Thank you for your contribution.

We'll need to import the image into the repository rather than include the online reference. @darcywong00 can you make that happen?

**Comment by mcdurdin** [comment]
@darcywong00 do we want to cherry-pick this to stable-14.0 also?

**Comment by darcywong00** [comment]
@mcdurdin - Since this PR is off his fork, it might be easier to just merge this. Then I'll add the image locally on a follow-on PR.

Sure we can cherry-pick to stable-14.0 too

**Comment by mcdurdin** [comment]
This change has been merged in #4842. Thank you again for your contribution.

**Comment by jahorton** [comment]
So, we'll have a follow-on to get the image into `master`, right?  #4842 only covers `stable`.

**Pull request closed without merging**
