### PR TITLE
chore(developer): resolve excessive-fatal-exception issue

### PR DESCRIPTION
**Pull request by srl295**
- add an e2e test to expose this issue
- remove the fatal exception - it doesn't add anything of value. Actual error is already propagated to the user.
 
#10894

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
To my mind, the fatal error is something that is a bug in our compiler. We want to know about it, which is what is happening. It's kinda hard to write a test for this because if we knew what was causing the fatal error, we should be fixing the fatal error instead

**Comment by srl295** [comment]
> To my mind, the fatal error is something that is a bug in our compiler. We want to know about it, which is what is happening. It's kinda hard to write a test for this because if we knew what was causing the fatal error, we should be fixing the fatal error instead

Fixing the fatal error  might require restructuring callbacks and is discussed in #10894

**Comment by mcdurdin** [comment]
> Fixing the fatal error might require restructuring callbacks and is discussed in #10894

I'm not seeing the restructure discussion?

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by mcdurdin** [comment]
Does this close the original issue?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.287-beta](https://keyman.com/downloads/releases/beta/17.0.287)

**Pull request merged**
