### PR TITLE
fix(web): keyboard-documentation rendering mode

### PR DESCRIPTION
**Pull request by jahorton**
## User Testing

TEST_KBD_DOCS:  Visit the "Tests keyboard documentation rendering" Web test page and wait.  Verify that the following keyboards get rendered:
- Amharic
- EuroLatin (SIL)
- Lao Basic (once for a tablet touch-layout, then once for a desktop-layout [including CAPS, TAB, ... keys])
- Cameroon AZERTY
- Khmer Angkor

### CODE REVIEW

**Comment by mcdurdin** [comment]
What is this PR changing?

**Comment by jahorton** [comment]
> What is this PR changing?

The help page keyboard-documentation rendering system was broken; the code was trying to reference the gesture engine, which we don't actually build when in "static" / keyboard-doc-rendering mode.  This would most prominently affect keyboard help pages on help.keyman.com, I believe.

**Comment by jahorton** [comment]
To follow up on that, for the current `master`, this test page renders nothing due to errors:

image

That's the page I specified for the user test.

**Comment by mcdurdin** [comment]
Is there a Sentry report for this? (And if not, should there be?)

**Review by ermshiperete — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_KBD_DOCS (PASSED):** Tested using "Test keyboard documentation rendering" web test page and verified that the above mentioned keyboards got rendered. Seems to be working fine.

..Keyboard rendering 1

   


..Keyboard rendering 2

   


..Keyboard rendering 3

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.248-alpha](https://keyman.com/downloads/releases/alpha/17.0.248)

**Pull request merged**
