### PR TITLE
fix(developer): include Keyman Core in Keyman Developer 🐞

### LINKED ISSUE #5648: bug(developer): an error occurs when starting the debugger in 15.0.104
**Describe the bug**

After installing Keyman Developer and Keyman for Windows from the build in https://github.com/keymanapp/keyman/pull/5640 and start the debugger, an error occurs.

```
Details for error report for Keyman app:
  Application Identifier: tike-15.0.104-alpha-test-5640
  Error Identifier: F982BFBF7DFB4F6B2B3E13580882A5A1
```

**Expected behavior**

No error should occur at this point. The debugger should start as usual.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 15.0.104 alpha
 - Target Application: Keyman Developer

**Keyman Developer:**
 - Keyman Developer version: 15.0.104 alpha

---
Keyboard project for testing: [pr_5640.zip](https://github.com/keymanapp/keyman/files/7063693/pr_5640.zip)

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5648.

Includes kmnkbp0-0.dll in the installer for Keyman Developer.

# User Testing

* TEST_BASIC: Load a keyboard in Keyman Developer, and press F5 to start debugging. It should start!

### CODE REVIEW

**Comment by darcywong00** [comment]
> It looks like the build failed?

The build agent is reporting a signing error saying the kmnkbp0-0.dll from https://github.com/keymanapp/keyman/pull/5649/commits/5b9e49ce4ea61e16ed68b6e6639460bd13e8a69b has the wrong company. Will just have to wait a few weeks

**Comment by MakaraSok** [comment]
- **TEST_BASIC: BLOCKED** build error

**Comment by mcdurdin** [comment]
> The build agent is reporting a signing error saying the kmnkbp0-0.dll from [5b9e49c](https://github.com/keymanapp/keyman/commit/5b9e49ce4ea61e16ed68b6e6639460bd13e8a69b) has the wrong company. Will just have to wait a few weeks

Yes, kmnkbp0-0.dll does not include a version information resource. Looking into how best to fix that now.

**Comment by mcdurdin** [comment]
I have patched the version information check to skip checking of kmnkbp0-0.dll, which will be fixed in #5672.

@keymanapp-test-bot retest

**Comment by MakaraSok** [comment]
* **TEST_BASIC: PASSED** The debugger does start.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.111-alpha](https://keyman.com/downloads/releases/alpha/15.0.111)

**Pull request merged**
