### PR TITLE
feat(web): testing page for font-load / key-scale interactions ⛲

### PR DESCRIPTION
**Pull request by jahorton**
As requested for #10506, this PR implements a half-decent user-test setup for ensuring that key-cap scaling calculations take effect _after_ the corresponding font has been loaded.

This test works by setting the base font size on touch layouts to an extreme value (`'4em'`) and replacing the glyphs for all standard a-z characters with identical, evenly-sized large dots.  The key point here:  **_evenly-sized_**.  Default fonts for a-z are variable width, so if key-cap scaling results in unevenly-sized dots, we know that scaling was applied _before_ our "dotty" font was loaded.

Obviously, it's a kind of crude - and very "constructed" - setup... but it's sufficient for a decent test.

Expected:

image

(Yes, even the 'a'-'z' in the actual _output_ are replaced by dots.)

Also... yes, there's an obvious issue here with the frame-key key-cap scaling.  It's a separate issue:

image

... even if not yet documented _as_ an issue.

## User Testing

**TEST_SPECIAL_KEYCAPS**:  From the KeymanWeb user-test page index on a mobile device, use the new "`Test key-cap scaling / font load interactions (#10506)`" test page and verify it works properly.
- Chrome emulation of a mobile device is perfectly fine.

1. Visit the "`Test key-cap scaling / font load interactions (#10506)`" test page.
2. Swap to the "Special" keyboard.
3. Verify that all the key-caps for all standard keys (which will be large dots) are evenly-sized.
    - Pay special attention to the QWERTY 'w' and 'm' keys.
    - For the purposes of this test, disregard any issues for keys with special styling - SHIFT, BKSP, ENTER, etc.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> Also... yes, there's an obvious issue here with the frame-key key-cap scaling. It's a separate issue:
> 
> image
> 
> ... even if not yet documented _as_ an issue.

Will tis be documented as an issue?

**Review by mcdurdin — APPROVED** [review]
RSLGTM even

**Comment by jahorton** [comment]
> > Also... yes, there's an obvious issue here with the frame-key key-cap scaling. It's a separate issue:
> > image
> > ... even if not yet documented _as_ an issue.
> 
> Will this be documented as an issue?

I opted to handle it directly as part of #10535.

**Comment by mcdurdin** [comment]
> I opted to handle it directly as part of #10535.

Glad to hear -- these cross references really help :grin:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.257-alpha](https://keyman.com/downloads/releases/alpha/17.0.257)

**Pull request merged**
