### PR TITLE
chore(ios): Xcode 14 upgrade 🍒 

### LINKED ISSUE #8514: chore(core): sprintf deprecated in xcode 14
Arising from xcode upgrade to 14.2.

Per [build log](https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_macOS/374425?buildTab=log&focusLine=337&logView=flowAware&linesState=110):

```
16:40:00   c++ -Isrc/libkmnkbp0.0.dylib.p -Isrc -I../../../src -fcolor-diagnostics -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Werror -std=c++14 -O3 -isystem../../../../common/include -isystem../../../include -isysteminclude -DKMN_KBP -DKMN_KBP_EXPORTING -Wctor-dtor-privacy -Wdouble-promotion -Wendif-labels -Wno-unknown-pragmas -Wno-missing-field-initializers -Wnon-virtual-dtor -Wshadow -Wimplicit-fallthrough -Wno-double-promotion -Wshorten-64-to-32 -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -fvisibility=hidden -fvisibility-inlines-hidden -MD -MQ src/libkmnkbp0.0.dylib.p/kmx_kmx_debug.cpp.o -MF src/libkmnkbp0.0.dylib.p/kmx_kmx_debug.cpp.o.d -o src/libkmnkbp0.0.dylib.p/kmx_kmx_debug.cpp.o -c ../../../src/kmx/kmx_debug.cpp
16:40:00   ../../../src/kmx/kmx_debug.cpp:61:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
16:40:00     sprintf(windowinfo,
16:40:00     ^
16:40:00   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
16:40:00   __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
16:40:00   ^
16:40:00   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
16:40:00           #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
16:40:00                                                         ^
16:40:00   ../../../src/kmx/kmx_debug.cpp:111:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
16:40:00       sprintf(buf, "['%s' 0x%x]", s_key_names[vk], vk);
16:40:00       ^
16:40:00   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
16:40:00   __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
16:40:00   ^
16:40:00   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
16:40:00           #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
16:40:00                                                         ^
```

### PR DESCRIPTION
**Pull request by sgschantz**
In support of move from Xcode 13.4 to 14.2

Requires change of iOS Target Version from 12 to 12.2
macOS target version remains at 10.10

🍒 -picked from PR #8015 

Fixes #8514.

## User Testing
A basic smoke test is needed for Keyman for macOS and Keyman for iOS

* **TEST_MAC** 
1. Verify that Keyman for macOS is operating as expected.

* **TEST_IOS**
1. Verify that Keyman for iOS is operating as expected.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (PASSED):** Tested with the attached PR build in iOS 16.2 / iPhone Simulator (updated Xcode version is 14.2) and here is my observation: 1. Able to install different language keyboards. 2. Switching between Keyboards are working as expected. 3. Keyman is working fine as a System keyboard.

**Comment by sgschantz** [comment]
@keymanapp-test-bot retest TEST_MAC

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_MAC (PASSED):** Retested with Keyman 16.0.140-test-8487 build in macOS and here is my observation: 1. Switching Keyboard is working fine with other apps like Notes, Messages etc., 2. But, it is not working with LibreOffice Writer. So, I have posted a separate issue (keyboard switching not working in LibreOffice writer)  #8599 in Github.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.140](https://keyman.com/downloads/releases/stable/16.0.140)

**Pull request merged**
