### PR TITLE
epic: LDML keyboard support 🙀

### PR DESCRIPTION
**Pull request by mcdurdin**
* Implements #7042

issue label: [epic-ldml](https://github.com/keymanapp/keyman/labels/epic-ldml)

_Process: We'll use this PR comment as a central location for all issues and PRs relating to the epic-ldml project, so this comment our landing page for the project. All epic-ldml PRs will eventually merge into this branch before landing in `master`. Edit this comment rather than adding additional content_

# To-do Items

_Process: add to-do items here, convert to issues as appropriate._

- [ ] move IO out of Keyman Core into Keyman Engine
  - [ ] Linux
  - [ ] Windows
  - [ ] Developer
  - [ ] Tests

- [ ] #7310 

_Process: add all related issues and PRs here, categorised for ease of tracking_

# Specifications

### Overview / Common
* #7043

### Core
* #5015

### Developer
* #7047
* #5016 
* #5077 
* #5078

# Issues

### Overview / Common
* #7044
* #7045 

### Core
* #7046

### Developer
* #7532 

# Pull Requests

### Common
* #7049
* #7050

### Core
* #7048

### Developer

@keymanapp-test-bot skip
- we are not ready for user testing on this work yet.

### CODE REVIEW

**Comment by srl295** [comment]
- [ ] TODO: pull in testing plan from https://keymanapp.slack.com/archives/C6Q9WS09G/p1660607437990639?thread_ts=1660602108.186109&cid=C6Q9WS09G for keyup/keydown.

**Comment by srl295** [comment]
@mcdurdin  Does it make sense to use this PR (and retitle it 'Phase 1') for an A17S7 merge to master? Or would you refer _another_ PR from a chore branch for the actual merge to master and keep #7054 open?  

For that matter maybe #7042 (the epic issue) should be retitled 'LDML Hardware' and make a new epic-ldml for subsequent work (keep the label, just a new holding ticket / PR ).  Thoughts?

**Comment by mcdurdin** [comment]
> @mcdurdin Does it make sense to use this PR (and retitle it 'Phase 1') for an A17S7 merge to master? Or would you refer _another_ PR from a chore branch for the actual merge to master and keep #7054 open?

We'll merge this one to master (retitling it) when we finish the hardware stuff to the right level, and create a new branch with the name feature-ldml-touch perhaps for the next round.

> For that matter maybe #7042 (the epic issue) should be retitled 'LDML Hardware' and make a new epic-ldml for subsequent work (keep the label, just a new holding ticket / PR ). Thoughts?

I think we keep #7042 as the epic issue; there's a lot of content there that relates to touch, and it's all part of the same epic.

**Comment by srl295** [comment]
@mcdurdin  does it need `@keymanapp-test-bot skip`?

**Review by srl295 — APPROVED** [review]
LGTM!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.58-alpha](https://keyman.com/downloads/releases/alpha/17.0.58)

**Pull request merged**
