### PR TITLE
feat(ios): add spacebar text controls 🍒 🌌

### PR DESCRIPTION
**Pull request by mcdurdin**
Cherry-pick of #5365.

Relates to #949.

Mirror of #5349 (Android), for iOS.

* Adds setSpacebarText() API to Keyman Engine for iOS
* Adds displayName API to Keyman Engine for iOS
* Sets default spacebar text to keyboard name for FirstVoices Keyboards
* Does not add preference UI

### CODE REVIEW

**Comment by mcdurdin** [comment]
# User Testing

@keymanapp/testers 

1. Please perform a basic acceptance test on Keyman for iOS. There should be no visible change from previous stable-14.0 release - no new crashes etc :) Note that this will require building and installing in the simulator. If this will be a problem, let me know.
2. FirstVoices Keyboards:
    * Please perform a basic acceptance test on FirstVoices Keyboards. There should be no new crashes or behaviour changes apart from the point below. (Again this will require building and installing in the simulator.)
    * The keyboard should now show just the name of the keyboard, not the langtags.json language name. For example, St’át’imcets keyboard should show only 'St’át’imcets' and not 'Lillooet' (langtags.json language name).

**Review by jahorton — APPROVED** [review]

**Comment by MakaraSok** [comment]
No artifact is found to test.

image

**Comment by mcdurdin** [comment]
> No artifact is found to test.

To test iOS builds, you have to build it on your machine and run in the simulator, sadly.

**Comment by jahorton** [comment]
> > No artifact is found to test.
> 
> To test iOS builds, you have to build it on your machine and run in the simulator, sadly.

Yup.  Apple doesn't allow .apk-like installations.  It's through Apple's App Store, through TestFlight, or through Xcode.  They're very strict.  For test builds... only the latter of those options is available.

**Comment by MakaraSok** [comment]
Tried and built a couple of time, but unsuccessful.

```
note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
** BUILD FAILED **
```

Branch and path I'm currently on:
```
makarasok@Makaras-MBP ios % git status
On branch feat/ios/cherry-pick/spacebar-text-controls
Your branch is up to date with 'origin/feat/ios/cherry-pick/spacebar-text-controls'.

nothing to commit, working tree clean
```

**Comment by jahorton** [comment]
> Tried and built a couple of time, but unsuccessful.
> 
> ```
> note: Using new build system
> note: Building targets in parallel
> note: Using codesigning identity override: 
> note: Planning build
> note: Analyzing workspace
> note: Constructing build description
> note: Build preparation complete
> ** BUILD FAILED **
> ```
> 
> Branch and path I'm currently on:
> 
> ```
> makarasok@Makaras-MBP ios % git status
> On branch feat/ios/cherry-pick/spacebar-text-controls
> Your branch is up to date with 'origin/feat/ios/cherry-pick/spacebar-text-controls'.
> 
> nothing to commit, working tree clean
> ```

Right... when going for stable, things get a bit tricky.  You'll probably need to use a `git clean -fxd` command at the repo's root first, removing all pre-existing build products, then running a full build.  No `-no-carthage` shortcuts or anything of the sort.  (Hopefully I got the command right.)

Things changed _enough_ between 14.0 and 15.0 that a full, clean build is necessary to make things work.

**Comment by mcdurdin** [comment]
@keymanapp/testers can you update on status of this test?

**Comment by MakaraSok** [comment]
## Keyman for iOS
**TEST-1: PASSED** - no crashes experienced on both in app and as a system keyboard.

##  FirstVoices Keyboards for iOS
**TEST-2: PASSED** - no crashes on both in app and as a system keyboard. The spacebar does show only the keyboard name.
image

@jahorton Thanks you for your help with the build issues. 💯

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.278](https://keyman.com/downloads/releases/stable/14.0.278)

**Pull request merged**
