### PR TITLE
change(ios): setText now uses JSON serialization 🍒

### PR DESCRIPTION
**Pull request by jahorton**
🍒-pick of #5321.

### CODE REVIEW

**Comment by mcdurdin** [comment]
@jahorton can you please ensure that your local `stable-14.0` is up to date as this is using outdated build scripts, causing build triggers to fail.

**Comment by mcdurdin** [comment]
Triggered the build manually. It [failed](https://build.palaso.org/viewLog.html?buildId=275779&buildTypeId=Keyman_iOS_TestPullRequests&tab=buildLog&_focus=260):

```
[09:58:55][Step 2/2] /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift:233:21: error: type 'SentryManager' has no member 'captureAndLog'
[09:58:55][Step 2/2]       SentryManager.captureAndLog(error.localizedDescription)
[09:58:55][Step 2/2]       ~~~~~~~~~~~~~ ^~~~~~~~~~~~~
```

**Comment by jahorton** [comment]
> Triggered the build manually. It [failed](https://build.palaso.org/viewLog.html?buildId=275779&buildTypeId=Keyman_iOS_TestPullRequests&tab=buildLog&_focus=260):
> 
> ```
> [09:58:55][Step 2/2] /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift:233:21: error: type 'SentryManager' has no member 'captureAndLog'
> [09:58:55][Step 2/2]       SentryManager.captureAndLog(error.localizedDescription)
> [09:58:55][Step 2/2]       ~~~~~~~~~~~~~ ^~~~~~~~~~~~~
> ```

Oh yeah... right.  That's a 15.0-only change.  That function utilizes the updated Sentry dependency, so it never landed on `stable`.

**Review by darcywong00 — APPROVED** [review]
lgtm

Though isn't there a 14.0 Sentry call that's available?

**Comment by jahorton** [comment]
1.  I'd have to look up the `sentry-cocoa 4.3.x` way of doing that call
2. It'd be the _only such call_ in the 14.0-stable codebase.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.277](https://keyman.com/downloads/releases/stable/14.0.277)

**Comment by mcdurdin** [comment]
When we cherry-pick, can we ensure we reference the original issue (#5200).

**Comment by mcdurdin** [comment]
I think I need to tweak the bot to ignore closed PRs and issues...

**Pull request merged**
