### PR TITLE
[Mac] #1069 - Added SIL logo to DMG image & About box. Updated copyright

### PR DESCRIPTION
**Pull request by tombogle**

### CODE REVIEW

**Comment by mcdurdin** [comment]
Can you include screenshots of the DMG window in this PR?

**Comment by tombogle** [comment]
screen shot 2018-09-06 at 9 18 36 am

**Comment by tombogle** [comment]
You have an amazing eye to notice that the logo and "Keyman" text were out of proportion. I didn't do that - it's always been that way, but you are correct. Whoever did it for some reason added the logo and the text as two separate graphics.

**Comment by tombogle** [comment]
New screenshot of DMG layout:
image

**Comment by tombogle** [comment]
New screenshot of DMG layout:
image

**Comment by tombogle** [comment]
image

**Pull request merged**
