### PR TITLE
fix(android): host-page banner initialization

### LINKED ISSUE #11507: bug(android): host-page show-banner does not null-guard against uninitialized OSK
Pretty much the title.  I noticed this while attempting to reproduce something else; I got the following error via local simulation:

```
KMW JS Log: Line 72, file:///data/user/0/com.tavultesoft.kmapro.debug/app_data/android-host.js:Uncaught TypeError: Cannot read property 'bannerController' of undefined
```

It arose from here:

https://github.com/keymanapp/keyman/blob/53b583e009f37803f84d3aace38cd9813dafaed5/android/KMEA/app/src/main/assets/android-host.js#L72

Should the method be called before the Web engine initializes, it will fail.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11507.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
Does this need a cherry-pick to 17.0-stable?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Pull request merged**
