### PR TITLE
chore(common): bash version for run-required-test-builds.sh 🍒

### PR DESCRIPTION
**Pull request by mcdurdin**
Cherry-pick of #5267.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
Four different build failures:

* Android fail is down to a Linux BA error:

  ```
  [10:14:55][Step 2/3] Execution failed for task ':kMAPro:validateSigningRelease'.
  [10:14:55][Step 2/3] > Keystore file '/c/cert/Android Key Store/KeymanAndroidKeyStore' not found for signing config 'release'.
  ```

* Web fail is because the browserstack tunnel killer script (at least for Linux) was not backported to 14.0
* iOS fail is down to Carthage? (@jahorton)
* macOS fail is down to arm64 build (M1) -- why it's failing now, I don't know.

**Comment by darcywong00** [comment]
> Web fail is because the browserstack tunnel killer script (at least for Linux) was not backported to 14.0

That was 🍒 -picked in #5235 ?

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by jahorton** [comment]
I see all the builds passed after the merge with the current `stable-14.0` - perhaps the errors were all due to an originally out-of-sync base?

**Comment by mcdurdin** [comment]
> I see all the builds passed after the merge with the current `stable-14.0` - perhaps the errors were all due to an originally out-of-sync base?

I think so. I hope so!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.277](https://keyman.com/downloads/releases/stable/14.0.277)

**Pull request merged**
