### PR TITLE
fix(web): track load error detail 🍒

### PR DESCRIPTION
**Pull request by mcdurdin**
Cherry-pick of #6442

This is a follow-up for #6331. We still did not have enough detail to be able to trace the root cause of the load errors. This adds a little more diagnostics.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
A hiccup in the iOS build. Do we just try again?

**Comment by mcdurdin** [comment]
> A hiccup in the iOS build. Do we just try again?

Nope. 14.0-stable build is broken because we had to update our build agents to XCode 13. It requires us to change all the dependencies to xcframeworks, which we did for 15.0-alpha in #5107, #5155, #5164 and #5933. Not sure if the effort is worth it, given we are about to go to 15.0-stable in a few weeks.

**Review by darcywong00 — APPROVED** [review]
lgtm.

This has the original commit with `ev`. But that's fine.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.289](https://keyman.com/downloads/releases/stable/14.0.289)

**Pull request merged**
