### PR TITLE
fix(developer): use KeymanWeb.Codes for 17.0+

### LINKED ISSUE #8147: chore(developer): use new `KeymanWeb.Codes` prefix for 17.0+ web compiled keyboards
```suggestion
  var modCodes = KeymanWeb.Codes.modifierCodes;
  var keyCodes = KeymanWeb.Codes.keyCodes;
```

We'll need to continue to support `com.keyman.text.Codes` for existing, debug-compiled keyboards. So I suggest that we update the compiler for 17.0 to emit the following for keyboards that target 17.0:

```js
  var modCodes = KeymanWeb.Codes.modifierCodes;
  var keyCodes = KeymanWeb.Codes.keyCodes;
```

For keyboards that target older versions, the compiler will continue to emit:

```js
  var modCodes = com.keyman.text.Codes.modifierCodes;
  var keyCodes = com.keyman.text.Codes.keyCodes;
```

I'll turn this into an issue against Developer 17.0.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/7809#discussion_r1094020949_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #8147.

Keyboards debug-compiled for web 17.0+ will use `KeymanWeb.Codes.` instead of `keyman.osk.`.

# User Testing

* **TEST_DEBUGGER:** Create a new keyboard in Developer, and set its `store(&VERSION)` line to '17.0'. Compile the keyboard, and test it in the web debugger. Verify that the keyboard loads in Keyman Developer Server in the browser and that there are no Javascript errors (you will need to look at the Javascript console to be certain)

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (FAILED):** Tested with Keyman Developer 17.0.204-alpha-test-9913 on Windows 11 OS (VM) and here is my observation: 1. Created a new keyboard using Keyman developer. 2. Set the Version number. 3.Compiled the Keyboard. Got a warning message 'You must include debug information to start the debugger. Check 'Include debug information' in the Keyboard menu'. 4. I noticed that the 'Include Debug Information' option was already checked. 5. I am getting this message repeated whenever I try to start debugging option. Seems to be an issue.

**Comment by mcdurdin** [comment]
@bharanidharanj thanks for this test. It looks like you bumped up against the fix in #9901. I have rebased this to include that fix, so if you could retest this, that'd be great, thanks!

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
> @bharanidharanj thanks for this test. It looks like you bumped up against the fix in #9901. I have rebased this to include that fix, so if you could retest this, that'd be great, thanks!
> 
> @keymanapp-test-bot retest

@mcdurdin Sure, I will do it.

**Comment by bharanidharanj** [comment]
> @bharanidharanj, I'm sorry, I wasn't clear on the console. The console is the Web Developer Console, available by pressing F12 and selecting the Console tab:
> 
> image
> 
> Would you mind retesting please?
> 
> @keymanapp-test-bot retest

@mcdurdin Thanks for the clarification. Yes, I will retest and add my comment.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (FAILED):** Retested as per your instructions and here is my observation: 1. Got an error message in the Web Developer Console. Seems to be an issue.

**Comment by mcdurdin** [comment]
Fortunately, that warning can be safely ignored 😀 so this is a pass! Thank
you!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.205-alpha](https://keyman.com/downloads/releases/alpha/17.0.205)

**Pull request merged**
