### PR TITLE
epic: new gesture engine 🐵

### PR DESCRIPTION
**Pull request by mcdurdin**
Implements #5029, enabling the following types of gestures within KeymanWeb, Keyman for Android, and Keyman for iPhone and iPad.

### Multitaps

Main PRs:
- #9740
- #9876
- #10103

<details><summary>Small videos (dropdown)</summary>

<details open><summary><strong>Phones</strong> (animated gif dropdown)</summary>

multitap-apple

</details>

<details><summary><strong>Tablets</strong> (animated gif dropdown)</summary>

multitapple-tablet

</details>

When multitapping across layers...

<details><summary>Layer-crossing previews</summary>

mt-layer-crossing-previews

Note how the key-hints in the background swap as the key continues to be tapped.  (The fact that the shift-key doesn't illuminate/highlight was a keyboard-design bug on my part at the time of recording.)

</details>

</details>

In 16.0, we supported a single type of multitap - the ability to double-tap the SHIFT key to reach a CAPS layer under certain conditions.  This restriction is now fully removed.

- It is possible to multitap across multiple layers from the same base key.
- When multitap keys produce text output, the context for any related keystroke rules is always based on the state of the context **before** the base key was tapped.
- The two points above interact well, as seen in the final screen recording within the dropdown above.  You can both output text _and_ layer-shift during multitaps without things breaking.

### Flicks

Main PRs:
- #9909 
- #9957
- #10173

<details><summary>Small videos (dropdown)</summary>

orienting-flick-preview

We set the preview to "move" for certain flick directions because of practicalities - consider where your finger would be during the flick and how it would obstruct your ability to see the preview.

</details>

A new gesture type, "flicks" allow you press a key down and drag it in one of the four cardinal directions (up, right, down, left) or one of the four intercardinal directions to select a subkey.  You must move a set distance before the flick will fully trigger, with a smaller threshold being required near the start of the flick to prevent being interpreted as a longpress.

There's a "middle-ground" threshold between the two.  Once reached, this threshold will "lock" the flick direction in place, allowing for a polished preview animation.  Moving the touchpoint back toward the start location will "unlock" the flick and allow a different direction to be selected.

### Modifier longpresses - the "modipress"

(_**Modi**_-fier long-_**press**_.)

Main PRs:
- #9876
- #9973

Apologies for the lack of video / animated gifs:  it is much harder to clearly record a multi-finger gesture.  The approaches I looked at for this don't display circles for each ongoing touch, which is vital for clarity.

Have you ever wanted to type just a key or two from an alternate layer and then automatically return to your original layer, no matter which it was?  If you:

1. Hold down the layer-shifting key with one finger...
2. Then type with a different finger (one or many keys) or wait out the longpress timer...
3. And only _then_ release the layer-shifting key...

... you'll automatically be returned to your original layer, no matter which it was - all without the need for custom `nextlayer` definitions on the keys used in step 2.  While it may _sound_ a bit technical, it's something that many people naturally try to do and have gotten used to with other modern touch-keyboard solutions.

In essence, it allows you to treat a layer-shifting key as a longpress key, with its destination layer as the subkey menu.  That said, you can still use regular longpresses during this gesture!

This gesture type may also combine with multitaps **_if_** the base key only changes the active layer.  (We strongly recommend that all reachable keys for such a multitap only shift layers.)  Multitapping, then _holding_ at the end of such a multitap, will lock the `nextlayer` for the final tap of the multitap in place... until released, as with steps 1-3 listed above.

### Custom key-hints

Main PR:
- #9829

<details><summary>Examples from keyboards seen in the recordings above (dropdown)</summary>

_(defaultHint: 'flick')_

image

_(each key has a custom `hint` value)_

image

</details>

Note that only one hint per key (on its top-right) may be specified at this time.  We're strongly considering extending this in a future version of Keyman, but such extensions will not land in 17.0.

----

This PR also enhances existing gestures:

### Longpress

Main PR:
- #9698

<details><summary>Small videos (dropdown)</summary>

<details><summary>Gigantic longpress menu - two rows, second with one less key</summary>

longpress 1

Going beneath the longpress's base key (rather than the subkey menu) will cancel selection, allowing the user to abort the longpress if they release the touch in such a location.
</details>

<details open><summary>Fitts's law - loose selection range</summary>

longpress 2 - fitts law

</details>

<details><summary>Swift longpresses - working with muscle memory</summary>

longpress 3 - semiflicks

The 's' longpress is there for comparison on the _standard_ longpress wait timing, while the rest trigger and execute far more quickly.  As long as the longpress-shortcut flick is in a generally upward direction - within roughly 67.5 degrees of a purely-upward direction - and the user doesn't shoot extremely far, the shortcut will trigger early.

This shortcut is not enabled on keys that have defined flick gestures in any of the "upward" directions.

</details>

<details><summary>Fitts's law for system keyboards</summary>

longpress 4 - constrained mode fitts

</details>

</details>

### "Roaming touch"

"Roaming touch", the keyboard mode in which the selected key changes as you move your finger from key to key before a longpress timer triggers, was largely broken in recent versions of KeymanWeb, but has been restored.  

However, it will be explicitly disabled for keyboards with flicks.  It's worth noting that there's not much difference in the motion of a rightward flick and a rightward "roam" - it would be difficult to differentiate between the two on keys with such a flick.  We believe consistent treatment of flickless and flick-enabled keys to be vital for clarity and simplicity... and the simplest way forward is to prevent overcomplicating how such a motion is handled by turning off roaming touch.

------

Oh, and backing all of this:

### Abstract gesture engine

In order to implement these gestures, we have implemented a custom engine for gesture-recognition.  While research turned up plenty of pre-existing engines for _common_ gesture types - pinch, zoom, drag, etc - we were unable to find anything that clearly supported specifying custom gesture definitions - let alone full sets of them - in a manner that would be compatible with our needs.

Of particular note is that most of our gestures consist of multiple "states" - this gesture engine could be considered a gesture-oriented [finite-state machine (FSM)](https://en.wikipedia.org/wiki/Finite-state_machine).  Transitioning along any FSM edge - that is, recognizing a completed, valid gesture state - blocks all other edges and triggers a new 'state' from which different edges (potential follow-up gesture states) are allowed.

This gets _further_ complicated due to some 'fun' interactions that are possible among the gesture types we support.  Of particluar note is that in many cases, starting a new touch should "auto-complete" certain types of previous gestures.  The new touch should not be considered as _part_ of those gestures, even though it does _trigger_ them.  If such a _trigger_ does occur, the pre-existing gesture should _fully_ resolve, if possible, before further processing the triggering touch.

It also gives us some of the benefits described below:

_Originally from #6842:_

By developing an isolated module for gesture support, we'll be able to demo and test gesture behavior outside of KeymanWeb.  One of my design goals with this is actually to enable gesture _unit tests_ by recording tracked input sequence data.  This may be achieved by keeping the core logic headless and replicating recorded input sequences in a headless environment.

-----------

## Related Issues

- [x] https://github.com/keymanapp/keyman/issues/7067

# User Testing

**TEST_REGRESSION_WEB**:  As the branch now seems ready to merge down to `master` Web, we should run a [full regression test suite](https://github.com/keymanapp/keyman/wiki/Platform-Acceptance-Test-for-Web) on it.
- Any tests corresponding to those from #9973 may be ignored, as they were literally just run.
- Therefore, ignore the new SUITE_TOUCH_GESTURES section.  (I literally just copied the tests from #9973 there.)

**TEST_REGRESSION_ANDROID_KBD**:  We should also run the [SUITE_KEYBOARD_FUNCTIONALITY](https://github.com/keymanapp/keyman/wiki/Platform-Acceptance-Test-for-Android#suite_keyboard_functionality-keyboard-tests) set of tests from the Android regression-test suite.

**TEST_REGRESSION_IOS_PREDTEXT**:  We should also run the [SUITE_PREDICTIVE_TEXT_AND_AUTO_CORRECTION](https://github.com/keymanapp/keyman/wiki/Platform-Acceptance-Test-for-iOS#suite_predictive_text_and_auto_correction-predictive-text-and-auto-correction) set of tests from the iOS regression-test suite.

### CODE REVIEW

**Comment by jahorton** [comment]
Note https://github.com/keymanapp/keyman/pull/7741#issuecomment-1322875467 when it comes time to merge; I originally did some test index reorganization, but there were a few `hrefs` that needed adjustment.  Refer to https://github.com/keymanapp/keyman/pull/7741#issuecomment-1322875467.

**Comment by jahorton** [comment]
Related:  https://github.com/keymanapp/keyman/issues/5511

It'll be lower-priority to implement than the main gesture types we've already added in Developer (multi-tap, output-key flick), but we can probably implement it in the same release cycle.

**Comment by MayuraVerma** [comment]
if the mutlitap  17.0.36 (0.7324.7695)

**Comment by mcdurdin** [comment]
> if the mutlitap feature is available in 17.0.36 (0.7324.7695),
> 
> If I can get the keyboard format. I can test also.

* The gesture work in the apps is still in process, not yet ready to test.
* The gesture design tools are available in Keyman Developer 16.0.138.

**Comment by MayuraVerma** [comment]
No pressure, Just curious if the gesture engine ready for testing

**Comment by mcdurdin** [comment]
> No pressure, Just curious if the gesture engine ready for testing

Not yet.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_REGRESSION_WEB (PASSED):** I ran the full regression test suite for the web (except SUITE_TOUCH_GESTURES section) with the given "KeymanWeb Test Home" test page and here is my observation: 1. Tested in all Desktop Platforms (Windows_Firefox, Chrome, MacOS_Safari, Chrome and Firefox, Linux_Firefox) and it seems to be working as expected. No critical issues were found during my testing. 2. Additionally, I conducted tests on touch platforms such as Android, iPhone, and iPad using the specified browsers and configurations, and they appear to be functioning properly.

**Comment by jahorton** [comment]
> # Test Results
> 
>     * **TEST_REGRESSION_ANDROID_KBD (FAILED):** Run the regression test for Android (Suite_Keyboard_Functionality) in the Android Mobile (ver 13)and here is my observation: 1. Tested (TEST_INAPP_LATIN_KEYBOARD_PORTRAIT) and I am getting keyboard error message while using backspace, enter and space keys during the testing. Seems to be an issue.
> 
> [omitted]
> 
> ..video file
> ErrorinKeyboard.mp4

Timestamp in video is ~1:36, after coming out of the language-picker.  Just noting, since the video is not isolated to the error itself.

**Comment by jahorton** [comment]
TODO:

- KMW's `build.sh` has a "temporary" tie-in component for the gesture engine.  We should be able to drop that in favor of plain build dependencies now.
    - That said, the test-page copy stuff should be migrated to the test-resource copying shell-script.

**Comment by jahorton** [comment]
@keymanapp-test-bot retest TEST_REGRESSION_ANDROID_KBD 

#10136 should be fixed by #10185 now, and I believe that was the reason for the previously-failing user test.

**Comment by jahorton** [comment]
iOS build failure from the last commit:

```
07:51:22 
  /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/oem/firstvoices/ios/FirstVoices.xcodeproj: error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "D7TR486TEH" with a private key was found. (in target 'SWKeyboard' from project 'FirstVoices')

07:51:22 
  /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/oem/firstvoices/ios/FirstVoices.xcodeproj: error: Provisioning profile "FirstVoices_Keyboards_SWKeyboard" expired on 10 Dec 2023. (in target 'SWKeyboard' from project 'FirstVoices')

07:51:22 
  warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'SWKeyboard' from project 'FirstVoices')

07:51:22 
  /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/oem/firstvoices/ios/FirstVoices.xcodeproj: error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "D7TR486TEH" with a private key was found. (in target 'FirstVoices' from project 'FirstVoices')

07:51:22 
  /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/oem/firstvoices/ios/FirstVoices.xcodeproj: error: Provisioning profile "FirstVoices_Keyboards" expired on 10 Dec 2023. (in target 'FirstVoices' from project 'FirstVoices')

07:51:22 
  warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'FirstVoices' from project 'FirstVoices')

07:51:22 
  warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'FirstVoices' from project 'FirstVoices')

07:51:22 
  ** ARCHIVE FAILED **

07:51:22 
  

07:51:22 
  

07:51:22 
  [oem/firstvoices/ios] Build failed! Error: [65] when executing command: 'xcodebuild -quiet -configuration Release -derivedDataPath "/Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/oem/firstvoices/ios/build" -scheme FirstVoices -archivePath /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/oem/firstvoices/ios/build/Build/Products/Release-iphoneos/FirstVoices.xcarchive archive -allowProvisioningUpdates VERSION=17.0.227 VERSION_WITH_TAG=17.0.227-alpha-test-7324'

07:51:22 
  

07:51:22 
  [oem/firstvoices/ios] ## build failed
```

> Provisioning profile "FirstVoices_Keyboards_SWKeyboard" expired on 10 Dec 2023.

For the FirstVoices subproject.

**Comment by mcdurdin** [comment]
> merge master into your branch

and I see now that this is a separate failure ... opening as a new issue

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_REGRESSION_ANDROID_KBD (FAILED):** Retested with the attached PR build (Keyman 17.0.227-alpha-test-7324 in the Android Mobile device (ver 13) and here is my observation: 1. While testing  TEST_INAPP_LATIN_KEYBOARD_LANDSCAPE test in the lanscape mode the OSK shrinks it width after using the globe key. Here, What I did is :
1. In the Landscape mode, typed some letter using the OSK. 
2. Used Backspace and Enter button after typing each words. 
3. Clicked the globe key. 
4. Selected the same keyboard from the Picker menu. 

Here, I noticed that the OSK shrinks its width on the Keyman home page. Seems to be an issue.

**Comment by jahorton** [comment]
> # Test Results
> 
>     * **TEST_REGRESSION_ANDROID_KBD (FAILED):** Retested with the attached PR build (Keyman 17.0.227-alpha-test-7324 in the Android Mobile device (ver 13) and here is my observation: 1. While testing  TEST_INAPP_LATIN_KEYBOARD_LANDSCAPE test in the lanscape mode the OSK shrinks it width after using the globe key. Here, What I did is :
> 
> 
>     1. In the Landscape mode, typed some letter using the OSK.
> 
>     2. Used Backspace and Enter button after typing each words.
> 
>     3. Clicked the globe key.
> 
>     4. Selected the same keyboard from the Picker menu.
> 
> 
> Here, I noticed that the OSK shrinks its width on the Keyman home page. Seems to be an issue.
> 

Documented as #10241.  I have reproduced this on master - thus it is not a feature-gestures issue. There's a chance this is related to recent ✨ Android optimizations.

At any rate... it's not something to block upon.

**Review by jahorton — APPROVED** [review]
While I'm the true author, this has long been a "holding" / staging PR for all the accumulated feature changes.

Everything we need to 'release' the feature is now ready.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.230-alpha](https://keyman.com/downloads/releases/alpha/17.0.230)

**Pull request merged**
