### PR TITLE
fix(developer): ensure file modified after import from layout

### LINKED ISSUE #5577: bug(developer): developer doesn't save imported touch layout
**Describe the bug**
When importing a touch layout from "on screen", the new layout shows in the Design and Code windows, but is not saved nor used when compiling the keyboard.

**To Reproduce**
Start Keyman Developer (version 14.0.280.0), Project, New Project, Basic, OK
Keyboard Name: xyz, BCP 47 tag: qaz, OK
Keyboards, open xyz.kmn
Layout tab, set q to U+0259 (latin small letter schwa), set Q to U+018F (latin capital letter schwa)
(selecting "Code" shows:
```
+ [SHIFT K_Q] > 'Ə'
+ [K_Q] > 'ə'
```
in the .kmn file)
On-Screen tab, click "Auto-fill from underlying layout" box, then "Fill from layout button"
Touch Layout tab, shows "tablet" and "phone" layouts, each with four rows of keys and "default", "shift", "numeric" layers.
Select "phone" layout, then "Del" to delete phone layout, leaving only a tablet layout.
Click "Import from On Screen", get "You must save changes to your keyboard before import" message.  Click "Yes" to save.
There's now a tablet layout with five rows and two layers.
Ctrl+S to save.
Build tab, "Compile Keyboard" button, then "Test Keyboard on web" button and "Open debugger in local browser" button.
In browser, F12, F5 to switch to touch layout, click in the text box and keyboard appears, but it's the default 4-row keyboard without the schwa.
In Explorer, look at source/xyz.keyman-touch-layout. The file contains the 4-row keyboard (and "q" not schwa).

**Workaround**
Touch Layout tab, select "Code", Ctrl+A to select all the text, Ctrl+C to copy.
Close Developer
Open source/xyz.keyman-touch-layout, Ctrl+A to select all the text, Ctrl+V to paste in the code copied above. Save file.
Open Developer
Build tab, "Compile Keyboard" button, then "Test Keyboard on web" button and "Open debugger in local browser" button.
In browser, F12, F5 to switch to touch layout, click in the text box and keyboard appears, the 5-row keyboard with the schwa.

**Expected behavior**
Developer should actually write the touch layout to disk and use it!

---

**Keyman Developer:**
 - OS: Windows 10 20H2 x64
 - Keyman Developer version: 14.0.280.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5577.

This ensures that the touch layout file is marked as modified after running Import From Layout in Keyman Developer, so that changes are not lost when you save.

# User Testing

* TEST_SAVED: Verify that the file changes are saved

**Instructions:** (taken from #5577)

Start Keyman Developer (version 14.0.280.0), Project, New Project, Basic, OK
Keyboard Name: xyz, BCP 47 tag: qaz, OK
Keyboards, open xyz.kmn
Layout tab, set q to U+0259 (latin small letter schwa), set Q to U+018F (latin capital letter schwa)
(selecting "Code" shows:
```
+ [SHIFT K_Q] > 'Ə'
+ [K_Q] > 'ə'
```
in the .kmn file)
On-Screen tab, click "Auto-fill from underlying layout" box, then "Fill from layout button"
Touch Layout tab, shows "tablet" and "phone" layouts, each with four rows of keys and "default", "shift", "numeric" layers.
Select "phone" layout, then "Del" to delete phone layout, leaving only a tablet layout.
Click "Import from On Screen", get "You must save changes to your keyboard before import" message.  Click "Yes" to save.
There's now a tablet layout with five rows and two layers.
Ctrl+S to save.
Build tab, "Compile Keyboard" button, then "Test Keyboard on web" button and "Open debugger in local browser" button.
In browser, F12, F5 to switch to touch layout, click in the text box and keyboard appears, but it's the default 4-row keyboard without the schwa.
In Explorer, look at source/xyz.keyman-touch-layout. The file contains the 4-row keyboard (and "q" not schwa).

### CODE REVIEW

**Comment by MakaraSok** [comment]
- **TEST_SAVED: BLOCKED** Error occurs when trying to "Fill from layout" on "On-Screen" tab.

```
Could not load Core to import keyboard: System Error. Code: 126.
The specified module could not be found
```



Tested with Windows 10 Pro `20H2` and Keyman Developer of this build `15.0.110.0`.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
I've merged the fix from #5649 into this which should address that blocking issue.

@keymanapp-test-bot retest

**Comment by MakaraSok** [comment]
* **TEST_SAVED: PASSED** The OSK shown when `Test Keyboard on web` is consistent with the `xyzzy.keyman-touch-layout`.

Chrome emulator:


Touch layout code view"
```
{
  "tablet": {
    "displayUnderlying": false,
    "layer": [
      {
        "id": "default",
        "row": [
          {
            "id": "1",
            "key": [
              {
                "id": "K_1"
              },
              {
                "id": "K_2"
              },
              {
                "id": "K_3"
              },
              {
                "id": "K_4"
              },
              {
                "id": "K_5"
              },
              {
                "id": "K_6"
              },
              {
                "id": "K_7"
              },
              {
                "id": "K_8"
              },
              {
                "id": "K_9"
              },
              {
                "id": "K_0"
              },
              {
                "id": "K_HYPHEN"
              },
              {
                "id": "K_EQUAL"
              },
              {
                "width": "100",
                "id": "K_BKSP",
                "sp": "1",
                "text": "*BkSp*"
              }
            ]
          },
          {
            "id": "2",
            "key": [
              {
                "id": "K_Q",
                "pad": "75",
                "text": "\u0259"
              },
              {
                "id": "K_W"
              },
              {
                "id": "K_E"
              },
              {
                "id": "K_R"
              },
              {
                "id": "K_T"
              },
              {
                "id": "K_Y"
              },
              {
                "id": "K_U"
              },
              {
                "id": "K_I"
              },
              {
                "id": "K_O"
              },
              {
                "id": "K_P"
              },
              {
                "id": "K_LBRKT"
              },
              {
                "id": "K_RBRKT"
              },
              {
                "width": "10",
                "sp": "10"
              }
            ]
          },
          {
            "id": "3",
            "key": [
              {
                "id": "K_BKQUOTE"
              },
              {
                "id": "K_A"
              },
              {
                "id": "K_S"
              },
              {
                "id": "K_D"
              },
              {
                "id": "K_F"
              },
              {
                "id": "K_G"
              },
              {
                "id": "K_H"
              },
              {
                "id": "K_J"
              },
              {
                "id": "K_K"
              },
              {
                "id": "K_L"
              },
              {
                "id": "K_COLON"
              },
              {
                "id": "K_QUOTE"
              },
              {
                "id": "K_BKSLASH"
              }
            ]
          },
          {
            "id": "4",
            "key": [
              {
                "width": "160",
                "id": "K_SHIFT",
                "sp": "1",
                "text": "*Shift*"
              },
              {
                "id": "K_oE2"
              },
              {
                "id": "K_Z"
              },
              {
                "id": "K_X"
              },
              {
                "id": "K_C"
              },
              {
                "id": "K_V"
              },
              {
                "id": "K_B"
              },
              {
                "id": "K_N"
              },
              {
                "id": "K_M"
              },
              {
                "id": "K_COMMA"
              },
              {
                "id": "K_PERIOD"
              },
              {
                "id": "K_SLASH"
              },
              {
                "width": "10",
                "sp": "10"
              }
            ]
          },
          {
            "id": "5",
            "key": [
              {
                "width": "140",
                "id": "K_LOPT",
                "sp": "1",
                "text": "*Menu*"
              },
              {
                "width": "930",
                "id": "K_SPACE"
              },
              {
                "width": "145",
                "id": "K_ENTER",
                "sp": "1",
                "text": "*Enter*"
              }
            ]
          }
        ]
      },
      {
        "id": "shift",
        "row": [
          {
            "id": "1",
            "key": [
              {
                "id": "K_1"
              },
              {
                "id": "K_2"
              },
              {
                "id": "K_3"
              },
              {
                "id": "K_4"
              },
              {
                "id": "K_5"
              },
              {
                "id": "K_6"
              },
              {
                "id": "K_7"
              },
              {
                "id": "K_8"
              },
              {
                "id": "K_9"
              },
              {
                "id": "K_0"
              },
              {
                "id": "K_HYPHEN"
              },
              {
                "id": "K_EQUAL"
              },
              {
                "width": "100",
                "id": "K_BKSP",
                "sp": "1",
                "text": "*BkSp*"
              }
            ]
          },
          {
            "id": "2",
            "key": [
              {
                "id": "K_Q",
                "pad": "75",
                "text": "\u018F"
              },
              {
                "id": "K_W"
              },
              {
                "id": "K_E"
              },
              {
                "id": "K_R"
              },
              {
                "id": "K_T"
              },
              {
                "id": "K_Y"
              },
              {
                "id": "K_U"
              },
              {
                "id": "K_I"
              },
              {
                "id": "K_O"
              },
              {
                "id": "K_P"
              },
              {
                "id": "K_LBRKT"
              },
              {
                "id": "K_RBRKT"
              },
              {
                "width": "10",
                "sp": "10"
              }
            ]
          },
          {
            "id": "3",
            "key": [
              {
                "id": "K_BKQUOTE"
              },
              {
                "id": "K_A"
              },
              {
                "id": "K_S"
              },
              {
                "id": "K_D"
              },
              {
                "id": "K_F"
              },
              {
                "id": "K_G"
              },
              {
                "id": "K_H"
              },
              {
                "id": "K_J"
              },
              {
                "id": "K_K"
              },
              {
                "id": "K_L"
              },
              {
                "id": "K_COLON"
              },
              {
                "id": "K_QUOTE"
              },
              {
                "id": "K_BKSLASH"
              }
            ]
          },
          {
            "id": "4",
            "key": [
              {
                "width": "160",
                "id": "K_SHIFT",
                "sp": "1",
                "text": "*Shift*"
              },
              {
                "id": "K_oE2"
              },
              {
                "id": "K_Z"
              },
              {
                "id": "K_X"
              },
              {
                "id": "K_C"
              },
              {
                "id": "K_V"
              },
              {
                "id": "K_B"
              },
              {
                "id": "K_N"
              },
              {
                "id": "K_M"
              },
              {
                "id": "K_COMMA"
              },
              {
                "id": "K_PERIOD"
              },
              {
                "id": "K_SLASH"
              },
              {
                "width": "10",
                "sp": "10"
              }
            ]
          },
          {
            "id": "5",
            "key": [
              {
                "width": "140",
                "id": "K_LOPT",
                "sp": "1",
                "text": "*Menu*"
              },
              {
                "width": "930",
                "id": "K_SPACE"
              },
              {
                "width": "145",
                "id": "K_ENTER",
                "sp": "1",
                "text": "*Enter*"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.111-alpha](https://keyman.com/downloads/releases/alpha/15.0.111)

**Pull request merged**
