### PR TITLE
fix(web): get row-height for flick constraints after performing layout

### LINKED ISSUE #11650: bug(web): flicks occasionally become fully disabled
### Describe the bug

While I haven't yet noted any consistent patterns that would trigger the issue, during use of the system keyboard on iOS on my personal device, the keyboard has occasionally gone completely unresponsive to flicks.

When this triggers, multitap on shift (for caps) still works fine, as does longpress.  Even modipress is fine - just not flicks.  Any and all flicks, however, are completely ignored until the keyboard is swapped or reselected from the globe-key menu.  (Just re-selecting the active keyboard is enough.)  Longpress up-flick shortcutting does not appear to trigger in this state either - only the timer component seems operable then.  Layer-changing is not enough to trigger a reset - the keyboard itself must be reset.  (Layer changing itself still works, to be clear.)

After checking within Sentry for potentially-related error reports near the time of the observed error, nothing even closely related could be found.

### Reproduce the bug

No currently-known repro exists.  It generally happens when I start using flicks frequently in succession, I think?  But it triggers sporadically and randomly for me, and I haven't been able to narrow down a cause yet.  I usuallly reset, then re-attempt whatever I was doing whenever it triggers, but doing so has never retriggered the issue for me.

If and when #11229 goes through, I should be able to use webview-inspection to get more insight.

Also of note:  I don't recall ever having recently changed layers whenever it triggered.  The most recent instance had certainly been at least 7 keystrokes after the most recent layer change, if not considerably more.  (I wasn't exactly counting at the time.)  I had not recently used a modipress input, either.

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.321-beta, other previous versions.  Should also trigger on 17.0.326.

### Operating system

iOS

### Device

iPhone SE 2

### Target application

any

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11650.

It turns out that the underlying error for the observed flick-breakages is due to the current layer's row-height being `undefined`... because it's initialized immediately _after_ we try to access it, as part of `this.layerGroup.refreshLayout`:

A layer's `rowHeight` field is initialized only here: 

https://github.com/keymanapp/keyman/blob/b63acb156feb71bb5daee19041c53da766f38706/web/src/engine/osk/src/keyboard-layout/oskLayer.ts#L153-L165

It would appear that _most_ of the time, an extra call is triggered; that extra call would have the value initialized by the first call.

While it's extremely hard to reproduce, and I thus lack any specific test instructions to give...

## User Testing

TEST_GESTURES: Use Keyman for Android or Keyman for iOS with the default (EuroLatin) keyboard and verify that gestures work as expected.

### CODE REVIEW

**Comment by dinakaranr** [comment]
# Test Results
* **TEST_GESTURES (FAILED):** I tested this issue with the attached "Keyman 18.0.47-alpha-test-11691" build on an Android 13 and 14 (emulator and physical device) environment: Here is my observation.
 
I tested the gesture features, such as "long press,"  "flick," and "multitap". I can hold the key and select a letter from the submenu. Caplock is enabled after pressing the "shift" key multiple times. "Long press" and "Multitap" are working fine. Flick is working when you slide down the key. 
It does not work if you slide the finger in various directions on a key to reach alternate outputs. Please clarify this flick feature.

1. On Android: I am getting an error on the toast message bar when holding the shift key and moving to the right side.
2. Steps to reproduce:
3. Installed the "Keyman 18.0.47.apk" file and gave all permissions to the application.
4. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
5. Open the Keyman app.
6. Press the "123" button.
7. Press the "ELY(Shift) button.
8. Press the "?i-"(Shift) button and move to the right side.
9. Actual Results: Here, an error appeared on the toast message bar.
Note: This issue appears only on the Android app. 
Please refer to the attached video.
https://github.com/keymanapp/keyman/assets/19683059/fb4a2218-c900-418a-a950-a5466abb7200

**Comment by jahorton** [comment]
> * It does not work if you slide the finger in various directions on a key to reach alternate outputs. Please clarify this flick feature.

That's entirely correct - that keyboard only supports downward flicks.

> On Android: I am getting an error on the toast message bar when holding the shift key and moving to the right side.

That part is not expected.  I've found a matching Sentry report at https://keyman.sentry.io/issues/5047437108/events/0e48b4ca75bc4a7db05386982935d063/, which is unfortunately lumped in with a different set of events.

Fortunately, I'm able to get a reproduction of this pretty easily on my iPhone (when using Web inspection to see the logs).  It's unrelated, fortunately, and will be fairly simple to fix.

Accordingly,

TEST_GESTURES: PASS

**Comment by jahorton** [comment]
The reported error has been spun off to #11704.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.50-alpha](https://keyman.com/downloads/releases/alpha/18.0.50)

**Pull request merged**
