### PR TITLE
fix(mac): prevent duplicate keyboards in list

### LINKED ISSUE #4058: bug(mac): install the same keyboard with different methods give two of the same keyboard on the list
**Describe the bug**

Khmer Angkor keyboard was installed twice: (1) from the download in the configuration and (2) from the keyman.com website download.

The result of this is that two Khmer Angkor keyboards is found in the list of keyboard:
image

**Expected behavior**

Once an installation of an existing keyboard is installed, Keyman should notify that the keyboard being installed existing already.

---

**Keyman for macOS:**
 - OS: macOS Mojave
 - Keyman version: 14.0.195-alpha
 - Target Application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Additional context**

It is observed that the keyboard is listed only once in the Configuration:
image

### LINKED ISSUE #4528: bug(mac): the keyboard menu on the taskbar and the configuration are inconsistent
**Describe the bug**

Install an already-install keyboard would add the same keyboard to the keyboard menu on the taskbar, but not in the configuration itself.

**To Reproduce**

1. Go to 'Configuration'
2. Click on 'Download keyboard...'
3. Install a keyboard and then install it again
4. See error in the keyboard menu off of the taskbar

**Expected behavior**

The same keyboard should not be listed more than once on the keyboard menu.

**Screenshots**

image

---

**Keyman for macOS:**
 - OS: macOS Mohaje 10.14.4
 - Keyman version: 14.0.243-beta
 - Target Application: Keyman Configuration and the keyboard menu on the taskbar

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4058.
Fixes #4528.

Prevents duplicate keyboards from appearing in the list. If there are already duplicates in the list, they will be cleaned up the next time a keyboard is added or removed in Configuration.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.262-beta](https://keyman.com/downloads/releases/beta/14.0.262)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.264-beta](https://keyman.com/downloads/releases/beta/14.0.264)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)

**Pull request merged**
