### PR TITLE
chore(web): finalization for replacement of Karma with Web Test Runner 🏃

### LINKED ISSUE #10497: chore(web): karma is deprecated, find an alternative test runner
See also #10494

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10497.

Now that we've finished converting our browser-based testing engine from Karma to @web/test-runner, we can formally remove our old test-engine's dependencies entirely - an action with a notably large changeset of its own.

- [ ] Note that at this stage, we have not yet established BrowserStack configs as per https://github.com/keymanapp/keyman/pull/11404#issuecomment-2104007029 for nightly testing.
    - This might be made into a follow-up issue and will likely be a separate PR in one form or another.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by jahorton** [comment]
The latest build has a successfully-passing "Test: Language Modeling Layer (Common)" run, which includes new Web Test Runner tests.  The custom TC-oriented reporter appears to be working properly; its tests are showing up properly in the "Tests Passed" list.

**Comment by jahorton** [comment]
Re: Web - something fell over with the WebKit test run within `common/web/keyboard-processor`.  Will have to inspect that.

... I should consider taking the time to investigate ways to get better data about mysterious errors like this; we have our own custom TC reporter now, so surely we can get something more useful in this scenario... with a little effort.

**Comment by jahorton** [comment]
Ah, finally found out why I've been having trouble with certain tests against WebKit:

On our Linux BAs, the stability reporter was able to surface the following message:
```
09:00:15   ╔══════════════════════════════════════════════════════╗
09:00:15   ║ Host system is missing dependencies to run browsers. ║
09:00:15   ║ Missing libraries:                                   ║
09:00:15   ║     libevent-2.1.so.7                                ║
09:00:15   ║     libgstcodecparsers-1.0.so.0                      ║
09:00:15   ║     libflite.so.1                                    ║
09:00:15   ║     libflite_usenglish.so.1                          ║
09:00:15   ║     libflite_cmu_grapheme_lang.so.1                  ║
09:00:15   ║     libflite_cmu_grapheme_lex.so.1                   ║
09:00:15   ║     libflite_cmu_indic_lang.so.1                     ║
09:00:15   ║     libflite_cmu_indic_lex.so.1                      ║
09:00:15   ║     libflite_cmulex.so.1                             ║
09:00:15   ║     libflite_cmu_time_awb.so.1                       ║
09:00:15   ║     libflite_cmu_us_awb.so.1                         ║
09:00:15   ║     libflite_cmu_us_kal16.so.1                       ║
09:00:15   ║     libflite_cmu_us_kal.so.1                         ║
09:00:15   ║     libflite_cmu_us_rms.so.1                         ║
09:00:15   ║     libflite_cmu_us_slt.so.1                         ║
09:00:15   ║     libx264.so                                       ║
09:00:15   ╚══════════════════════════════════════════════════════╝
```

Which leads me back to something I'd been seeing, but never actually bothered with until now 'cause it "just worked" on Windows and Mac:  `npx playwright install-deps`

Looks like we do need that command on Linux BAs.

**Comment by mcdurdin** [comment]
> npx playwright install-deps

That should not be in a build script. Installing system-wide deps does not belong in a build script.

**Review by mcdurdin — APPROVED** [review]
LGTM. I didn't review every line of code in all the tests, but the PR chains looks good to me.

**Review by ermshiperete — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.42-alpha](https://keyman.com/downloads/releases/alpha/18.0.42)

**Pull request merged**
