### PR TITLE
fix(android): Propagate custom help links

### LINKED ISSUE #2390: [Android] Custom help link not always propagated
Found during investigation of 2386

The first time a keyboard .kmp package is installed, the custom help link (assuming it contains welcome.htm) is correctly assigned to the first language.

When installing other languages listed in kmp.json or reinstalling the keyboard, this custom help link doesn't get assigned.

Screenshot_20191128-104422
Screenshot should list a right arrow linking to the local welcome.htm file.

Tested with Keyman [12.0.4211](https://downloads.keyman.com/android/stable/12.0.4211/keyman-12.0.4211.apk) and [nrc_crk_cans 1.0.1](https://downloads.keyman.com/keyboards/nrc_crk_cans/1.0.1/nrc_crk_cans.kmp)

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2390 

When keyboards from a .kmp package are installed, the custom help link (welcome.htm) wasn't always propagated. It works on the initial keyboard installed, but not for the additional keyboards.

Changes:
1. Change the key to `ARG_CUSTOM_HELP_LINK`
2. Propagate existing help links in `createKeyboardInfoMap()`

### User Testing
1. Do a clean install
2. After the keyboard Cloud catalog downloads, install a kmp package that contains welcome.htm (e.g. [sil_cameroon_qwerty.kmp](https://downloads.keyman.com/keyboards/sil_cameroon_qwerty/6.0.1/sil_cameroon_qwerty.kmp). This installs Afade (Latin), the first listed language in the package.
3. From the "Settings" menu, add language for Aghem and install SIL Cameroon QWERTY.
4. From the "Settings" menu, add languagea from the cloud (e.g. Khmer --> Khmer Angkor)
5. From the globe keyboard picker, verify you can display help links ("i" on each keyboard) for:
  - [ ] Afade (Latin) - local welcome.htm file
  - [ ] Aghem - local welcome.htm file
  - [ ] Khmer - help.keyman.com/keyboards/khmer_angkor/1.0.6/

Note #2451, assets (images & css styling) aren't rendered when viewing the custom help file

### CODE REVIEW

**Comment by darcywong00** [comment]
@MakaraSok when you get back into the office for testing, here's the 
PR build [apk](https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/176195:id/release/kMAPro-debug.apk)

**Comment by MakaraSok** [comment]
@mcdurdin @darcywong00 

> 4. From the "Settings" menu, add languagea from the cloud (e.g. Khmer --> Khmer Angkor)

Keyman keeps crashing when trying to install a keyboard from the cloud.

> 5. From the globe keyboard picker, verify you can display help links ("i" on each keyboard) for:
> 
> * [x]  Afade (Latin) - local welcome.htm file
> * [x]  Aghem - local welcome.htm file

The help pages are viewable as expected.

> * [x]  Khmer - help.keyman.com/keyboards/khmer_angkor/1.0.6/

The keyboard was not able to be installed. Keyman crashes.

image

**Comment by darcywong00** [comment]
> The keyboard was not able to be installed. Keyman crashes.

@MakaraSok Can you provide details on the device you're using?
I loaded the apk in an emulator for Pixel 2 (Android API 28) and was able to download the Burmese / Burmese (burmese02) keyboard

**Comment by darcywong00** [comment]
> @MakaraSok Can you provide details on the device you're using?

In a PM, he said Android 6.0.1 on Nexus 5

**Comment by darcywong00** [comment]
@MakaraSok here's the latest PR [apk](https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/176694:id/release/kMAPro-debug.apk)

**Comment by MakaraSok** [comment]
@darcywong00 I still get error when trying to install a keyboard from the online library. Khmer Angkor was in the process of being downloaded, but then Keyman crashed. See the screenshot below.

image

**Comment by darcywong00** [comment]
I don't know why Khmer Angkor keeps crashing for you. But it installs fine for me on the emulator (same Android 6 on Nexus device).

And you got it working on an Abua keyboard. So I'll go ahead and merge this.

**Comment by mcdurdin** [comment]
@darcywong00 can you follow up with @MakaraSok on the crashing on his device?

**Pull request merged**
