### PR TITLE
chore(android): 🍒 Update Play publishing plugin to 3.5.0 and other plugins

### LINKED ISSUE #6334: chore(android): build warnings
```
[15:27:27][Step 5/6] getMappingFile(): Could not find method getMappingFileProvider() for arguments [] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
[15:27:27][Step 5/6] getMappingFile(): Could not find method getMappingFileProvider() for arguments [] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
[15:27:27][Step 5/6] WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
[15:27:27][Step 5/6] It will be removed at the end of 2019.
[15:27:27][Step 5/6] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[15:27:27][Step 5/6] To determine what is calling variantOutput.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
```

https://build.palaso.org/viewLog.html?buildId=309466&buildTypeId=KeymanAndroid_Build&tab=buildLog&_focus=1522

### PR DESCRIPTION
**Pull request by darcywong00**
🍒 -pick parts of #5098, #6217, #6223 to stable-14.0

* Gradle build tools to 4.2.1 (This update fixes #6334)
* Play publishing plugin to 3.5.0
* Junit to 1.1.2
* Robolectric to 4.5.1
* gradle-wrapper to 6.8

I also had to update the remal plugin version in order for the build to work.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by darcywong00** [comment]
Ugh, updating the Gradle plugin would mean 🍒 picking #5098 .

Maybe we can hold off on this unless the stable builds fail to publish?

**Comment by mcdurdin** [comment]
> Maybe we can hold off on this unless the stable builds fail to publish?

I think it's going to fail... given the issue is API changes on play.google.com, but sure we can wait. I don't have a problem merging that PR to stable-14.0; I re-reviewed it just now and it seems pretty clean.

**Comment by darcywong00** [comment]
I had to force-push the branch to revert the `package-lock.json` files that Lerna keeps "updating" :/

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.289](https://keyman.com/downloads/releases/stable/14.0.289)

**Pull request merged**
