### PR TITLE
fix(windows): Ensure UAC window comes to foreground

### LINKED ISSUE #3936: bug(windows): User Account Control does not always receive focus when installing a keyboard
**Describe the bug**
When installing a new keyboard, the User Account Control does not pop up for the user to take action; rather the dialogue box is blinking in the taskbar while showing "Installing Keyboard" (See screenshot01). This might be confusing for the new users as they would be sitting and waiting for the installation to finish without knowing Keyman is requesting permission (See screenshot02).

Screenshot01
image

Screenshot02
image

**Expected behavior**
The User Account Control should be in focus or shown to the user so that they can take action accordingly.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 20H2, build 19042.630
 - Keyman version:  14.0.187-alpha
 - Target Application: [self]

---

**Additional Context:**
The current stable version does exactly what is expected.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3936.

This is a trial change as I am not able to reproduce the problem on my machine, probably due to timing.

@makarasok, can you please test if this resolves the UAC window not coming to foreground on your test scenario for #3936?

### CODE REVIEW

**Comment by MakaraSok** [comment]
This fix does make the UAC window comes to the foreground of the desktop. Test was done on a VM running Windows 10 Pro 20H2.

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.235-beta](https://keyman.com/downloads/releases/beta/14.0.235)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
