### PR TITLE
fix(ios): fv: replace Zip framework to prevent crash on startup 🏠

### LINKED ISSUE #9819: bug(ios): FV Keyboards stable-16.0.142 app crashes on launch
Per Apple review, the stable-16.0.142 build of FV Keyboards app crashed on launch. There are no code changes from 16.0.141. Is it possible this is due to an XCode upgrade since we last built the stable release?

According to the attached reports, the Zip.framework dependency is missing:

```
"Library not loaded: @rpath\/Zip.framework\/Zip",
"Referenced from: <72FF9EF0-6AC4-37C9-AC53-394B27DF552E> \/Volumes\/VOLUME\/*\/FirstVoices.app\/Frameworks\/KeymanEngine.framework\/KeymanEngine",
"Reason: tried: 
'\/usr\/lib\/swift\/Zip.framework\/Zip' (no such file, not in dyld cache), 
'\/private\/preboot\/Cryptexes\/OS\/usr\/lib\/swift\/Zip.framework\/Zip' (no such file), 
'\/private\/var\/containers\/Bundle\/Application\/ECC845CE-BA49-4217-9DFD-1605188C26DA\/FirstVoices.app\/Frameworks\/Zip.framework\/Zip' (no such file), 
'\/private\/var\/containers\/Bundle\/Application\/ECC845CE-BA49-4217-9DFD-1605188C26DA\/FirstVoices.app\/Frameworks\/KeymanEngine.framework\/Frameworks\/Zip.framework\/Zip' (no such file), 
'\/private\/var\/containers\/Bundle\/Application\/Frameworks\/Zip.framework\/Zip' (no such file), 
'\/usr\/lib\/swift\/Zip.framework\/Zip' (no such file, not in dyld cache), 
'\/private\/preboot\/Cryptexes\/OS\/usr\/lib\/swift\/Zip.framework\/Zip' (no such file), 
'\/private\/var\/containers\/Bundle\/Application\/ECC845"
```

---

Guideline 2.1 - Performance - App Completeness

We were unable to review your app as it crashed on launch. We have attached detailed crash logs to help troubleshoot this issue.

Review device details: 

- Device type: iPad 
- OS version: iOS 17.0.3

Next Steps

To address the crash in your app, follow these steps:

1. Fully symbolicate the crash report. See [Adding Identifiable Symbol Names to a Crash Report](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/adding_identifiable_symbol_names_to_a_crash_report) for an explanation of the symbolication process.
2. Match the crash report to a common pattern. Based on the pattern, take specific actions to further investigate the crash. See [Identifying the Cause of Common Crashes](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/identifying_the_cause_of_common_crashes).
3. Test your app on a device to ensure that it now runs as expected.
4. Once you’ve addressed the crash, create and submit a new build to the App Store for review.

Resources

For additional information on crash reports, see [Diagnosing Issues Using Crash Reports and Device Logs](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs).

---

* [crashlog-905474A5-F733-4C77-A738-EC2016ED4285.txt](https://github.com/keymanapp/keyman/files/13058736/crashlog-905474A5-F733-4C77-A738-EC2016ED4285.txt)
* [crashlog-DD07E783-BEA5-42B4-B789-109E00E5E802.txt](https://github.com/keymanapp/keyman/files/13058738/crashlog-DD07E783-BEA5-42B4-B789-109E00E5E802.txt)
* [crashlog-7F62B778-16EC-4387-B17C-B5249CFC8852.txt](https://github.com/keymanapp/keyman/files/13058739/crashlog-7F62B778-16EC-4387-B17C-B5249CFC8852.txt)
* [crashlog-848F31F5-3C41-4B5F-B01D-779AFD184247.txt](https://github.com/keymanapp/keyman/files/13058740/crashlog-848F31F5-3C41-4B5F-B01D-779AFD184247.txt)

### PR DESCRIPTION
**Pull request by sgschantz**
Replacing marmelroy/Zip framework with weichsel/ZIPFoundation due to problems with using the [Zip framework and Carthage](https://github.com/marmelroy/Zip/issues/70). Attempts to use Zip framework were unsuccessful in #9942 

Fixes #9819  

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
From standup - we'll need to
* thoroughly test the unzipping
* notify consumers of Keyman Engine for iOS (KAB, FV, etc)

**Review by mcdurdin — APPROVED** [review]
RSLGTM

Can you add "Cherry-pick of #xxxx" where xxxx is the PR on master to the initial comment?

**Comment by sgschantz** [comment]
> RSLGTM
> 
> Can you add "Cherry-pick of #xxxx" where xxxx is the PR on master to the initial comment?

I could but I was calling #10018 a cherry-pick of this PR. I wrote this one first, but I moved it to 17 to gain testing via TestFlight. Should I add to the comment that this is cherry-picked by #10018? I'm figuring that they cannot be cherry-picking each other...

**Comment by mcdurdin** [comment]
> I'm figuring that they cannot be cherry-picking each other...

Oh I see, carry on then as you were :grin:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.143](https://keyman.com/downloads/releases/stable/16.0.143)

**Pull request merged**
