### PR TITLE
change(web): merges split async method in gesture engine 🪠

### PR DESCRIPTION
**Pull request by jahorton**
This PR merges a split `async` method within the gesture engine, hopefully improving gesture performance a small bit.

By reducing the impact of the JS `async` keyword (and related TS helpers) slightly - paying the cost once, not twice, we can shave off several milliseconds over time when receiving touch events.  (In a 10s profile on an older Android device, I noted approximately 12ms spent on the declaration line of _each_ of the two `async` methods being merged here.)
- Reference: https://madelinemiller.dev/blog/javascript-promise-overhead/
- Downcompiling to ES6 does result in our code using some `tslib` helpers for full `async` support, and that _does_ contribute some overhead - I see its helper functions show up during code profiles, too.

Also, I believe merging the methods helps to make the affected class's implementation clearer.  Were it not for this point, I'd probably not bother, as ~10ms out of 10s is only a 1% improvement - rather negligible in the grand scheme of things.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
I guess LGTM? It seems marginal benefit but the refactor looks okay

**Comment by jahorton** [comment]
Given the request to rework #11140 by splitting it, and the fact that this change is pretty much "ready to go" as is, it no longer makes sense to base this PR upon #11140.  The changes are orthogonal and safe to move up in this fashion, so I've rebased accordingly.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.305-beta](https://keyman.com/downloads/releases/beta/17.0.305)

**Comment by mcdurdin** [comment]
@jahorton this alert [^^^](https://github.com/keymanapp/keyman/pull/11142#issuecomment-2053687225) from @sentry-io is on a merge PR so not sure if you saw it?

**Comment by jahorton** [comment]
I didn't, but that's a report matching #11165, which was already fixed with #11178.

**Pull request merged**
