### PR TITLE
fix(common): declare dep on @keymanapp/ldml-keyboard-constants 🏠

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes: #12470

@keymanapp-test-bot skip

### CODE REVIEW

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
@mcdurdin does this need a release note? it's kind of an 'its not broken anymore' fix.

**Comment by mcdurdin** [comment]
No release note needed for alpha -- it is expected to be broken. We still have the history.md with every PR

**Comment by mcdurdin** [comment]
Yeah, it will get a release note when we push the 17.0.331-stable release button (which will be a week away because I am afk until then)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.331](https://keyman.com/downloads/releases/stable/17.0.331)

**Pull request merged**
