### PR TITLE
fix(common/core): incxstr checks all character while incrementing

### LINKED ISSUE #4604: bug(windows): incxstr needs extra robustness for malformed strings
**Describe the bug**
In the incxstr function, there are a number of places where we don't check a character but jump over it, assuming it is valid (`p += 2` kinda thing). We need to check every character as we increment so we don't miss a U+0000 end of string with malformed data. 

Discovered while working on #4596.

---

**Keyman for Windows/macOS/Linux:**
 - Keyman version: 14.0.252-beta

### PR DESCRIPTION
**Pull request by SabineSIL**
Fixes #4604.

In a string some characters after UC_SENTINEL (FFFF) had not been checked while incrementing due to a p+=2 movement of the pointer. If a \0 had been located between UC_SENTINEL (FFFF)  and another control character the \0 han not been detected in some cases which then resulted in a buffer overrun,

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by mcdurdin** [comment]
Thank you for this PR! Would you be able to include the unit test that you wrote as well please?

**Comment by mcdurdin** [comment]
@keymanapp-test-bot skip 

I don't think we need user testing for this -- unit tests more appropriate.

**Comment by mcdurdin** [comment]
Replaced by #5712

**Pull request closed without merging**
