### PR TITLE
fix(ios): iOS 13 and 14 only - stuck settings toggles

### PR DESCRIPTION
**Pull request by jahorton**
Fixes one issue noted on #5547.

Apparently there's a new setting (enabled by default) on the type of UI structures we've been using for the Settings UI, and that setting caused the affected list items' interactivity to override interaction attempts with their contained toggles.

That's all an inference from https://developer.apple.com/forums/thread/660915, admittedly.  But, adding that line does do the trick (for once).

Tested in Simulator 14.4 and 13.5.

## User Testing

@keymanapp/testers 

Platforms:
- [ ] iOS / Simulator / 13.x device runtime
- [ ] iOS / Simulator / 14.x device runtime

If you don't already have two separate runtimes set up for your computer's Simulator...

image

Then click the '+' at the bottom left of the screen seen here (in the background):

image

That presents the "Create a new simulator" popup seen in that screenshot.

From there, the tests:
Confirm that the toggles work correctly for the following menus and that they have their intended effects: 
- [ ] TEST_SETTINGS: "Settings"
- [ ] TEST_LANGUAGE_SETTINGS: "English Settings" (under Installed Languages)

### CODE REVIEW

**Comment by mcdurdin** [comment]
I guess this will need a cherry pick as well

**Comment by jahorton** [comment]
> I guess this will need a cherry pick as well

Oh, of course.  It'll be a very easy 🍒, at least.

**Comment by jahorton** [comment]
Should I formalize those comments as an actual test suite, or are we fine letting it go without?

**Comment by mcdurdin** [comment]
> Should I formalize those comments as an actual test suite, or are we fine letting it go without?

I think @MakaraSok should definitely test this given he picked up the error in the first place.

**Review by mcdurdin — APPROVED** [review]

**Comment by MakaraSok** [comment]
Downloading a 3.37GB of a simulator component on a mobile hotspot is not considerably slow even though the measured internet download speed is at 35 mbps. The test result will come out as soon as the configuration of the simulator is done. Leaving it downloading for now...

**Comment by MakaraSok** [comment]
Do I have to have an Xcode account?

After a long while of waiting, this appears:
image

**Comment by jahorton** [comment]
Huh... sounds like that may be a requirement.  Didn't anticipate this issue.

**Comment by MakaraSok** [comment]
## User Testing

@keymanapp/testers 

Platforms:
- [ ] iOS / Simulator / 13.x device runtime [haven't successfully installed this yet]

From there, the tests:
Confirm that the toggles work correctly for the following menus and that they have their intended effects: 
- [ ] TEST_SETTINGS: "Settings"
- [ ] TEST_LANGUAGE_SETTINGS: "English Settings" (under Installed Languages)

---

Platforms:
- [x] iOS / Simulator / 14.x device runtime

From there, the tests:
Confirm that the toggles work correctly for the following menus and that they have their intended effects: 
- [x] TEST_SETTINGS: "Settings"
- [x] TEST_LANGUAGE_SETTINGS: "English Settings" (under Installed Languages)

**Comment by jahorton** [comment]
Glad it confirms the fix part, at least.  Just wish you could also test that it doesn't adversely affect 13.0.

**Comment by MakaraSok** [comment]
I need help on getting the simulator for 13.x installed on my machine.

**Comment by jahorton** [comment]
> I need help on getting the simulator for 13.x installed on my machine.

There's a very strong chance this isn't a simple matter; it'll take time to resolve unless someone who already has an Apple Developer account (so... probably Marc) runs that test in your stead.  There's licensing and organizational permissions stuff required.

**Comment by MakaraSok** [comment]
A p p l e . . .

**Comment by mcdurdin** [comment]
> After a long while of waiting, this appears:

Can you click the [Details] button to get the full reason for the failure?

**Comment by jahorton** [comment]
> > After a long while of waiting, this appears:
> 
> Can you click the [Details] button to get the full reason for the failure?

I mean, he could... but I think we already have the full reason in that screenshot.  You and I have an Apple Developer account; he doesn't.

**Comment by mcdurdin** [comment]
> I mean, he could... but I think we already have the full reason in that screenshot. You and I have an Apple Developer account; he doesn't.

In my research, I found reports that the generic error message shown was not actually the real reason for the problem, and the Details gave helpful additional information. Also, nothing to suggest that there were blocks on downloading the simulator images. So wanted to isolate that, given he already does have Apple Developer access in a number of areas already.

**Comment by jahorton** [comment]
> (One suggestion was that network errors could cause this message to appear, if a download glitched half way, which does sound like it matches the symptoms he experienced pretty well -- a very long delay and then the error message).

... this makes too much sense.  I've definitely had pains like _that_ before with similar downloads from Apple.  While I don't recall ever seeing that message, that certainly doesn't preclude it from being a possibility.  Good point.

**Comment by jahorton** [comment]
So... what should be done for now?  Are we fine letting this merge as is, not having been able to test on an older iOS version?

**Comment by mcdurdin** [comment]
> So... what should be done for now? Are we fine letting this merge as is, not having been able to test on an older iOS version?

@MakaraSok and I are planning to try and resolve the older simulator download problems today. So give it another few days.

**Comment by jahorton** [comment]
Just did a `master` merge so that a simulator artifact will be available for testing this time; that PR happened after this one was originally made.

**Comment by MakaraSok** [comment]
Thank you for waiting. Please check the test results above.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.98-alpha](https://keyman.com/downloads/releases/alpha/15.0.98)

**Pull request merged**
