### PR TITLE
fix(android/engine): Fix sticky long-press keys

### LINKED ISSUE #6636: bug(android/engine): Longpress pop-ups appear uninvited and persist
Follow-on to #5301 

@katelem24 reports on the community site https://community.software.sil.org/t/keyman-15-beta-feedback/5755/29
> Once in a while longpress pop-ups appear when one has not long-pressed the key, and will not go away except you press another key or switch layer. Sometimes they block the way to required keys, and moving the insertion point will not remove the pop-ups.

more screenshots on the community site...

## Configuration
Apps Used:
Google Keep, Google Chrome, Google Notebook, Word Web dictionary.

Keyman Version:
15.0.225 and 15.0.228

Platform:
Android, 8.1

Device:
Tecno POP 2

----------------

On investigation, it seems the GestureDetector isn't always getting the final ACTION_UP which dismisses all the popups.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #6636

The logic to clear popup keys depends on GestureDetector triggering `MotionEvent.ACTION_UP`. This PR pulls the handling out of the if/else because sometimes, the `ACTION_UP` event goes through the if() block.

https://github.com/keymanapp/keyman/blob/1747722ebdd264587a876b73a2c253801ef0fdcc/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java#L285-L289

## User Testing
Setup - A physical Android device. Don't use emulator because the scenario involves typing fast on the OSK (e.g. two thumbs)

* **TEST_BETA_STICKY_KEYS** - Verify beta build can have long-press keys stuck
1. On the Android device, install 15.0.249 beta of Keyman for Android
https://downloads.keyman.com/android/beta/15.0.249/keyman-15.0.249.apk
2. Dismiss the "Get Started" menu 
3. In the Keyman app, quickly type with the default sil_euro_latin keyboard on the OSK.
4. After typing a long paragraph, observe if a long-press keys become stuck (displayed while not holding down on a key)
5. Verify at some point, the long-press key is stuck. If you see this bug, this test is PASS
6. Uninstall the beta build of Keyman for Android.  

* **TEST_POPUPS** - Verify popup keys don't get stuck on
1. On the Android device, install the PR build of Keyman for Android 
2. Dismiss the "Get Started" menu
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Type on the OSK using the following scenarios and verify expected output:
    * Clicking a suggestion on the suggestion banner - should insert the suggestion
    * short-press a key and release - should insert the base key
    * long-press a key, select a long-press key, and release - should insert the long-press key
    * long-press a key, while keeping the finger down, move off the long-press options, and release - should **not** output
    * long-press a key, while keeping the finger down, move off the long-press options, then move back on a long-press option so it's highlighted, and release - should output the long-press key
    * quickly type a long paragraph (e.g. repeat the word "reply") - verify long-press keys don't get stuck (displayed when not touching a key)

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_BETA_STICKY_KEYS (PASSED):** Tested this in my Android Mobile device (Version 11) with the Keyman 15.0.249 beta build as per the instructions and it seems that the long press keys did not get stuck after typing a long paragraph. Seems to be working fine.

**Comment by bharanidharanj** [comment]
* **TEST_POPUPS (PASSED):** Tested this in my Android Mobile (Version 11) with Keyman 15.0.250-beta build, as per the instructions and it seems to be working fine in all conditions.

**Comment by darcywong00** [comment]
> Tested this in my Android Mobile device (Version 11) with the Keyman 15.0.249 beta build as per the instructions and it seems that the long press keys did not get stuck after typing a long paragraph. Seems to be working fine.

TEST_BETA_STICKY_KEYS should have shown a long-press key getting stuck. Like quickly typing <kbd>y</kbd> multiple times and release sometimes results in the long-press keys being displayed.

@keymanapp-test-bot retest TEST_BETA_STICKY_KEYS

**Review by mcdurdin — APPROVED** [review]
LGTM. Nice clean update.

**Comment by bharanidharanj** [comment]
* **TEST_BETA_STICKY_KEYS (FAILED):** Oops! Yes, Darcy! Retested this with Keyman 15.0.249-beta build in my Android Mobile device and this time I was able to see the clicking on any long-press key getting stuck and it displayed for a while.

Long Press Key Problem:

**Comment by darcywong00** [comment]
@bharanidharanj - TEST_BETA_STICKY_KEYS is expecting the long-press key to be stuck (a bug), but the test itself should PASS if you see the bug. I'll edit the step to expect that.

@keymanapp-test-bot retest TEST_BETA_STICKY_KEYS

**Comment by bharanidharanj** [comment]
> @bharanidharanj - TEST_BETA_STICKY_KEYS is expecting the long-press key to be stuck (a bug), but the test itself should PASS if you see the bug. I'll edit the step to expect that.
> 
> @keymanapp-test-bot retest TEST_BETA_STICKY_KEYS

@darcywong00 Okay, Thanks for the Clarification.

**Comment by bharanidharanj** [comment]
* **TEST_BETA_STICKY_KEYS (PASSED):** Tested this as per the instructions and I was able to reproduce this bug in the Android Mobile device (as it mentioned in the User Testing steps).

**Pull request merged**
