### PR TITLE
feat(linux): Add column for installation location

### LINKED ISSUE #8631: feat(linux): Add column for area where keyboards are installed.
(From https://github.com/keymanapp/keyman/issues/8619#issuecomment-1513325138)

Add another column that shows the area where a keyboard is installed: user/shared/system. Maybe only show or fill the column if we have keyboards from more than one area.

Currently it is confusing if you have the same keyboard multiple times:

image

### PR DESCRIPTION
**Pull request by ermshiperete**
Closes #8631.

## km-config with new Location column

image

## Previous version

image

# User Testing

## Preparations

- The tests can be run on any Linux version

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot
- Install EuroLatin (SIL) keyboard for German into the user area: 
  ```
  km-package-install --package sil_euro_latin --bcp47 de
  ```
- Install EuroLatin (SIL) keyboard for French into the shared area: 
  ```
  sudo km-package-install --shared --package sil_euro_latin --bcp47 fr
  ```
- Verify that both German and French show up in the keyboard dropdown in the top bar. Otherwise reboot.

## Tests

**TEST_LOCATION_COLUMN**: New column exists and shows expected values

- open Keyman Configuration
- verify that EuroLatin (SIL) shows up twice. In the Location column one of these rows should have the value `~/.local/share/keyman`, the other `/usr/local/share/keyman`

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
The location column is quite noisy -- if it can only have those two values in it, then should the UI show a more friendly name? Would be fine for the command line tool to show more detail. In theory a tooltip could show the actual path?

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_LOCATION_COLUMN (PASSED):** Tested with the attached PR build (17.0.114-1~PR-8897+focal2) in Wasta 20.04 Linux OS (VM) and here is my observation: 1. After running the above two commands in the terminal window, I was able to see the installed German and French keyboards in the taskbar. 2. Able to see the Eurolatin(SIL) folder appears in the above mentioned location. 

..Eurolatin in Keyman Configuration dialog

   


..Eurolatin in Path1

   


..Eurolatin in Path2

**Comment by ermshiperete** [comment]
> The location column is quite noisy -- if it can only have those two values in it, then should the UI show a more friendly name? Would be fine for the command line tool to show more detail. In theory a tooltip could show the actual path?

Renamed the column to "Area" and now show only "User/Shared/System". The tooltip on the row shows the actual keyboard path:

image

**Comment by mcdurdin** [comment]
> Renamed the column to "Area" and now show only "User/Shared/System". The tooltip on the row shows the actual keyboard path:

Excellent!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.116-alpha](https://keyman.com/downloads/releases/alpha/17.0.116)

**Pull request merged**
