### PR TITLE
chore(resources):  update CLDR to post-PRI 🙀 

### PR DESCRIPTION
**Pull request by srl295**
- needed for #8717 

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
merged in #9483 so that tests pass…

**Review by mcdurdin — APPROVED** [review]
RSLGTM

**Comment by srl295** [comment]
> RSLGTM

If all tests ran

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.162-alpha](https://keyman.com/downloads/releases/alpha/17.0.162)

**Pull request merged**
