### PR TITLE
fix(windows): setup should ignore cert revocation

### LINKED ISSUE #4385: bug(windows): Keyman Setup could not connect to keyman.com to download additional resources
**Describe the bug**

Downloading the latest beta version (14.0.232) or using an older beta version, and then install them to see the following error. Verify that the internet connect is working while browsing.

image

**Expected behavior**

The installation should get through without any error. 

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.232-beta or older
 - Target Application: self

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4385.

Chrome has ignored certificate revocation for many years. If it's good enough for Chrome, it's good enough for us. Right?

More seriously, sometimes Windows has trouble with its certificate revocation cache, and it seems to be difficult to predict when this will happen. This results in error 12057.

https://knowledge.broadcom.com/external/article/169185/ssl-visibility-how-to-resolve-the-certi.html
https://www.imperialviolet.org/2012/02/05/crlsets.html

### CODE REVIEW

**Comment by mcdurdin** [comment]
@MakaraSok can you 

1. Turn on the internet option "Check for server certificate revocation" again
2. Restart
3. Test build 14.0.233 of Keyman Setup to verify that it is still failing with that build
4. Finally, check the test version artifact for this pull request to see if it succeeds?

image

**Comment by MakaraSok** [comment]
> 1. Turn on the internet option "Check for server certificate revocation" again
> 2. Restart
> 3. Test build 14.0.233 of Keyman Setup to verify that it is still failing with that build

Strangely enough, the error does not occur with "Check for server certificate revocation" checked. :/

> 4. Finally, check the test version artifact for this pull request to see if it succeeds?

And the same goes for this.

**Comment by mcdurdin** [comment]
> Strangely enough, the error does not occur with "Check for server certificate revocation" checked. :/

If we can't replicate the problem, never mind. The change clearly continues to work 😁

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
@mcdurdin I've just got to test this on Windows 10 Pro 20H2 x32 and the error message appears after clicking to install Keyman 14.0.233-beta. With the setting checked, this build does get through with flying color. So, as you said this is still worth doing.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.235-beta](https://keyman.com/downloads/releases/beta/14.0.235)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
