### PR TITLE
chore(windows): Remove old Kannada setup strings 🍒

### PR DESCRIPTION
**Pull request by darcywong00**
Follow-on to #8189 and 🍒 pick of #8257 to stable-16.0 

The Keyman for Windows Setup listed Kannada twice because the old `kn-IN/strings.xml` file was still around.

## User Testing

* **TEST_WINDOWS_SETUP_KANNADA** - Verifies Kannada listed once in Setup
1. Launch the PR build of Keyman for Windows
2. On the Setup screen, click the language list
3. Verify Kannada "ಕನ್ನಡ" is listed once

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by darcywong00** [comment]
@bharanidharanj - this is testing the UI languages available from the installer (Before Keyman for Windows is installed) and not the list from Keyman Configuration.  Could you please retest with the installer?

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
> @bharanidharanj - this is testing the UI languages available from the installer (Before Keyman for Windows is installed) and not the list from Keyman Configuration. Could you please retest with the installer?
> 
> @keymanapp-test-bot retest

@darcywong00 Oops, Sorry ..Darcy! Okay, I will retest it. Thanks.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_WINDOWS_SETUP_KANNADA (PASSED):** Retested with the attached PR build and I was able to see the Kannada UI name appears in the UI language list.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.139](https://keyman.com/downloads/releases/stable/16.0.139)

**Pull request merged**
