### PR TITLE
fix(web): prevents auto-accept immediately after reversion

### PR DESCRIPTION
**Pull request by jahorton**
Addresses part of https://github.com/keymanapp/keyman/issues/11963. 

In particular, this change ensures that auto-correct doesn't immediately undo reversions immediately after applying them.  Suppose a name is typed that's not in the dictionary.  (I ran into this personally when typing "Esther" and trying to get "Esther" to actually 'stick'.)  The idea:
- Reverting restores the original text, as it was.
- If I'm undoing an auto-correct, the original text may well have been correct.
- If I tap space right after a reversion, I likely mean for the reverted text to be preserved, rather than re-corrected.  
    - I didn't want whatever suggestion was applied, so we should be way less aggressive about auto-applying one.
- On the other hand, if I make edits to the text before pressing space, auto-correct might be reasonable again.

Note that the logic doesn't actually check that we're reverting an auto-correct.  That would take additional work.

## User Testing

**TEST_GENERAL_PREDICTIONS**:  Test that standard predictive-text operations work as expected.

**TEST_WITHOUT_SELECTION**:   Using Keyman for Android, the EuroLatin (SIL) keyboard, and the MTNT English model, verify that a context-preserving suggestion is not presented unnecessarily.

1. Type `corr`.
2. Verify that multiple suggestions starting with `corr` appear.
3. Verify that no `"corr"` suggestion appears.
4. Type `ect` - resulting in `correct`.
5. Verify that multiple suggestions starting with `correct` appear.
6. Verify that `correct` is auto-selected.
7. Verify that no `"correct"` suggestion appears.  (Specifically, that no such suggestion _with visible quotes_ appears.)
8. Type `l` - resulting in `correctl`.
9. Verify that `"correctl"` appears as a suggestion.
10. Verify that `correctly` is auto-selected.

**TEST_PRESERVE_AMONG_MANY**:  Using Keyman for Android, the EuroLatin (SIL) keyboard, and the MTNT English model, verify that a context-preserving suggestion is presented that operates properly.

1. Type `Esthe`.
    - A non-selected suggestion `"Esthe"` should be presented
    - The suggestion `Either` should be auto-selected.
2. Apply the `"Esthe"` suggestion.
    - The context should be preserved, with space added after it.
3. Type `Esthe` again.
4. This time, press the spacebar.
    - `Esthe` should be replaced with `Either `.

**TEST_PRESERVE_AMONG_ONE**:  Using Keyman for Android, the EuroLatin (SIL) keyboard, and the MTNT English model, verify that a context-preserving suggestion is presented that operates properly.

1. Type `zoologists`.
    - A non-selected suggestion `"zoologists"` should be presented
    - The suggestion 'apologists` should be auto-selected.
    - There should be no other suggestions on display.
    - If `apologists` appears but is not auto-selected, FAIL this test.
    - If it does not appear at all, retry this step.
2. Apply the `zoologists` suggestion.
    - The context should be preserved, with space added after it.

**TEST_REVERSION_BEHAVIOR**: Verify that applying a reversion never results in an automatically-selected suggestion.

1. Using the EuroLatin (SIL) keyboard and the MTNT model...
2. Type `Esther`.
3. Verify that `either` is auto-selected.
4. Press space, automatically accepting `either`.
5. Press backspace once.
6. Select `"Esther"`.
7. Verify that none of the presented suggestions are auto-selected.
8. Press space once and verify that `Esther` remains in the context.
9. Verify that no `"Esther"` suggestion is presented.

### CODE REVIEW

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "Keyman 18.0.71-alpha-test-11970" build on the Android 14(emulator & physical devices) environment: Here is my observation.

* **TEST_GENERAL_PREDICTIONS (Passed):** 
1. Installed the "Keyman-18.0.71.apk" file and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app. Enable the "Predictions" and install the "Dictionary"
4. Enter some sentences in the text area.
5. Verified that the predictive text appears on the banner.
6. Verified that the predictive text was highlighted on a banner. 
7. Verified that the space appears after selecting a word. 

* **TEST_WITHOUT_SELECTION (Passed):**
1. I have followed the steps provided under the "TEST_WITHOUT_SELECTION".
2. I verified suggestion works well on a banner.
Hence, the "correctly" word appears and works as per the steps. 

* **TEST_PRESERVE_AMONG_MANY (Passed):**
1. I have followed the steps that are provided under the "TEST_PRESERVE_AMONG_MANY".
2. I verified suggestion works well on a banner.
3. Hence, the "Esthe" word appears and works as per the steps. 
4. Space appears after selecting an "Esthe" suggestion.
5. "Esthe" should be replaced with "Either".

* **TEST_PRESERVE_AMONG_ONE (Passed):**
1. I have followed the steps that are provided under the "TEST_PRESERVE_AMONG_ONE".
2. I verified suggestion works well on the banner.
3. Hence, the "apologists" word was auto-highlighted on the banner after entering "zoologists" 
4. The "zoologists" suggestion was selected from the banner and then space appeared.

* **TEST_REVERSION_BEHAVIOR (Passed):**
1. I have followed the steps that are provided under "TEST_REVERSION_BEHAVIOR".
2. I verified suggestion works well on a banner.
3. "either" is auto-highlighted. If pressing the "Spacebar" then automatically select which word is highlighted.
Above mentioned scenarios work well in the "Keyman 18.0.71-alpha-test-11970" build.

**Comment by mcdurdin** [comment]
> The idea:
> 
> * Reverting restores the original text, as it was.
> * If I'm undoing an auto-correct, the original text may well have been correct.
> * If I tap space right after a reversion, I likely mean for the reverted text to be preserved, rather than re-corrected.
>   
>   * I didn't want whatever suggestion was applied, so we should be way less aggressive about auto-applying one.
> * On the other hand, if I make edits to the text before pressing space, auto-correct might be reasonable again.

This sounds good to me.

**Review by mcdurdin — APPROVED** [review]
LGTM. I look forward to testing auto-accept soon on my phone!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.73-alpha](https://keyman.com/downloads/releases/alpha/18.0.73)

**Pull request merged**
