### PR TITLE
fix(developer): support named character codes at end of line

### PR DESCRIPTION
**Pull request by mcdurdin**
If a named character code was followed by a `\n`, it would not be recognised.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Regression in #4547

**Comment by darcywong00** [comment]
#4547 also used `iswblank` in NamedCodeConstants.cpp 
Are those also affected?

**Comment by mcdurdin** [comment]
> Are those also affected?

No it's okay -- we treat `\n` as a token so it is removed from the string before it reaches the `AddCode_IncludedCodes` function.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.263-beta](https://keyman.com/downloads/releases/beta/14.0.263)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)

**Pull request merged**
