### PR TITLE
fix(web): pre-init keyboard activation awaits init before proceeding

### LINKED ISSUE #11504: bug(ios): keyboard activation attempted too early during host-page load
Sentry Issue: [KEYMAN-WEB-K0](https://keyman.sentry.io/issues/5272291189/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'this.keyboardCache.defaultStub')
  at ContextManager.getFallbackStubKey (@keymanapp/keyman/web/src/app/webview/src/contextManager.ts:154:17)
  at <anonymous> (@keymanapp/keyman/web/src/app/webview/src/contextManager.ts:169:34)
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11504.

@keymanapp-test-bot skip

We don't have a consistent repro here, but it's quite clear to me that the issue is triggered due to the lack of this guard.  There's nothing in the iOS engine's `ios-host.js` that would prevent calling `setKeymanLanguage` before the page's `load` event is fired.  (The implication:  we're dealing with a race condition.)  I'm confident this is enough to fix the issue.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
This will need to be cherry-picked to stable-17.0

**Comment by jahorton** [comment]
Huh... while the test configuration seemed to be fine before merging all the web-test-runner stuff through to `master`, it seems the test scoping isn't working correctly now that it's actually on `master`, based on the Web test-run failure.  I'm investigating that now.

**Comment by jahorton** [comment]
The issue noted in the previous comment will be addressed by #11509.

**Review by ermshiperete — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Pull request merged**
