### PR TITLE
[WIP] feat(linux): Add ability to configure keyboard options

### LINKED ISSUE #2473: [Linux] Feature request: Handle keyboard settings that use options.htm
As mentioned in keymanapp/help.keyman.com#97, `if()` statement is incomplete on Linux because the options.htm form is not supported.

For reference, here's a screenshot of Keyman Desktop when keyboard options are available:
desktop keyboards

### PR DESCRIPTION
**Pull request by darcywong00**
Originally started to address #1790

Some keyboards (e.g sil_ipa or sil_cipher_music) include an `options.htm` file to adjust keyboard settings. On Keyman Desktop, this gets stored in the registry and Keyman Desktop applies the setting when the keyboard is selected.

This PR modifies Keyman for Linux with the following :

### keyman-config
Add an "Options" button that is enabled if the keyboard includes an `options.htm` file. The list of options are then stored in DConf in the path `/desktop/ibus/keyman/options/packageID/keyboardID/options.` as a string such as
```
['option_key=jianpu','another_key=two']
```

keyman config options

### ibus-keyman
When initializing a keyboard, also read the "options" key in Dconf. If the key-value pair exists, pass it to the keyboard processor.

### Limitations
These TODO's can be deferred for a future release:
- [ ] Currently, Keyman Config displays keyboard packages in the list. So the "Options" button is limited to where package ID = keyboard ID
- [x] Multiple options could be defined in `options.htm`. For now, only the first one gets processed in ibus-keyman
- [ ] For now, the user needs to toggle keyboards for the options to take effect. ibus-keyman would need to be updated to watch for updates in DConf and apply the options to keyboardprocessor.

----

### User Testing
1. Check out repo (assuming steps for dev environment in README.md are already done)
2. In the `/linux` folder
  * `make reconf`
  * `make fullbuild`
  * `sudo make install`
3. Launch km-config (in `/usr/local/bin`) and download and install keyboards (follow steps from the [guide](https://help.keyman.com/products/linux/12.0/guide/installing-keyboard)
  * Pick 1 keyboard that doesn't have `options.htm` (like khmer_angkor)
  * Pick 1 keyboard that does have `options.htm` (like sil_ipa or sil_cipher_music)
4. For the keyboard without `options.htm`, verify keyboard functions fine
5. For the keyboard with options.htm (sil_cipher_music), verify Indoensian cipher (default option)
  * Enable "Indonesian (Cipher Music (SIL)) keyboard
  * Type `q` which is rendered `ꞌ`.
  * Type `=` two times to get `̿`  
6. From Keyman Config, select sil_cipher_music and click "Options" and set "Chinese cipher"
  * Toggle to another keyboard "English" and toggle back to "Indonesian (Cipher Music (SIL)).
  * Type `q` which is rendered `ꞌ`.  
  * Type `=` two times to get `̳`

# SIL Cipher Music keyboard options
sil_cipher_music options

# SIL IPA keyboard options
sil_ipa options

### CODE REVIEW

**Comment by mcdurdin** [comment]
This is looking good overall. However I think we need to resolve the following limitation in particular:

>  Multiple options could be defined in options.htm. For now, only the first one gets processed in ibus-keyman

Another thing to consider is how [`save()`](https://help.keyman.com/developer/language/reference/save) interacts with this.

**Comment by darcywong00** [comment]
ibus-keyman updated to handle multiple options.

I manually inserted bogus options via DConf an​d tested with SIL IPA, SIL Cipher Music, and Khmer Angkor (control keyboard w/o options)

**Comment by darcywong00** [comment]
Back to wip for supporting `save()` from the keyboard

**Comment by darcywong00** [comment]
Abandoning this PR because the work is resumed in #2566 for 13.0 Beta

**Pull request closed without merging**
