### PR TITLE
fix(web): touch-move cancellation

### PR DESCRIPTION
**Pull request by jahorton**
Fixes an issue accidentally introduced by commit https://github.com/keymanapp/keyman/pull/5278/commits/d582e69b73abef05cee27b44a846ea1584fe2a88 of #5278.

Changing the styling property of the `VisualKeyboard` root to fixed caused the `yMin` calculation to receive markedly different values than it did before, causing `touchMove`s before the appearance of popup keys to instantly break the touch gesture.  I found it simplest to maintain the 'spirit' of the original logic, opting for a threshold of 1/3 a row's height above the top of the layer group.

## User Testing
@MakaraSok 

Please load up Keyman on Android and ensure that touch-based behaviors still work as expected.  In particular, try moving your finger to a side immediately after touching a key - does the keytip or highlighting (whichever occurs on the device) properly track the key under your finger as you move it?

### CODE REVIEW

**Comment by MakaraSok** [comment]
Tested on Pxel 2 Emulator API 29, Adnroid 10. The keytip does highlight the right key as the finger moves around right after touching a key before popup keys show up.

_I've tried to verify whether this behaves differently in this build (https://github.com/keymanapp/keyman/pull/5278), but to my surprise the same behavior is observed. I did not find any hiccup._

**Comment by jahorton** [comment]
I suppose the Android-specific code may have bypassed the parts that were broken; it's possible that it was never affected.  Best to _ensure_, rather than to assume.  Thanks for checking.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.70-alpha](https://keyman.com/downloads/releases/alpha/15.0.70)

**Pull request merged**
