### PR TITLE
chore(common): cleanup meson deprecations and warnings

### PR DESCRIPTION
**Pull request by mcdurdin**
Most warnings have been cleaned up:

* min meson version is now 1.0
* additional parameters such as check, recursive added
* uses now global_source_root() instead of source_root()
* catting files on Windows wasn't actually working -- used in unit tests. This is because meson passes paths with forward slashes to cmd.exe `type` command, which doesn't understand them. This is bad, because we were running effectively null tests for the affected tests. Fortunately, the same tests were configured correctly on macOS and Linux, and were all passing, so no serious damage.

There is one significant warning left:

`WARNING: Project targets '>=1.0' but uses feature deprecated since '0.64.0': copy arg in configure_file. Use fs.copyfile instead`

Refer to mesonbuild/meson#12792. I have opened a PR against that to undeprecate `copy` kwarg in a future version of meson.

@keymanapp-test-bot skip

Fixes: #8399

### CODE REVIEW

**Comment by mcdurdin** [comment]
Looks like [Debian Packaging](https://github.com/keymanapp/keyman/actions/runs/9219881568/job/25365802156#step:5:262) is using Meson 0.61:

> Get:111 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 meson all 0.61.2-1 [519 kB]

@ermshiperete is this solvable?

**Comment by ermshiperete** [comment]
> Looks like [Debian Packaging](https://github.com/keymanapp/keyman/actions/runs/9219881568/job/25365802156#step:5:262) is using Meson 0.61:
> 
> > Get:111 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 meson all 0.61.2-1 [519 kB]
> 
> @ermshiperete is this solvable?

This affects building the source package which currently runs on Ubuntu 22.04 which comes with meson 0.61. We could try to run the `sourcepackage` step on Ubuntu 24.04 which has meson 1.3.

**Comment by mcdurdin** [comment]
> There is one significant warning left:
> 
> `WARNING: Project targets '>=1.0' but uses feature deprecated since '0.64.0': copy arg in configure_file. Use fs.copyfile instead`
> 
> Refer to [mesonbuild/meson#12792](https://github.com/mesonbuild/meson/issues/12792). I have opened a PR against that to undeprecate `copy` kwarg in a future version of meson.

https://github.com/mesonbuild/meson/pull/13250 was merged so we won't attempt to work around this warning, we'll just wait until we update to that version of meson in the future.

**Comment by mcdurdin** [comment]
@ermshiperete getting this error, which I am not sure what to do with at this point:
 
https://github.com/keymanapp/keyman/actions/runs/9230695157/job/25399347203#step:5:64

```
Broken keyman-build-deps:amd64 Depends on meson:amd64 < none | 0.61.2-1 @un uH > (>= 1.0)
  Removing keyman-build-deps:amd64 because I can't find meson:amd64
```

**Comment by ermshiperete** [comment]
> @ermshiperete getting this error, which I am not sure what to do with at this point:
> 
> https://github.com/keymanapp/keyman/actions/runs/9230695157/job/25399347203#step:5:64
> 
> ```
> Broken keyman-build-deps:amd64 Depends on meson:amd64 < none | 0.61.2-1 @un uH > (>= 1.0)
>   Removing keyman-build-deps:amd64 because I can't find meson:amd64
> ```

As discussed in our meet-after: The build is using the job definition from the `master` branch, so it's still building with Ubuntu 22.04.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.52-alpha](https://keyman.com/downloads/releases/alpha/18.0.52)

**Pull request merged**
