### PR TITLE
change(ios): defer registration of fonts past initialization

### PR DESCRIPTION
**Pull request by jahorton**
Addresses part of #1492.

See https://github.com/keymanapp/keyman/issues/1492#issuecomment-2290743167 - font registration takes a surprisingly high amount of time during app and keyboard initialization - enough so that it appears to affect launch stability for the system keyboard mode.

## User Testing

TEST_APP_AND_KEYBOARD:  Using Keyman for iOS, validate that...
- the app launches normally and the keyboard works.
- the system keyboard (once enabled) launches normally and the keyboard works.

### CODE REVIEW

**Review by mcdurdin — COMMENTED** [review]
Questions:

1. Do custom fonts still work correctly in the system keyboard and the text area for Keyman?
2. Assuming the fonts do still work, could this cause an [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) in the keyboard when the font changes over?

**Comment by jahorton** [comment]
> I am surprised that you didn't add user tests to verify that registered fonts still work

This requires actually knowing of cases that trigger the code.  If you have suggestions, I'm all ears.  Secondly, it's _just_ a simple delayed call - the _only_ worry I'd have would be FOUC-related.  Even if that occurs... would we prefer the keyboard failing to load over a little start-up FOUC?

**Comment by mcdurdin** [comment]
> This requires actually knowing of cases that trigger the code. If you have suggestions, I'm all ears. I'd rather not write a test that doesn't _actually_ test what I think it does.

Khmer Angkor keyboard uses displayMap -- so the application of the font is essential. It would be a good test keyboard.

> Secondly, it's _just_ a simple delayed call - the _only_ worry I'd have would be FOUC-related. Even if that occurs... would we prefer the keyboard failing to load over a little start-up FOUC?

I prefer not to make assumptions about the outcomes. Obviously FOUC is better than failure. But it's also good to know if this does end up with that side-effect, because that is also not ideal, particularly e.g. if the FOUC results in the user seeing tofu for a moment, because that looks messy.

**Review by mcdurdin — APPROVED** [review]
I see that we are not capturing any exceptions from `registerCustomFonts()` with this change, which is another possible difference -- is this something to care about?

I assume you plan to cherry-pick to stable?

LGTM

**Comment by jahorton** [comment]
After a bit of searching, it appears that `gff_amharic` includes a number of fonts that will fail the `fontExists` check and thus trigger font-registration requests.   I happened to have this package installed already in the simulator I'm using to develop and locally-test the branch; just had to think about it and check for breakpoint hits after the `fontExists` check.

I don't see any FOUC in-keyboard or out-of-keyboard when testing with this.  Using this in Simulator with the Reminders app, there's not even a pixel of shift I can notice within Reminder-app text typed with either... even if I simulate a device restart and then bypass the app without the Keyman system keyboard being the first to launch.  The keyboard only has its usual minor startup behaviors, so far as I can tell.  All keycaps I could think to check for issues look fine, too.
- So... is there a chance I'm missing something?
- Is there a more thorough reset I should try?  I find it odd that there's literally _no_ shift, even in third-party app text.

I'd like to be clear on these bits before I attempt to write a test; it's important to know what observations are important to specify.

**Comment by dinakaranr** [comment]
# Test Results

* **TEST_REVERSION_DISPLAY_STRING (Passed):**
I tested this issue with the attached "Keyman 18.0.90-alpha-test-12190" build on the iPhone 13 and iOS 17.4. Here is my observation.
1. Installed the "Keyman-18.0.90.apk" file and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Selected the "EuroLatin(SIL)" as default keyboard.(3.0.2 version)
4. Open the Keyman app. Enable the "Predictions" to install the "Dictionary."
5. Added a sentence to the keyman notepad and chrome(search).
6. Enter a word and observe that the word is highlighted on the banner.
7. Press the "Spacebar" and then the word added.
The word is selected using a cursor from left to right and right to left.
The word prediction works on the banner and selection works correctly.
Thank you.

**Comment by jahorton** [comment]
> I see that we are not capturing any exceptions from `registerCustomFonts()` with this change, which is another possible difference -- is this something to care about?

I just decided to follow-up with this and give it its own error handling - but Swift then presents us with a warning:

```
'catch' block is unreachable because no errors are thrown in 'do' block
```

So... Swift itself says it's not something to care about.

(Swift uses `do-catch`, rather than `try-catch`.  `try` is for statements that may throw errors.)

**Comment by mcdurdin** [comment]
> * So... is there a chance I'm missing something?

I think perhaps look at Khmer Angkor and its OSK?

**Comment by jahorton** [comment]
> > * So... is there a chance I'm missing something?
> 
> I think perhaps look at Khmer Angkor and its OSK?

Done with the follow-up PR (#12210), which has now passed its tests as well.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.98-alpha](https://keyman.com/downloads/releases/alpha/18.0.98)

**Pull request merged**
