### PR TITLE
refactor(android/app): Move Settings activities from KMEA to KMAPro

### PR DESCRIPTION
**Pull request by darcywong00**
Prep work for addressing #3595

This moves the following Activities from KMEA to KMAPro:
1. `KeyboardSettingsActivity`
2. `KMPBrowserActivity`
3. `LanguageSettingsActivity`
4. `LanguagesSettingsActivity`

Other minor changes to note:
* Add intent filter priority so Keyman is prioritized over Chrome
* Move prediction/correction (preference) strings from `LanguageSettingsActivity` to `KMManager`
* Refactor `DownloadResultReceiver` out of `MainActivity`

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM. Are there any Keyman Engine API changes as a result of this that need to be documented?

**Comment by darcywong00** [comment]
> Are there any Keyman Engine API changes as a result of this that need to be documented?

To date, we've only been documenting KMManager methods.
While this PR moved the following two to KMManager
```
* public static String getLanguagePredictionPreferenceKey(String langID);
* public static String getLanguageCorrectionPreferenceKey(String langID);
```
they're intended for kmapro/LanguageSettingsActivity  and not really for other keyboard developers to consume.

**Comment by mcdurdin** [comment]
> they're intended for kmapro/LanguageSettingsActivity and not really for other keyboard developers to consume.

We should probably document them accordingly -- so other developers don't (mis)use them!

**Comment by darcywong00** [comment]
Noted in the wiki

**Pull request merged**
