### PR TITLE
fix(web): active element selection in multi-touch scenarios

### LINKED ISSUE #4797: bug(web): KMW active-element management breaks in multi-touch scenarios
Sentry Issue: [KEYMANWEB-COM-C6](https://sentry.keyman.com/organizations/keyman/issues/4138/?referrer=github_integration)

```
TypeError: a.setTextCaret is not a function
  at setFocusWithTouch (https://s.keyman.com/kmw/engine/14.0.270/src/domEventHandlers.ts:616:9)
  at b.<anonymous> (https://s.keyman.com/kmw/engine/14.0.270/src/domEventHandlers.ts:553:7)
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4797.

According to MDN's notes on browser compatibility, there should be no loss of compatibility with these changes.
- `touches`: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches#browser_compatibility
- `changedTouches`: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/changedTouches#browser_compatibility

### User Testing

Note:  this will require testing on a live touch device; Chrome emulation does not support multiple touches.  As such, you'll likely need a test setup using a service similar to `ngrok` to properly 'serve' the testing page for your device.

As for the actual test... it's best to refer to the repro notes in #4797.  Note that you'll need to use developer mode and open the console view to verify that no errors occur; the user-visible effect (broken longpress key menu) still remains, as that's a separate (OSK) issue.

Some 'fun' things you can do now:  touch the top-most input element on the "unminified source" testing page, and without letting go, touch the second.  Without releasing either finger, try to scroll the top element - it'll scroll properly.  If you don't mind playing Twister with your fingers, use yet another to type with the OSK, and the second input element should receive the keystroke, even if actively scrolling the first, so long as both of the first two touches are held.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
I think this makes sense, although I am having trouble picturing how a given touch is valid or not per `isValidTouch` .

**Comment by jahorton** [comment]
> I think this makes sense, although I am having trouble picturing how a given touch is valid or not per `isValidTouch` .

This makes sure that the `Touch` passed back to the method actually corresponds with a valid `OutputTarget` - an element on the page that KMW has attached to.  In multitouch, it's possible to have one of the event's touches be randomly on the page in a place KMW should ignore.

**Comment by mcdurdin** [comment]
Can you add a comment to `isValidTouch` for future maintainers per https://github.com/keymanapp/keyman/pull/5134#issuecomment-847459235? Thanks!

**Comment by jahorton** [comment]
The current iOS behavior is 100% expected - #5107 hasn't landed yet.

**Comment by jahorton** [comment]
One final question:  this should be easily possible to 🍒-pick.  Do so?

**Comment by mcdurdin** [comment]
> One final question: this should be easily possible to 🍒-pick. Do so?

Yes please, as we don't want to keep the crash scenario any longer than we have to.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.53-alpha](https://keyman.com/downloads/releases/alpha/15.0.53)

**Pull request merged**
