### PR TITLE
change(ios): modernization of the Keyman app main screen's layout logic

### LINKED ISSUE #6664: bug(iOS):  text obscurable in landscape on notched devices
**Describe the bug**

As they say "a picture's worth a thousand words"...

image

While the example text _is_ merely "key smash", note that the notch is obscuring some of it!

**To Reproduce**
1. Open the Keyman app
2. Rotate the device into landscape orientation
3. Type away! 

**Expected behavior**
We should _probably_ have the actual text area respect the device's "safe area" - never allowing the text near that notch.

---

**Keyman for iPhone/iPad/Android:**
 - Device: any notched iPhone (X, 11, 12, 13, etc.)
 - OS: iOS 11+
 - Keyman version: 14.0.x, 15.0.x
 - Target application:  Keyman app

### PR DESCRIPTION
**Pull request by jahorton**
Note:  this PR is based on #6599.  I noticed _and_ fixed the underlying bug while testing it before arriving at that PR's best solution!  Then I noticed that I could split this code off into its own PR... and here we are.

Fixes #6664.

So, it turns out that the app's `MainViewController` hasn't seen a lot of love in a while.  Like, the old layout code was written before safe areas were even a thing!  That, of course, makes properly respecting safe areas a bit tricky.  So, rather than maintain the old-style code... why not give it some love and modernize it?

With these changes in place:

image

For the help section:

image

While not perfectly ideal, the yellow peeking through is visually balanced on each side and helps prevent the notch from obscuring any part of the actual help pages.  Also, noting the nav bar, this part cannot be tested directly unless the base branch is set as is, hence the minor PR chain.

Also, if we would prefer, we could just stick this in draft until after 15.0's release and then apply it in early 16.0 alpha.  It's set up as it currently is because of its base branch.

## User Testing

As this _does_ actually change a substantial part of the app's layout handling, there's actually a bit more to test here than you might initially expect.

### Test environments

- GROUP_IPHONE_SE:  Test on the (notchless) iPhone SE (2nd gen) through Simulator
- GROUP_IPHONE_12:  Test on the (notched) iPhone 12 Pro Max through Simulator
- GROUP_IPAD_PRO: Test on any IPad Pro target available through Simulator.  Any **one** will suffice.
    - Basically, make sure things look fine on tablets, too.

Note:  depending on your test environment, you may want use the app's "Text Size" option to dramatically increase the text size.  Makes things much less tedious.

### Actual tests

- TEST_TEXTAREA_LANDSCAPE_WIDTH:  Within the Keyman app, in **landscape** orientation, type some "key smash" - without spaces - until the first line is full.  Then, type a little further.
    - If the text does not word-wrap and is instead obscured by some physical boundary of the device, fail this test.
    - On notched devices, this may occur significantly before the device's edge.  The boundary should be approximately symmetric - equal on both left and right-hand sides:
        <details><summary>Example screenshot</summary>

        image

        This _passes_, as there is even spacing on the left and right sides.
        
        </details>

- TEST_TEXTAREA_PORTRAIT_WIDTH:  Within the Keyman app, in **portrait** orientation, type some "key smash" - without spaces - until the first line is full.  Then, type a little further.
    - If the text does not word-wrap and is instead obscured by some physical boundary of the device, fail this test.

- TEST_TEXTAREA_LANDSCAPE_SCROLL:  Within the Keyman app, in **landscape** orientation, type in multiple lines of text until the text is just above the keyboard.  Then, add an extra line or two.
    - If the text area does not auto-scroll to keep the text caret (and your most-recently typed text) in view, fail this test.
    - Then, scroll the text area up and down.
        - You should be able to view all previously typed text.
        - Whenever you "release" your scrolling input, there should never be excess space either above or below all of the text.

- TEST_TEXTAREA_PORTRAIT_SCROLL:  Within the Keyman app, in **portrait** orientation, type in multiple lines of text until the text is just above the keyboard.  Then, add an extra line or two.
    - If the text area does not auto-scroll to keep the text caret (and your most-recently typed text) in view, fail this test.
    - Then, scroll the text area up and down.
        - You should be able to view all previously typed text.
        - Whenever you "release" your scrolling input, there should never be excess space either above or below all of the text.

- TEST_HELP_LAYOUT:  Go to the in-app help and verify that the page looks properly laid out.
    - Then, rotate the device and verify that the layout still looks appropriate.
    - If you cannot see the entirety of the line reading "Keyman for iPhone and iPad 15.0 Help", fail this test.
    - If any part of any of the help navigation buttons at the bottom (from #6654) are even partially obscured, fail this test.
    - Do not fail this test if there are "light yellow bars" at the left and righthand side of the help page.
    - Do fail this test if there is a "light yellow bar" either above or below the help page and/or toolbar.
        <details><summary>Example screenshot</summary>

        image

        This _passes_.  Note how the yellow bars ensure that the notch does not, at any time, cover help page text.
        
        </details>

### CODE REVIEW

**Comment by bharanidharanj** [comment]
### GROUP_IPHONE_SE: Test on the (notchless) iPhone SE (2nd gen) through Simulator

* **TEST_TEXTAREA_LANDSCAPE_WIDTH (FAILED):** Tested this as per the instructions and it seems that there is no even space appears on both left and right sides of the pane in a notchless device. (Is this an expected one?)
 

* **TEST_TEXTAREA_PORTRAIT_WIDTH (FAILED):** Tested this as per the instructions and it seems that there is no even space on both left and right sides of the pane in a notchless device.
 

* **TEST_TEXTAREA_LANDSCAPE_SCROLL (PASSED):** Tested this as per the instructions and it seems to be working as expected. 
 

* **TEST_TEXTAREA_PORTRAIT_SCROLL (PASSED):** Tested this as per the instructions and it seems to be working as expected. 
 

* **TEST_HELP_LAYOUT (FAILED):** Tested this as per the instructions and it seems that the text appears partially, after rotating the device from portrait to landscape mode.

**Comment by bharanidharanj** [comment]
### GROUP_IPHONE_12: Test on the (notched) iPhone 12 Pro Max through Simulator

* **TEST_TEXTAREA_LANDSCAPE_WIDTH (PASSED):** Tested this as per the instructions and it is working as expected. 


* **TEST_TEXTAREA_PORTRAIT_WIDTH (PASSED):** Tested this as per the instructions and it is working as expected.


* **TEST_TEXTAREA_LANDSCAPE_SCROLL (PASSED):** Tested this as per the instructions and it is working as expected.


* **TEST_TEXTAREA_PORTRAIT_SCROLL (PASSED):** Tested this as per the instructions and it is working as expected.


* **TEST_HELP_LAYOUT (FAILED):** Tested this as per the instructions and it seems that there is light yellow bar appears at the top and the bottom of the view.

**Comment by bharanidharanj** [comment]
### GROUP_IPAD_PRO: Test on any IPad Pro target available through Simulator.  Any **one** will suffice.

* **TEST_TEXTAREA_LANDSCAPE_WIDTH (PASSED):** Tested this as per the instructions in IPad Pro iOS 15.0 Simulator and it is working as expected. 


* **TEST_TEXTAREA_PORTRAIT_WIDTH (PASSED):** Tested this as per the instructions in IPad Pro iOS 15.0 Simulator and it is working as expected. 
  

* **TEST_TEXTAREA_LANDSCAPE_SCROLL (PASSED):** Tested this as per the instructions in IPad Pro iOS 15.0 Simulator and it is working as expected. 
 


* **TEST_TEXTAREA_PORTRAIT_SCROLL (PASSED):** Tested this as per the instructions in IPad Pro iOS 15.0 Simulator and it is working as expected. 
 


* **TEST_HELP_LAYOUT (FAILED):** Tested this as per the instructions in IPad Pro iOS 15.0 Simulator and it seems that a light yellow bar appears at the top and bottom of the view.

**Comment by jahorton** [comment]
Thanks for the test runs & screenshots, @bharanidharanj.

Based on those screenshots, all of the tests are passes.  Apparently I wrote the test cases a bit unclearly, given how a total of 5(!) got labeled differently.  Any notes on what might have made the spec a little more clear there?

------

For the purposes of this PR...

#### **GROUP_IPHONE_SE**: [original results](https://github.com/keymanapp/keyman/pull/6666#issuecomment-1138619836)

**TEST_TEXTAREA_LANDSCAPE_WIDTH**:  **PASSED**

> 

As the iPhone SE has no notch, we don't expect there to be extra space on the sides, just like with the iPad Pro.  I realize I may have only _implied_ that this is the default expectation, with notched devices being the exception.

From the original test def:

> On notched devices, this **may** occur significantly before the device's edge.

"May": don't fail if it happens, but don't require it _to_ happen.  So long as that doesn't conflict with any of the other requirements, of course.

**TEST_TEXTAREA_PORTRAIT_WIDTH**:  **PASSED**

> 

Same as above.

* **TEST_HELP_LAYOUT**:  **PASSED**

> 

It's a scrollable web page.  Now, if parts of the page were permanently obscured, unreadable after any amount of scrolling, then we'd have a problem.


### GROUP_IPHONE_12: [original results](https://github.com/keymanapp/keyman/pull/6666#issuecomment-1138663528)

**TEST_HELP_LAYOUT**:  **PASSED** 

> 
>
> Tested this as per the instructions and it seems that there is light yellow bar appears at the top and the bottom of the view.

Uh... the way the device is rotated, that'd be the "left" and "right" of the view for this orientation, not the "top" and the "bottom".

I tried to make this clear in the original spec.  Granted, I had the screenshot hidden by default on the spec for this test, but...

> image
>
> **This _passes_.**  Note how the yellow bars ensure that the notch does not, at any time, cover help page text.

Perhaps I shouldn't have had that in an initially-hidden place?

### GROUP_IPAD_PRO: [original results](https://github.com/keymanapp/keyman/pull/6666#issuecomment-1138695887)

**TEST_HELP_LAYOUT**:  **PASSED** 

> image

Same as mentioned with the versions against the other GROUPs above.  Except... I don't see the same light yellow bar in this one?

------

... you know, until now, I never even considered that the navigation bar and toolbar might be seen as a "light yellow."  Is _that_ what the confusion is?  If so, it's _so_ light I'd (personally) say "_very_ light yellow", "_pale_ yellow," or most likely, "yellow-tinted" for those bars!  It hadn't even crossed my mind!   

"Light yellow" _was_ intended to mean "the same color as the text area".  So this may well have been my fault.  Just "yellow" would be closer to this: 

image

Note how much more saturated that is; the navigation bar is a whole extra level-of-magnitude lighter than the text area when compared to it.  The text area is "close enough" to be _just_ "light" yellow.

**Review by sgschantz — APPROVED** [review]
It would be nice to see some of these large methods be broken up, especially when adding several lines of new code. The method viewDidLoad() is over 100 lines and has some natural breaks where there is a commented section of cohesive code, such as "Set up TextView" or "Set up Navbar". If these chunks were broken out as private methods, it would make it easier to read and comprehend the larger public method.

Other than that, it looks good!

**Comment by bharanidharanj** [comment]
> Thanks for the test runs & screenshots, @bharanidharanj.
> 
> Based on those screenshots, all of the tests are passes. Apparently I wrote the test cases a bit unclearly, given how a total of 5(!) got labeled differently. Any notes on what might have made the spec a little more clear there?
> 
> For the purposes of this PR...
> #### **GROUP_IPHONE_SE**: [original results](https://github.com/keymanapp/keyman/pull/6666#issuecomment-1138619836)
> 
> **TEST_TEXTAREA_LANDSCAPE_WIDTH**: **PASSED**
> 
> > 
> 
> As the iPhone SE has no notch, we don't expect there to be extra space on the sides, just like with the iPad Pro. I realize I may have only _implied_ that this is the default expectation, with notched devices being the exception.
> 
> From the original test def:
> 
> > On notched devices, this **may** occur significantly before the device's edge.
> 
> "May": don't fail if it happens, but don't require it _to_ happen. So long as that doesn't conflict with any of the other requirements, of course.
> 
> **TEST_TEXTAREA_PORTRAIT_WIDTH**: **PASSED**
> 
> > 
> 
> Same as above.
> 
>     * **TEST_HELP_LAYOUT**:  **PASSED**
> 
> 
> > 
> 
> It's a scrollable web page. Now, if parts of the page were permanently obscured, unreadable after any amount of scrolling, then we'd have a problem.
> ### GROUP_IPHONE_12: [original results](https://github.com/keymanapp/keyman/pull/6666#issuecomment-1138663528)
> 
> **TEST_HELP_LAYOUT**: **PASSED**
> 
> > 
> > Tested this as per the instructions and it seems that there is light yellow bar appears at the top and the bottom of the view.
> 
> Uh... the way the device is rotated, that'd be the "left" and "right" of the view for this orientation, not the "top" and the "bottom".
> 
> I tried to make this clear in the original spec. Granted, I had the screenshot hidden by default on the spec for this test, but...
> 
> > image
> > **This _passes_.**  Note how the yellow bars ensure that the notch does not, at any time, cover help page text.
> 
> Perhaps I shouldn't have had that in an initially-hidden place?
> ### GROUP_IPAD_PRO: [original results](https://github.com/keymanapp/keyman/pull/6666#issuecomment-1138695887)
> 
> **TEST_HELP_LAYOUT**: **PASSED**
> 
> > image
> 
> Same as mentioned with the versions against the other GROUPs above. Except... I don't see the same light yellow bar in this one?
> 
> ... you know, until now, I never even considered that the navigation bar and toolbar might be seen as a "light yellow." Is _that_ what the confusion is? If so, it's _so_ light I'd (personally) say "_very_ light yellow", "_pale_ yellow," or most likely, "yellow-tinted" for those bars! It hadn't even crossed my mind!
> 
> "Light yellow" _was_ intended to mean "the same color as the text area". So this may well have been my fault. Just "yellow" (though perhaps, "bright yellow") would be closer to this:
> 
> image
> 
> Note how much more saturated that is; the navigation bar is a whole extra level-of-magnitude lighter than the text area when compared to it. The text area is "close enough" to be _just_ "light" yellow.

Thank you so much, @jahorton for your explanation given with the modified results. Actually, I had some doubts while posting some of the results (ie., alignment of text in notchless mobile, light yellow bar visible at the bottom and the top of the screen)  that I have posted in this PR. Your detailed comments helps me a lot to understand this issue.

**Comment by jahorton** [comment]
> It would be nice to see some of these large methods be broken up, especially when adding several lines of new code.

Just added a new commit that does exactly this and only this to that `viewDidLoad` function.  Anything further would likely be out of scope here.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.254-beta](https://keyman.com/downloads/releases/beta/15.0.254)

**Pull request merged**
