### PR TITLE
[Android] Handle RTL metadata on keyboard downloads

### LINKED ISSUE #764: [Android] Handle RTL metadata on keyboard downloads
Parse from `kmp.json`. Eventually might be used to modify the text field.
Doesn't need to be passed to KMW

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #764

Pull `rtl` metadata from kmp.json and cloud API
If `rtl` isn't defined, it's assumed `false`.

This does create a side effect of previously installed keyboards not containing `rtl` info, so they'll all assume `rtl=false`.

### CODE REVIEW

**Comment by darcywong00** [comment]
I'm a little unsure how far `rtl` needs to be propagated into keyboard info, since it's not used for KMW...

**Comment by darcywong00** [comment]
A side by side comparison of
1. `abc` with **EuroLatin (SIL)** Keyboard followed by
2. `شالر` with **Arabic Izza** Keyboard

| Master branch | RTL applied |
| ---------------- | ------------- |
| master euro-izza | rtl euro-izza |

**Comment by mcdurdin** [comment]
Now I am a little concerned about this. If we don't specify directionality, what does the control do? Does it use the directionality of the first letter? Or something else?

**Comment by mcdurdin** [comment]
Hmm. That means I think we shouldn't be applying this PR. Because Android is already going to give more useful behaviour without the RTL hint...  Sorry :(

**Comment by darcywong00** [comment]
Closing this PR and keeping Android in control of text direction

**Pull request closed without merging**
