### PR TITLE
[Mac] Beta About Box seems stuck

### PR DESCRIPTION
**Pull request by rfaramir**
Issue [Mac] About box is stuck and has no controls #1529
I'd like feedback on the new look that I needed to use to make it visible.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/141384:id/kvk/index.html)

**Comment by mcdurdin** [comment]
Can you paste screenshots of the new look in?

**Comment by rfaramir** [comment]
> Can you paste screenshots of the new look in?

screenshot-new-about-box

**Comment by mcdurdin** [comment]
I think the buttons should all be the same colour.  The top line of blue text should be brought down closer to the second line of blue text. Also both those lines should probably be black -- blue is a hint of being an URL.

**Comment by rfaramir** [comment]
> blue is a hint of being an URL.

So, the linked license info should be blue and the un-clickable version and copyright text should be black?
And what color should the two buttons be (Configuration and Close)?

**Comment by mcdurdin** [comment]
> So, the linked license info should be blue and the un-clickable version and copyright text should be black?

Sounds good to me.

> And what color should the two buttons be (Configuration and Close)?

Ideally, they should like system buttons, yeah?

**Comment by rfaramir** [comment]
OK, can do.

> Ideally, they should like system buttons, yeah?

So, black text, then. I'll put up a pic in a moment.

**Pull request merged**
