### PR TITLE
chore(android,linux,windows): Check in crowdin strings for Bura-Pabir

### PR DESCRIPTION
**Pull request by darcywong00**
This checks in the crowdin strings for Bura-Pabir (language code bwr-NG) though some of the platforms automatically use bwr-NT.

TODO: reun iOS project through XCode

## User Testing
For all the platforms, load the PR build, set the UI to "Bura-Pabir", and verify the UI is in Bura-Pabir

* **TEST_ANDROID** - Tests Bura-Pabir UI for Android
1. Load the PR build in an Android 5.0 emulator (SDK 21)
2. In the Keyman app, go to Settings --> Display Language --> Bura-Pabir
3. Verify the UI is in Bura-Pabir

* **TEST_IOS** - Tests Bura-Pabir UI for iOS [Skip since not available]
1. Start the app
2. Change the UI to Bura-Pabir locale
3. Verify the app refreshes with Bura-Pabir strings

* **TEST_WINDOWS** - Tests Bura-Pabir UI for Windows

* **TEST_LINUX** - Tests Bura-Pabir UI for Linux
1.  start Keyman configuration with: `LANGUAGE=bwr_NT km-config`

### CODE REVIEW

**Comment by MakaraSok** [comment]
* **TEST_ANDROID: PASSED** The UI indeed switches to Bura-Pabir.
* **TEST_WINDOWS: BLOCKED** No build to download, see the screenshot below.
image

* **TEST_LINUX: BLOCKED** No build either.
image

**Comment by MakaraSok** [comment]
No build to download still:
image

**Comment by MakaraSok** [comment]
* **TEST_LINUX: PASSED** The UI is shown in Bura-Pabir, but one err on the translation of "Yes" and "No" on the following dialogue box. This is shown after clicking to uninstall a keyboard. Can we ask the translator and have the confirmation that the translation of the two words are intended to be left in English or are they already translated (yet they happen to have the same spelling as English)?

https://crowdin.com/translate/keyman/428/en-bwrng?filter=basic&value=3#q=no
https://crowdin.com/translate/keyman/428/en-bwrng?filter=basic&value=3#q=yes


image

**Comment by MakaraSok** [comment]
* **TEST_WINDOWS: BLOCKED** The UI language switch to the Bura-Pabir, but some strings are still English. This might be because some strings haven't yet/fully been localized.

i.e. https://crowdin.com/translate/keyman/all/en-bwrng?filter=basic&value=3#q=cancel
image

The translation of some terms are not consistent as far as I can tell. "Text Editor" was left untranslated else where, but not this. Is this intended?
https://crowdin.com/translate/keyman/all/en-bwrng?filter=basic&value=3#q=text%20editor

"Exit" was localized else where, but not when there is a shortcut marker with.

https://crowdin.com/translate/keyman/all/en-bwrng?filter=basic&value=3#q=exit

It looks like the translation of this language needs to be double-checked and fully translated if otherwise.

**Comment by mcdurdin** [comment]
> * WINDOWS: The UI language switch to the Bura-Pabir, but some strings are still English. This might be because some strings haven't yet/fully been localized.

The dialog headers and buttons are not all localized for some of the 'message dialogs' like the one you pictured (basically dialogs which are just a message). We shouldn't block on those strings.

**Comment by mcdurdin** [comment]
> LINUX: The UI is shown in Bura-Pabir, but one err on the translation of "Yes" and "No" on the following dialogue box

My guess is those strings have not been internationalized yet.

**Comment by MakaraSok** [comment]
> > LINUX: The UI is shown in Bura-Pabir, but one err on the translation of "Yes" and "No" on the following dialogue box
> 
> My guess is those strings have not been internationalized yet.

So the test result for Windows is technically a PASSED, but in anyway we should let the translator(s) of the language know.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.147-alpha](https://keyman.com/downloads/releases/alpha/15.0.147)

**Pull request merged**
