### PR TITLE
chore(web): updates MTNT for pred-text testing page to 0.1.5 (casing)

### PR DESCRIPTION
**Pull request by jahorton**
Parallels https://github.com/keymanapp/lexical-models/pull/109, updating the predictive-text testing page to use the new version of the MTNT model.

### CODE REVIEW

**Comment by darcywong00** [comment]
This is a separate issue
When I load the test page (in desktop mode), clicking the suggestions
* doesn't insert the suggestion
* blanks the 3 suggestions

desktop test page

No errors in the console

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by jahorton** [comment]
> This is a separate issue
> When I load the test page (in desktop mode), clicking the suggestions
> 
>     * doesn't insert the suggestion
> 
>     * blanks the 3 suggestions
> 
> 
> desktop test page
> 
> No errors in the console

Yeah... we've never supported predictive text on desktop.  That's just a byproduct of how the page force-enables  predictive text.  The page is only intended for use with mobile form-factors.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.227-beta](https://keyman.com/downloads/releases/beta/14.0.227)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)

**Pull request merged**
