### PR TITLE
feat(ios) - Parse crowdin translation file for iOS projects (initially km locale)

### PR DESCRIPTION
**Pull request by darcywong00**
This PR adds to `l18n-start` to process the translation files from crowdin.com (downloaded as `Keyman.zip`.

For iOS afaict, each "locale" has 3 files to copy over (2 for KMEI, 1 for the Keyman app).

Other notes:
* Currently, only the `km` locale gets processed. When iOS is ready to handle everything, just remove the loop in `download-crowdin-ios.sh` 
* *.strings are UTF-16 text files. Someone will need to set up some .gitattributes magic for Git to diff them.
* Also using crowdin API to download the Keyman.zip file

### User Testing
1. Add `KEYMAN_CROWDIN_TOKEN` to your shell profile (see Setup in /resources/build/l10n/README.md)
2. Open a Git Bash to `resources/build/l10n/download` and run
```
./download-crowdin.sh -ios
```

This will: 
1. Download Keyman.zip from crowdin.com to /.crowdin-tmp
2. unzip Keyman.zip to crowdin/ 
3. copy the iOS files to their destinations.
Note some of the files from crowdin.com start at en.lproj and will be copied to locale paths like km.lproj.

### CODE REVIEW

**Comment by jahorton** [comment]
> For iOS afaict, each "locale" has 3 files to copy over (2 for KMEI, 1 for the Keyman app).

Currently.  Very little i18n has actually taken place in iOS, so there will probably be more files before all is said and done.  The Android app is miles ahead in this regard.

**Comment by darcywong00** [comment]
Question for discussion:
The [export](https://support.crowdin.com/api/export/) API call can be used (once per 30 minutes) to have crowdin rebuild the translation files (Keyman.zip). It returns one of two statuses:
1. `built` - project rebuilt
2. `skipped` - no change in project files, so nothing rebuilt

Would we want to call this before downloading?

**Comment by darcywong00** [comment]
I'm likely to abandon this PR to use crowdin [CLI (v3)](https://support.crowdin.com/cli-tool-v3/) instead of reinventing everything in Bash...

**Comment by darcywong00** [comment]
Replaced with #2895

**Pull request closed without merging**
