### PR TITLE
fix(oem/fv): Add fv_hulquminum_combine and fv_kwadacha_tsekene :cherries:  🏠

### PR DESCRIPTION
**Pull request by darcywong00**
:cherries: pick of #10269 and #10292 to stable-16.0

Addresses the FV app portion of keymanapp/keyman#2502 for 16.0

> we don't see a recently added keyboard in the list anywhere to download (Hul̓q̓umin̓um̓/hulquminum_combine

Also adds fv_kwadacha_tsekene

### Note: 
fv_hulquminum has name: `Hul’q’umi’num’` (Hul\u2019q\u2019umi\u2019num\u2019)
fv_hulquminum_combine has name: `Hul̓q̓umin̓um̓` (Hul\u0313q\u0313umin\u0313um\u0313)

## User Testing
**Setup** - Install the PR build of FV for Android or FV for iPhone and iPad

* **TEST_ANDROID** - Verifies the latest versions of the 3 reported keyboards can be installed
1. Install the PR build of FirstVoices for Android on an Android device/emulator
2. Launch the FV App
3. From the Setup menus, install the following keyboards (regions in parenthesis):
   * fv_southern_tutchone (Western Subarctic)
   * fv_hulquminum_combine (BC Coast)
   * fv_dane_zaa_zaage (Western Subarctic)
4. From the FV setup menu, set FirstVoices as the default system keyboard
5. Launch a separate app
6. Switch through the FV keyboards and verify the following versions:
    *  fv_southern_tutchone (9.2.1)
    * fv_hulquminum_combine (1.0)
    * fv_dane_zaa_zaage (9.3)
    * fv_kwadacha_tsekene (1.0)
7. Verify fv_southern_tutchone is not a plain QWERTY layout

* **TEST_IOS** - Verifies the latest versions of the 3 reported keyboards can be installed
1. Install the PR build of FirstVoices for iPhone and iPad on an iOS device/emulator
2. Launch the FV App
3. From the Setup menus, install the following keyboards (regions in parenthesis):
   * fv_southern_tutchone (Western Subarctic)
   * fv_hulquminum_combine (BC Coast)
   * fv_dane_zaa_zaage (Western Subarctic)
   * fv_kwadacha_tsekene (BC Interior)
4. From the FV setup menu, set FirstVoices as the default system keyboard
5. Launch a separate app
6. Switch through the FV keyboards and verify the following versions:
    *  fv_southern_tutchone (9.2.1)
    * fv_hulquminum_combine (1.0)
    * fv_dane_zaa_zaage (9.3)
    * fv_kwadacha_tsekene (1.0)
7. Verify fv_southern_tutchone is not a plain QWERTY layout

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID (PASSED):** Tested with the attached PR build (FirstVoices 16.0.145-test-10285) in the Android Mobile device (ver 13) and here is my observation: 1. Installed southern_tutchone (Western Subarctic), hulquminum_combine (BC Coast) and dane_zaa_zaage (Western Subarctic) keyboards. 2. Noticed that the dane_zaa_zaage version was 9.2. 3. Verified that the southern_tutchone is not a plain QWERTY layout. 

..dane_zaa_zaage keyboard version 

   


..southern_tutchone keyboard

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (FAILED):** Tested with the attached PR build (FirstVoices 16.0.145) in iOS 15.5 / iPhone 13 Pro Max simulator and here is my observation: 1. Installed southern_tutchone, hulquminum_combine and dane_zaa_zaage keyboards. 2. After setting FirstVoices keyboard as the default keyboard, opened safari browser app. 3. Set the FirstVoices keyboard. Noticed that the FirstVoices keyboard was missing after clicking the search bar.

**Comment by darcywong00** [comment]
@bharanidharanj - Did the globe key on the FV keyboard let you switch to other FV keyboards?

**Comment by bharanidharanj** [comment]
> @bharanidharanj - Did the globe key on the FV keyboard let you switch to other FV keyboards?

No, @darcywong00 The globe key does allow me to switch to other FV keyboards. Seems to be an issue.

**Comment by darcywong00** [comment]
I'm confused why the FV keyboard shows EuroLatin and won't switch to others. Can you retest on a physical iOS device?

@keymanapp-test-bot retest TEST_IOS

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (FAILED):** notes

> I'm confused why the FV keyboard shows EuroLatin and won't switch to others. Can you retest on a physical iOS device?
> 
> @keymanapp-test-bot retest TEST_IOS

@darcywong00 Tried to download the FirstVoices in the real iPhone 13 mobile and noticed that the TestFlight only downloads the Keyman build. It would be better to attach the FirstVoices build (TestFlight internal version).

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (FAILED):**  Retested with the attached PR build (FirstVoices 16.0.145) in iOS 17.0 / iPhone 15 Pro Max simulator and here is my observation: 1. Installed southern_tutchone, hulquminum_combine and dane_zaa_zaage keyboards. 2. After setting FirstVoices keyboard as the default keyboard, opened safari browser app. 3. Noticed that the FirstVoices keyboard was missing after clicking the search bar.

**Comment by bharanidharanj** [comment]
> I'm confused why the FV keyboard shows EuroLatin and won't switch to others. Can you retest on a physical iOS device?
> 
> @keymanapp-test-bot retest TEST_IOS

@darcywong00 Yes. After switching to FV keyboard, it shows EuroLatin keyboard instead of FV keyboard.

**Comment by darcywong00** [comment]
@bharanidharanj and @sgschantz were able to get TestFlight to load PR builds on a device, so let's try testing iOS again

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (FAILED):** Retested with that attached PR build (FirstVoices 16.0.145-test-10285) in the iPhone 13 Mobile devices (ver iOS 16.6) and here is my observation: 1. Installed southern_tutchone, hulquminum_combine and dane_zaa_zaage keyboards. 2. After setting FirstVoices keyboard as the default keyboard, opened Chorme browser app. 3. Verified that the fv_southern_tutchone is not a plain QWERTY layout. 4. However, the fv_kwadacha_teskene keyboard was missing under BC Interior keyboard language list. 

..Sourthern_tutchone System keyboard

   


..Kwadacha_teskene keyboard missing

**Comment by darcywong00** [comment]
> . 4. However, the fv_kwadacha_teskene keyboard was missing under BC Interior keyboard language list

Ah, I had to re-trigger another iOS build to get that in. (The triggers don't make a build when just changing the .csv file)

@keymanapp-test-bot retest TEST_IOS

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (OPEN):** Retested with the updated PR build (FirstVoices 16.0.145-test-10285) in the iPhone 13 Mobile devices (ver iOS 16.6) and here is my observation: 1. Installed southern_tutchone, hulquminum_combine, dane_zaa_zaage and Kwadacha_teskene keyboards. 2. Verified that the version number are same as it mentioned in the test steps. 2. After setting FirstVoices keyboard as the default keyboard, opened Safari browser app. 3. Verified that the fv_southern_tutchone is not a plain QWERTY layout. 


..southern_tutchone system keyboard

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.145](https://keyman.com/downloads/releases/stable/16.0.145)

**Pull request merged**
