### PR TITLE
fix(android): Don't show welcome.htm on keyboard package update

### LINKED ISSUE #4936: bug(android): Don't display welcome.htm when updating keyboard
#4413 separated the display of welcome.htm from package installation.

Now when installing keyboard updates, the welcome.htm is displayed when it should be a silent install.

Steps to repro:
1. Create a test build with an older version of sil_euro_latin (e.g. [1.9.3](https://downloads.keyman.com/keyboards/sil_euro_latin/1.9.3/sil_euro_latin.kmp))
2. Start Keyman
3. Install the keyboard update for sil_euro_latin
4. See the welcome.htm get displayed

Expected result: welcome.htm does not get displayed.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4936

This cleans up the usage of `KmpInstallMode` so that keyboard package updates don't display the welcome.htm file.
* Moved KmpInstallMode from the app to Keyman Engine for Android
* Added `KmpInstallMode.fromString()` utility
* Have CloudKeyboardPackageDownloadCallback.java set `KmpInstallMode.Silent` on keyboard package updates
 
This does not address serializing classes to pass data in intents (#5265)

- [x] TODO before merging - Revert test code https://github.com/keymanapp/keyman/commit/fcca82891b9a91b0c621ee178a67b05d75eea9d2 needed so PR build includes old version of sil_euro_latin (v 1.9.3). 

## User Testing
Setup
1. Load the PR build of "Keyman for Android". This includes an older version of sil_euro_latin to access keyboard package updates
Note: there's a separate un-addressed issue #6554 about the blank suggestion bar after keyboard installs

* **TEST_UPDATE** - Verifies welcome.htm not displayed on keyboard package updates
1. Start Keyman and dismiss "Get Started" menu if needed
3. Wait for the app to check for available updates
4. When notified of available updates, select the Keyman menu "Install Updates" (On a phone, you'll need to click the 3 dot overflow icon first)
5. At the confirmation dialog, click "Download" to get the keyboard package update
6. Verify the keyboard package downloads, installs, and does **not** display welcome.htm file.

* **TEST_DICTIONARY_INSTALL** - Verifies keyboard and dictionary installs
1. Start Keyman
2. From the Keyman Settings menu, search for a keyboard that has an associated dictionary (e.g. fv_sencoten)
3. Install the keyboard package
4. When the keyboard finishes installing, verify welcome.htm file is displayed (if it's included in the package)
5. Wait for the app to check for associated dictionary
6. Verify the associated dictionary package downloads and installs in the background

* **TEST_ASSOCIATED_LANGUAGE** - Verifies associated language during keyboard package installs
1. Start Keyman
2. From the Keyman Settings menu, search for a keyboard of a specified Akum language. In the Keyman search box, type "`l:id:aku-latn`"  and select "sil_cameroon_qwerty"
3. Click install
4. When the keyboard package installs, verify the "Akum" language is pre-selected in the language selection menu
5. Finish keyboard installation

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_UPDATE (FAILED):** Tested this with the attached PR build and noticed that available updates is missing and clicking on the 3 dots overflow icon, the Install Updates option is not there in the Keyman menu. Seems to be an issue. 
 


* **TEST_DICTIONARY_INSTALL (PASSED):** Verified and it is working as expected. 
 


* **TEST_ASSOCIATED_LANGUAGE (PASSED):** Akum language is pre-selected in the langauge selection menu. Working as expected.

**Comment by darcywong00** [comment]
> the Install Updates option is not there in the Keyman menu.

@bharanidharanj - Did you wait a while to allow the app to check for updates?

@keymanapp-test-bot retest TEST_UPDATE

**Comment by darcywong00** [comment]
@keymanapp-test-bot skip TEST_UPDATE

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.240-beta](https://keyman.com/downloads/releases/beta/15.0.240)

**Pull request merged**
