### PR TITLE
refactor(web): OSK modularization - common-path code -> OSKView ✂️

### PR DESCRIPTION
**Pull request by jahorton**
Follows #5619.

This PR serves as the first major step in a (conceptually) three part sequence intended to fully split the OSK's code paths into distinct, specialized OSK implementations.  Toward that end, this PR is focused on defining a new `abstract` base class for the future specialized versions - the `OSKView`.

This PR moves all common code and logic for OSK management into `OSKView`, leaving all "specialized" logic within `OSKManager` for now.  In follow-up PRs, `OSKManager` will be split into two separate classes - one for desktop OSKs, one for touch - each of which will subclass `OSKView`.  Given that this will, overall, be splitting 1 monolithic class into a total of 3... ✂️ felt appropriate for this PR chain.

Great care was taken (in tandem with #5619) to ensure that this common base class - `OSKView` - would be able to implement the 📐-added `refreshLayout` subsystem directly, rather than having to pawn it off to its future derived subclasses.  This in turn ensures that the base class can handle near-all of the `VisualKeyboard` layout logic internally without any need for specialized intervention.

There are also some nomenclature shifts for some of the default-value methods in `OSKManager`, as their original names implied different purposes than those they have actually served.

# User Testing

### SUITE_DESKTOP: `desktop` form factor tests

**Platform / browser combinations**:
- **GROUP_WIN**: Windows / Chrome
- **GROUP_MAC**: macOS / Firefox
    - Unless otherwise specified, use the "**Test unminified KeymanWeb**" test page.

**Suite tests**

- **TEST_RESIZING**:  Verify that desktop OSK resizing operates normally.

    <details><summary>Precise instructions</summary>

    Using the resize handle (image) for the desktop OSK, resize it at least three different ways.
     - The test "passes" if the OSK rescales according to the resize-handle's new position each time.  (The aspect ratio is _not_ locked, so narrow+tall and wide+short are both possible.)

    </details>

- **TEST_HARDWARE_SHIFT**:  A physical SHIFT keypress should affect the OSK's shift key.

    Using the `khmer_angkor` keyboard, press and hold your physical keyboard's `SHIFT` key.
    - Expected result:  on the OSK, the `shift` layer should be displayed and the `SHIFT` key highlighted.

- **TEST_OSK_KEY_SEQUENCE**:  Using the OSK with a keyboard for English, type "The ".  (Include the space)

    <details><summary>Detailed key sequence</summary>

    So, in sequence:
    - SHIFT
    - T
    - SHIFT (to return to the default layer)
    - h
    - e
    - (spacebar)

    </details>

### **SUITE_PHONE**:  `phone` form-factor tests (both in-app and out-of-app)

**Platform / browser combinations**:
- **GROUP_CHROME_EMU**:  Chrome emulation / iOS 

    Use the "**Prediction - robust testing**" test page.

- **GROUP_ANDROID**:  Android / System keyboard mode

    Ensure that predictive text is enabled for English.

- **GROUP_IOS**:  iOS / Keyman app

    Ensure that predictive text is enabled for English.

**Suite tests**

- **TEST_ROTATE_P-TO-L**:

    1. With Keyman not active, load it in a portrait orientation.
    2. Once loaded, rotate the device to a landscape orientation.
        - On Android devices, you may need to press something like this for the rotation to occur:
        - The test "passes" if the OSK rotates properly.

- **TEST_ROTATE_L-TO-P**:

    1. With Keyman not active, load it in a landscape orientation.
    2. Once loaded, rotate the device to a portrait orientation.
        - On Android devices, you may need to press something like this for the rotation to occur:
        - The test "passes" if the OSK rotates properly.

- **TEST_LAYER_CAPTIONING**:  Touch-OSK layer shifting + spacebar captioning

    Using the `sil_euro_latin` keyboard, swap among the 'default', 'shift', 'numeric', 'symbol', and 'currency' layers.
    - Expected results:
        - the layer should always change correctly.
        - the space bar should be properly captioned on each layer.

- **TEST_SWAP**:  Keyboard swapping via globe key

    With at least two total keyboards available / installed, confirm that swapping between them works properly.

- **TEST_BOUNDARY_KEYS**:  Use of keys on the keyboard's edges

    <details><summary>Detailed steps</summary>

    Using `sil_euro_latin`, use the following keys, pressing as close as possible to their respective edge of the keyboard:
    - `a` (use the key's left edge)
    - the spacebar (use the key's bottom edge)
    - `t` (use the key's top edge)

    All should output normally.

    </details>

- **TEST_PREDICTIONS**:  ensure that predictions work correctly.

    <details><summary>Detailed steps</summary>

    1. Set `sil_euro_latin` as the active keyboard.
    2. Ensure that predictions are enabled.
    3. Reload/refresh your test setup by force-closing, then restarting the app used for testing.
    4. With the reloaded keyboard active, verify that default suggestions are shown.
    5. Type "th" and verify that suggestions beginning with "th" are shown.

    </details>

### CODE REVIEW

**Comment by jahorton** [comment]
SUITE_PHONE

GROUP_IOS

TEST_SWAP:  Passed

Assuming that selecting one of the menu options swapped to the proper keyboard, this is what is intended.

**Comment by jahorton** [comment]
> > LGTM I guess -- most of this is chunks moved between files and it's kinda hard to tell what is new and what isn't. It would be good for more functions to have a header comment directly explaining their purpose.
> > For example, you have:
> > ```
> >     // Corresponds to the desktop OSK's _Show, but acts as a core, common method 
> >     // usable by all display patterns.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But it would be better to be explaining _directly_ here what the purpose of the function is (assume that the reader of the comment has never heard of `_Show`), with a side note at the end about how it relates to `_Show`.
> 
> Admittedly... I'm kind of still working that out; I plan to 'nix `_Show` entirely. (Well, or turn it into a pure 'legacy' wrapper of better-designed methods.) Currently in the design phase for a PR that'll clarify activation + visibility modeling; I had to triage it out of this one and its follow-up to keep complexity down. (Those two aspects are complex enough on their own to receive a focused PR.)
> 
> That's probably part of why I subconsciously wanted to leave things in draft for so long; I myself am not perfectly clear on it yet, but it's a _very_ useful stepping-stone to reaching clarity.

Things in this direction (management of OSK visibility and activation) will fully stabilize in #5661.  There are quite a few more changes by that point; I definitely needed the "stepping-stone" changes made here.   I've made sure to add plenty of documentation for the final set of related methods and properties in that PR.

**Comment by jahorton** [comment]
> > ## SUITE_DESKTOP: `desktop` form factor tests
> > 
> > * GROUP_WIN: Windows / Chrome
> >   
> >   * **TEST_RESIZING: PASSED** but there is a separate issue:
> >     When reposition, the keyboard minimizes itself to a bar.
> >     
> 
> Could you describe in more detail when you saw this and what you did to trigger it? I don't see anything of the sort on my machine, and it shouldn't be happening.

@MakaraSok

**Comment by mcdurdin** [comment]
> Admittedly... I'm kind of still working that out; I plan to 'nix `_Show` entirely. (Well, or turn it into a pure 'legacy' wrapper of better-designed methods.) Currently in the design phase for a PR that'll clarify activation + visibility modeling; I had to triage it out of this one and its follow-up to keep complexity down. (Those two aspects are complex enough on their own to receive a focused PR.)
> 
> That's probably part of why I subconsciously wanted to leave things in draft for so long; I myself am not perfectly clear on it yet, but it's a _very_ useful stepping-stone to reaching clarity.

All good, but really makes it even more important to have a code comment that stands on its own without reference to `_Show` :grin:

**Comment by jahorton** [comment]
In reply to your last concern:

> I've made sure to add plenty of documentation for the final set of related methods and properties in [that PR](https://github.com/keymanapp/keyman/pull/5661).

[original comment](https://github.com/keymanapp/keyman/pull/5620#issuecomment-912200929)

**Pull request merged**
