### PR TITLE
(pt-pt) translation improvements

### PR DESCRIPTION
**Pull request by mareuo**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by jahorton** [comment]
Note that we use Crowdin for our localization efforts; it would be best to contribute there.  If the same changes don't exist within our Crowdin project, they'll likely get overwritten in future updates.

If that is already in place, but we just haven't pulled that data in yet, our apologies, and thanks for making us aware. My coworker that usually handles the updates is out of office for a bit, so it's certainly something we could have missed.

**Comment by mareuo** [comment]
done

**Comment by jahorton** [comment]
Thanks!  My colleague is pulling in Crowdin updates now with #11974; hopefully that'll cover everything.  We'll double-check after it goes through.

**Comment by darcywong00** [comment]
Ah, I've already merged #11974 and only saw this PR now.

There's 2 merge conflicts on the mac [Localizable.strings](https://crowdin.com/editor/keyman/587/en-pt?view=comfortable&filter=basic&value=3). Can you check if Crowdin has your latest updates?

```
/* fonts label in the Package Information window */
<<<<<<< master
"fonts-label" = "Fontes:";
=======
"fonts-label" = "Tipos de letra:";
>>>>>>> master

/* message displayed to alert user to need grant accessibility permission */
<<<<<<< master
"privacy-alert-text" = "Para funcionar corretamente, o Keyman requer recursos de acessibilidade:\n\nConceda acesso em Definições do Sistema, Segurança & Privacidade.\nReinício do sistema.";
=======
"privacy-alert-text" = "Para funcionar corretamente, o Keyman requer recursos de acessibilidade:\n\nConceda acesso em Definições do Sistema, Segurança e Privacidade.\nReinício do sistema.";

/* Text of menu item in Input Menu when no Keyboards are configured -- include parentheses  */
"no-keyboard-configured-menu-placeholder" = "(Nenhum teclado configurado)";
>>>>>>> master
```

I'll close this PR, and we'll use the crowdin tooling to get additional updates as needed.

**Pull request closed without merging**
