### PR TITLE
fix(web): Make banner initialization more robust

### LINKED ISSUE #4794: bug(web): postConfigure on undefined
Sentry Issue: [KEYMAN-ANDROID-RQ](https://sentry.keyman.com/organizations/keyman/issues/4233/?referrer=github_integration)

```
sendKMWError
```

More info from the Sentry error

KMKeyboard.sendKMWError
packageID: indonesia
keyboardID: indonesia
keyboardType: SYSTEM
cm_message: Could not load model 'benny_lin.id.kamus_indonesia': Cannot read property 'postConfigure' of undefined
cm_sourceID: file:///data/data/com.tavultesoft.kmapro.debug/app_data/keyman-sentry.js
keyboardName: Indonesia
cm_lineNumber: 208

### LINKED ISSUE #4869: bug(android): Loading keyboard "indonesia" in Keyman for Android 14 causes fatal error
**Describe the bug**

`Fatal keyboard error with indonesia:indonesia for keyboard. Loading default keyboard`

I've had this bug for quite some time, today I'm trying to repro it for bug report.

**To Reproduce**

1. Go to Keyman for Android
2. Click on language selector, choose keyboad (Bahasa Indonesia: Indonesia)
3. Wait a couple of second

**Expected behavior**

I can use my keyboard 😂

**Screenshots**

---

**Keyman for iPhone/iPad/Android:**
 - Device: Nokia 2.2
 - OS: Android 10, 5 March 2021
 - Keyman version 14.0.270
 - Target application: Keyman 14.0.270, or WhatsApp 2.20.201.23, or Telegram 7.6.0
 - 
---

**Keyboard**
 - Keyboard name: Bahasa Indonesia https://keyman.com/keyboards/indonesia
 - Keyboard version: 1.0
 - Language name: Bahasa Indonesia (Indonesia)

**Additional context**

It worked fine in previous keyman that I had. The bug only occur after I updated it to version 14.0

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4794. 
Fixes #4869. 
Replaces PR #4795

When the suggestion banner is disabled, there's some keyboard transitions I saw in the Chrome debugger where the KMW banner state is `undefined`.
~This PR updates the banner to blank (or image) in these transitions.~
This PR improves the banner initialization so it won't get into invalid states

### User Testing
@MakaraSok 
1. Install the test build
2. From the Settings menu, install the `indonesia` keyboard.
3. Let the associated dictionary for indonesia install in the background
4. From the Settings menu, go to "Installed Languages" --> "Indonesia" and turn off suggestions
5. Exit back to the Keyman app
6. Use the globe button to toggle between sil_euro_latin and indonesia keyboards several times
7. Verify no KMW crashes (no Toast notifications about errors and falling back to default sil_euro_latin)

Without this change, even bringing up the keyboard picker and exiting out would be enough to cause a crash within 5 tries.

### CODE REVIEW

**Review by jahorton — CHANGES_REQUESTED** [review]
Again, something's wrong if that's being set to `undefined` at any point.  I'd rather understand the situation leading to it.

At least you've documented something approaching a repro; I'll investigate with that.  And... yep, worked swimmingly.

**Comment by jahorton** [comment]
Given the results of your investigation, I was able to quickly diagnose the cause and identify a clean fix.  Accordingly, I've written https://github.com/keymanapp/keyman/pull/4966 as a patch-PR for this.  (Don't feel like you need to wait for me to merge it if you like what you see.)

Pretty sure the `git blame` for the underlying root rests on me here.

**Comment by darcywong00** [comment]
I've updated this PR title to reflect the fixes from #4966

**Review by jahorton — APPROVED** [review]

**Comment by MakaraSok** [comment]
@darcywong00 No error was experienced when switching between keyboards multiple times within the Keyman app and as a system keyboard.

**Pull request merged**
