### PR TITLE
fix(web): use intended source for prediction-to-context matching 🔩

### PR DESCRIPTION
**Pull request by jahorton**
Originally part of #11424, this potential bug was spotted due to enforcing `"noUnusedLocals"` against the lm-worker codebase.  It's pretty clear that `finalInput` had an intended use... but... simply wasn't used.

It's notable that we haven't (knowingly) had any related bugs in the time it's been like this, so we're probably safer by _not_ 🍒-picking this change at this time.  I believe the change should actually be fine, as it would usually resolve to the same value, but there's little reason to risk it at this time.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM, although it would be good to know what the end-user impact is -- if there is no impact then surely we should just be deleting `finalInput` and using `inputTransform` after all?

**Comment by jahorton** [comment]
> LGTM, although it would be good to know what the end-user impact is -- if there is no impact then surely we should just be deleting `finalInput` and using `inputTransform` after all?

Followup set as #11620.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Pull request merged**
