### PR TITLE
chore(common): Update crowdin strings for Spanish (es-ES and es-419)

### PR DESCRIPTION
**Pull request by darcywong00**
This adds localization for Spanish (es-ES) and disambiguates the existing locale name for Spanish - Latin America (es-419).
* **Español** for es-ES
* **Español - Latinoamérica** for es-419

TODO
- [x] @jahorton to add `es` locale for iOS and macOS projects

## User Testing
**Setup** - Install the PR build of Keyman for the corresponding platforms

GROUP_WINDOWS - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for Windows
GROUP_MACOS - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for macOS
GROUP_LINUX - Verifies Spanish locales (es_ES and es_419) on Keyman for Linux 
GROUP_ANDROID - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for Android
GROUP_IOS - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for iPhone and iPad

* **TEST_SPANISH_LOCALES** - Verifies Spanish locale on Keyman
1. Launch Keyman
2. Verify UI can be changed to Spanish /  Español 
3. Verify UI can be changed to Spanish - Latin America / Español - Latinoamérica

### CODE REVIEW

**Review by ermshiperete — APPROVED** [review]

**Comment by bharanidharanj** [comment]
### GROUP_WINDOWS: - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for Windows

* **TEST_SPANISH_LOCALES (PASSED):** Tested with the attached Keyman build (17.0.126-alpha-test-9040) in Windows 11 OS (VM) and here is my observation: 1. Verified that the UI can be changed to Spanish  2. Verified that the UI can be changed to Spanish - Latin America. 

..Spanish UI

   

   

..Spanish - Latin America UI

**Comment by bharanidharanj** [comment]
### GROUP_LINUX: - Verifies Spanish locales (es_ES and es_419) on Keyman for Linux 

* **TEST_SPANISH_LOCALES (PASSED):** Tested with the attached Keyman build (17.0.126-alpha-test-9040) in Ubuntu Focal 20.04 Linux OS (VM) and here is my observation: 1. Verified that the UI can be changed to Spanish 2. Verified that the UI can be changed to Spanish - Latin America. I noticed that some buttons are still holding with english label names. (Download Keyboard, Options, Keyboard layouts etc.,)

..Spanish UI

   



..Spanish - Latin America UI

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for Android

* **TEST_SPANISH_LOCALES (PASSED):** Tested with the attached Keyman build (17.0.126-alpha-test-9040) in Android 12 / API 31 emulator and here is my observation: 1. Verified that the UI can be changed to Spanish 2. Verified that the UI can be changed to Spanish - Latin America.

..Spanish UI

   

   


..Spanish Latin-America UI

**Comment by bharanidharanj** [comment]
### GROUP_IOS: - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for iPhone and iPad

* **TEST_SPANISH_LOCALES (PASSED):** Tested with the attached Keyman build (17.0.126-alpha-test-9040) in iOS 16.4 / iPhone Max Pro Simulator and here is my observation: 1. Verified that the UI can be changed to Spanish 2. Verified that the UI can be changed to Spanish - Latin America.

..Spanish UI

   
   


   


..Spanish Latin-America

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MACOS: - Verifies Spanish locales (Español and Español - Latinoamérica) on Keyman for macOS

* **TEST_SPANISH_LOCALES (PASSED):** Tested with the attached Keyman build (17.0.126-alpha-test-9040) in iOS 16.4 / iPhone Max Pro Simulator and here is my observation: 1. Verified that the UI can be changed to Spanish 2. Verified that the UI can be changed to Spanish - Latin America.

..Spanish

   

   


..Spanish Latin-America

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.129-alpha](https://keyman.com/downloads/releases/alpha/17.0.129)

**Pull request merged**
