### PR TITLE
chore(web): merge `master` into `epic/web-core` 🎼

### PR DESCRIPTION
**Pull request by ermshiperete**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
This PR is currently targeting `master` -- that doesn't seem right.

**Comment by ermshiperete** [comment]
> This PR is currently targeting `master` -- that doesn't seem right.

Oops! Thanks for noticing! Would be quite a lot of commits for a merge from master into master :smile:

**Review by rc-swag — APPROVED** [review]
RSLGTM

**Comment by mcdurdin** [comment]
FWIW, I have a script which does this automatically each sprint -- no need to do it by hand.

**Pull request merged**
