### PR TITLE
epic: conversion of Keyman Engine for Web to ES modules 🧩

### PR DESCRIPTION
**Pull request by jahorton**
This is the base branch for an ongoing conversion of Keyman Engine for Web code; when complete, it will be based upon use of ES modules rather than the old "namespace"-style structure it was previously using.

Other goals include complete modularization of Keyman Engine for Web's on-screen keyboard component.  While still included in KMW, it will also be able to function independently and be compilable as a standalone project.  As we are considering reuse of Web's OSK within the desktop-platform Keyman apps, this will be a very notable step toward accomplishing such a goal.

At this time, this branch also includes an update for Web's README.md corresponding to the changeset from the 📜 set of Web code reorganization PRs ending with #7831.  (It should be re-updated again near completion.)

------

Approximate state of modularization so far (so GitHub won't hide the comment on us):

```mermaid
graph TD;
    OSK[web/src/engine/osk];
    KP["common/web/keyboard-processor"];
    IP["common/web/input-processor"];
    OSK-->KP;
    IP-->KP;
    Utils["common/web/utils"];
    KP---->Utils;
    Wordbreakers["common/models/wordbreakers"];
    Models["common/models/templates"];
    Models-->Utils;
    LMWorker["common/web/lm-worker"];
    LMWorker-->Models;
    LMWorker-->Wordbreakers;
    LMLayer["common/predictive-text"];
    LMLayer-->LMWorker;
    IP-->LMLayer;

    subgraph PredText["WebWorker + its interface"]
        LMLayer;
        LMWorker;
        Models;
        Wordbreakers;
    end

    subgraph Headless["Fully headless components"]
        direction LR
        KP;
        IP;
        Utils;
        PredText;
    end

    subgraph ClassicWeb["Previously unmodularized components"]
        Device[web/src/engine/device-detect];
        Device----->Utils;
        Elements[web/src/engine/element-wrappers];
        Elements-->KP;
        KeyboardCache[web/src/engine/package-cache];
        KeyboardCache-->IP;
        DomUtils[web/src/engine/dom-utils];
        DomUtils-->Utils;
        OSK-->DomUtils;
        OSK---->IP;
        Configuration[web/src/engine/paths];
        Configuration-->OSK;
        CommonEngine[web/src/engine/main];
        CommonEngine-->Configuration;
        CommonEngine-->Device;
        CommonEngine-->KeyboardCache;
        CommonEngine-->OSK;
        Attachment[web/src/engine/attachment];
        Attachment-->DomUtils;
        Attachment-->Elements;
    end

    subgraph WebEngine["Keyman Engine for Web (top-level libraries)"]
        Browser[web/src/app/browser];
        WebView[web/src/app/webview];

        WebView--->CommonEngine;

        Browser--->CommonEngine;
        Browser-->Attachment;
    end
```

(This technically includes changes from not-yet-published commits, but it's pretty accurate to where things are headed.)

Note that the `element-wrappers` child package will be referenced by the `app/browser` target, which is not included in the graph above.  (It'd rest higher up.)

------

Pending tasks of note:
- [x] Fully modularize all of KMW
    - Achieved by everything through #8891.
- [x] Unit test scripts for CI builds should be defined in the new ./ci.sh test action from #8001, rather than Web's ./build.sh or ./test.sh.
    - Handled by #8830.
- [x] #8148 
- [x] Address, then resolve all comments for #8055.
    -  They're loose threads that were unresolvable at the time.
    - Being handled by #8963.
- [x] SO MANY loose threads for #8056... but there's no clear checklist for them.
    - General guideline for this:  check all doc-comments for all "EventMap" types in the following files:
        - [x] oskView.ts
        - [x] visualKeyboard.ts
        - There may be others, but those are the main two of note... and that I could find with preserved 'original implementation' code.
        - Partially(?) addressed by https://github.com/keymanapp/keyman/pull/8630.
- [x] Ensure that no regression in line with https://github.com/keymanapp/keyman/issues/3910 occurs.  (Can be expensive long-term if we let that one slip by!)
    
    image

    (Verified with #8891)

- [x] Follow-up on https://github.com/keymanapp/keyman/pull/8624#discussion_r1191843605:  duplication of OSK hide & show events
    - See #8970.
- [x] There are some notable inconsistencies with internal event nomenclature, as noted by https://github.com/keymanapp/keyman/pull/8591#discussion_r1174745023
    - Handled in #9012.
- [x] I've probably mucked up a lot of the tsconfig project references.  It's "fine" when using our build script infrastructure, but it'd likely lead to unintended compilation issues if someone were to ignore them.
    - Handled by #8830.
- [x] It would be wise to look through the various build-bundler.js implementations and determine a common set of config options that could be inherited by all components.
    - Handled by #9025.
- [x] It would also be wise to look through all the tsconfig.json configurations and determine the maximal common set for Web. 
    - We'll want something like this for the full repo eventually.  Having a top-level Web variant should help with that future effort.
    - Handled in #9011.
- [x] Test against this keyboard: https://help.keyman.com/keyboard/english_shavian_qwerty/1.0/english_shavian_qwerty
    - A published keyboard that actually implements `K_ROPT` (the "hide keyboard" key) on the touch layout, even in-app.  An edge case I'll easily miss if not careful.
    - Verified with #8891 on Android.  Should still add an Android and an iOS user test for it.
- [x] As requested at https://github.com/keymanapp/keyman/pull/8821#discussion_r1206174982, we should add explicit documentation for public-API functions and methods.
    - That comment was for a specific instance, but the principle is probably intended for all API functions.
    - Addressed by #9036.
- [x] Thorough testing of selection, start-of-context behavior, etc.
    - https://github.com/keymanapp/keyman/pull/8462#issuecomment-1475698005
    - See #7865 and #7866.  We haven't fully addressed them yet, but there's some material in there good for reproducing certain issues that could be adaptable into user tests.
- Re user-testing: 
    - [x] https://github.com/keymanapp/keyman/pull/8905/files#r1222280122
        - Developer test-host page testing on mobile devices / under mobile emulation
    - [x] See #8963.
- [x] Before merging, run a full regression-test suite on KMW and the mobile apps in order to find possible regressions.
- [x] Update keymanweb.com to use boolean `false` instead of string `'false'` for KMW's `setActiveOnRegister` initialization option when using KMW 17.0+: https://github.com/keymanapp/keyman/pull/8458#discussion_r1147289009
    - See https://github.com/keymanapp/keymanweb.com/pull/75, which should merge when this lands.

Note: Refer also to #8047, the original version of this PR before a `git merge` disaster happened on what was intended as a child PR.

## User Testing 

Due to the scale of user testing involved, the actual user tests will be posted under separate issues:

TEST_MAIN_WEB:  See https://github.com/keymanapp/keyman/issues/9037 / https://github.com/keymanapp/keyman/issues/9037#issuecomment-1596692617.
- Only pass when _all_ tests in #9037 pass acceptably.

TEST_OTHERS:  See https://github.com/keymanapp/keyman/issues/9039 / https://github.com/keymanapp/keyman/issues/9039#issuecomment-1596774336
- Only pass when _all_ tests in #9039 pass acceptably.

TBD(?):  do the mobile apps need their own full regression tests again?

### CODE REVIEW

**Comment by jahorton** [comment]
For any changes before this point, refer to #8047 and its descendant PRs, which were all merged properly after reviews - that is, before the accidental merge disaster triggered by merging #8549, which had its base branch improperly set.

Anything after this point is from work after the necessary git-reversion shenanigans that were needed to patch up the state of the repo.

**Comment by jahorton** [comment]
TEST_OTHERS: PASSED

TEST_MAIN_WEB:  PASSED - Though an issue did arise for one of the tests due to differences between a test keyboard's phone and tablet layouts.  I've made tweaks accordingly.

- [ ] When merging, copy #9037's description over as the new content for the [Platform Acceptance Test for Web wiki page](https://github.com/keymanapp/keyman/wiki/Platform-Acceptance-Test-for-Web).
    - But do include the wiki page's `SUITE_INSPECT` in its original position.
    - Do a find-and-replace on its URL links when copying the description text over:  `Keymanweb_TestPullRequests/390024:id/src` => `Keymanweb_TestPullRequests/TBD:id/src`, since that's the established pattern for the Wiki's version of acceptance testing.

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.130-alpha](https://keyman.com/downloads/releases/alpha/17.0.130)

**Pull request merged**
