### PR TITLE
chore(common): Update to Unicode 16.0

### PR DESCRIPTION
**Pull request by darcywong00**
Unicode 16.0.0 was recently [released](https://www.unicode.org/versions/Unicode16.0.0/)

## Changes
* Update KEYMAN_VERSION_UNICODE to 16.0.0
* Download Unicode.16.0 characters using the resources/standards-data/unicode-character-database/download.sh script

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
Investigating core unit test fails
```
Test failed at ../../../tests/unit/ldml/test_unicode.cpp:175:
02:45:08   expected: 16
02:45:08   actual:   15
```

**Comment by srl295** [comment]
> Investigating core unit test fails
> 
> ```
> Test failed at ../../../tests/unit/ldml/test_unicode.cpp:175:
> 02:45:08   expected: 16
> 02:45:08   actual:   15
> ```

@mcdurdin @darcywong00 so… the test is working as designed. 
The problem here is that it needs ICU4C v76 which isn't release for another month, and then Node.js based on that. 

I assume keyman 18 release will be after those dates, so perhaps we need some way to skip this test until a later phase?

**Comment by srl295** [comment]
@darcywong00 if you need to unblock & assign me an issue to followup:

```diff
diff --git a/core/tests/unit/ldml/test_unicode.cpp b/core/tests/unit/ldml/test_unicode.cpp
index b36f1a3e38..ea670c2437 100644
--- a/core/tests/unit/ldml/test_unicode.cpp
+++ b/core/tests/unit/ldml/test_unicode.cpp
@@ -172,7 +172,7 @@ const std::string &block_unicode_ver) {
   // the cxx_icu can come from the Ubuntu environment, so do not depend on it
   // for now.
   //assert_basic_equal(node_icu_unicode_major, cxx_icu_unicode_major);
-  assert_basic_equal(node_icu_unicode_major, block_ver_major);
+  // assert_basic_equal(node_icu_unicode_major, block_ver_major);
 
   // seems less important if the C++ ICU verison matches the Node.js ICU version.
   //assert_basic_equal(cxx_icu_major, node_icu_major);
```

**Review by srl295 — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.110-alpha](https://keyman.com/downloads/releases/alpha/18.0.110)

**Pull request merged**
