### PR TITLE
[web] [iOS] [Android] Adjust position of subkeys and key previews

### LINKED ISSUE #1848: [iOS] Long press repeating characters in recent 12.0 alpha builds
I don't know if this is related, but there are issues with long press repeating characters in this build. For example, with Khmer Angkor, type សួស្តី and it comes out as សួសត្តី. Only appears to happen in iOS native app, not in KeymanWeb on iOS with same keyboard.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/1824#issuecomment-504248985_

### LINKED ISSUE #1850: [iOS] key previews and popups are offset in 12.0 alpha
**Describe the bug**

The key preview and longpress popups are offset due to the banner positioning in the latest 12.0 alphas. Appears to be an issue in system and in-app keyboards. Presence or absence of banner doesn't seem to affect the issue, suggesting that the calculation just needs to subtract the previous iOS-implemented banner height.

**Screenshots**

---
  
**iPhone/iPad:**
 - Device: iPhone 7
 - OS: iOS 12.3.1
 - Keyman version 12.0 alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #1850 
Fixes #1848 

This needs test against Android to ensure it doesn't affect calculations there (working on it now).

Also fixes init order error with `correctOSKTextSize` which would occur in some situations.

The reason it fixes #1848 is that the longpress popup was overlapping the key, which meant that the web control received a touch release at the same time as the popup, so two events were fired.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/155370:id/kvk/index.html)

**Comment by mcdurdin** [comment]
Last issue with the PR was due to a bug in an earlier PR which had since been corrected: longpress menus were crashing on Android, because of an inverted test in KMKeyboard.java `onTouchEvent`. All looking pretty solid now.

**Comment by jahorton** [comment]
I don't see any net change on Android... so hopefully that's what we're expecting?  Longpress still works as well as ever, shows up in the same position, etc.

**Comment by mcdurdin** [comment]
> I don't see any net change on Android... so hopefully that's what we're expecting? Longpress still works as well as ever, shows up in the same position, etc.

Yes, reworking this impacted Android because I removed iOS-specific code so then had to go and fix Android as well. So I wanted both platforms to be tested given this. As far as I can remember, on `master` Android was fine.

**Pull request merged**
