### PR TITLE
fix(android): hardware keystrokes now include mnemonic processing 🧓

### PR DESCRIPTION
**Pull request by jahorton**
Addresses at least part of #10159.

The current changeset is sufficient to resolve the issue within the Keyman for Android app without breaking other keyboards.

Related tasks:
- [x] Add unit tests for conversion of 'normal' key events to mnemonic, legacy ones
    - See #10464.

## User Testing

TEST_ANDROID_IPA: With an external hardware keyboard connected to an Android device, use Keyman for Android with the `sil_ipa` keyboard.

1. Connect an external (usb) keyboard to the Android mobile device. 
2. Within the Keyman app, use the keyboard-search to install the `sil_ipa` keyboard, then activate it.
3. Type "n >" using an external keyboard in the text area.
4. Expected result: `ŋ`

TEST_ANDROID_EUROLATIN: With an external hardware keyboard connected to an Android device, use Keyman for Android with the `sil_euro_latin` keyboard.

1. Connect an external (usb) keyboard to the Android mobile device. 
2. Within the Keyman app, use the keyboard-search to install the `sil_euro_latin` keyboard, then activate it.
3. Type `o \ e` using an external keyboard in the text area.
4. Expected result: `œ`
5. Hit Enter twice.
6. Type `= e` using an external keyboard in the text area.
7. Expected result: `ə`

Minor notes:
- `sil_ipa` is mnemonic.
- `sil_euro_latin` is not mnemonic _on mobile platforms / in KeymanWeb_.  (It _is_ mnemonic for the main desktop apps, though.)

### CODE REVIEW

**Comment by jahorton** [comment]
File-size check is almost certainly due to merging with `master` today shortly after merging in #7934.

**Review by mcdurdin — APPROVED** [review]
LGTM although I think that we should be aware that neither positional nor mnemonic layouts work correctly on KMW on non-us base layouts.

**Review by ermshiperete — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID_IPA (FAILED):** Crash while opening the Keyman app, after installing it. 

   


* **TEST_ANDROID_EUROLATIN (FAILED):** Crash while opening the Keyman app, after installing it.

**Comment by jahorton** [comment]
@keymanapp-test-bot retest all

In line with https://github.com/keymanapp/keyman/pull/10465#issuecomment-1904983394, I'm assuming there was something on master momentarily (at the time of this PR's creation/rebase) that's since been corrected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.250-alpha](https://keyman.com/downloads/releases/alpha/17.0.250)

**Pull request merged**
