### PR TITLE
fix(ios/engine): engine migration always precedes installs

### PR DESCRIPTION
**Pull request by jahorton**
Fixes an issue reported through other channels by a third-party KeymanEngine user that seemed to obliterate keyboards installed on their app's first launch (and _only_ during that first launch).  Should be 🍒-picked, as the underlying issue can cause similar unintuitive issues for other 3rd-party framework users.

------

The changes to resource installation in 14.0 did a lot to disentangle the process for installing keyboards and models from KeymanEngine's `Manager` monolith-class.  Unfortunately, it turns out there was one subtle but critical strand of entanglement that wasn't quite removed.

While resource installation itself isn't dependent on a `Manager` instance existing, the `Migrations` system called early on in `Manager`'s init _must_ run _before_ any resources are installed; otherwise, its current logic will obliterate anything newly installed.  Think of it this way: for new installs, it's very much like installing resources for the 14.0 format, then saying "now update those resources from the 2.0 format to the 14.0 format."  _Technically_, it's an issue with the `Migrations` subsystem, but it's actually rather hard to fix within it due to limitations with the last-engine-version detection system.  (Especially in a way that would be safe to 🍒-pick for `stable`.)

Fortunately, all that modularity makes it possible for us to transplant the code responsible for running `Migrations`.  (I ran a trace and performed a test run to ensure there are no accidental recursion shenanigans occurring.)  Making it part of `ResourceFileManager` now makes sense.  While it can't be run as part of the class's `init`, as `Migrations` does need to refer back to `ResourceFileManager`, a little state tracking will pave a way for the class to ensure that the `Migrations` subsystem always runs first.

## User Testing

@keymanapp/testers 

- [ ] TEST_DIRTY:  Ensure that the iOS app successfully launches when installed over a previous, customized installation.
    - Verify that all previously-installed keyboards are still installed.
    - Swapping among the keyboards via the picker is enough to tell us what we need.

- [ ] TEST_CLEAN:  Ensure that the iOS app successfully launches from a _clean_ install.
    - There are two ways to do this:
        - Set Xcode to target a device that you have not previously used for any tests.
        - Reset a simulated device that you have previously used:

            image

            Run that to reset a simulated device, which will erase all existing Keyman settings on said simulated device.

### CODE REVIEW

**Comment by jahorton** [comment]
Note for self:

- [ ] TEST_DEV:  Modify KMSample1 by removing the following line:

    https://github.com/keymanapp/keyman/blob/049ffc90807d738a49931254545f42fe726d759d/ios/samples/KMSample1/KMSample1/ViewController.swift#L16

    Ensure that the sample app still loads properly and displays the installed keyboard.  (Doing so on `master` should repro the original error.)

That one line is what stood in the way of us catching the problem ourselves earlier; that early reference to `Manager` initializes it and thus triggered `Migrations`.  The 3rd-party engine user who experienced the issue didn't have a similar line of code.

**Comment by jahorton** [comment]
Well... seems like that change isn't enough to repro the issue on `master`.  This is likely because of the `TextView` class, which will initialize `Manager.shared` during its `performCommonInit()` method (called during class init).  As it's part of an .xib spec, that's... gonna be harder to stub out temporarily for a full, authentic repro test.

I can confirm that the change doesn't seem to _break_ anything, at least.

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by MakaraSok** [comment]
## User Testing

@keymanapp/testers 

- [x] TEST_DIRTY: **PASSED** 
    - the iOS app successfully launches when installed over a previous, customized installation
    - all previously-installed keyboards are still installed

_before installing this build, there are four keyboards in the keyboard menu; and after installing this build the four keyboards are still there. Swapping between keyboards is not an issue._

- [x] TEST_CLEAN: **PASSED** - the iOS app successfully launches from a _clean_ install

_Xcode was set to target iPhone SE (2nd Gen) which has not previously been used for any tests._

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.90-alpha](https://keyman.com/downloads/releases/alpha/15.0.90)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.90-alpha](https://keyman.com/downloads/releases/alpha/15.0.90)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.90-alpha](https://keyman.com/downloads/releases/alpha/15.0.90)

**Pull request merged**
