### PR TITLE
fix(ios/engine): package installation language-picker improvements

### PR DESCRIPTION
**Pull request by jahorton**
Already-installed resources from a package were previously set to be installable upon download / install-from-file.  These should be pre-marked.  (Note the greyed options.)

Additionally, if a package supports multiple languages for a resource and the first language is already installed, the default selection shifts to the first language not currently paired with the resource.

Screen Shot 2020-09-28 at 10 04 54 AM

Previously-installed language pairings may be selected for reinstallation:

Screen Shot 2020-09-28 at 10 02 30 AM

This _should_ reinstall _all_ possible resource pairings for that language, even if some were manually removed.  Otherwise, only currently-installed resource pairings will be updated.  If the resource is then deselected, the grayed-out formatting will be restored.

"Install" will still be selectable even if no _new_ selections have been made... as long as at least one resource pairing from the package has already been installed.

Screen Shot 2020-09-28 at 10 08 43 AM

If nothing has been previously installed from the package _and_ nothing is marked for installation, then the "Install" button will be unselectable.  (Even if something was previously picked; this aspect hadn't been working correctly before.)

Screen Shot 2020-09-28 at 10 09 16 AM

### CODE REVIEW

**Comment by darcywong00** [comment]
> Additionally, if a package supports multiple languages for a resource and the first language is already installed, the default selection shifts to the first language not currently paired with the resource

I wonder if a better UX is to disable the "Select language(s)" button until the user chooses a language.

If the keyboard package came from keyman.com with a BCP47 tag, I think we should still have that as the default selection.

**Comment by jahorton** [comment]
> If the keyboard package came from keyman.com with a BCP47 tag, I think we should still have that as the default selection.

Oh right, I didn't mention this.  I've already set that in place, too.  If the code is supplied, it will be automatically selected even if a prior installation exists.

**Comment by jahorton** [comment]
> > Additionally, if a package supports multiple languages for a resource and the first language is already installed, the default selection shifts to the first language not currently paired with the resource
> 
> I wonder if a better UX is to disable the "Select language(s)" button until the user chooses a language.

I mean, I could be wrong... but we wouldn't be providing a 'default' selection in the first place if requiring manual selection were the better UX.

**Comment by mcdurdin** [comment]
> Previously-installed language pairings may be selected for reinstallation:

Does this mean that greyed out entries may be selected by touching on them? That's a fairly non-standard UI metaphor, if so.

**Comment by jahorton** [comment]
> > Previously-installed language pairings may be selected for reinstallation:
> 
> Does this mean that greyed out entries may be selected by touching on them? That's a fairly non-standard UI metaphor, if so.

For most of the branch's development, they weren't selectable.  Then... I realized that they probably should be selectable, so I re-enabled them.  What would be a better UI metaphor?

At least I abstracted all the table-cell style specification into one central method, so it'll be easy to tweak if we'd like.

**Comment by mcdurdin** [comment]
> What would be a better UI metaphor?

I think my first question is, what is the difference between grey tick and selected tick? i.e. what does Keyman do differently? Does Keyman need to do anything differently for those two scenarios?

**Comment by jahorton** [comment]
> > What would be a better UI metaphor?
> 
> What is the difference between grey tick and selected tick? i.e. what does Keyman do differently? Does Keyman need to do anything differently for those two scenarios?

Gray tick:
- the user has _not_ selected the language for installation.  (This is that language's "base state" for the screen.)
- the corresponding resource-language pairing already has (at least) one existing installation from the package.
    - like how the old cloud-based language picker marked resources that were already installed
- if left gray when "Install" is clicked:
    - Previously installed resources for that language will be updated / (re-)installed.
    - No missing resources will be installed.
        - For example, if a package contains two 'en'-supporting keyboards, the user installs for 'en', then removes 1 of the 2... this state will _not_ reinstall the one that the user removes.

Selected tick:
- the user has actually selected the language for installation.
- will install _all_ resources for that language from the package
    - all previously-installed resources will be updated
    - any missing resources will be installed
        - In this example, the previously-removed resource will be restored.

**Comment by mcdurdin** [comment]
Okay. I understand the difference. But I think it's too subtle to expect the average user to understand it! 

IMO, the grey tick should be read only on this screen.

I don't think we really need to have the selected tick option for already-installed resources -- the user can always re-add the missing language link themselves, or uninstall+reinstall the package in the worst case.

That probably doesn't simplify the code but should simplify the documentation 😉

**Comment by jahorton** [comment]
> IMO, the grey tick should be read only on this screen.
> 
> I don't think we really need to have the selected tick option for already-installed resources -- the user can always re-add the missing language link themselves, or uninstall+reinstall the package in the worst case.

This _is_ how they'd re-add the missing language link, at least with the current state of iOS.  There's no separate language-association menu like there is for Android.  Alternatively, they'd have to remove all other package-supported resources for the affected language... which doesn't make for the simplest documentation.  (There's no general "uninstall the whole package" option anywhere.)

**Comment by mcdurdin** [comment]
> I've said all along that this was the iOS reinstall strategy for this use case; it's just now becoming more formal as part of the UI.

I think I need to see the whole UI model to understand this. It feels like we are hiding away some things that may need to be visible. For example: how does a user add a language for just one of the two keyboards in a package? Or remove a language association for just one of the keyboards (for example, think of a package like the [Heidelberg Input Solution](https://keyman.com/keyboards/heidelberginputsolution), which has multiple keyboards for Devanagari -- but the typical user will want only one of them; yes I know this is only desktop at present...).

**Comment by jahorton** [comment]
> I think I need to see the whole UI model to understand this. It feels like we are hiding away some things that may need to be visible. For example: how does a user add a language for just one of the two keyboards in a package? Or remove a language association for just one of the keyboards (for example, think of a package like the [Heidelberg Input Solution](https://keyman.com/keyboards/heidelberginputsolution), which has multiple keyboards for Devanagari -- but the typical user will want only one of them; yes I know this is only desktop at present...).

At install time, all package resources for each selected language will be installed.  No options past "which language?".

After that, the user is free to go to Settings > Installed Languages > (language) and remove the unwanted keyboards there.

**Comment by mcdurdin** [comment]
> After that, the user is free to go to Settings > Installed Languages > (language) and remove the unwanted keyboards there.

But they cannot add another language from there? That feels awkward.

**Comment by jahorton** [comment]
> > After that, the user is free to go to Settings > Installed Languages > (language) and remove the unwanted keyboards there.
> 
> But they cannot add another language from there? That feels awkward.

We _could_ add a new menu item on the ResourceInfoView (this thing)

Screen Shot 2020-09-28 at 12 29 17 PM

to add extra languages, I suppose.  It's technically an extra layer deep, though.

Keep in mind that the user already has direct access to the package via Install From File at a higher-level menu; the iOS app caches all installed packages.  (In theory, to facilitate sharing the packages ad-hoc style.)

**Comment by mcdurdin** [comment]
> Keep in mind that the user already has direct access to the package via Install From File at a higher-level menu; the iOS app caches all installed packages. (In theory, to facilitate sharing the packages ad-hoc style.)

Yeah, I know that, but that's not the first place I'd look to add another language for a given keyboard. It may be worth doing some design review I think to ensure that the Android and iOS experiences don't diverge unnecessarily.

**Review by mcdurdin — APPROVED** [review]
LGTM; we'll review any design changes as a later task

**Pull request merged**
