### PR TITLE
chore(ios,windows): Update crowdin strings for Azerbaijani

### PR DESCRIPTION
**Pull request by darcywong00**
One of the translators on translate.keyman.com flagged 3 Windows strings for Azerbaijani as incorrect. Here's the 3 strings.

*Update:*
It's grown to 40+ strings. Per Ken
> I read through several of the issues, and I think his translation is okay.

## User Testing
@keymanapp/testers 

We generally haven't done any special testing when updating Crowdin strings. You can:

### Test 1 - Keyman for Windows
* Get the test build installer and select "Azerbaycanca" (closest resemblance  of  typing "Azerbaijani") during Setup
keyman setup - az
* After Setup finishes, open Keyman Configuration --> Display In --> Azerbaijani
* Spot check the Keyman UI

### Test 2 - Keyman for iPhone and iPad
* This probably involves building the app from this branch. I'm not familiar with how you'd set the locale for Azerbaijani

### CODE REVIEW

**Comment by darcywong00** [comment]
Putting this back to draft for a second translator to confirm the additional 40+ changes.

**Comment by darcywong00** [comment]
ok , going back to draft as the translator is now updating other platforms...

**Comment by darcywong00** [comment]
> Display In --> Azerbaijani

Hmm, this doesn't appear as an option in the latest stable 14.0.279. Will have to check if the string was correctly translated...

**Comment by MakaraSok** [comment]
## User Testing
@keymanapp/testers 

### Test 1 - Keyman for Windows - **PASSED**
*  no obvious issues in both the configuration and the taskbar menu

### Test 2 - Keyman for iPhone and iPad​ - **FAILED**
_This is based off of the build on this PR._
* "Get Started" is still in English. 
   image

* "Spacebar Caption" is shown up as something else.
   image

* Other things under "Spacebar Caption" are also shown up something else.
   image

_These are also observed when choosing Khmer as the UI language._

**Comment by darcywong00** [comment]
> "Get Started" is still in English

Keyman for iPhone and iPad has a menu string  `menu-get-started` for "Get Started". Maybe @jahorton knows if the "Get Started" panel should be updated to use that too.

**Comment by jahorton** [comment]
> When I looked in crowdin, I didn't see strings for "Spacebar Caption". Maybe dictionary keys needs to be generated for them?

Those _are_ the dictionary keys.  It looks as if they didn't get initialized / uploaded to Crowdin, though.

**Comment by darcywong00** [comment]
Looking at https://github.com/keymanapp/keyman/blob/ef747ffa697736c0d22b691f4806db636656db37/ios/keyman/Keyman/Keyman/en.lproj/Localizable.strings#L70-L78
I see the "Get Started" items are localized, but not the title for "Get Started". This can be created as a separate issue from this PR which is updating the Azerbaijani strings.

**Comment by MakaraSok** [comment]
> * "Spacebar Caption" is shown up as something else.

This issue might have to be fixed in this PR.

**Comment by darcywong00** [comment]
> This issue might have to be fixed in this PR.

I've created #5531 as a separate issue to address the UI strings still in English.
It's separate from this PR which only updates Azerbaijani strings.

**Comment by jahorton** [comment]
> > "Get Started" is still in English
> 
> Keyman for iPhone and iPad has a menu string `menu-get-started` for "Get Started". Maybe @jahorton knows if the "Get Started" panel should be updated to use that too.
> 
> When I looked in crowdin, I didn't see strings for "Spacebar Caption". Maybe dictionary keys needs to be generated for them?

Ah, I see how that got missed.  That string is built into the XIB... but fortunately, it's on an exposed item that should be easy to update.  Pushed a one-line fix for it.

Granted, it's not in Azerbaijani, but...

<details>
<summary>Confirmation</summary>

My emulated test device was set up to facilitate a quick and easy test with Spanish, which does have a l10n already.

image

So, that should fix that noted issue.

</details>

**Review by mcdurdin — APPROVED** [review]
LGTM. Even if there are minor additional future updates, this is a good iteration.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.94-alpha](https://keyman.com/downloads/releases/alpha/15.0.94)

**Pull request merged**
