### PR TITLE
fix(ios/samples): samples should use package-oriented API 🍒 

### PR DESCRIPTION
**Pull request by jahorton**
A 🍒-pick of #4771.

We can easily wait for a few other issues to arise before merging this; it's almost 100% sample-focused.  We _will_ want this merged eventually though - both our help docs and our engine presentation will require it.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM. Can merge when ready; stable builds are triggered manually so that won't cause a build by itself.

Note: automatic `HISTORY.md` changes to `stable` branches will need to be manually copied into `master` in order for them to be published to help.keyman.com.

**Comment by jahorton** [comment]
> LGTM. Can merge when ready; stable builds are triggered manually so that won't cause a build by itself.
> 
> Note: automatic `HISTORY.md` changes to `stable` branches will need to be manually copied into `master` in order for them to be published to help.keyman.com.

Hmm.  What's the best way to handle this?  As a part of 
> stable builds are triggered manually

or on a case-by-case basis through follow-up PRs?

**Comment by mcdurdin** [comment]
> What's the best way to handle this?

I think it would be good to do it straight after triggering the stable build, because that will update HISTORY.md on the stable-14.0 branch. I just need to remember to do it!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.271](https://keyman.com/downloads/releases/stable/14.0.271)

**Pull request merged**
