### PR TITLE
chore(core): feature-ldml merge from master, again 🙀

### PR DESCRIPTION
**Pull request by srl295**
Some merge with your merge!

Followon to #7884 tracking everything on master since that point.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/84108876@N00/5359422568" title="Splitting and Merging">Splitting and Merging</a>
''Photo credit: Jason Pratt''

#7042 🙀 

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
@mcdurdin OK this should be a shoo-in assuming it passes!

**Comment by srl295** [comment]
Definitely need to make sure tests pass, merged #7884  too quickly

**Review by mcdurdin — APPROVED** [review]
LGTM. If tests don't pass, we can revisit!

**Comment by srl295** [comment]
@mcdurdin  all passed!

**Pull request merged**
