### PR TITLE
[Android] Use file browser to navigate to install local .kmp files

### LINKED ISSUE #629: [Android] KMP not installing with Samsung "My Files" browser
User reports during a demo that the intent for KMP wasn't triggering Keyman to install the keyboard.

From logcat, the system intent can't find an activity to handle Intent ` {
act=android.intent.action.VIEW dat=content://0@media/external/file/XYZ }`

Configuration: Keyman Android 10.0.10000058
Android 6.x
Filebrowser: My Files

Issue also on Android 7.0 with "My Files" browser. The KMP does install via  another file browser (Amaze)

### LINKED ISSUE #1722: Easier method to install Keyman keyboard from local source on Android
It is very difficult to install a Keyman keyboard (.kmp) file on Android without internet access.

A few suggested methods were as follows:

- Download a different File Manager
- Use Dropbox or Google Drive

Without Internet, Dropbox or Google Drive don’t work.

Creating an HTML file with a link also poses a challenge, because while you can download the .kmp file, when you try to open it, it doesn’t know that Keyman should be used.

People can Bluetooth/share it, but that poses the same problem (it doesn’t know Keyman should be used).

As well, many (most?) of the Android devices I have worked with in PNG have a default file manager that does not recognize that Keyman can open a .kmp file (FYI: they also didn’t recognize the Bloom Reader could open Bloom files, this is relevant later). I have found that ES File Explorer works, so can install ES File Explorer on a device that I have access to.

But then when that person shares the vernacular Keyman keyboard file with somebody else, the next phone probably does not have ES File Explorer (or another file manager that works). They don’t know that they need to get one (or which one works), or they don’t have internet so can’t get another file manager. Now they’re stuck.

The way that Bloom Reader dealt with this was to add a “Find Bloom books on this device” feature. This scans the whole device (including SD card) and automatically imports any Bloom content into Bloom Reader:

Find Bloom books on this device

That feature in Bloom makes it SO easy to load Books into Bloom Reader in comparison to having to get a different File Manager installed, etc. I didn't even attempt to describe the different File Manager method to a PNGan friend because it just seemed too confusing. I'm concerned the same thing will happen with Keyman.

Adding something like this to the Keyman app (that would look for .kmp files on the device and offer to install them) would be really helpful. I imagine something like a “Find keyboards on this device” option on the “add keyboard” screen. It’s possible there could be multiple .kmp files (older vs newer or different languages), so that would need to be considered too. Do you give the choice of installing the latest version of each language available?

Thanks,

James

--

Original discussion here: https://community.software.sil.org/t/install-keyman-from-local-storage/2049/3

### LINKED ISSUE #1966: [Android] KMP installation issues
From #1904:

> 11. Unable to install KMP file using Chrome or File Browser (Nokia 3)

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #629
Fixes #1722
Fixes #1966 

Some vendor-provided file browsers aren't launching local .kmp files with Keyman. 

Filtering by file-extension doesn't always work. For example, a file named `/Downloads/nrc.en.mtnt.model.kmp` is treated internally by the file browser with a name like:  `content://com.android.providers.downloads.documents/document/33` 

This PR allows users to "Add Keyboard from Device" from the "Settings" menu. This launches a system file browser to navigate to a specific local .kmp file. Since the interaction is within the Keyman app, we can then process the selected .kmp file. Though the text says "Add Keyboard...", lexical model packages can also be installed this way.

settings

Tested configurations for keyboard and lexical model .kmp packages:
- [x] Samsung Tab S2 tablet
- [x] Nokia 3

(edited to address review comment about not using a menu option from the main app)

Reference: 
http://www.androiddocs.com/guide/topics/providers/document-provider.html

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/160566:id/kvk/index.html)

**Comment by jahorton** [comment]
This tested successfully with an emulated (via Android Studio) Pixel 2 on API 28.

**Comment by mcdurdin** [comment]
This worked successfully on a Nokia 3 phone (Android Pie / 9.0). Looking good.

Some notes:

* File Browser icon should be shown in Settings, Languages, not in the top-most menu. And it should be shown as "Add from local storage", or something like that. I guess the best way would be to add a question after touching the `(+)` button:

    ```
      Install keyboard from:

      [ Local Storage ]    [ Keyman Online ]
    ```
* There are no overwrite prompts when installing over a keyboard that is already installed, even if downgrading.
* By default, the browser shows quite large icons, and there is no way to differentiate .kmp files (the filenames are generally too long to show the extension).
* .kmp files don't have a special icon; is this customisable?
* Is it possible to filter to just .kmp files?
* This'll need some docs ;-) (by default "Show internal storage" is switched off, but some users may need to look there, which is kinda overwhelming!)
* Searching for "kmp" finds all .kmp files on the device, as far as I can tell.
* It works with Google Drive as well :)

**Comment by darcywong00** [comment]
> There are no overwrite prompts when installing over a keyboard that is already installed, even if downgrading.

I think from the ad-hoc distribution [design](https://docs.google.com/document/d/1sj7W6pCiN-_iRss5iRdib1aHaSTmYoLIueQSKJeNy8Q/edit#heading=h.mq0rc28mf031), we display the the keyboard package version and welcome.htm, and when the user confirms "install", it overwrites existing package.

**Comment by mcdurdin** [comment]
> > There are no overwrite prompts when installing over a keyboard that is already installed, even if downgrading.
> 
> I think from the ad-hoc distribution [design](https://docs.google.com/document/d/1sj7W6pCiN-_iRss5iRdib1aHaSTmYoLIueQSKJeNy8Q/edit#heading=h.mq0rc28mf031), we display the the keyboard package version and welcome.htm, and when the user confirms "install", it overwrites existing package.

True. So we can leave that for a future version. It's probably good to warn on downgrade at least (but future functionality is fine!)

**Comment by darcywong00** [comment]
> File Browser icon should be shown in Settings, Languages, not in the top-most menu. And it should be shown as "Add from local storage", or something like that. I guess the best way would be to add a question after touching the (+) button:

I'll move the file-browser to "Settings" as a new entry "Add keyboard from local device". Since the PackageActivity to handle kmp's is currently in the main app, I won't be able to move the File browser  into the KMEA "Add new language" list.

**Comment by darcywong00** [comment]
> Is it possible to filter to just .kmp files?

afaict, I can't specify a filter based on file extension. And I haven't found a way to associate a Keyman icon with .kmp files. :(

> by default "Show internal storage" is switched off, but some users may need to look there, which is kinda overwhelming!

I found a "SHOW_ADVANCED" setting that should default "Show internal storage" to on now.

**Comment by mcdurdin** [comment]
> I found a "SHOW_ADVANCED" setting that should default "Show internal storage" to on now.

I'm not sure if we want this on by default or not? What do you think?

**Comment by darcywong00** [comment]
> I'm not sure if we want this on by default or not? What do you think?

I figure nearly all  the installs will come from "Downloads" which is still accessible when `SHOW_ADVANCED` is false.

**Comment by darcywong00** [comment]
I'll hold off on merging so @mcdurdin can get a final round of testing tomorrow

**Comment by mcdurdin** [comment]
LGTM; we should still consider moving `Add from device` into a dialog accessed from the `(+)` button in the future, but let's move on. Also, a tool to scan the device and external storage (but not Google Drive!) [a-la Bloom](https://github.com/keymanapp/keyman/issues/1722) would be good for reducing friction; again, this is a big step forward so let's not do that for now.

**Pull request merged**
