### PR TITLE
chore(android): log fontpath error

### PR DESCRIPTION
**Pull request by mcdurdin**
Relates to #5509 - improve error log so we can clarify what is going wrong.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.90-alpha](https://keyman.com/downloads/releases/alpha/15.0.90)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.90-alpha](https://keyman.com/downloads/releases/alpha/15.0.90)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.90-alpha](https://keyman.com/downloads/releases/alpha/15.0.90)

**Pull request merged**
