### PR TITLE
chore(developer): upgrade ngrok to v3 🍒 🏠

### LINKED ISSUE #10357: chore(developer): upgrade ngrok to v3
Keyman Developer currently only downloads version 2.3 of ngrok. However,

> all ngrok agents version 3.1 and older will stop working on January 15th, 2024 for all free users. 

So we need to update the URL where we download ngrok.zip.

This needs to be done for v16 and v17.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10357. Cherry-pick of #10359.

# User Testing

TEST_NGROK_UPGRADE: In Keyman Developer, Tools|Options|Server, Configure Server, click `Download or update ngrok`. Once the download completes, the label to the right of the button should show "ngrok version 3.5.0" or similar (it must be version 3.2 or later to pass).

TEST_NGROK_WORKING: In Keyman Developer, verify that you have enabled ngrok in Keyman Developer Server Options. Open a keyboard, and test it on web. Verify that a URL appears in the list of server web addresses, and that when you select it to Open in browser, the test web site works correctly.

Note: your ngrok entry will look different to this but will be a public website:
image

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NGROK_UPGRADE (PASSED):** 1. Installed the attached Keyman Developer 16.0.145-test-10360 on Windows 11 OS (VM). 2. Opened Options / Server tab. 3. Clicked Configure Server button. 4. Clicked the 'Download or update ngrok' button. 5. Verified that the "ngrok version" was changed to "3.5.0". It seems to be working fine.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NGROK_WORKING (FAILED):** 1. Installed the attached Keyman Developer 16.0.145-test-10360 on Windows 11 OS (VM). 2. Opened Options / Server tab. 3. Enabled ngrok in Keyman Developer Server option. 4. Clicked the Test keyboard on web button. Here, I noticed that the URL for the ngrok was missing in the web address pane. Seems to be an issue.  

..ngrok server option enabled

   


..ngrok web address link was missing

**Comment by mcdurdin** [comment]
> * **TEST_NGROK_WORKING (FAILED):** 1. Installed the attached Keyman Developer 16.0.145-test-10360 on Windows 11 OS (VM). 2. Opened Options / Server tab. 3. Enabled ngrok in Keyman Developer Server option. 4. Clicked the Test keyboard on web button. Here, I noticed that the URL for the ngrok was missing in the web address pane. Seems to be an issue.

I wasn't able to reproduce this. When I tested, I found that if Keyman Developer Server was already running on my host, then ngrok would not start on the VM, because only one ngrok session can run for a given account. Is that possibly what was happening for you?

**Comment by bharanidharanj** [comment]
> > * **TEST_NGROK_WORKING (FAILED):** 1. Installed the attached Keyman Developer 16.0.145-test-10360 on Windows 11 OS (VM). 2. Opened Options / Server tab. 3. Enabled ngrok in Keyman Developer Server option. 4. Clicked the Test keyboard on web button. Here, I noticed that the URL for the ngrok was missing in the web address pane. Seems to be an issue.
> 
> I wasn't able to reproduce this. When I tested, I found that if Keyman Developer Server was already running on my host, then ngrok would not start on the VM, because only one ngrok session can run for a given account. Is that possibly what was happening for you?

@mcdurdin I retested this PR with my Windows 10 Native machine and I was able to reproduce this issue. ie., the ngrok web link was missing under the Web addresses pane.

**Comment by mcdurdin** [comment]
> @mcdurdin I retested this PR with my Windows 10 Native machine and I was able to reproduce this issue. ie., the ngrok web link was missing under the Web addresses pane.

When you ran this test, was Keyman Developer also running in a VM?

**Comment by bharanidharanj** [comment]
> > @mcdurdin I retested this PR with my Windows 10 Native machine and I was able to reproduce this issue. ie., the ngrok web link was missing under the Web addresses pane.
> 
> When you ran this test, was Keyman Developer also running in a VM?

@mcdurdin I closed the virtual machine running the Windows 11 operating system.

**Comment by bharanidharanj** [comment]
> @bharanidharanj I have addressed the issue that was causing ngrok to fail (region specification). Would you mind re-testing this once the build finishes? Thanks!
> 
> @keymanapp-test-bot retest

@mcdurdin Sure. I will do it.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NGROK_UPGRADE (PASSED):** Tested with the attached PR build (Keyman Developer 16.0.145-alpha-test-10360) on a clean Windows 11 machine (VM) and here is my observation : 1. Updated with the latest version of ngrok version in the Keyman Developer Server Options dialog. 2. Verified that the version 3.5.0 label name appears on the dialog. 

   


* **TEST_NGROK_WORKING (PASSED):** 1. Got the ngrok token and pasted it in the Authentication token fiel. 2. Restared Keyman Developer build. 3. Opened Build tab. 4. Compiled the keyboard.  5. Clicked the "Test Keyboard on web" button. 6. Verified that the "ngrok-free.app" link appears on the web addresses list. 7. Able to open ngrok test page without having any problem. Seems to be working fine. Thanks.

..ngrok web link 

   


..ngrok test page

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.145](https://keyman.com/downloads/releases/stable/16.0.145)

**Pull request merged**
