### PR TITLE
[Android] Fix gradle scripts for CI build using build.sh instead of gradle runner

### PR DESCRIPTION
**Pull request by mcdurdin**
Instead of using system properties, we use environment variables. This has the added
benefit of being easily testable externally.

### CODE REVIEW

**Comment by mcdurdin** [comment]
I used very clear commit messages on this PR.

**Comment by mcdurdin** [comment]
Should we plan to cherry-pick to 11.0? Without it, 11.0 builds will fail, if we ever have the need to do them; I am thinking that this is low priority though as we tend to work evergreen on Android.

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/153183:id/kvk/index.html)

**Comment by mcdurdin** [comment]
> Will the Sample, Test, and OEM apps be covered in a separate PR?

Good point. Yes, I'll do them as the next PR.

**Comment by mcdurdin** [comment]
> Good point. Yes, I'll do them as the next PR.

As we cannot yet merge due to migration underway, I'll add the updates to this PR instead...

**Comment by mcdurdin** [comment]
And ... the test / sample build.gradle files don't appear to need any updates.

**Comment by mcdurdin** [comment]
I've updated the firstvoices build.gradle as well; however, the necessary key files, etc, won't be available until we have completed the configuration of Play Store with FPCC.

**Pull request merged**
