### PR TITLE
refactor(developer): move functions and variables into CompilerErrors.cpp 🌋

### PR DESCRIPTION
**Pull request by mcdurdin**
Groundwork for rework of compiler errors. No functional changes.

Relates-to: #10866

@keymanapp-test-bot skip

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by markcsinclair** [comment]
It would probably be a good idea to pull the tests relating to `AddCompileWarning()` and `AddCompileError()` from `gtest-compiler-test.cpp` into a new file, say, `gtest-compilererrors-gtest.cpp`.  This shortens  `gtest-compiler-test.cpp`, keeps the tests relating to `CompilerErrors.cpp` together, and would also reduce the amount of fixtures needed to support those more focused tests.  I am happy to have a go at this if you wanted to raise a separate issue for it.

**Comment by mcdurdin** [comment]
> It would probably be a good idea to pull the tests relating to `AddCompileWarning()` and `AddCompileError()` from `gtest-compiler-test.cpp` into a new file, say, `gtest-compilererrors-gtest.cpp`. This shortens `gtest-compiler-test.cpp`, keeps the tests relating to `CompilerErrors.cpp` together, and would also reduce the amount of fixtures needed to support those more focused tests. I am happy to have a go at this if you wanted to raise a separate issue for it.

I agree, and would be happy for you to do that. But I think we should wait until the dust settles on the 🌋 PR chain, because CompilerErrors.cpp becomes _far_ smaller once done. The full chain of volcanoes:
* #12030
* #12031 
* #12044
* #12045
* #12048 
* #12059 
* #12060 
* #12061 
* #12063

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.81-alpha](https://keyman.com/downloads/releases/alpha/18.0.81)

**Pull request merged**
