### PR TITLE
refactor(linux): Update ibusimcontext.c

### PR DESCRIPTION
**Pull request by ermshiperete**
This change adds the upstream changes to ibusimcontext.c to our test ibusimcontext.c file up to commit
https://github.com/ibus/ibus/commit/506ac9993d5166196b7c4e9bfa9fb0f9d3792ffa plus [our two prefilter commits](https://github.com/ibus/ibus/pull/2440).

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
Confirming this isn't needed for 16.0 beta?

**Comment by ermshiperete** [comment]
> Confirming this isn't needed for 16.0 beta?

I thought about that on my way home yesterday. I think we should cherry-pick it to beta, but we don't have to hold back the release for it.

**Review by mcdurdin — APPROVED** [review]
RSLGTM - although I note the failing build!

**Comment by ermshiperete** [comment]
Sorry for the force-push. I realized that I need the autotools change from beta, so I could either merge `master` (which would make the review even messier) or rebase (which makes it hard to compare to the original version of the PR, but at least only shows my changes).

**Comment by ermshiperete** [comment]
It might be good to take another look since fixing the failing test required some significant changes. Because of the rebase you might want to take a look at the last commit if you want to see what changed from the last review.

**Review by mcdurdin — APPROVED** [review]
Re-approving

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.16-alpha](https://keyman.com/downloads/releases/alpha/17.0.16)

**Pull request merged**
