### PR TITLE
fix(android): Add Tamil lexical model to KMSample2

### PR DESCRIPTION
**Pull request by darcywong00**
Cherrypick of #3123 to `stable-13.0`

2 additional changes:
* `stable-13.0` copies the model asset files instead of installing `example.ta.wordlist.model.kmp`
* Add node_modules to top level .gitignore (to reduce the diffs when developers switch between 14.0 and stable-13.0)

### CODE REVIEW

**Comment by jahorton** [comment]
>     * `stable-13.0` copies the model asset files instead of installing `example.ta.wordlist.model.kmp`

Why?  Would using the .kmp have made things unnecessarily complex in `stable`?

**Comment by darcywong00** [comment]
> Why? Would using the .kmp have made things unnecessarily complex in `stable`?

#2928 shows the changes from copying asset files (stable-13.0) to installing kmp in 14.0

**Comment by jahorton** [comment]
> > Why? Would using the .kmp have made things unnecessarily complex in `stable`?
> 
> #2928 shows the changes from copying asset files (stable-13.0) to installing kmp in 14.0
> 
> Also, the asset files follow the pattern used in KMSample1. That's just how things were done pre-14.0

The only difference I can discern there is that we used to bundle the .model.kmp in KMEA, but now do that in KMAPro.  It didn't remove any references to the .js or the .json.

The reason I'm pushing back - the sample would be better if developers didn't have to manually unbundle the .model.kmp.

**Comment by darcywong00** [comment]
> The reason I'm pushing back - the sample would be better if developers didn't have to manually unbundle the .model.kmp.

They still need to unbundle the keyboard into assets/ in 13.0 (and append a file version).

The intent in this PR was just to cherrypick and not add more 14.0 functionality.

**Pull request merged**
