### PR TITLE
fix(ios): adds i18n for some error alerts

### PR DESCRIPTION
**Pull request by jahorton**
I identified a few escapees during work on #4568; time to round 'em up and let localization happen.

Note:  is set as a child PR of #4568 due to high-proximity changes, along with one addition therein to highlight the need for this fix.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM, although I don't understand why the two Localizable.strings are both empty files?

**Comment by jahorton** [comment]
> LGTM, although I don't understand why the two Localizable.strings are both empty files?

There's... some sort of git setting necessary to override its defaults.  Seems to think those plain-text files are actually binary for some reason.

**Comment by mcdurdin** [comment]
> There's... some sort of git setting necessary to override its defaults. Seems to think those plain-text files are actually binary for some reason.

https://stackoverflow.com/a/21020607/1836776

**Comment by mcdurdin** [comment]
It thinks they are binary because they are UTF-16LE, which it doesn't recognise by default.

**Comment by darcywong00** [comment]
@jahorton - can you see if converting the .strings files to UTF-8 works?

From an [SO thread](https://stackoverflow.com/questions/36206842/how-to-make-git-consider-strings-files-as-text-file-instead-of-binary-file) there's a reference to Cocoa documentation about Xcode being able to copy and convert back to UTF-16

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html

**Comment by mcdurdin** [comment]
@jahorton you'll also need to convert the existing strings files from UTF-16 to UTF-8.

**Comment by jahorton** [comment]
Took a bit to find it, but Xcode has this:

Screen Shot 2021-03-04 at 9 09 00 AM

It doesn't show unless you've clicked _within_ the file, for some reason.  The _other_ caveat... is that it simply doesn't work.  "Convert" did literally nothing.  Had to use an [online tool](https://subtitletools.com/convert-text-files-to-utf8-online) instead.  Yet another case of "thanks, Apple!"

**Comment by mcdurdin** [comment]
> Had to use an [online tool](https://subtitletools.com/convert-text-files-to-utf8-online) instead.

VSCode is my go-to for file encoding conversion, "Change file encoding" command

**Comment by jahorton** [comment]
While the files still aren't viewable on this PR, using "View File" no longer talks about the file being binary, so it should be fixed for the future now.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.253-beta](https://keyman.com/downloads/releases/beta/14.0.253)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)

**Pull request merged**
