### PR TITLE
[LMLayer] Wordbreaker specification

### PR DESCRIPTION
**Pull request by jahorton**
Provides the rough skeleton needed by https://github.com/keymanapp/lexical-models/pull/3 for wordbreaking support.

Also generates .d.ts files for the internal worker - these (and the handwritten index.d.ts -> LMLayer.d.ts) files are published under build/includes.  The goal is that these (particularly, LMLayerWorker.d.ts and message.d.ts) may be periodically copied into keymanapp/lexical-models for use in model development.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/143326:id/kvk/index.html)

**Comment by eddieantonio** [comment]
LGTM! Will you add the implementation to this PR?

**Comment by jahorton** [comment]
Our big focus this sprint is on getting infrastructure in place that's needed to supply models to the app and get them through to the LMLayer, but not so much on actually _doing_ anything with the LMLayer at this point.  The compiler toolchain has higher priority at the moment, since it'll be required and needs significantly more work to reach its targets.

Unfortunately, that means there's little-to-no time at this moment to implement word-breakers - this is being done now so that any models supplying a word breaker (two examples exist in keymanapp/lexical-models) don't instantly break due to them when supplied to the LMLayer.

**Comment by eddieantonio** [comment]
Sounds good, @jahorton! Merge at will!

**Pull request merged**
