### PR TITLE
feat(linux): Fix Linux packaging on i386

### PR DESCRIPTION
**Pull request by ermshiperete**
Debian defines multiple similar environment variables. On most architectures the results are the same.
But on i386 libraries are expected in `/usr/lib/i386-linux-gnu`. `DEB_TARGET_MULTIARCH` gives that value (`i386-linux-gnu`), whereas the previous `DEB_TARGET_GNU_TYPE` gives `i686-linux-gnu` which then results in our libraries not being found.

### CODE REVIEW

**Comment by mcdurdin** [comment]
This [build](https://jenkins.lsdev.sil.org/job/pipeline-keyman-packaging/job/PR-5250/4/) failed with:

```
19:56:45  engine.c: In function ‘ibus_keyman_engine_process_key_event’:
19:56:45  engine.c:682:25: error: ‘KM_KBP_MODIFIER_CAPS’ undeclared (first use in this function); did you mean ‘KM_KBP_MODIFIER_ALT’?
19:56:45           km_mod_state |= KM_KBP_MODIFIER_CAPS;
19:56:45                           ^~~~~~~~~~~~~~~~~~~~
```

Which seems strange.

**Comment by darcywong00** [comment]
> This [build](https://jenkins.lsdev.sil.org/job/pipeline-keyman-packaging/job/PR-5250/4/) failed with:
> 
> ```
> 19:56:45  engine.c: In function ‘ibus_keyman_engine_process_key_event’:
> 19:56:45  engine.c:682:25: error: ‘KM_KBP_MODIFIER_CAPS’ undeclared (first use in this function); did you mean ‘KM_KBP_MODIFIER_ALT’?
> 19:56:45           km_mod_state |= KM_KBP_MODIFIER_CAPS;
> 19:56:45                           ^~~~~~~~~~~~~~~~~~~~
> ```
> 
> Which seems strange.

I'm getting that fail on #5269 too

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.67-alpha](https://keyman.com/downloads/releases/alpha/15.0.67)

**Pull request merged**
