### PR TITLE
fix(linux): Fix stray `[-vv]` in man pages

### LINKED ISSUE #6240: bug(linux): Stray `[-vv]` in the description of the man page
Observed during [acceptance testing for v15](https://github.com/keymanapp/keyman/issues/6200#issuecomment-1036316258).

`man km-package-install` and `man km-package-list-installed` show the text `[-vv]` out of context in the description.

### PR DESCRIPTION
**Pull request by ermshiperete**
Additionally, don't print the date in the footer. This often overlaps with the program name and version.

Also print usage in addition to error if wrong arguments are given.

Fixes #6240.

# User Testing

Environment: any Linux version

- **TEST_INST**: man page for km-package-install

  In a terminal run `man km-package-install`. Verify that there is no `[-vv]` in the `DESCRIPTION` section. Verify that at the bottom   of the man page the program name and version don't overlap the with the program name at the right edge.

- **TEST_LIST**: man page for km-package-list-installed

  In a terminal run `man km-package-list-installed`. Verify that there is no `[-vv]` in the `DESCRIPTION` section. Verify that at the bottom of the man page the program name and version don't overlap the with the program name at the right edge.

- **TEST_INST_ERR**: error message for km-package-install

  In a terminal run `km-package-install`. Verify that this outputs a line with the usage above the error message.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
## User Test Results


   * **TEST_INST: FAILED** Tested it in Impish 20.10 Linux OS and able to see the [-vv] in the Description.

 



   * **TEST_LIST: FAILED** Tested it in Impish 20.10 Linux OS and able to see the [-vv] in the Description. 

 


   * **TEST_INST_ERR : PASSED** Tested this in Impish 20.10 Linux OS and able to see error message.

**Comment by ermshiperete** [comment]
@bharanidharanj Looks like the wrong version got installed. We now added a "Test Artifacts" section for Linux to the "User Test Results" comment that the testbot creates, so you can click on that link and get the correct version to install. That should be easier to find now. Could you try again, please?

Screenshot from 2022-02-19 17-42-45

@keymanapp-test-bot retest all

**Comment by bharanidharanj** [comment]
> @bharanidharanj Looks like the wrong version got installed. We now added a "Test Artifacts" section for Linux to the "User Test Results" comment that the testbot creates, so you can click on that link and get the correct version to install. That should be easier to find now. Could you try again, please?
> 
> Screenshot from 2022-02-19 17-42-45
> 
> @keymanapp-test-bot retest all

@ermshiperete Sure. I will test and add my comment.

**Comment by bharanidharanj** [comment]
* **TEST_INST: PASSED**  Downloaded and installed Keyman 15.0.199-alpha build in Impish 20.10 Linux OS and I was able to see [-vv] was removed from the Description section.
* **TEST_LIST: PASSED**  Downloaded and installed Keyman 15.0.199-alpha build in Impish 20.10 Linux OS and I was able to see [-vv] was removed from the Description section.
* **TEST_INST_ERR: PASSED**  Downloaded and installed Keyman 15.0.199-alpha build in Impish 20.10 Linux OS and verified and the output lines shows the error message.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.201-alpha](https://keyman.com/downloads/releases/alpha/15.0.201)

**Pull request merged**
