### PR TITLE
fix(ios): context-initial diacritic handling

### LINKED ISSUE #10040: bug(ios): LTR / RTL mark not filtered when diacritics are attached
From a bug noted during personal testing of #9973 on my iPhone:

> Also, something probably worth note/making an issue: TEST_APP_10_KEY_DIACRITICS will fail if performed on an iOS device if the `7` key step is removed... if the text area is empty before starting the test. My intuition tells me that this is due to one of the iOS quirks we noticed a while back: the iOS equivalent to a text-services framework signals a context reset any time the active text-input receiver has its text cleared. Well... multitapping on a context-initial diacritic-output-only key probably isn't helping things there, possibly causing a context-desync between the app and the keyboard engine. That doesn't seem _entirely_ right, but it's probably quite related.
> 
> As it appears to be due to something iOS-specific and does not occur on Android, I think this issue should be documented and pursued separately.

Did a little investigation:  our old enemy, U+200E (https://unicode-explorer.com/c/200E) has returned to haunt us.  It's being automatically inserted at the start of the context whenever a diacritic is added in that position or directly after a different diacritic meeting this compound condition (e.g., it can chain).

This is occurring via `setKeymanVal` calls to the ios-host.js script:

https://github.com/keymanapp/keyman/blob/6b8a06a52faa16d3f1d3501ff8ac5ee66f1535fa/ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js#L292-L295

This has been verified via breakpoint when performing a repro for the conditions described above - that if-condition will trigger, resulting in, among other things, a deadkey-wipe.

The Swift-side interface that calls this:

https://github.com/keymanapp/keyman/blob/6b8a06a52faa16d3f1d3501ff8ac5ee66f1535fa/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift#L231-L251

Well, huh.  That _should_ handle it, right?  Well... here's the thing...

Screen Shot 2023-11-22 at 10 27 52 AM

Screen Shot 2023-11-22 at 10 26 16 AM

So... there's no match, the character-ordering header codepoint doesn't get filtered, do not pass Go, do not collect $200, etc.  Of course, that _did_ work before... so a recent-ish version of iOS must have changed how the byte-header gets encoded.  The filter-block was written in #1756 for version 14.0 in May 2019, and there _have_ been quite a few new versions of iOS since then.

Also, I'd noticed weirdness with predictive-text even on `master` - how an extra backspace was needed after reaching cleared text at the start of context for predictions to work right.  It's definitely the same thing - our pred-text engine doesn't filter out rendering-order marks either.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10040.

Swift's default string-handling is "too clever for its own good", at least from our perspective.  For starters, while replacing a plain `\ufffe` by matching `\uffe` will work fine... it will _not_ replace the same code point if the string is `\ufffe\u0300` - it considers it to be a single grapheme cluster and carries out replacement on that level, a level within which the single char does not match the paired-char string.  We have to shift into alternative character-handling modes and manually handle such cases ourselves.

So, our checks for the marks were valid... so long as no diacritics were (naively) associated with the script-directionality marks.  The problem was with how Swift handles combining characters that got 'clustered' with directionality marks.

## User Testing

**TEST_APP_10_KEY_DIACRITICS**:  Using the Keyman for iOS test artifact...

1. Download this KMP: https://jahorton.github.io/diacritic_rota.kmp
    - Can also be found via the main page at https://jahorton.github.io.
2. Open / install it for use within the Keyman app.
3. Tap the '◌̀' key.  (The key between backspace [above] and enter [below], representing a diacritic)
4. Double-tap the `8` key.
    - Expected total result: `à`
5. Triple-tap the '◌̀' key - a circumflex diacritic should appear over the `à`.
6. Triple-tap the `9` key.
    - Expected total result: `àê`
7. Tap the '◌̀' key.  A diacritic should appear over the `ê`.
8. Open the in-app Settings menu.
    - Note, for test maintenance:  the point of this step and the next one is to trigger a context-reset.
9. Close the in-app Settings menu.
10. Double-tap the `8` key.
    - Expected final result:  `àềa`
        image
    - For clarity:
        - With a copy of the `à`'s accent-mark on top the original `ê`, as in the cropped screenshot above.  
            - It looks different in raw-text form here due to GitHub's font / rendering.
        - Note:  there is no matching accent-mark on the second `a`.

**TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES**:  Using the Keyman for iOS test artifact, attempt to reproduce the crash reported by this comment:  https://github.com/keymanapp/keyman/pull/10589#issuecomment-1921074745
- Refer to this one for details if needed: https://github.com/keymanapp/keyman/pull/10589#issuecomment-1940600108
- I'm not convinced that it won't happen, but things _could_ be a bit different now that other work in the same area has landed.  And it's best to check now.

TEST_CONTEXT_START_MANIPULATIONS:  Using the Keyman for iOS test artifact...

1. Clear all existing text within the application.
2. Swap to the `sil_euro_latin` keyboard.
3. Type `Ther`.
4. Use a predictive-text suggestion - verify that it applies properly.
5. Enter backspace one time, then select the leftmost "suggestion" (which should have quotes)
6. Verify that the end result is `Ther`.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_APP_10_KEY_DIACRITICS (FAILED):** Tested with the attached PR build (keyman 17.0.258 (0.10589.10282)) in the iPhone 13 mobile device (ios version 16.6) and here is my observation: 1. Downloaded from https://jahorton.github.io site then installed diacritic_rota.kmp file via Keyman app. 2. Verified that the output à appears on the screen after double-tapping '8' key. 3. However, I got a crash after triple tapping '◌̀  key on the screen. Seems to be an issue.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_CONTEXT_START_MANIPULATIONS (PASSED):** Tested with the attached PR build (keyman 17.0.258 (0.10589.10282)) in the iPhone 13 mobile device (ios version 16.6) and here is my observation: 1. Swapped to the sil_euro_latin keyboard. 2. Typed "Ther" text on the screen. 3. Selected 'Therefore' predictive-text from the suggestion bar. 4. Pressed the Backspace key one time, then selected the leftmost 'suggestion' (which had quotes). 5. Verified that the result "Ther" appeared on the screen.

**Comment by jahorton** [comment]
> * **TEST_APP_10_KEY_DIACRITICS (FAILED):** Tested with the attached PR build (keyman 17.0.258 (0.10589.10282)) in the iPhone 13 mobile device (ios version 16.6) and here is my observation: 1. Downloaded from https://jahorton.github.io site then installed diacritic_rota.kmp file via Keyman app. 2. Verified that the output à appears on the screen after double-tapping '8' key. 3. However, I got a crash after triple tapping '◌̀  key on the screen. Seems to be an issue.
>        

Can you please confirm the device details for me?  I don't see any corresponding crash logs from Apple that match the device.  That said, I _do_ see crash logs for this PR's build... but they are for an iPhone 14 (`Hardware Model: iPhone14,5`) running `iPhone OS 17.1.1`... not an iPhone 13 running 16.6.

There are three logs corresponding to this test artifact, taken in fairly quick succession.  For ease of inspection, I've copied them here: [PR crash logs.zip](https://github.com/keymanapp/keyman/files/14132883/PR.crash.logs.zip)

And for greater ease, here's the most relevant content of one of the three:

```
Incident Identifier: B075465E-C499-4B34-BC43-51C64B0183A6
Hardware Model:      iPhone14,5
Process:             Keyman [8989]
Path:                /private/var/containers/Bundle/Application/41CF42E4-E8A4-46B9-97EC-F94E954C61F8/Keyman.app/Keyman
Identifier:          Tavultesoft.Keyman
Version:             17.0.258 (0.10589.10282)
AppStoreTools:       15C5500a
AppVariant:          1:iPhone14,5:17
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           Tavultesoft.Keyman [603]

Date/Time:           2024-02-01 16:25:20.4853 +0530
Launch Time:         2024-02-01 16:24:23.6981 +0530
OS Version:          iPhone OS 17.1.1 (21B91)
Release Type:        User
Baseband Version:    3.10.02
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: Keyman [8989]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1b5d94870 __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x1ae0b3c00 objc_exception_throw + 60 (objc-exception.mm:356)
2   Foundation                    	0x1b52fed18 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 188 (NSException.m:252)
3   UIFoundation                  	0x1c0f2e4ac -[NSTextRange initWithLocation:endLocation:] + 468 (NSTextRange.m:0)
4   UIFoundation                  	0x1c0f3f560 __70-[NSTextParagraph enumerateSubstringsFromLocation:options:usingBlock:]_block_invoke + 132 (NSTextElement.m:518)
5   Foundation                    	0x1b4d71348 -[NSString enumerateSubstringsInRange:options:usingBlock:] + 1592 (NSString.m:1423)
6   UIFoundation                  	0x1c0f39090 -[NSTextParagraph enumerateSubstringsInRange:options:usingBlock:] + 180 (NSTextElement.m:482)
7   UIFoundation                  	0x1c0f2af9c -[NSTextParagraph enumerateSubstringsFromLocation:options:usingBlock:] + 300 (NSTextElement.m:515)
8   UIFoundation                  	0x1c0f8dfc4 __74-[NSTextLayoutManager enumerateSubstringsFromLocation:options:usingBlock:]_block_invoke_4 + 332 (NSTextLayoutManager.m:3879)
9   UIFoundation                  	0x1c0f2d63c -[NSTextContentStorage enumerateTextElementsFromLocation:options:usingBlock:] + 3908 (NSTextContentManager.m:1717)
10  UIFoundation                  	0x1c0f38870 -[NSTextLayoutManager enumerateSubstringsFromLocation:options:usingBlock:] + 196 (NSTextLayoutManager.m:3846)
11  UIKitCore                     	0x1b8846d48 -[_UITextKit2LayoutController rangeOfCharacterClusterAtIndex:type:] + 312 (_UITextKit2LayoutController.m:989)
12  UIKitCore                     	0x1b8fb1ca0 -[UITextInputController _rangeForBackwardsDelete] + 104 (UITextInputController.m:1283)
13  UIKitCore                     	0x1b8fb2214 __39-[UITextInputController deleteBackward]_block_invoke + 120 (UITextInputController.m:1377)
14  UIKitCore                     	0x1b8fb440c -[UITextInputController _performWhileSuppressingDelegateNotifications:] + 48 (UITextInputController.m:1968)
15  UIKitCore                     	0x1b8fb215c -[UITextInputController deleteBackward] + 172 (UITextInputController.m:1374)
16  UIKitCore                     	0x1b8fd3c80 __39-[UITextView _deleteBackwardAndNotify:]_block_invoke + 44 (UITextView.m:3621)
17  UIKitCore                     	0x1b8fb440c -[UITextInputController _performWhileSuppressingDelegateNotifications:] + 48 (UITextInputController.m:1968)
18  UIKitCore                     	0x1b8fd3c40 -[UITextView _deleteBackwardAndNotify:] + 164 (UITextView.m:3620)
19  UIKitCore                     	0x1b880c614 -[UIKBInputDelegateManager _deleteBackwardAndNotify:reinsertText:overrideOriginalContextBeforeInputWith:] + 472 (UIKBInputDelegateManager.m:832)
20  UIKitCore                     	0x1b8af96a8 -[UIKeyboardImpl deleteBackwardAndNotifyAtEnd:deletionCount:reinsertTextInLoop:] + 248 (UIKeyboardImpl.m:15607)
21  UIKitCore                     	0x1b8aeefbc -[UIKeyboardImpl performKeyboardOutput:checkingDelegate:forwardToRemoteInputSource:] + 1424 (UIKeyboardImpl.m:12728)
22  UIKitCore                     	0x1b8aee700 -[UIKeyboardImpl performKeyboardOutput:forwardToRemoteInputSource:] + 32 (UIKeyboardImpl.m:12562)
23  UIKitCore                     	0x1b8adffa4 __77-[UIKeyboardImpl _processInputViewControllerKeyboardOutput:executionContext:]_block_invoke + 480 (UIKeyboardImpl.m:8251)
24  UIKitCore                     	0x1b8b16e78 -[UIKeyboardImpl _performKeyboardOutput:respectingForwardingDelegate:] + 252 (UIKeyboardImpl.m:23641)
25  UIKitCore                     	0x1b8adfd98 -[UIKeyboardImpl _processInputViewControllerKeyboardOutput:executionContext:] + 168 (UIKeyboardImpl.m:8216)
26  UIKitCore                     	0x1b8ad13cc -[UIKeyboardImpl performOperations:withTextInputSource:] + 56 (UIKeyboardImpl.m:3516)
27  UIKitCore                     	0x1b8b1c088 __67-[UIKeyboardImpl(UIKitInternal) _performInputViewControllerOutput:]_block_invoke + 168 (UIKeyboardImpl.m:24701)
28  UIKitCore                     	0x1b81dbc2c -[UIKeyboardTaskEntry execute:] + 208 (UIKeyboardTaskQueue.m:869)
29  UIKitCore                     	0x1b81dbb10 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 324 (UIKeyboardTaskQueue.m:447)
30  UIKitCore                     	0x1b8b33738 -[UIKeyboardTaskQueue addTask:] + 96 (UIKeyboardTaskQueue.m:572)
31  UIKitCore                     	0x1b8b1bfbc -[UIKeyboardImpl(UIKitInternal) _performInputViewControllerOutput:] + 144 (UIKeyboardImpl.m:24699)
32  UIKitCore                     	0x1b897bfc8 __54-[_UITextDocumentInterface _didPerformOutputOperation]_block_invoke + 84 (UIInputViewControllerInterface.m:321)
33  libdispatch.dylib             	0x1bdc636a8 _dispatch_call_block_and_release + 32 (init.c:1530)
34  libdispatch.dylib             	0x1bdc65300 _dispatch_client_callout + 20 (object.m:561)
35  libdispatch.dylib             	0x1bdc73998 _dispatch_main_queue_drain + 984 (queue.c:7813)
36  libdispatch.dylib             	0x1bdc735b0 _dispatch_main_queue_callback_4CF + 44 (queue.c:7973)
37  CoreFoundation                	0x1b5cdf20c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1780)
38  CoreFoundation                	0x1b5cdbf18 __CFRunLoopRun + 1996 (CFRunLoop.c:3149)
39  CoreFoundation                	0x1b5cdb668 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
40  GraphicsServices              	0x1f90a65ec GSEventRunModal + 164 (GSEvent.c:2196)
41  UIKitCore                     	0x1b80f82b4 -[UIApplication _run] + 888 (UIApplication.m:3685)
42  UIKitCore                     	0x1b80f78f0 UIApplicationMain + 340 (UIApplication.m:5270)
43  Keyman                        	0x104a3fa78 main + 68 (AppDelegate.swift:16)
44  dyld                          	0x1d872edcc start + 2240 (dyldMain.cpp:1269)
```

There are two other logs in the bundled `.xccrashpoint`:  both running Keyman 16.0.144 (stable), dated Jan 22
- one dated Jan 22, UTC -6
- one dated Dec 16, UTC +7

So, interestingly... this specific crash isn't actually unique to this PR... but it certainly arose more frequently / consistently with that one device giving us three logs.

Also interesting, of course, is the content of the logs themselves.  The only frame from the Keyman app is _extremely_ low on the stack!

---

I've also installed the current artifact for this PR on my personal device and attempted a repro.  No crashes occurred and the test passed... on my device (running iOS 17.3) - neither in-app or as a system keyboard.

**Comment by bharanidharanj** [comment]
@jahorton Here is the configuration detail of the iPhone 13 Mobile device. Sorry for the confusion. I am using iOS 17.1.1 version.

**Comment by jahorton** [comment]
@keymanapp-test-bot retest TEST_APP_10_KEY_DIACRITICS

**Comment by bharanidharanj** [comment]
@jahorton Sorry for the late response. Finally, I have identified what caused the issue in the PR. Here is what I did while following the steps: 
1. After Step 4, I could see the result à on screen. 
2. Next, I pressed the <Enter> key to move to the next line. 
3. Then, triple tapped the 9 key, which leads to crash. 

Here, the problem is after I got the first result, I moved to the new line in the input text screen. which might have caused the Keyman Crash. 

FYI, I tried the same steps with current master branch build (17.0.265) and I encountered the same crash. 

However, if I don't enter a new line, I don't experience any crashes, and it appears to be working fine.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_APP_10_KEY_DIACRITICS (PASSED):** I retested with the attached PR build (TestFlight version 17.0.266 (0.10589.10349)) on my iPhone 13, and here are my observations:

1. I downloaded and installed the diacritic.rota.kmp file in the Keyman app.
2. I tapped the '◌̀' key, then double-tapped the 8 key, which showed the expected result, à.
3. When I triple-tapped the '◌̀' key, the circumflex diacritic appeared over the à key.
4. Triple-tapping the 9 key displayed the result àê on the text screen.
5. Tapping the '◌̀' key showed a diacritic over the ê key.
6. I opened the in-app Settings menu and then closed it, following the suggestion.
7. Double-tapping the 8 key showed àềa on the text input screen.

It seems to be working fine.

**Comment by jahorton** [comment]
> Here, the problem is after I got the first result, I moved to the new line in the input text screen. which might have caused the Keyman Crash.
> 
> FYI, I tried the same steps with current master branch build (17.0.265) and I encountered the same crash.
> 
> However, if I don't enter a new line, I don't experience any crashes, and it appears to be working fine.

Right, I didn't try doing any new-line stuff afterward.  That's worth investigating... and has led me to observe some pretty odd behavior I'll need to investigate.

**Comment by jahorton** [comment]
Merging of this PR should be delayed until #10728 can be merged into it & a re-run of the user test is done on the result.

**Comment by jahorton** [comment]
@keymanapp-test-bot retest TEST_APP_10_KEY_DIACRITICS

I've just merged in some updates that had some merge conflicts, so it's best to make sure everything's still intact.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_APP_10_KEY_DIACRITICS (PASSED):** Retested with the attached PR build (keyman 17.0.271-beta-test-10589) on an iPhone 13 mobile device and here is my observation: 1. Got the expected total result à, after running step 4. 2. Got the second expected total result àê, after running step 6. 3. Opened then closed the In-App Settings menu.4. Verified that expected final result àềa, after running step 10. Seems to be working fine.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES (PASSED):** Retested with the attached PR build (keyman 17.0.271-beta-test-10589) on an iPhone 13 mobile device and here is my observation: 1. Switched to sil_euro_latin keyboard. 2. Typed Ther. 3. Used a predictive-text suggestion and verified that it applied properly. 4. Entered backspace one time. 5. Selected the leftmost "Ther" (suggestion) word. 6. Verified that the result showed "Ther". Seems to be working fine.

**Comment by jahorton** [comment]
> # Test Results
> 
> * **TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES (PASSED):** Retested with the attached PR build (keyman 17.0.271-beta-test-10589) on an iPhone 13 mobile device and here is my observation: 1. Switched to sil_euro_latin keyboard. 2. Typed Ther. 3. Used a predictive-text suggestion and verified that it applied properly. 4. Entered backspace one time. 5. Selected the leftmost "Ther" (suggestion) word. 6. Verified that the result showed "Ther". Seems to be working fine.

@keymanapp-test-bot retest TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES 

The description of the test more closely matches TEST_CONTEXT_START_MANIPULATIONS instead.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES (FAILED):** Retested this issue with Keyman 17.0.271-beta-test-10589 on an iPhone 13 Mobile device and here is my observation: 1. Followed the steps as mentioned in Test_App_Key_Diacritics user test. 2. Able to see the expected output after running step 4.  3. Next, I pressed the key to move to the next line. 4. Then, triple tapped the 9 key. 5. Pressed enter key to move to the next line. 6. Triple tap diacritic '◌̀  leads to crash. I have attached the video file for reference. 
 
https://github.com/keymanapp/keyman/assets/19683143/a2bf4af4-d96b-4f48-ac70-e006d072937d

**Comment by jahorton** [comment]
> # Test Results
> 
>     * **TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES (FAILED):** Retested this issue with Keyman 17.0.271-beta-test-10589 on an iPhone 13 Mobile device and here is my observation: 1. Followed the steps as mentioned in Test_App_Key_Diacritics user test. 2. Able to see the expected output after running step 4.  3. Next, I pressed the key to move to the next line. 4. Then, triple tapped the 9 key. 5. Pressed enter key to move to the next line. 6. Triple tap diacritic '◌̀  leads to crash. I have attached the video file for reference.
> 
> 
> keymancrash.mp4

While I don't get a local repro in Simulator copying your input pattern, I definitely _do_ see some odd behavior anyway.

Repro based on the video's input sequence:
1. Single tap the diacritic key.
2. Double-tap <kbd>8</kbd> (result: `à`)
3. Tap the ENTER key
4. Triple-tap <kbd>9</kbd>(result: `e` on its own line)
5. Tap the ENTER key
6. Triple-tap the diacritic key
    - First tap:  standard diacritic
    - Second tap:  the post-`e` newline is deleted, then the diacritic is replaced
    - Third tap: the `e` itself is deleted and the diacritic is replaced

**Comment by jahorton** [comment]
... I just realized the bit noticed in the last comment may be _extremely_ difficult to resolve.  The only way to delete pre-caret text in iOS requires use of a character-cluster-oriented backspace.  We've already noted, during this PR's development, that iOS likes to attach diacritics to the prior character, regardless of how little sense it may make - see the `\uffe\u0300` problem.  Therefore, if the would-be base char is past the context-window boundary... there's not really anything we can do that isn't _super_ finicky.  The backspace WILL delete the would-be base char, and there's literally no way to know what it is before executing the backspace that doesn't involve nasty, finicky context manipulations.

**Comment by jahorton** [comment]
> # Test Results
> 
>     * **TEST_APP_10_KEY_DIACRITICS_WITH_NEWLINES (FAILED):** Retested this issue with Keyman 17.0.271-beta-test-10589 on an iPhone 13 Mobile device and here is my observation: 1. Followed the steps as mentioned in Test_App_Key_Diacritics user test. 2. Able to see the expected output after running step 4.  3. Next, I pressed the key to move to the next line. 4. Then, triple tapped the 9 key. 5. Pressed enter key to move to the next line. 6. Triple tap diacritic '◌̀  leads to crash. I have attached the video file for reference.
> 
> 
> keymancrash.mp4

So, two bits of news.

1. I've managed to reproduce the crash.
2. I've managed to reproduce the crash _without the Keyman keyboard active_!

https://github.com/keymanapp/keyman/assets/25213402/1544ed57-f692-4bc9-b0fa-f984885f16b8

I used Keyman to produce the text, but I can trigger the bug with a backspace from the _default iOS system keyboard_!

Therefore, it's pretty safe to say that this crash isn't our fault.  Apple would probably say "it's the keyboard designer's fault - you shouldn't allow typing text like that."

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.280-beta](https://keyman.com/downloads/releases/beta/17.0.280)

**Pull request merged**
