### PR TITLE
chore(common): Add Crowdin strings for Portuguese (pt-PT)

### PR DESCRIPTION
**Pull request by darcywong00**
This adds the crowdin strings for [Portuguese, Portugal](https://translate.keyman.com/project/keyman/pt-PT), which is separate from [Portuguese, Brazilian](https://translate.keyman.com/project/keyman/pt-BR).

TODO before testing
- [x] @sgschantz to run the iOS and macOS projects through XCode to add pt-PT locale.

## User Testing
Note, the overall crowdin progress on Portuguese is 98%, so there will still be a few untranslated strings that show in English.

* **TEST_ANDROID**
1. Load the PR build of Keyman for Android
2. From the Keyman "Settings" menu, change the "Display Language" to "Português do Portugal"
3. Return to the Keyman app and verify the strings are in Portuguese

* **TEST_IOS**
1. Load the PR build of Keyman for Android
2. Set the device locale to Portuguese (does iOS distinguish Portugal from Brazil?)
3. Return to Keyman and verify strings are in Portuguese

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the device locale to Portuguese
3. Return to Keyman and verify strings are in Portuguese. Note, the macOS translation is 83% complete, so there will be a few English strings

### CODE REVIEW

**Comment by sgschantz** [comment]
This looks good in iOS and pretty good on Mac.  On Mac I did notice some inconsistencies for the word 'keyboard'. In most places it appears as 'Teclado' but in others, such as in the Config window, it is also in English:

image

**Comment by bharanidharanj** [comment]
* **TEST_ANDROID (PASSED):** Tested as per the instructions and the Keyman UI menu changes to Portuguese. Now, Most of the Strings are in Portuguese. FYI, I noticed that Clicking on the Enable Keyman as system-wide keyboard option opens Manage on-screen keyboards page which fully appears in English Texts. 

Portuguese UI Menu:
 

Info label name should be changed to Portuguese:
 

Manage on-screen keyboards UI appears in English:

**Review by ermshiperete — APPROVED** [review]

**Comment by mcdurdin** [comment]
Code LGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.234-beta](https://keyman.com/downloads/releases/beta/15.0.234)

**Pull request merged**
