### PR TITLE
chore: merge beta to master

### PR DESCRIPTION
**Pull request by mcdurdin**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
Getting Jenkins packaging error for Linux, @ermshiperete:

```
API verification failed for libkmnkbp0.so
```

**Comment by mcdurdin** [comment]
Linux build error now too:

```
../../ibus-keyman/tests/ibusimcontext.c: In function ‘_process_key_event_done’:
../../ibus-keyman/tests/ibusimcontext.c:258:39: error: ‘IBUS_PREFILTER_MASK’ undeclared (first use in this function); did you mean ‘IBUS_MODIFIER_MASK’?
	258 |     ((GdkEventKey *)event)->state &= ~IBUS_PREFILTER_MASK;
			|                                       ^~~~~~~~~~~~~~~~~~~
			|                                       IBUS_MODIFIER_MASK
../../ibus-keyman/tests/ibusimcontext.c:258:39: note: each undeclared identifier is reported only once for each function it appears in
../../ibus-keyman/tests/ibusimcontext.c: In function ‘ibus_im_context_filter_keypress’:
../../ibus-keyman/tests/ibusimcontext.c:486:60: error: ‘IBUS_PREFILTER_MASK’ undeclared (first use in this function); did you mean ‘IBUS_MODIFIER_MASK’?
	486 |   if (event->state & IBUS_IGNORED_MASK && !(event->state & IBUS_PREFILTER_MASK))
			|                                                            ^~~~~~~~~~~~~~~~~~~
			|                                                            IBUS_MODIFIER_MASK
../../ibus-keyman/tests/ibusimcontext.c: In function ‘_ibus_context_forward_key_event_cb’:
../../ibus-keyman/tests/ibusimcontext.c:979:22: error: ‘IBUS_PREFILTER_MASK’ undeclared (first use in this function); did you mean ‘IBUS_MODIFIER_MASK’?
	979 |   } else if (state & IBUS_PREFILTER_MASK) {
			|                      ^~~~~~~~~~~~~~~~~~~
			|                      IBUS_MODIFIER_MASK
```

**Review by jahorton — APPROVED** [review]

**Comment by ermshiperete** [comment]
> Linux build error now too:

TC agent got updated to Focal and that replaced our custom ibus version with stock ibus.

**Comment by ermshiperete** [comment]
> Getting Jenkins packaging error for Linux, @ermshiperete:
> 
> ```
> API verification failed for libkmnkbp0.so
> ```

Last build already succeeded on Jenkins. It failed before because it ran on an unsuitable, outdated agent (Xenial-based) that comes with an outdated version of the tool we run that's missing support for some parameters. I changed the build script to limit the API verification step to the Bionic agent.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.17-alpha](https://keyman.com/downloads/releases/alpha/17.0.17)

**Comment by srl295** [comment]
> Linux build error now too:
> 
> ```
> ../../ibus-keyman/tests/ibusimcontext.c: In function ‘_process_key_event_done’:
> ../../ibus-keyman/tests/ibusimcontext.c:258:39: error: ‘IBUS_PREFILTER_MASK’ undeclared (first use in this function); did you mean ‘IBUS_MODIFIER_MASK’?
>   258 |     ((GdkEventKey *)event)->state &= ~IBUS_PREFILTER_MASK;
>       |                                       ^~~~~~~~~~~~~~~~~~~
>       |                                       IBUS_MODIFIER_MASK
> ../../ibus-keyman/tests/ibusimcontext.c:258:39: note: each undeclared identifier is reported only once for each function it appears in
> ../../ibus-keyman/tests/ibusimcontext.c: In function ‘ibus_im_context_filter_keypress’:
> ../../ibus-keyman/tests/ibusimcontext.c:486:60: error: ‘IBUS_PREFILTER_MASK’ undeclared (first use in this function); did you mean ‘IBUS_MODIFIER_MASK’?
>   486 |   if (event->state & IBUS_IGNORED_MASK && !(event->state & IBUS_PREFILTER_MASK))
>       |                                                            ^~~~~~~~~~~~~~~~~~~
>       |                                                            IBUS_MODIFIER_MASK
> ../../ibus-keyman/tests/ibusimcontext.c: In function ‘_ibus_context_forward_key_event_cb’:
> ../../ibus-keyman/tests/ibusimcontext.c:979:22: error: ‘IBUS_PREFILTER_MASK’ undeclared (first use in this function); did you mean ‘IBUS_MODIFIER_MASK’?
>   979 |   } else if (state & IBUS_PREFILTER_MASK) {
>       |                      ^~~~~~~~~~~~~~~~~~~
>       |                      IBUS_MODIFIER_MASK
> ```

this was the same issue i saw 'on WSL'. looks like i didn't actually make the issue

**Comment by srl295** [comment]
> > Linux build error now too:
> 
> TC agent got updated to Focal and that replaced our custom ibus version with stock ibus. I re-enabled llso and pso and updated to our custom ibus version.

@ermshiperete  any tips on solving this locally?

**Pull request merged**
