### PR TITLE
fix(common): fix broken common/web/types cases 🙀

### LINKED ISSUE #8419: bug(common/web): common/web/types unit test failures
### Describe the bug

With the current state of `master` (https://github.com/keymanapp/keyman/commit/4c68bc1decde6b5ec6ca9be4cbec6496148edd62), the following sequence reports 28 failing unit tests from `common/web/types`:

```
> git clean -fx

> common/web/keyman-version/build.sh build

> common/web/types/build.sh build test
```

I ran into this while working on #8418.

### Reproduce the bug

See above.

### Expected behavior

Unit tests should pass.

### PR DESCRIPTION
**Pull request by srl295**
Fixes #8419

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
force pushed for typo fix

**Comment by jahorton** [comment]
It's definitely looking better than before, but my local runs result in the following:

```
 1) TouchLayoutFileReader
       should read a valid file:
     Error: ENOENT: no such file or directory, open 'C:\keymanapp\keyman\common\web\types\build\src\keyman-touch-layout.clean.spec.json'
      at Object.openSync (node:fs:586:3)
      at Object.readFileSync (node:fs:454:35)
      at loadKeymanTouchLayoutCleanJsonSchema (file:///C:/keymanapp/keyman/common/web/types/test/helpers/index.ts:21:13)
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/keyman-touch-layout/test-keyman-touch-layout-file-reader.ts:10:20)
      at processImmediate (node:internal/timers:466:21)

  2) TouchLayoutFileReader
       should fixup numeric types in a valid legacy file:
     Error: ENOENT: no such file or directory, open 'C:\keymanapp\keyman\common\web\types\build\src\keyman-touch-layout.clean.spec.json'
      at Object.openSync (node:fs:586:3)
      at Object.readFileSync (node:fs:454:35)
      at loadKeymanTouchLayoutCleanJsonSchema (file:///C:/keymanapp/keyman/common/web/types/test/helpers/index.ts:21:13)
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/keyman-touch-layout/test-keyman-touch-layout-file-reader.ts:39:20)
      at processImmediate (node:internal/timers:466:21)

  3) TouchLayoutFileReader
       should fixup remove empty arrays in a valid legacy file:
     Error: ENOENT: no such file or directory, open 'C:\keymanapp\keyman\common\web\types\build\src\keyman-touch-layout.clean.spec.json'
      at Object.openSync (node:fs:586:3)
      at Object.readFileSync (node:fs:454:35)
      at loadKeymanTouchLayoutCleanJsonSchema (file:///C:/keymanapp/keyman/common/web/types/test/helpers/index.ts:21:13)
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/keyman-touch-layout/test-keyman-touch-layout-file-reader.ts:61:20)
      at processImmediate (node:internal/timers:466:21)

  4) kpj-file-reader
       kpj-file-reader should read a valid file:
     AssertionError: expected [Function] to not throw an error but 'Error: ENOENT: no such file or directory, open \'C:\\keymanapp\\keyman\\common\\web\\types\\build\\src\\kpj.schema.json\'' was thrown
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/kpj/test-kpj-file-reader.ts:16:12)
      at processImmediate (node:internal/timers:466:21)

  5) kvks-file-reader
       kvks-file-reader should compile with kvk-file-writer:
     AssertionError: expected [Function] to not throw an error but 'Error: ENOENT: no such file or directory, open \'C:\\keymanapp\\keyman\\common\\web\\types\\build\\src\\kvks.schema.json\'' was thrown
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/kvk/test-kvk-round-trip.ts:53:12)
      at processImmediate (node:internal/timers:466:21)

  6) kvks-file-reader
       kvks-file-writer
         kvks-file-writer should match what kvk-file-reader reads:
     AssertionError: expected [Function] to not throw an error but 'Error: ENOENT: no such file or directory, open \'C:\\keymanapp\\keyman\\common\\web\\types\\build\\src\\kvks.schema.json\'' was thrown
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/kvk/test-kvk-round-trip.ts:76:14)
      at processImmediate (node:internal/timers:466:21)

  7) kvks-file-reader
       should read a valid file:
     AssertionError: expected [Function] to not throw an error but 'Error: ENOENT: no such file or directory, open \'C:\\keymanapp\\keyman\\common\\web\\types\\build\\src\\kvks.schema.json\'' was thrown
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/kvk/test-kvks-file.ts:16:12)
      at processImmediate (node:internal/timers:466:21)

  8) ldml keyboard xml reader tests
       should fail to load: invalid-structure-per-dtd.xml:
     AssertionError: loading invalid-structure-per-dtd.xml: expected null to be truthy
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:124:16)
      at processImmediate (node:internal/timers:466:21)

  9) ldml keyboard xml reader tests
       should fail to load: invalid-conforms-to.xml:
     AssertionError: loading invalid-conforms-to.xml: expected null to be truthy
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:124:16)
      at processImmediate (node:internal/timers:466:21)

  10) ldml keyboard xml reader tests
       should load: import-minimal.xml:
     AssertionError: loading import-minimal.xml: expected null to be truthy
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:124:16)
      at processImmediate (node:internal/timers:466:21)

  11) ldml keyboard xml reader tests
       should load: import-minimal1.xml:
     AssertionError: loading import-minimal1.xml: expected null to be truthy
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:124:16)
      at processImmediate (node:internal/timers:466:21)

  12) ldml keyboard xml reader tests
       should load: import-minimal2.xml:
     AssertionError: loading import-minimal2.xml: expected null to be truthy
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:124:16)
      at processImmediate (node:internal/timers:466:21)

  13) ldml keyboard xml reader tests
       should load: import-symbols.xml:
     AssertionError: loading import-symbols.xml: expected null to be truthy
      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:124:16)
      at processImmediate (node:internal/timers:466:21)

  14) ldml keyboard xml reader tests
       should fail to load: invalid-import-wrongroot.xml:

      expected errors to be included
      + expected - actual

       [
         {
      -    "code": 3149828
      -    "message": "Import could not read data with path techpreview/keys-Zyyy-punctuation.xml: expected the form 'techpreview./*.xml'"
      +    "code": 3149829
      +    "message": "Invalid import file techpreview/keys-Zyyy-punctuation.xml: expected names as root element."
         }
       ]

      at Context.<anonymous> (file:///C:/keymanapp/keyman/common/web/types/test/helpers/reader-callback-test.ts:135:18)
      at processImmediate (node:internal/timers:466:21)



------------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------File                                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------All files                                 |   85.38 |    78.94 |   61.95 |   85.38 |                                                                       
 src/keyman-touch-layout                  |   66.06 |     90.9 |   66.66 |   66.06 |                                                                       
  keyman-touch-layout-file-reader.ts      |   91.35 |    94.44 |      50 |   91.35 | 26,31-32,71-73,78                                                     
  keyman-touch-layout-file-writer.ts      |   41.66 |       75 |      75 |   41.66 | 35-83                                                                 
 src/kpj                                  |   41.47 |       40 |      10 |   41.47 |                                                                       
  keyman-developer-project.ts             |   41.93 |    14.28 |       0 |   41.93 | ...42-44,47-49,52-68,83-87,90-103,110-114,117-124,131,134-142,147,153 
  kpj-file-reader.ts                      |   40.77 |      100 |   33.33 |   40.77 | 26-31,34-38,41-67,70-92                                               
 src/kvk                                  |   92.82 |    63.93 |   73.68 |   92.82 |                                                                       
  kvk-file-reader.ts                      |   94.11 |    66.66 |     100 |   94.11 | 11-12                                                                 
  kvks-file-reader.ts                     |   86.58 |    68.96 |   71.42 |   86.58 | 69-74,92-93,95-96,101-102,114-121,162-163                             
  kvks-file-writer.ts                     |   90.26 |       50 |     100 |   90.26 | 22-23,25-26,31-32,88-90,111-112                                       
  visual-keyboard.ts                      |   91.25 |       25 |      25 |   91.25 | 18-21,27,37-38                                                        
 src/ldml-keyboard                        |   82.68 |    75.71 |   94.44 |   82.68 |                                                                       
  ldml-keyboard-xml-reader.ts             |   82.68 |    75.71 |   94.44 |   82.68 | ...99,107-109,144-145,169-192,198-212,243-244,247,297,301-303,382-383 
 src/util                                 |   97.09 |    95.45 |   78.57 |   97.09 |                                                                       
  common-events.ts                        |      94 |      100 |   66.66 |      94 | 38,43,47                                                              
  util.ts                                 |   97.05 |     92.3 |     100 |   97.05 | 63-64                                                                 
 test/helpers                             |   94.87 |      100 |   85.71 |   94.87 |                                                                       
  index.ts                                |   94.87 |      100 |   85.71 |   94.87 | 34-35                                                                 
 test/ldml-keyboard                       |   80.21 |      100 |   16.66 |   80.21 |                                                                       
  test-ldml-keyboard-xml-reader.ts        |   72.51 |      100 |       0 |   72.51 | 7-9,36-42,48-54,60-67,73-83                                           
------------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------ERROR: Coverage for lines (85.38%) does not meet global threshold (90%)
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: @keymanapp/common-types
npm ERR!   at location: C:\keymanapp\keyman\common\web\types
[common/web/types] ## test failed
```

This section of that table was completely red:

```
  keyman-touch-layout-file-writer.ts      |   41.66 |       75 |      75 |   41.66 | 35-83                                                                 
 src/kpj                                  |   41.47 |       40 |      10 |   41.47 |                                                                       
  keyman-developer-project.ts             |   41.93 |    14.28 |       0 |   41.93 | ...42-44,47-49,52-68,83-87,90-103,110-114,117-124,131,134-142,147,153 
  kpj-file-reader.ts                      |   40.77 |      100 |   33.33 |   40.77 | 26-31,34-38,41-67,70-92     
```

**Comment by mcdurdin** [comment]
Would be worth rebasing on #8431 which adds common/ unit tests to CI

**Comment by srl295** [comment]
@mcdurdin @jahorton rebased PTAL

**Comment by mcdurdin** [comment]
common/web test failure is fixed in a7cba84 in #8431.

**Comment by srl295** [comment]
rebased yet again

**Comment by srl295** [comment]
@jahorton 

> It's definitely looking better than before, but my local runs now result in the following:

that sounds like `clean` happened but not `configure`/`build` …  see if the rebase fixed it

**Review by mcdurdin — APPROVED** [review]

**Comment by jahorton** [comment]
> that sounds like `clean` happened but not `configure`/`build` …  see if the rebase fixed it

Just tried again; I needed to `clean` -> `build` both `common/web/keyman-version` and `common/web/types`; the tests all pass after that.  Neglecting the former seemed to result in the same test failures.

**Comment by mcdurdin** [comment]
Clean builds are gonna be required (or potentially `--force-deps`) when there's a lot of flux in the deps as there is right now.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.68-alpha](https://keyman.com/downloads/releases/alpha/17.0.68)

**Pull request merged**
