### PR TITLE
chore(web): renames folder for namespaced Web code 🧩

### PR DESCRIPTION
**Pull request by jahorton**
`engine/main` is about the best name I've come up with for the top-level structure of Web's engine, but it's currently occupied by namespace-based Web code.  This simply just... moves it out of the way, allowing new code that's module-based to be developed within the corresponding folder.

The intent is for `engine/main` to implement the common, base forms of classes referenced by both engine types while the engine types subclass them within their own subpackages.

There was a bit of rebasing involved with setting this PR up, so one line that might have been missed on the prior PR made it in here.  Ah well.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
OK I guess but I don't really understand why we are moving from `main` to `namespaced-main` -- is this temporary?

**Comment by jahorton** [comment]
> OK I guess but I don't really understand why we are moving from `main` to `namespaced-main` -- is this temporary?

My intent is to progressively "empty" namespaced code out of `namespaced-main` and put it back into `main` as I modularize it.
Keeping it in the same place is prone to a _lot_ of busy-work in tsconfig.json, since I'd have to filter out namespace-based code when compiling modularized code.

It also provides a fairly solid visual that says "this part of the codebase hasn't been converted, but this other part has been."

So, a quick "from" (namespaced) / "to" (modularized) mapping:
- `engine/namespaced-main` => `engine/main`
- `app/embed` => `app/webview-hosted`
- `app/web` => `app/site-engine`
    - The latter two are my current working names for my current leading-edge work that's not yet been turned into a formal PR.  Feel free to suggest alternative folder names if preferred.

**Comment by mcdurdin** [comment]
Looking at where they are being used, could go with:
* `app/embed` => `app/webview`
* `app/web` => `app/browser`

Or `app/lite` / `app/full`? Looks at the nomenclature from another angle.

Or `app/private` / `app/public`?

Or `app/in-app` / `app/browser`? But "in-app" is kinda confusing here.

I'm not really liking any of them all that much...

**Comment by jahorton** [comment]
> Looking at where they are being used, could go with:
> * `app/embed` => `app/webview`
> * `app/web` => `app/browser`

I'll think I'll go with that version.

**Pull request merged**
