### PR TITLE
chore: Fail TC build if triggering Jenkins build fails

### PR DESCRIPTION
**Pull request by ermshiperete**
@keymanapp-test-bot skip

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by jahorton** [comment]
Is there a version of this for `master` as well?

**Comment by ermshiperete** [comment]
> Is there a version of this for `master` as well?

There is now :smile: #8152

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.139](https://keyman.com/downloads/releases/stable/16.0.139)

**Pull request merged**
