### PR TITLE
refactor(developer): update app context as well as cached context for keyboard debuggers 🌱

### LINKED ISSUE #10214: refactor(developer): debugger: manage app_context as well as cached_context 🌱

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10214.

# User Testing

* **TEST_DEBUGGER:** Open a .kmn keyboard project and verify that keyboard debugger continues to function correctly through a series of tests.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (FAILED):** Tested with the attached PR build (Keyman Developer 17.0.247-alpha-test-10462) on Windows 10 OS and here is my observation: 1. Created a new Keyman Keyboard (.kmn) project. 2. Compiled it. 3. Opened the debugger by pressing F5 key. 3. Pressing 'a' key from the keyboard leads to an error message. Seems to be an issue. 

..Fatal error

   

..Error message in Node window

**Review by srl295 — APPROVED** [review]
looks like good refactoring

**Comment by mcdurdin** [comment]
Hi @bharanidharanj, can you retest this one, once the build finishes, as I have made some updates. I am not sure that it is going to address the problem but would like to retest before I dig deeper if possible, thanks!

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (PASSED):** Retested with the updated PR build (Keyman Developer 17.0.248-alpha-test-10462) in Windows 10 OS and here is my observation: 1. Got a warning message after pressing the F5 key from the keyboard. 2. So, I closed the project. Removed .json files from C:\Users\Admin\AppData\Roaming\Keyman\Keyman Developer. 3. Opened another project (eg., malar_malayalam). Clicked the uprgrade project button from the project window. 4. Pressing F5 key after opening the project. 5. Verified that it is working fine after using the project in the Debugger window. Seems to be working fine. 

..warning message

   

..working fine in the debugger window

**Pull request merged**
