### PR TITLE
fix(android/engine): Use FLAG_IMMUTABLE for PendingIntent for Android S+ 🍒

### PR DESCRIPTION
**Pull request by darcywong00**
🍒 pick of #7844 to stable-15.0 
It may be another week till 16.0 gets released, so this prevents keyboard updates from crashing on Android S+ devices.

## User Testing - Modified from #7844 since 15.0 doesn't contain updates to make it easier to test keyboard updates
Setup - For each group, use the Android device, orientation, and Android OS as specified in the group. Do **not** install Keyman for Android until instructed in Setup step
1. On the device, download the old version [1.0 of sil_nko Keyman keyboard](https://downloads.keyman.com/keyboards/sil_nko/1.0/sil_nko.kmp)
2. On the device, turn on airplane mode (sets device offline)
3. On the device Settings, manually set the date/time to 1 year  past (~Oct 2021)
4. Install the PR build of Keyman for Android
5. Launch Keyman for Android
6. From Keyman Settings, install the old version of sil_nko from local file. (Install for "Mandingo" language)
7. Completely exit Keyman
8. On the device Settings, set the date/time to automatically update from the network
9. On the device, turn off airplane mode (sets device back online)

**GROUP_PHONE_PORTRAIT_API_21** - Verifies update installs for phone in portrait orientation on Android 5.0 (API 21)
**GROUP_PHONE_PORTRAIT_API_31** - Verifies update installs for phone in portrait orientation on Android 12.0 (API 31)

**TEST_KEYBOARD_UPDATE**
1. Launch Keyman for Android and dismiss the "Get Started" menu
2. After a while, see if notifications appear about keyboard updates being available. If they don't appear, completely exit Keyman and relaunch.
3. When there's notifications about Keyman updates being available, click the Keyman overflow menu to select "Install Updates"
4. Verify Keyman prompts confirmation to download a keyboard update for sil_nko
5. Accept the dialog
6. Verify after a while, the keyboard updates in the background.
7. After a while, the keyboard updates. Note, 15.0 doesn't contain some keyboard package updates so it likely will install for the first listed language in sil_nko

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM if needed

**Comment by darcywong00** [comment]
> This would only be needed if we are targeting Android S+ right? Is that API level 31?

Right, which we recently had to do in #7814

**Comment by darcywong00** [comment]
> This would only be needed if we are targeting Android S+ right? Is that API level 31?

Hmm, this even causes crashes on my Android 11.0 device (API 30) trying to install keyboard from the QR code link.
Should be resolved when the next 16.0 beta build goes out.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.274](https://keyman.com/downloads/releases/stable/15.0.274)

**Pull request merged**
