### PR TITLE
fix(core): ldml backspace processing should delete all markers 🙀 

### PR DESCRIPTION
**Pull request by srl295**
- current code would only delete a single marker and fall through
- should loop consuming all markers until a non-marker char is hit

- [x] needs unit test
- [x] needs user test

split from #11172

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
LGTM

**Review by mcdurdin — APPROVED** [review]

**Comment by srl295** [comment]
@mcdurdin didn't get user tests yet but otherwise ready

**Comment by srl295** [comment]
@keymanapp-test-bot skip

**Comment by srl295** [comment]
@rc-swag ok go ahead and merge this once the parent is merged..

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.315-beta](https://keyman.com/downloads/releases/beta/17.0.315)

**Pull request merged**
