### PR TITLE
chore(common): Check in crowdin strings for Kanuri 📜

### PR DESCRIPTION
**Pull request by darcywong00**
This checks in the crowdin strings for the locale `kr` for Kanuri. Does not include macOS.

- [x] TODO: @sgschantz to check on adding kr (kr-NG?) locale in XCode

## User Testing
For the listed platforms:
1. Load the PR build
2. Set the UI/locale to Kanuri
3. Verify the UI is Kanuri
Note: The crowdin translator left some strings in English, so that's out of our control

* **TEST_ANDROID**
1. Verify Kanuri strings are like the screenshot
Screenshot_1639536811

* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing

* **TEST_LINUX**
1. start Keyman configuration with: `LANGUAGE=kr_NG km-config`

* **TEST_WINDOWS**
1. start Keyman
2. Change UI to "Nasara" (that's the language name the TWB translator used)

### CODE REVIEW

**Comment by mcdurdin** [comment]
Kanuri `kr` is a macrolanguage tag. Is this the appropriate tag for the language? `kby`, `knc` and `krt` are the individual languages under `kr` (ISO639-3 `kau`). What OS support is there for `kr`?

**Review by mcdurdin — COMMENTED** [review]
I note that quite a number of the strings are still in English. Is this intentional?

**Comment by darcywong00** [comment]
> Kanuri `kr` is a macrolanguage tag. Is this the appropriate tag for the language? `kby`, `knc` and `krt` are the individual languages under `kr` (ISO639-3 `kau`). What OS support is there for `kr`?

Good questions. TWB told me to use the following:
> * Language name: Kanuri / Dialect of: Nigeria / Crowdin language code: - / Three-letter code: kau / Locale code: kr-NG

On my Win 10, adding Kanuri (Latin) shows up as `kau`.

----

> I note that quite a number of the strings are still in English. Is this intentional?

The TWB translator kept those strings in English... 😕

**Comment by mcdurdin** [comment]
> The TWB translator kept those strings in English... 😕

Can we follow up with them? The other translations seem a lot more complete.

**Comment by sgschantz** [comment]
Kanuri is supported on iOS as of version 15.1 and Xcode version 13.1, but it is not available in Xcode 12.4 that we are currently building with. I think it would be best to not attempt adding iOS support until we are using a version of Xcode that allows us to specify that language directly.

**Comment by mcdurdin** [comment]
We are going to have to find a way of supporting languages that are not supported by the OS for iOS and macOS. This is going to keep coming up as a problem.

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: FAILED**
A number of strings are still in English mostly entirely.

    

- **TEST_IOS: FAILED** The UI language doesn't switch to Kanuri even though the iOS UI language has successfully been switched to it.

- **TEST_LINUX: BLOCKED**

Ubuntu -  the language cannot be found in the "language settings".

   


Wasta - the language cannot be found in the "language settings".

   


- **TEST_WINDOWS: BLOCKED**

Windows 10 - the language is not in one of the languages in the dropdown menu:

   


Windows 11 - the language is not in one of the languages in the dropdown menu:

**Comment by darcywong00** [comment]
> > The TWB translator kept those strings in English... 😕
> 
> Can we follow up with them? The other translations seem a lot more complete.

Here's the answer I got from TWB
> Kanuri: we spoke with our linguist and he explained that the content is sometimes really technical, and therefore there are no equivalents for terms in the language. Paraphrasis or functional translations would be difficult to provide, lengthy and descriptive at best. Moreover, Kanuri and English co-exist in Nigeria and are in close contact, and therefore there is quite a lot of transference and usage of English terms in this language.

@MakaraSok - that means the English strings in Android should be fine.

@keymanapp-test-bot retest TEST_ANDROID

**Comment by darcywong00** [comment]
@MakaraSok 
I've updated the Windows test to use the language the TWB translator used (Nasara).
@keyman-test-bot retest TEST_WINDOWS

Does TEST_LINUX work if you specify `LANGUAGE=kr_NG km-config` in the instructions?

**Review by mcdurdin — APPROVED** [review]

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: PASSED** 
- **TEST_LINUX: PASSED**
- **TEST_WINDOWS: BLOCKED** No artifact to download for testing.

Here is what is shown on TC.
image

**Comment by darcywong00** [comment]
> TEST_WINDOWS: BLOCKED No artifact to download for testing.

@MakaraSok - The test artifacts from Dec 15 have expired, so I've kicked off another Windows build. It should be available in 30 min.

@keymanapp-test-bot retest TEST_WINDOWS

**Comment by MakaraSok** [comment]
- **TEST_WINDOWS: PASSED** The UI language does show up as Nasara and switches to it when chosen.

image

**Comment by darcywong00** [comment]
> We are going to have to find a way of supporting languages that are not supported by the OS for iOS and macOS. This is going to keep coming up as a problem.

We'll tackle this separately, so I'll go ahead and merge this

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.176-alpha](https://keyman.com/downloads/releases/alpha/15.0.176)

**Pull request merged**
