### PR TITLE
fix(android/app): Update storage permissions for Android 12.0+

### LINKED ISSUE #10659: bug(android/engine): Storage permission denied on Android 14.0+
Trying to install from Chrome Downloads, I get a toast from Keyman: "storage request permission was denied. May fail to install key..." 

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/10133#issuecomment-1886259886_

Also noticed in the user testing setup on #10624

## Steps to repro
1. On an Android 14.0+ device, download a kmp file in Chrome
2. Go to Chrome --> Downloads
3. Attempt to install the kmp file
4. Observe the toast error

See if these SO threads works

https://stackoverflow.com/questions/77386225/manifest-permission-manage-external-storage-does-not-work-on-android-14

https://stackoverflow.com/questions/72948052/android-13-read-external-storage-permission-still-usable

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #10659 and follows the permission refactoring from #10904

Reference
https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

This updates CheckPermissions to ask for the corresponding storage permissions needed to install local kmp files.

For Android API 30-32
* `Manifest.permission.READ_EXTERNAL_STORAGE`

For Android API 33+
* `Manifest.permission.READ_MEDIA_IMAGES` and 
* `Manifest.permissions.READ_MEDIA_VIDEO`. 
(I tested without `READ_MEDIA_AUDIO` and it seemed to worked)

**Note:**
For these devices, the user needs to still manually grant these permissions from Android Settings before Keyman can access local .kmp files. This is documented in the updated help page: grant-storage-permission.md

## User Testing
**Setup** - Install the PR build of Keyman for Android on the corresponding Android device/emulator (API number in the test name)
Also, from Chrome, download a local copy of [sil_ipa.kmp](https://downloads.keyman.com/keyboards/sil_ipa/1.8.7/sil_ipa.kmp)

* **TEST_API_31** - Verifies Keyman can access local kmp file on Android API 31
1. Verify device/emulator is Android 12.0 "S" / API 31
2. From Chrome --> Downloads --> select sil_ipa.kmp (Do not use Samsung MyFiles browser to access the file)
3. Select Keyman to handle the kmp file
4. Verify Keyman displays error about storage permission being denied
5. From Keyman for Android --> Info --> Troubleshooting --> How To - Grant Storage Permission
6. Follow the steps for the corresponding Android device to grant storage permission to Keyman
7. From Chrome --> Downloads --> select sil_ipa.kmp
8. Select Keyman to handle the kmp file
9. Verify the keyboard installation wizard appears
10. Finish installing sil_ipa and verify the IPA (SIL) keyboard appears

* **TEST_API_34** - Verifies Keyman can access local kmp file on Android API 34
1. Verify device/emulator is Android 14.0 "UpsideDownCake" / API 34
2. From Chrome --> Downloads --> select sil_ipa.kmp (Do not use Samsung MyFiles browser to access the file)
3. Select Keyman to handle the kmp file
4. Verify Keyman displays error about storage permission being denied
5. From Keyman for Android --> Info --> Troubleshooting --> How To - Grant Storage Permission
6. Follow the steps for the corresponding Android device to grant storage permission to Keyman
7. From Chrome --> Downloads --> select sil_ipa.kmp
8. Select Keyman to handle the kmp file
9. Verify the keyboard installation wizard appears
10. Finish installing sil_ipa and verify the IPA (SIL) keyboard appears

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM

Can we not request permission to access the files at the time it is needed? I've certainly seen that before. I would expect:

1. user selects file to open
2. Keyman pops a message saying it'll need file/video/photo access in order to open the file
3. User clicks OK, Keyman pops permission access request.
4. User clicks Allow, Keyman installs the package.

**Comment by darcywong00** [comment]
> Can we not request permission to access the files at the time it is needed? I've certainly seen that before. I would expect:

I think on older versions of Android, it used to prompt for the permission when the file is accessed. That seems to have changed over the years.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_API_31 (PASSED):** Tested with the attached PR build (Keyman 17.0.314-beta-test-11299) on an Android 12 / API 31 emulator and here is my observation: 1. Opened the page in Chrome browser. 2. Tried to download the sil_ipa.kmp file. Got an error message about storage permission being denied. 3. Opened the Info / Troubleshotting/ How To - Grant Storage permission. Followed the steps for the corresponding Android device to grant storage permission to Keyman. 4. Able to install sil_ipa.kmp file from Chrome/ Download folder. Verified the IPA (SIL) keyboard appears in Keyman In-App. Seems to be working as expected. 

..error message 
   

..Grant Storage permission help

   

..Allow Access
   
   


..Installed sil_ipa keyboard

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_API_34 (PASSED):** Tested with the attached PR build (Keyman 17.0.314-beta-test-11299) on an Android 14 / API 34 emulator and here is my observation: 1. Opened the page in Chrome browser. 2. Tried to download the sil_ipa.kmp file. Got an error message about storage permission being denied. 3. Opened the Info / Troubleshooting/ How To - Grant Storage permission. Followed the steps for the corresponding Android device to grant storage permission to Keyman. 4. Able to install sil_ipa.kmp file from Chrome/ Download folder. Verified the IPA (SIL) keyboard appears in Keyman In-App. Seems to be working as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.314-beta](https://keyman.com/downloads/releases/beta/17.0.314)

**Pull request merged**
