### PR TITLE
fix(oem/fv): Add fv_hulquminum_combine

### PR DESCRIPTION
**Pull request by darcywong00**
Addresses the FV app portion of keymanapp/keyman#2502

> we don't see a recently added keyboard in the list anywhere to download (Hul̓q̓umin̓um̓/hulquminum_combine

This will need to 🍒 pick to stable-16.0

### Note: 
fv_hulquminum has name: `Hul’q’umi’num’` (Hul\u2019q\u2019umi\u2019num\u2019)
fv_hulquminum_combine has name: `Hul̓q̓umin̓um̓` (Hul\u0313q\u0313umin\u0313um\u0313)

Some future TODO's:
* I wonder if keyboards.csv should be moved to the keyboards repo for FV staff to maintain.
* ~15 other keyboards had older versions in the csv file. I'm not certain the version info is used (it's also in kmp.json).

Testing depends on keymanapp/keyboards#2504 getting merged

## User Testing
**Setup** - Install the PR build of FV for Android or FV for iPhone and iPad

* **TEST_ANDROID** - Verifies the latest versions of the 3 reported keyboards can be installed
1. Install the PR build of FirstVoices for Android on an Android device/emulator
2. Launch the FV App
3. From the Setup menus, install the following keyboards (regions in parenthesis):
   * fv_southern_tutchone (Western Subarctic)
   * fv_hulquminum_combine (BC Coast)
   * fv_dane_zaa_zaage (Western Subarctic)
4. From the FV setup menu, set FirstVoices as the default system keyboard
5. Launch a separate app
6. Switch through the FV keyboards and verify the following versions:
    *  fv_southern_tutchone (9.2.1)
    * fv_hulquminum_combine (1.0)
    * fv_dane_zaa_zaage (9.3)
7. Verify fv_southern_tutchone is not a plain QWERTY layout

* **TEST_IOS** - Verifies the latest versions of the 3 reported keyboards can be installed
1. Install the PR build of FirstVoices for iPhone and iPad on an iOS device/emulator
2. Launch the FV App
3. From the Setup menus, install the following keyboards (regions in parenthesis):
   * fv_southern_tutchone (Western Subarctic)
   * fv_hulquminum_combine (BC Coast)
   * fv_dane_zaa_zaage (Western Subarctic)
4. From the FV setup menu, set FirstVoices as the default system keyboard
5. Launch a separate app
6. Switch through the FV keyboards and verify the following versions:
    *  fv_southern_tutchone (9.2.1)
    * fv_hulquminum_combine (1.0)
    * fv_dane_zaa_zaage (9.3)
7. Verify fv_southern_tutchone is not a plain QWERTY layout

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID (FAILED):** Tested with the attached PR build (First Voices)in the Android Mobile device (ver 13) and here is my observation: 1. Installed southern_tutchone (Western Subarctic), Hul̓q̓umin̓um̓ (BC Coast) and dane_zaa_zaage (Western Subarctic) keyboards from First Voices. 2. Set the FirstVoices as the default system keyboard. 3. Open Chrome browser app. 4. Clicked on the Google Search bar. 5. Opened the FirstVoices Keyboard picker menu. 5. Noticed that Suther Tutchone keyboard version is 9.2.2. 6. Verified that the southern_tutchone is seems to be qwerty layout(?).

..Southern Tutchone version

   


..Seems to be qwerty keyboard

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (FAILED):** Tested with the attached PR build (First Voices)in the iOS 17.0 / iPhone 15 Pro Max Simulator and here is my observation: 1. Installed southern_tutchone (Western Subarctic), Hul̓q̓umin̓um̓ (BC Coast) and dane_zaa_zaage (Western Subarctic) keyboards from First Voices. 2. Set the FirstVoices as the default system keyboard. 3. Open Chrome browser app. 4. Clicked on the Google Search bar. 5. Opened the FirstVoices Keyboard picker menu. 5. Noticed that Suther Tutchone keyboard version is 9.2.2. 6. Verified that the southern_tutchone is seems to be qwerty layout(?).

**Comment by darcywong00** [comment]
@bharanidharanj the layout looks to have "a" instead of q. Please retest because it looks like the layout does match https://help.keyman.com/keyboard/fv_southern_tutchone/9.2.2/fv_southern_tutchone

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID (PASSED):** Tested with the attached PR build (First Voices)in the Android Mobile device (ver 13) and here is my observation: 1. Installed southern_tutchone (Western Subarctic), Hul̓q̓umin̓um̓ (BC Coast) and dane_zaa_zaage (Western Subarctic) keyboards from First Voices. 2. Set the FirstVoices as the default system keyboard. 3. Open Chrome browser app. 4. Clicked on the Google Search bar. 5. Opened the FirstVoices Keyboard picker menu. 5. Noticed that Suthern_Tutchone keyboard version was changed from 9.2.1 to 9.2.2. 6. From the southern_tutchone help topic, it is confirmed the southern_tutchone keyboard layout was not an ordinary QWERTY keyboard layout. ie., instead of q it shows ä in the first row. 

   


* **TEST_IOS (PASSED):** Tested with the attached PR build (First Voices)in the iOS 17.0 / iPhone 15 Pro Max Simulator and here is my observation: 1. Installed southern_tutchone (Western Subarctic), Hul̓q̓umin̓um̓ (BC Coast) and dane_zaa_zaage (Western Subarctic) keyboards from First Voices. 2. Set the FirstVoices as the default system keyboard. 3. Open Chrome browser app. 4. Clicked on the Google Search bar. 5. Opened the FirstVoices Keyboard picker menu. 5. Noticed that Suthern_Tutchone keyboard version was changed from 9.2.1 to 9.2.2. 6. From southern_tutchone help topic, it is confirmed the southern_tutchone keyboard layout was not an ordinary QWERTY keyboard layout. ie., instead of q it shows ä in the first row.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.233-alpha](https://keyman.com/downloads/releases/alpha/17.0.233)

**Pull request merged**
