### PR TITLE
fix(windows): align title to top in Install Keyboard

### LINKED ISSUE #4179: bug(windows): titles in keyboard install dialog should be top-aligned
**Describe the bug**

image

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 20H2 x64 
 - Keyman version: 14.0.211-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4179.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.229-beta](https://keyman.com/downloads/releases/beta/14.0.229)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.230-beta](https://keyman.com/downloads/releases/beta/14.0.230)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
