### PR TITLE
fix(ios): Keyboard banner light/dark transitions

### LINKED ISSUE #2491: [iOS] Transition between light and dark modes does not transition in-app images
**Describe the bug**
As of #2312, we've got a near-complete dark mode implementation in place for version 13.0, but there are two little cases that're yet unhandled.

The first one:  the image banner doesn't yet show a dark-mode equivalent.

The second, and more tricky one:  If the user backs out to Settings and toggles between "light" and "dark" mode, theme-dependent images (like the toolbar & drop-down icons) will not swap automatically.

**To Reproduce**
1. Note your device's current appearance (light vs dark)
2. Open the Keyman app, let it load
3. Back out of the app (don't force-quit it!), then go to Settings
4. Change your device's appearance (so now, dark vs light)
  - On a real device, the option is at the top of Settings > Display & Brightness.
  - In the Simulator, you'll find it under Settings > Developer at the top.
5. Re-open the Keyman app.

Result:  if starting with light mode, the images used in the toolbar and drop-down menu should still be the "light-mode" images when the app is re-opened, despite all colors having transitioned to dark-mode settings.

**Expected behavior**
I would expect the images used in the toolbar and the drop-down menu to always match the device's active theme.  Unfortunately, this does not seem to be automatically done by current iOS color-theme support infrastructure.

**Screenshot**
When starting with light mode and transitioning to dark mode:

Screen Shot 2020-01-17 at 9 01 05 AM

Note that every icon is the "light mode" version.

---

**iPhone/iPad**
 - Device: any
 - OS: iOS 13.0+ only.
 - Keyman version: 13.0 alpha (after #2312, so likely 13.0.31+)
 - Target application: Keyman (in-app only)

**Additional context**
https://stackoverflow.com/a/57962920 shows some code that may be critical for addressing this.  If naught else, it should be a solid lead.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2491.
Is based on #2593.

This PR massively overhauls how the iOS app generates and displays the image banner typically used for the system keyboard.  Rather than maintain a set of static images for the banner, the app will now internally maintain a `UIView` and render that to a `base64` image string for use in KMW's image banner.  (I haven't yet removed the old banner images from the project, but there's little reason we couldn't.)

This allows the banner to adjust between light and dark mode styles freely, as the new backing `ImageBannerViewController` uses existing light/dark image assets - though getting them to transition was a pain.  This also allows the banner to adapt to each individual device's specifications, allowing a nice, pristine look on all devices.  So... to fix the main issue, adding an extra 'feature' was optimal:  we may now visually edit the banner as well.  Much better than further multiplying the static banner image set, which already lacked images optimal for some devices.

A minor snippet from the Interface Builder:

Screen Shot 2020-02-06 at 10 23 26 AM

Note that to do transitions optimally, the app is somewhat "misusing" `UIView`s - the backing `UIView` is never added to the window hierarchy.  This then requires misuse of `UIView.loadView` to force an appearance change.  (Well, unless we want to discard and create new `UIView` instances on light/dark transitions... which doesn't sound optimal.)  We simply can't do the standard work around of removing and readding the `UIView` to the view hierarchy, as it was never there to begin with.  It _might be_ possible to temp-add and then remove... I'm just a bit worried about adding extra chaos that way, as the keyboard's view doesn't exactly reserve any space for it.

iPhone SE:

Screen Shot 2020-02-06 at 9 57 49 AM
Screen Shot 2020-02-06 at 9 56 28 AM

iPhone X:

Screen Shot 2020-02-06 at 9 57 50 AM
Screen Shot 2020-02-06 at 9 56 29 AM

And, just in case of any worries, here's an iPhone SE for iOS 10:

Screen Shot 2020-02-06 at 10 15 23 AM

### Known issues

While this is really more of a leftover from #2487, I've noticed that if a keyboard without a lexical model is the first to load, the banner's height is usually incorrect when the system keyboard first loads.  Changing keyboards and/or orientation will fix the issue permanently until the system keyboard is next reloaded.
- I suspect this is due to something within `InputViewController`'s `topBarHeight` during keyboard-extension initialization - I feel like the "incorrect height" results from the default height if the device-request returns `nil`.  (That's just a lead though, and not necessarily the right answer.)
- At any rate, it's not optimal, but it's also not critical... and any required fix would be unrelated to this PR's changes.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Started reviewing but puzzled why we are doing it this way rather than just passing CSS or param to the web page to select background color? It seems a bit convoluted?

**Comment by jahorton** [comment]
> 
> 
> Started reviewing but puzzled why we are doing it this way rather than just passing CSS or param to the web page to select background color? It seems a bit convoluted?

For the majority of the keyboard, that's what is already being done.  The only thing affected by this PR is the banner itself.  Everything else is already in place.

The banner is trickier.  Historically, we've used a pure white banner 'background' (within the image) and a light grey OSK background - so we can't just reuse that parameter. (Granted, with a bit of work, one CSS styling sheet later may be able to do that.)

That said, since KeymanEngine for iOS is meant to serve as a library/engine that other apps may include, the best experience for other users would likely be found by allowing them to set a UIView for the banner like with this approach, even if it's a bit "convoluted" for our own use.  Other apps expect to interact with Swift code first and foremost.  They shouldn't _have_ to know that the banner is actually displayed on the Web side.  Yeah, we could require a CSS spec, but that's likely to feel convoluted for them.

Finally, there's the fact that requiring a CSS spec means adding yet another API to KMEI - there's currently no function to take a CSS stylesheet in a type-compatible way.  With this approach, we can easily reuse an existing API unaltered, leaving things... well, no messier than we found them.  This approach also provides what other users would feel to be a "clean" API for specifying their own banners in Swift.

**Comment by mcdurdin** [comment]
Also will we need to update the sample apps?

**Comment by jahorton** [comment]
After a bit more thought, I realized that the code was still a bit convoluted after all, as it originally took me a while to narrow down what was needed to make the banner work.  I've gone through and simplified that code; we no longer require a custom UIView implementation, which makes a big difference.

> Also will we need to update the sample apps?

The sample apps don't need an update for this - they can rely on their old static banner images without any changes.  Those images may not be optimal for dark mode, but they're just samples.

That said, other recent changes have broken KMSample2.  I'll get something started toward that.

**Pull request merged**
