### PR TITLE
[ios] device rotation layout fixes

### LINKED ISSUE #248: [Web] KeymanWeb on iOS does not display keyboard correctly in landscape
A problem analogous to that of https://github.com/keymanapp/keyman/issues/224 for the iOS app also exists for KeymanWeb, often on the same devices.  The system keyboard doesn't use the full available width when in landscape.

As #224 was fixed with https://github.com/keymanapp/keyman/commit/857657a1d000d6caa391052f16947a0ce2ab56f4, that commit may be worth referencing.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #248.

This addresses numerous issues affecting 'native-mode' KMW on iOS devices:

- issues with touch-alias element alignment post rotation
- issues with OSK layout & resizing
- issues with OSK text on larger iPhones (they were being treated as 'tablets' due to our resolution-checking code)

---

As of this point, it appears that the issue is fully resolved within 'native' KMW without affecting the Android app.  However, iOS app issues remain - though @jacobbullock has noted that it's quite possibly something related to #500.

**_Do NOT merge_** until #500 is fixed and further testing indicates that the iOS app will not be adversely affected by this PR.  There is a chance that the changes contained herein may introduce an extra issue, rather than the main remaining problem being #500.

### CODE REVIEW

**Comment by jahorton** [comment]
"Test completion" looks to require completion of work on #500 due to potential for cross-effects, as errors within the iOS app are arising that parallel that issue.  Work on this PR will be put on pause for now while awaiting further developments.

**Comment by jahorton** [comment]
New note:  it would additionally be wise to wait on a fix for #818 before merging this issue.  Investigation there indicates that iPhone 6-8 Plus and iPhone X do not currently suffer #818 due to side effects of an issue addressed by this PR.

**Comment by mcdurdin** [comment]
Given the difficulty we have had in getting the iOS rotation correct in-app, I am now going to postpone this  change. It's too big a change for the last sprint before release especially as Josh is not available.

**Comment by MayuraVerma** [comment]
Any updates on this?

**Comment by mcdurdin** [comment]
@MayuraVerma We will review this in version 11 once @jahorton is available to investigate. There have been a number of improvements to the iOS native rotation and scaling.

**Pull request closed without merging**
