### PR TITLE
chore(linux): Rename libkmnkbp0-0 package 〽️

### LINKED ISSUE #9733: chore(linux): Rename `libkmnkbp` to `libkeymancore`
As a follow-up of #9721 and #9722 we should rename the library to `libkeymancore` and also bump the version number. This also requires changes in the `debian` directory.

- new binary will be `libkeymancore.so.1.0`
- package names will be `libkeymancore` and `libkeymancore-dev`

_Edit: Updated library name following our discussion in standup meeting. `libkeymancore` is less cryptic than `libkmncore`._

### PR DESCRIPTION
**Pull request by ermshiperete**
Closes #9733.

# User Testing

**TEST_SMOKE**: Run a quick smoke test: install the packages from this PR, then test that installing a keyboard and typing with the keyboard still works.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> Debian packaging GHA check fails because the GHA on `master` is used for the build and that still contains the old name.

Tricky for this kind of thing... is there a good way around it?

**Comment by ermshiperete** [comment]
> > Debian packaging GHA check fails because the GHA on `master` is used for the build and that still contains the old name.
> 
> Tricky for this kind of thing... is there a good way around it?

#9812 :smile:

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_SMOKE (PASSED):** Tested with the attached PR build (keyman 17.0.196-alpha-local (package version 17.0.196-1~PR-9795-1597.1+mantic1) in Ubuntu 23.10 Mantic Minotaur OS (VM) and here is my observation: 1. Downloaded and installed some keyboards (like Amharic, Khmer, Korean Korda, Sanskrit etc., ) using keyman configuration dialog. 2. Tested the keyboards on LibreOffice Writer, Mozilla browser (search bar), and Text Editor and I could use the keyboards without any problem. 3.  Also, I did the smoke test on Wasta 20.04 Linux OS and it seems to be working fine. 

..smoke test on Ubuntu 23.10 mantic OS

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.197-alpha](https://keyman.com/downloads/releases/alpha/17.0.197)

**Pull request merged**
