### PR TITLE
docs(android): Document using gestures on touch, and remove references to Browser

### LINKED ISSUE #10627: docs(android): using new gestures
v17 includes new gestures. We should have user documentation for this.

See also #10628.

### PR DESCRIPTION
**Pull request by darcywong00**
First of a few small PRs in updating the Keyman for Android in-app help documentation.

Changes to the in-app documentation:
* Add documentation on new gesture features (Fixes #10627)
* Remove references to Keyman Browser (removed in #8430)
* Also fixes alignment of the share icon below the "Toolbar icons" header

@keymanapp-test-bot skip

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by jahorton** [comment]
I do not believe that this sufficiently fixes #10627.

See notes I've placed on #10628; we probably want something on a similar level on both platforms, though I suppose there is room for discussion.

**Comment by mcdurdin** [comment]
> I do not believe that this sufficiently fixes #10627.

I concur that we could do with more detail on flicks, although given the detail reqs were in #10628, that's perhaps not a surprise!

I have also added some notes to #10628 which are applicable.

**Comment by darcywong00** [comment]
I've added a separate page about gesture per your suggestions

https://github.com/keymanapp/keyman/issues/10628#issuecomment-1939760454

I also agree about avoiding  the term "modipress" since it's not in the LDML spec. (Maybe we use modifer-press?)

**Comment by darcywong00** [comment]
Gesture documentation updated to match 17.0 release notes
https://github.com/keymanapp/keyman/wiki/Keyman-17.0-Release-Notes#using-gestures-on-the-touch-layout-keys

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.269-beta](https://keyman.com/downloads/releases/beta/17.0.269)

**Pull request merged**
