### PR TITLE
chore(common): Cleanup Kannada locale

### LINKED ISSUE #8075: bug(windows): Kannada UI name appears twice in the UI language List in Keyman Configuration dialog
### Describe the bug

I noticed that the Kannada language name appears twice in the UI language List. 

### Reproduce the bug

1. Install Keyman 17.0.34-alpha-test-8074 build in Windows OS.
2. Open Keyman Configuration dialog. 
3. Click the 'Display in' list box. 
4. Scroll down and Select 'Kannada' language. 

Here, I noticed that the Kannada language appears twice in the list box. 

   

### Expected behavior

Kannada language name should not be duplicated in the UI list box. 

### Related issues

#7559

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.34-alpha-test-8074

### Operating system

Windows 11 OS 

### Device

Windows Desktop

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #8075 

This fixes several issues @MayuraVerma noted with the Kannada localization:
* Use `kn` on Windows instead of `kan-Knda-IN` (pre-Crowdin strings) and `kn-IN` (Crowdin strings). This fixes Kannada from being listed twice on the locale list.
* Updated other Kannada strings noted on Crowdin.

## User Testing
**Setup** - Load the PR build of Keyman for Windows

* **TEST_WINDOWS_KANNADA** - Verifies Kannada is only listed once
1. Start Keyman for Windows
2. Open Keyman Configuration dialog.
3. Click the 'Display in' list box.
4. Scroll down and Select 'Kannada' language.
5. Verify "Kannada" is only listed once
6. Select "Kannada"
7. Verify the UI is in Kannada.

* **TEST_WINDOWS_OLD_TO_NEW_KANNADA** - Test what happens when upgrading to this release when in Kannada locale
1. Install Keyman for Windows release 17.0.43 or earlier.
2. In Keyman Configuration, ensure that Kannada locale is selected.
3. Install this test build of Keyman for Windows.
4. Start Keyman Configuration. The locale will probably be back to English -- this is okay. What we want to ensure is that the Configuration doesn't go wrong in other ways (e.g. crash, blank screen, etc.)

### CODE REVIEW

**Comment by MayuraVerma** [comment]
Please apply this changes to V16 also.

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by darcywong00** [comment]
> Please apply this changes to V16 also.

I plan to 🍒 pick onto stable-16. But it's TBD when another 16.0 build gets released.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_WINDOWS_KANNADA (PASSED):** Tested with the attached PR build (17.0.45-alpha-test-8182) in Windows 11 OS and here is my observation: 1. It is showing only one Kannada name in the display list. Seems to be working as expected. 

   

* **TEST_WINDOWS_OLD_TO_NEW_KANNADA (FAILED):** Tested as per the instructions in Windows 11 OS and here is my observation: 1. Installed Keyman 17.0.39 build in the system. Able to see the duplicate name (kannada) appears in the display list. 2. Upgraded to Keyman 17.0.44-alpha and still the duplicate name appears in the list. Seems to be an issue. 

..before upgrade

   

..after upgrade

**Comment by darcywong00** [comment]
@bharanidharanj todl me he wrongly failed the second result.

@keymanapp-test-bot retest TEST_WINDOWS_OLD_TO_NEW_KANNADA

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.45-alpha](https://keyman.com/downloads/releases/alpha/17.0.45)

**Pull request merged**
