### PR TITLE
feat(ios/engine): language selection during (file-based) package installation

### PR DESCRIPTION
**Pull request by jahorton**
While it's not yet fully integrated into all installation pathways, the package installation prompt has been significantly reworked to allow language selection.

Additional work will be necessary to integrate this with installations triggered by keyboard search.

In the meantime, some screenshots:

Dark-mode portrait
Light-mode landscape
Dark-mode portrait single-select
iPad light mode

Note that this prompt relies on the language names that are compiled into each KMP file.  If and when those don't exist... the presented language list may be, uh, less than helpful.  (Of course, we can swap to a different scheme for language name lookup at a later time.  Perhaps something that consumes langtags.json?)

One language will be automatically selected when the prompt is displayed - the old 'default'.  This selection will automatically be visible thanks to a Swift option for associated autoscroll.

One last tidbit - this may need some debate, but for multiple-keyboard packages, it will install all keyboards matching the language(s) that the user selects.  Examples:
-  For a Greek+Hebrew combo package, if the user only selects Greek, they don't get the Hebrew keyboard.
-  For a Greek+Hebrew combo package, if the user selects both Greek and Hebrew:
    - The Greek keyboard is installed for Greek (does not support Hebrew)
    - The Hebrew keyboard is installed for Hebrew (does not support Greek)
-  If a package contains two keyboards for Thai and the user selects Thai, both keyboards will be installed (for Thai).
    - Nothing prevents the user from going into settings and removing one or the other afterward.
    - This is (probably) a rare edge case, so I don't mind there being a little roughness here.

... I could probably stand to add in a unit test for the "selected language(s)" -> "installed resources" mapping, granted.

-----

Regarding reviews:
- Note that if desired, it's _relatively_ easy to redo the constraints and placements of each of the three main views constituting the prompt:
    - The welcome.htm WebView
    - The language-selection table
    - The version + copyright footer

Each of the three has a base-level 'container'.  Within each, we can easily manipulate the UI elements.
- One possible future optimization:  for "compact" devices where the three main views are vertically stacked, add a "hide/display" button at the lower-left of the WebView.
   - "hide" - reduces the WebView's height to 30 or so pixels.  Mainly, enough so that the button is still displayed so that the user can later press...
   - "display" - unhides the WebView, returning it to its original height.
- Another:  when the list of languages is very short _and_ the views are vertically stacked, shrink the language-selection table to fit.
    - Unfortunately, iOS does _not_ natively facilitate this behavior; it'd require manual calculations, subclassing, etc.

### CODE REVIEW

**Comment by mcdurdin** [comment]
I like the concept and basic design. Some thoughts:

* I note that the `French Basic` example only has one language. Do we need to show the language list in that situation?
* Can we put the version/copyright string at the top of the screen, not below the language selection (for portrait mode on iPhone anyway)?
* The font size for the title 'Available Languages' seems disproportionate to the text in the list.
* I can see you've tried to make the most of the real estate for iPhone landscape. Despite that, I'm not sure that it is going to be particularly wonderful to use. Perhaps we just disable it and support only portrait? How does the rest of the app go in landscape?
* Does the color bar indicate selection? Can we use a standard iOS check mark instead?

image

And a hoopy idea: 

* What if starting to scroll the language list expanded it up slowly (as you scrolled) to eventually completely hide the readme. Scrolling back to the top of the list would reduce it back to the original size as it approached the top of the list. If this is really hard to do, then don't worry about it, but it could be a fairly intuitive way of growing the list unobtrusively (helpful for those really long lists).

I haven't yet reviewed the code 😁

**Comment by jahorton** [comment]
> I like the concept and basic design. Some thoughts:
> 
> * I note that the `French Basic` example only has one language. Do we need to show the language list in that situation?

Right, that'd be one possible optimization.  I figured that could be follow-up work, as it requires making things more complex than the current changes.  In particular, it'd require a bit of view-swapping and dynamic constraint maintenance.  Nothing that shouldn't be doable within a couple of hours of work once we know what we want, but alterations add up.
- For this example, which is better?
    - Do we display a simple label with the text "Installing for French"?
    - Or do we outright hide that view?
        - Dynamically moving the version + copyright footer either above/below the web view means a lot of "fun" constraint work.

> 
> * Can we put the version/copyright string at the top of the screen, not below the language selection (for portrait mode on iPhone anyway)?

We can put it directly underneath the "cancel / install" navbar, yes.  Also, I'm starting to think that in landscape, it should span the full width, rather than being placed above/beneath just the language selector.

> 
> * The font size for the title 'Available Languages' seems disproportionate to the text in the list.

:+1:

> 
> * I can see you've tried to make the most of the real estate for iPhone landscape. Despite that, I'm not sure that it is going to be particularly wonderful to use. Perhaps we just disable it and support only portrait? 

Wait... what?  I feel it's _more_ usable in landscape than in portrait!  That said, this would change if I implemented a "hide/display" toggle for the welcome page's display, or if we implemented a "joint scrolling" strategy like what I describe for an answer to a later point in this comment.

If necessary, https://stackoverflow.com/a/11785618 seems to show the way to restrict just this prompt to be "portrait-only", without affecting the rest of the app.

> How does the rest of the app go in landscape?

We've supported landscape mode (though _not_ upside down) for forever within the iOS app.

Screen Shot 2020-07-28 at 11 39 59 AM

Screen Shot 2020-07-28 at 11 41 59 AM

Screen Shot 2020-07-28 at 11 40 15 AM


> 
> * Does the color bar indicate selection? Can we use a standard iOS check mark instead?
> 
> 
> image

Should be possible; I'd just need to hunt down the code for this.

That said, a counter-argument:
- Current behavior - "please install this language"
- Check mark + dimming/disabled item - the language is _already_ installed for this package
    - There's currently no code handling this scenario
    - This matches our existing selection dynamics for the advanced lexical model installation picker.

Screen Shot 2020-07-28 at 11 57 52 AM


> 
> And a hoopy idea:
> 
> * What if starting to scroll the language list expanded it up slowly (as you scrolled) to eventually completely hide the readme. Scrolling back to the top of the list would reduce it back to the original size as it approached the top of the list. If this is really hard to do, then don't worry about it, but it could be a fairly intuitive way of growing the list unobtrusively (helpful for those really long lists).

If we don't mind the "available languages" header scrolling with the rest, something like that should be relatively possible; the trick is that it requires changing the "base three views" bit I described in the main description.  For _select_ device configurations, we'd want to put the WebView together with the language-selector within a `UIScrollView`.
- This would be easiest if we did it for _every_ device... but I don't recommend this for landscape iPhones, since we probably want to keep the WebView to a limited size (that would itself need internal scrolling).

> 
> 
> I haven't yet reviewed the code 😁

Understood.

Would it be reasonable to address design tweaks as follow-up issues should the scope become large?  I'd estimate a minimum of a half-day's work to make all the changes you're suggesting here, and possibly a whole day's work.

**Comment by mcdurdin** [comment]
> We can put it directly underneath the "cancel / install" navbar, yes. Also, I'm starting to think that in landscape, it should span the full width, rather than being placed above/beneath just the language selector.

Definitely. Even better: if it was part of the WebView and scrolled when you scrolled the readme. This could be implemented by having a page loaded in the webview with the copyright/version text in it, with an [expanding iframe](https://stackoverflow.com/questions/819416/adjust-width-and-height-of-iframe-to-fit-with-content-in-it) directly underneath that contained the readme. Could even put it below the Readme then or the copyright and version on separate lines as it doesn't consume screen real estate in the same way.

> For this example, which is better?
> * Do we display a simple label with the text "Installing for French"?
> * Or do we outright hide that view?

I think we hide the view. The keyboard will have enough detail in its name and readme, generally, to understand which language it is intended for.

> Wait... what? I feel it's _more_ usable in landscape than in portrait!

I feel like the readme is pretty squashed in portrait and may be unusable for many documents which may have images etc. But it doesn't really matter -- given the rest of the app supports landscape, we'll support it here too. They can always rotate their phone if they find it unwieldy.

> We've supported landscape mode (though _not_ upside down) for forever within the iOS app.

👍 

> Should be possible; I'd just need to hunt down the code for this.
> 
> That said, a counter-argument:
> 
> * Current behavior - "please install this language"
> * Check mark + dimming/disabled item - the language is _already_ installed for this package
>   
>   * There's currently no code handling this scenario
>   * This matches our existing selection dynamics for the advanced lexical model installation picker.

I'm not really understanding what you mean here. I think the issue is that the colored bar is unclear as to what it means, especially if there are just two languages in the list. A check mark makes it clear that the language is selected. We shouldn't be dimming the item when they select it here.

> If we don't mind the "available languages" header scrolling with the rest, something like that should be relatively possible

That's probably okay.

> * I feel like the welcome.htm files

But we're showing the readme here, not welcome, right? The welcome is shown after install.

> Can someone speed-scroll past it? Sure... but it still feels a bit wrong to require that right off the bat.

I don't understand?

> Would it be reasonable to address design tweaks as follow-up issues should the scope become large?

Yep. There are five issues I've noted here (I think!), and what I reckon belongs where:

# To address
* Font size of header.
* Check marks in language list.
* Placement of version/copyright string (ideally within the WebView so it becomes part of the scrollable content.)

# Follow-up issues
* Resizing of the language list. Follow-up.
* Hiding language list for single language.

**Comment by jahorton** [comment]
> 
> > Wait... what? I feel it's _more_ usable in landscape than in portrait!
> 
> I feel like the readme is pretty squashed in portrait and may be unusable for many documents which may have images etc. But it doesn't really matter -- given the rest of the app supports landscape, we'll support it here too. They can always rotate their phone if they find it unwieldy.

It's mostly an issue with older iOS phones, I think.  (Before iPhone X.)  Later-released devices tend to be taller proportionally, with the exception being the new iPhone SE 2, which at least has a higher base resolution.
- iPhone 8 and before:  aspect ratio 9:16
- iPhone X and after:  aspect ratio 9:19.5

(source: [DeviceKit](https://github.com/devicekit/DeviceKit/blob/master/Source/Device.generated.swift))

> > Should be possible; I'd just need to hunt down the code for this.
> > That said, a counter-argument:
> > 
> > * Current behavior - "please install this language"
> > * Check mark + dimming/disabled item - the language is _already_ installed for this package
> >   
> >   * There's currently no code handling this scenario
> >   * This matches our existing selection dynamics for the advanced lexical model installation picker.
> 
> I'm not really understanding what you mean here. I think the issue is that the colored bar is unclear as to what it means, especially if there are just two languages in the list. A check mark makes it clear that the language is selected. We shouldn't be dimming the item when they select it here.

:confused:  If it helps clarify, suppose that a user is actually installing a package for the second time.

That - the colored bar - is literally how the app handles selection in every other context, and this is how the app has been handling it for years.

Dim + check mark is how it's indicated that a resource _has already been installed, previously_ - and that's how the app's been handling _that_ scenario for years.  

To change visual language now would likely be confusing for users.  Consistency should be favored.  Also, if still confused, the user would figure out _pretty_ quickly when deselecting the auto-selected language - the Install button disables when no languages are picked.

Would it be fine to both color the bar + checkmark for "please install this", with dimmed & unselectable + checkmark indicating "already installed"?

> 
> > * I feel like the welcome.htm files
> 
> But we're showing the readme here, not welcome, right? The welcome is shown after install.

Nope, that's the welcome.htm.  Not sure why it's long been welcome.htm that's displayed here within the app, just stating what has been.

Worth note:  some keyboard packages don't contain readme.htm but do contain welcome.htm.  (Like `khmer_angkor`.)  Anecdotally, I much prefer sil_euro_latin's welcome.htm to its readme.htm; similarly for sil_cameroon_qwerty.  _**Especially**_ sil_cameroon_qwerty.

Screen Shot 2020-07-29 at 8 53 52 AM

I'd have to crack open other packages to give opinions there.
- Also, re: sil_euro_latin, its current readme.htm is about to become very redundant.  (It basically just says "hi, I support these languages." - something the app will _also_ be saying.)
- If we were to change things, I'd argue that (at least) if readme.htm isn't found, we display welcome.htm if it exists.
    - Might be nice to ensure welcome.htm can be viewed, too - this is the part with visual layout documentation, which provides the user with better info.

Also, there is no "shown after install" in iOS right now.  When install's completed, there are no further UI screens displayed; the app even "kicks" the user out, back to the main settings menu.  Pre-install is (currently) the only time the app automatically displays any non-keyboard/dictionary content from a package to the user.

Not saying we can't change these points; I'm just being descriptive about what actually exists right now.

**Comment by mcdurdin** [comment]
> Would it be fine to both color the bar + checkmark for "please install this", with dimmed & unselectable + checkmark indicating "already installed"?

Okay. We can revisit the visual style across the app in a future PR if we want. Agree consistency is important. Just a shame that the pattern we've ended up with is not really iOS styling.

> Worth note: some keyboard packages don't contain readme.htm but do contain welcome.htm. (Like `khmer_angkor`.) Anecdotally, I much prefer sil_euro_latin's welcome.htm to its readme.htm; similarly for sil_cameroon_qwerty. _**Especially**_ sil_cameroon_qwerty.

The whole readme vs welcome discussion is a bit of a tragedy 😆. What Keyman for Windows does is shows the Readme prior to install, then the Welcome (which **should** be called "documentation" or "help") is shown post-install. The Welcome is also what is shown if the user accesses the help for the keyboard from Configuration later.

That was the intended pattern for all platforms. I agree some of the keyboards have somewhat less-than-ideal content in their readme (could open issues against these keyboards I guess?). But having all the documentation presented at install time is also a problem: it diverts the user from the decision that they need to make: go ahead with install or not? The readme is supposed to help them with that; the welcome is supposed to take them through the minutiae of using the keyboard.

So I would like to make sure for v14 that we present the readme here. Whether or not we present the welcome immediately after install is then a secondary question for a future PR.

> If we were to change things, I'd argue that (at least) if readme.htm isn't found, we display welcome.htm if it exists.
> * Might be nice to ensure welcome.htm can be viewed, too - this is the part with visual layout documentation, which provides the user with better info.

Both of these are design discussions that impact all our platforms, not just iOS. For now, can we make sure we are making it consistent with Windows (as the 'reference' platform)?

**Comment by jahorton** [comment]
Something of minor interest I'm noticing - the selection-color shift _**is**_ the iOS default for indicating "selected" when working with `UITableView`s like this.  Displaying a checkmark takes extra handling and is less intuitive to handle at that.

Definitely still possible to manage, though.  Just requires some extra work.

**Comment by jahorton** [comment]
Regarding section header size... it's an ugly thing to change.

https://stackoverflow.com/questions/19802336/changing-font-size-for-uitableview-section-headers

Note that the font size is the same as seen elsewhere within the app:

Screen Shot 2020-07-30 at 1 35 34 PM

The row height is shorter, though - that's something much easier to change.  (Even section height - just not the _font_.)

_**However!**_  There is an alternative 'styling' that we can apply to the UITableView.  This one pretty closely matches what you see in iOS's system settings.

Screen Shot 2020-07-30 at 1 47 32 PM


The issue here is that the section header will not 'float' as the user scrolls through the languages.  For packages with numerous languages supported, this may cause the header to be hidden when the view is first launched (due to scroll position of the default selection).  Aside from that point, the change is basically free - far simpler and more maintainable than trying to forcibly control font size ourselves.

Finally, we could drop the header itself with little issue, although I think this is a worse solution due to removing useful context for the language-select menu.

----

Personally, I prefer the current styling, even if it does mean the section-header font size is a bit big.  After that, the alternate styling is a 'better' solution than the other options - and it's not that "far behind" the current styling, anyway.

**Comment by jahorton** [comment]
Pushed a couple of commits regarding some of the "more pressing" issues, but the way forward after that is less clear.

Screen Shot 2020-07-30 at 1 50 18 PM

I think a design discussion is in order regarding the other aspects.  While I _could_ go ahead and move the version + copyright bar, that's very likely to be moved again in whatever follow-up we decide on.  As the constraint work involved isn't insignificant, I'd rather "hold" on that for now.

----

One idea:

- iPhones only
    - single language supported by package
        - single screen: version, copyright, readme.htm
        - right navigation item = "Install"; no language list appears.
    - multiple languages supported by package
        - two screens:
            1.  version, copyright, readme.htm.  right navigation item = "Next"
            2.  language picker.  left navigation item = "Back", right = "Install", may swap back and forth without losing selections
- iPads only
    - keep current format (aside from version/copyright placement), hiding language list section if only one language is available.

**Comment by mcdurdin** [comment]
> Regarding section header size... it's an ugly thing to change.

This answer doesn't look that ugly? https://stackoverflow.com/a/23021471/1836776

> One idea:

I like it. But that's a fair bit more work I imagine? That avoids the screen real estate compromises and also clarifies the install process for the user; hopefully the majority of search results will have the correct language selected automatically and they will just be able to 'click through' the second page easily, also.

**Comment by jahorton** [comment]
> 
> 
> > Regarding section header size... it's an ugly thing to change.
> 
> This answer doesn't look that ugly? https://stackoverflow.com/a/23021471/1836776

From that answer:
> Note that you should also respond to heightForHeaderInSection to have any changes to your header's height accounted for in the layout of the table view.

From others:
> While this is a correct solution, be careful with this method. For a header longer than one line, you will have to perform the calculations of the height of the header in tableView:heightForHeaderInSection: which can be cumbersome.

Granted, we _are_ planning on keeping it short and single-lined.  Hopefully all localizations will respect this as well, otherwise... icky things will happen should we take this approach.

> This does not resize the header view, so if your font is larger or significantly different, such as Zapfino (don't ask why), it will cut the text out. If you have to calculate the size on your own, it's a mess and you shouldn't do it.

Possibly a bigger concern re: localizations?  We might be able to get away with it as long as we do a 'relative' font-size decrease, using the default font-size as a base value.

---- 

And of course, all of this is to alter default iOS styling, rather than simply letting defaults stand.

**Comment by jahorton** [comment]
> > One idea:
> 
> I like it. But that's a fair bit more work I imagine? That avoids the screen real estate compromises and also clarifies the install process for the user; hopefully the majority of search results will have the correct language selected automatically and they will just be able to 'click through' the second page easily, also.

Fair bit more work?  Sure.  That's what a follow-up PR is for.

**Comment by mcdurdin** [comment]
> Fair bit more work? Sure. That's what a follow-up PR is for.

Let's go with this approach. It'll avoid the whole question of the font size in the header as well 💯

**Pull request merged**
