### PR TITLE
test(common/web/types): unit tests for file-types

### PR DESCRIPTION
**Pull request by markcsinclair**
Unit tests for `util/file-types.ts`

See #9052

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by markcsinclair** [comment]
Function `replaceExtension(filename: string, oldExtension: string, newExtension: string): string` has a poor response to either the `oldExtension` or `newExtension` being `null`.

With a `null` `oldExtension` it throws `TypeError: Cannot read properties of null (reading 'length')`.

With a null `newExtension` it returns the base filename with the four characters `null` appended.

**Comment by mcdurdin** [comment]
> However, it does not seem to be used anywhere.

The fix seems straightforward in this case! DELETE!

**Comment by markcsinclair** [comment]
> > However, it does not seem to be used anywhere.
> 
> The fix seems straightforward in this case! DELETE!

I will open a separate issue and PR, but leave `replaceExtension()` in, with failing tests commented out` for now

**Comment by markcsinclair** [comment]
Note test file name changed to `util/file-types.tests.ts`

**Pull request merged**
