### PR TITLE
feat(web): conversion of Keyman Engine for Web to ES modules 🧩

### PR DESCRIPTION
**Pull request by jahorton**
This is the base branch for an ongoing conversion of Keyman Engine for Web code; when complete, it will be based on use of ES modules rather than the old "namespace"-style structure it was previously using.

Other goals include complete modularization of Keyman Engine for Web's on-screen keyboard component.  While still included in KMW, it will also be able to function independently and be compilable as a standalone project.  As we are considering reuse of Web's OSK within the desktop-platform Keyman apps, this will be a very notable step toward accomplishing such a goal.

At this time, this branch also includes an update for Web's README.md corresponding to the changeset from the 📜 set of Web code reorganization PRs ending with #7831.  (It should be re-updated again near completion.)

------

Approximate state of modularization so far (so GitHub won't hide the comment on us):

```mermaid
graph TD;
    OSK[web/src/engine/osk];
    KP["common/web/keyboard-processor"];
    IP["common/web/input-processor"];
    OSK-->KP;
    IP-->KP;
    Utils["common/web/utils"];
    KP---->Utils;
    Wordbreakers["common/models/wordbreakers"];
    Models["common/models/templates"];
    Models-->Utils;
    LMWorker["common/web/lm-worker"];
    LMWorker-->Models;
    LMWorker-->Wordbreakers;
    LMLayer["common/predictive-text"];
    LMLayer-->LMWorker;
    IP-->LMLayer;

    subgraph PredText["WebWorker + its interface"]
        LMLayer;
        LMWorker;
        Models;
        Wordbreakers;
    end

    subgraph Headless["Fully headless components"]
        direction LR
        KP;
        IP;
        Utils;
        PredText;
    end

    subgraph ClassicWeb["Previously unmodularized components"]
        Device[web/src/engine/device-detect];
        Device----->Utils;
        Elements[web/src/engine/element-wrappers];
        Elements-->KP;
        KeyboardCache[web/src/engine/package-cache];
        KeyboardCache-->IP;
        DomUtils[web/src/engine/dom-utils];
        DomUtils-->Utils;
        OSK-->DomUtils;
        OSK---->IP;
        Configuration[web/src/engine/paths];
        Configuration-->OSK;
        CommonEngine[web/src/engine/main];
        CommonEngine-->Configuration;
        CommonEngine-->Device;
        CommonEngine-->KeyboardCache;
        CommonEngine-->OSK;
    end

    subgraph WebEngine["Keyman Engine for Web (top-level libraries)"]
        Browser[web/src/app/browser];
        WebView[web/src/app/webview];

        WebView--->CommonEngine;

        Browser--->CommonEngine;
        Browser--->DomUtils;
        Browser--->Elements;
    end
```

(This technically includes changes from not-yet-published commits, but it's pretty accurate to where things are headed.)

Note that the `element-wrappers` child package will be referenced by the `app/browser` target, which is not included in the graph above.  (It'd rest higher up.)

------

🚧 Pending tasks of note 🚧:
- [ ] Fully modularize all of KMW
- [ ] Unit test scripts for CI builds should be defined in the new ./ci.sh test action from #8001, rather than Web's ./build.sh or ./test.sh.
- [ ] #8148 
- [ ] Address, then resolve all comments for #8055.
    -  They're loose threads that were unresolvable at the time.
- [ ] SO MANY loose threads for #8056... but there's no clear checklist for them.
    - General guideline for this:  check all doc-comments for all "EventMap" types in the following files:
        - [ ] oskView.ts
        - [ ] visualKeyboard.ts
        - There may be others, but those are the main two of note... and that I could find with preserved 'original implementation' code.
- [ ] Before merging, run a full regression-test suite on KMW and the mobile apps in order to find possible regressions.
- [ ] Ensure that no regression in line with https://github.com/keymanapp/keyman/issues/3910 occurs.  (Can be expensive long-term if we let that one slip by!)
- [ ] Update keymanweb.com to use boolean `false` instead of string `'false'` for KMW's `setActiveOnRegister` initialization option when using KMW 17.0+: https://github.com/keymanapp/keyman/pull/8458#discussion_r1147289009
- [ ] Thorough testing of selection, start-of-context behavior, etc.
    - https://github.com/keymanapp/keyman/pull/8462#issuecomment-1475698005

### CODE REVIEW

**Comment by jahorton** [comment]
Figured out why the "Language Modeling Layer" config was failing; a PR-review-motivated rename for #7894 got merged in, and the corresponding property in a lm-worker build-assist script here wasn't updated to match.  Simple fix, at least.

**Comment by jahorton** [comment]
Current state of modularization:

```mermaid
graph TD;
    OSK[web/src/engine/osk];
    KP["@keymanapp/keyboard-processor"];
    IP["@keymanapp/input-processor"];
    OSK-->KP;
    IP-->KP;
    Utils["@keymanapp/web-utils"];
    KP-->Utils;
    Wordbreakers["@keymanapp/models-wordbreakers"];
    Models["@keymanapp/models-templates"];
    Models-->Utils;
    LMWorker["@keymanapp/lm-worker"];
    LMWorker-->Models;
    LMWorker-->Wordbreakers;
    LMLayer["@keymanapp/lexical-model-layer"];
    LMLayer-->LMWorker;
    IP-->LMLayer;
    Device[web/src/engine/device-detect];
    Device-->Utils;
    Elements[web/src/engine/element-wrappers];
    Elements-->KP;
   
    DomUtils[web/src/engine/dom-utils];
    DomUtils-->Utils;
    OSK-->DomUtils;
```

More modules are coming, and it'll definitely get a bit noisy.

**Comment by mcdurdin** [comment]
Why did you merge this?

**Comment by mcdurdin** [comment]
> Why did you merge this?

See #8553 for reasons why. Trying to unravel now.

**Pull request merged**
