### PR TITLE
fix(common/core/web): mock construction with caret at index 0

### LINKED ISSUE #4463: bug(common/models): delete the left most word would give a duplicate of the whole phrase
**Describe the bug**

Type this (the quick brown fox) out in the Keyman for Android using EuroLatin (SIL) keyboard with the predictive text enabled. Now, please the cursor after "the" and choose "they" from the suggestion on the banner, and then delete it by pressing the backspace five times. On the fifth press of the backspace, a duplicate of the phrase should appear. The cursor is seen in between the duplicated phrases.

Screenshot_1612947496

**Expected behavior**

The fifth backspace should not generate a duplicate of the phrase. 

---

**Keyman for Android:**
 - Device: Pixel 2 API 29 (emulator)
 - OS: Android 10
 - Keyman version 14.0.235-beta-test-4427
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.3 (with MTNT)
 - Language name: English

**Additional context**

https://github.com/keymanapp/keyman/pull/4427

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4463.

The bug directly fixed by these changes triggered a context desync when embedded in the Android and iOS apps, which is what caused #4463.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
doncha love type safety?

Could we say if `typeof caretPos == 'Number'` instead? which may be slightly more obvious?

**Comment by jahorton** [comment]
... those aren't the checks I was expecting from CI.  Windows checks, not Web?

**Comment by mcdurdin** [comment]
https://build.palaso.org/viewLog.html?buildId=252707&buildTypeId=Keyman_Test&tab=buildLog&_focus=108#_state=108 shows the log. Will have to dig deeper to find out why it didn't trigger web build. I'd have expected web,android,ios,windows(developer) builds.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.17-alpha](https://keyman.com/downloads/releases/alpha/15.0.17)

**Pull request merged**
