### PR TITLE
fix(linux): Fix installation if shared kbd already installed

### LINKED ISSUE #7722: bug(linux): Error installing keyboard if shared keyboard is already installed
To reproduce:

- install a shared keyboard
  ```
  sudo km-package-install -s -p sil_el_ethiopian_latin
  ```
- install the same keyboard (not shared this time) for a different language
  ```
  km-config -i keyman://download/keyboard/sil_el_ethiopian_latin?bcp47=ssy-latn
  ```

Actual:
- dialog asking to uninstall the existing keyboard before installing it again
  image
- Press _Yes_ button
- Error shows: `ERROR:Keyboard directory for sil_el_ethiopian_latin does not exist. Aborting`

Expected:
- No dialog
- Keyboard gets installed

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #7722.

# User Testing

## Preparations

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)
- Reboot
- install a shared keyboard
  ```
  sudo km-package-install -s -p sil_el_ethiopian_latin
  ```

## Tests

**TEST_INSTALL**: Install the same keyboard for a different language

- open a terminal window and run
  ```
  km-config -i keyman://download/keyboard/sil_el_ethiopian_latin?bcp47=ssy-latn
  ```
- verify that the dialog "Keyboard is installed already. Do you want to uninstall then reinstall it?" doesn't show up
- verify that there is no error `ERROR:Keyboard directory for sil_el_ethiopian_latin does not exist. Aborting` output in the terminal window

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_INSTALL (OPEN):** Tested with the attached PR build in Ubuntu Bionic 18.04 Linux OS (VM)  and here is my observation: 1. Setup the environment as it mentioned in the Preparation Steps. 2. Run the command line as it mentioned in the Test Steps. 3. Able to see the sil_ethiopian installation dialog appears before the terminal window. It did not ask any warning message or any error message. 4. Able to install another Ethiopian keyboard without having any problem.

**Review by mcdurdin — COMMENTED** [review]
For clarification: because the keyboard was originally installed shared, but the subsequent install attempt is for current user?

The user may be trying to:

1. Install a new language for the keyboard, or
2. Install a new version of the keyboard

What should we do?

1. Tell the user that the keyboard is installed shared and abort?
2. Add a new command to add a language for a keyboard that is already installed, to disambiguate these actions?
3. Just add the language to the current user's settings for the already-installed keyboard?

**Review by mcdurdin — APPROVED** [review]
LGTM.

I appreciate the reasoning for this. :grin:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.107-beta](https://keyman.com/downloads/releases/beta/16.0.107)

**Pull request merged**
