### PR TITLE
[Web] Add regression test suite

### LINKED ISSUE #1652: [Web] Regression testing infrastructure
**Is your feature request related to a problem? Please describe.**
KeymanWeb needs to have more solid regression testing for keyboard layouts so we can refactor and update the compiler with more assurance.

**Describe the solution you'd like**
A set of regression tests based on the keymanapp/keyboards repo keyboards that can be run automatically, ideally on Node, but initially through a web driver.

**Describe alternatives you've considered**
Manual testing? Um...

**Product context**
 - OS: any (browser-based)

**Additional context**
I have some WIP code for generating test cases for keyboards (kmanalyze) -- will reference here once I create the PR. The infrastructure to run the tests needs completion. The existing Keyman Developer-based regression testing is insufficient as it is Windows-based. Anticipate being able to run tests based on both touch and hardware events in the future.

### PR DESCRIPTION
**Pull request by mcdurdin**
Replaces #1682 to remove dependency on if/else ladder fix.

Fixes #1652.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148333:id/kvk/index.html)

**Comment by mcdurdin** [comment]
Latest run went well. Showed some keyboard errors, but these don't need to be fixed in this PR. In fact, I want to fix them in a later PR to validate the process:

```
[11:10:55][Step 5/5] Starting result comparisons
[11:10:55][Step 5/5] c/clavbur9[1]: error in test: "̀" + [SHIFT K_3]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[6]: error in test: "̀" + [SHIFT K_3]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[11]: error in test: "̀" + [SHIFT K_4]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[16]: error in test: "̀" + [SHIFT K_4]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[20]: error in test: "̀" + [SHIFT K_5]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[25]: error in test: "̀" + [SHIFT K_5]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[29]: error in test: "̀" + [SHIFT K_7]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[34]: error in test: "̀" + [SHIFT K_7]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[38]: error in test: "̀" + [SHIFT K_9]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[43]: error in test: "̀" + [SHIFT K_9]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[48]: error in test: "̀" + [K_SLASH]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[53]: error in test: "̀" + [K_SLASH]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[62]: error in test: "̀" + [K_EQUAL]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[67]: error in test: "̀" + [K_EQUAL]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[77]: error in test: "̀" + [SHIFT K_2]: k.KCCM is not a function
[11:10:55][Step 5/5] c/clavbur9[82]: error in test: "̀" + [SHIFT K_2]: k.KCCM is not a function
[11:10:55][Step 5/5] fv/fv_gwichin[0]: error in test: "į" + [SHIFT 256]: no results found
[11:10:55][Step 5/5] fv/fv_han[0]: error in test: "Ë̌" + [SHIFT 269]: no results found
[11:10:55][Step 5/5] fv/fv_northern_tutchone[0]: error in test: "ä̀" + [SHIFT 269]: no results found
[11:10:55][Step 5/5] fv/fv_southern_tutchone[0]: error in test: "ä̀" + [SHIFT 269]: no results found
[11:10:55][Step 5/5] fv/fv_tagizi_dene[0]: error in test: "ṑ" + [SHIFT 270]: no results found
[11:10:56][Step 5/5] h/hieroglyphic[0]: error in test: "ḏḥwty" + [SHIFT K_SPACE]: no results found
[11:10:56][Step 5/5] Failed to load test results for n/nailangs: Unexpected end of JSON input
[11:10:56][Step 5/5] Failed to load test results for sil/sil_ipa: Unexpected end of JSON input
```

**Comment by jahorton** [comment]
Umm... `k.KCCM is not a function` is pretty accurate.  I'd have to load the keyboard to check, but did it somehow get compiled incorrectly?  `k.KFCM` exists, but `k.KCCM` has never been a thing.

**Comment by mcdurdin** [comment]
Yes, I am just reporting the issues right now, not trying to fix them. Also, I don't think those issues should be blocking the PR from merging, because they are separate issues. :)

**Comment by mcdurdin** [comment]
@jahorton The error is almost certainly coming from an attempt to load the khmer_angkor.js file. Are you sure you are testing on the correct branch (`web-regression-tests`)? Because I would expect that error on the old PR which was based on the if/else ladder bug fix, but not on this branch.

**Pull request merged**
