### PR TITLE
chore(oem/fv/ios): Remove build_keyboards.sh script

### PR DESCRIPTION
**Pull request by darcywong00**
In preparation for #2036, this removes build_keyboards.sh script since the FV apps should now be standardized in using the utility `downloadKeyboardPackage()` for downloading fv_all.kmp.

This updates the iOS configure step to
```
cp "$KEYBOARDS_CSV" "$KEYBOARDS_CSV_TARGET"
```
which may temporarily diverge when keyboards.csv gets streamlined in number of columns.

## User Testing
* **TEST_FV_IOS** - Verifies FirstVoices iOS app
1. Install the PR build of FirstVoices on an iOS device/emulator
2. Launch FV and use the setup step steps to install a  keyboard: BC Coast --> SENCOTEN
3. From the setup step, enable FV as the default system keyboard
4. Launch a browser and with FV as a system keyboard, verify you can type with it.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> downloadKeyboardPackage()

The spec for this app is that it includes the .kmp so it can be distributed offline. So I don't think we can do this.

**Comment by dinakaranr** [comment]
# Test Results

* **TEST_FV_IOS (Failed):**  I tested this issue with the "FirstVoices 18.0.35(0.11438.10973)" build from TestFlight App on the iOS mobile. Here is my observation.
1. Installed the "FirstVoices 18.0.35(0.11438.10973)" file.
2. Open the FirstVoices App.
3. Click the "Press here" button.
"FirstVoices Keyboards Crashed" message box appeared. Hence, I could not proceed to the "User Testing" steps. So, I failed this test. Thanks. 
Please refer to the screenshot

**Comment by darcywong00** [comment]
aha - I had a typo in my BASH script which prevented fv_all.kmp from downloading to the right place. Please retest @dinakaranr 

@keymanapp-test-bot retest

**Review by mcdurdin — APPROVED** [review]

**Comment by dinakaranr** [comment]
# Test Results

* **TEST_FV_IOS (PASSED):** I tested this issue with the "FirstVoices 18.0.35(0.11438.10998)" build from TestFlight App on the iOS mobile. Here is my observation.
1.    Installed the "FirstVoices 18.0.35(0.11438.10998)" file.
2.    Open the FirstVoices App.
3.    Click the "Press here" button.
4.    Installed the BC Coast --> SENCOTEN keyboard.
5.    Enable FV as the default system keyboard.
6.    Open the Chrome browser, and then enter some text in the address bar and Google search box.

Here, the FirstVoice keyboard appeared when trying to type a letter. I can enter letters from SENCOTEN's keyboard. It works well. Thank you.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.37-alpha](https://keyman.com/downloads/releases/alpha/18.0.37)

**Pull request merged**
