### PR TITLE
[Android] Add SIL logo as  app splash screen

### PR DESCRIPTION
**Pull request by darcywong00**
This addresses the Android platform for #1069

### CODE REVIEW

**Comment by darcywong00** [comment]
The splash screen looks like this

splash screen

**Comment by mcdurdin** [comment]
I don't think we want just an SIL logo in the splash screen. It needs to be both Keyman and SIL logos. "Keyman by SIL" type of thing.

**Comment by mcdurdin** [comment]
Thanks -- could you provide a screenshot of the update please?

**Comment by darcywong00** [comment]
atm, I can add multiple logos to the splash screen, but not text.
splash 2

Some of the splash screen recommendations say to use a contrasting background with the logo...

**Comment by mcdurdin** [comment]
Okay, I think the Keyman icon needs to be middle and large, and the SIL logo small at the bottom. The user is opening the Keyman app, not the SIL app :)

White background please!

**Comment by darcywong00** [comment]
Here's take 3.

I used the biggest Keyman logo I could find "Logo320x234.png", but
* a bigger one would be better (can you send me one?)
* diy means I lose the **Keyman** text

splash 3

**Comment by mcdurdin** [comment]
There are more images on the Team Drive (Keyman/Resources/Images/Keyman 9.0 Futago). Bu maybe we should discuss this in a standup before doing another round of graphics?

**Comment by darcywong00** [comment]
Closing this PR; the work will be done on 11.0 with the updated spec

**Pull request closed without merging**
