### PR TITLE
chore(common): update copyright year in various locations

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Review by jahorton — COMMENTED** [review]
No KMW copyright changes?

Screen Shot 2020-12-22 at 9 04 43 AM

Granted, a lot of KMW's copyrights are marked either 2019 or 2017-2019... looks like they'd missed the 2020 update.

This likely also affects the `common/models`, `common/predictive-text`, and `common/core/web` folders.

I do suppose those could be addressed separately, if desired.

**Comment by mcdurdin** [comment]
> No KMW copyright changes?

I was avoiding updating code files and trying to update only important metadata (e.g. README) and content that is end-user-visible in built products.

**Review by jahorton — APPROVED** [review]
Ah.  Then, in that case, LGTM.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.215-beta](https://keyman.com/downloads/releases/beta/14.0.215)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)

**Pull request merged**
