### PR TITLE
chore(common): Update km strings

### LINKED ISSUE #5531: bug(ios): Some UI still in English
While testing updated crowding strings for Azerbaijani, @makarasok noted the following UI is still in English
* "Get Started" is still in English. 
   image
Note, the crowding string exists for "Get Started" as a menu string

* "Spacebar Caption" is shown up as something else.
   image

* Other things under "Spacebar Caption" are also shown up something else.
   image

_These are also observed when choosing Khmer as the UI language._

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/5486#issuecomment-888952143_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #5531

This pulls in another round of Khmer strings, particularly for iOS and macOS.

## User Testing

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the locale to Khmer
3. Note any strings that are not Khmer

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Khmer
3. Note any strings that are not Khmer

### CODE REVIEW

**Review by ermshiperete — APPROVED** [review]

**Review by sgschantz — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
* **TEST_MACOS (PASSED):** Installed the attached PR build in Mac Mini OS (Monterey 12.3) and changed the UI into Khmer and no Khmer Strings appears in the desktop.

**Comment by MakaraSok** [comment]
- **TEST_MACOS: FAILED** not working after installing the build and switch locale to Khmer in the Language and Region of macOS 12.3.1.

image

**Comment by MakaraSok** [comment]
After the machine is restarted, the UI language has switches to the expected locale, km.

Only two spots which are seen to be in English.

(1) The scan QM code box:

image

(2) The copyright line in the About window:

image

**Pull request merged**
