### PR TITLE
[mac] Update version strings to 11.0.0

### PR DESCRIPTION
**Pull request by rfaramir**

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/138332:id/kvk/index.html)

**Comment by darcywong00** [comment]
Can you edit the PR and change `master` to `beta`?

**Comment by darcywong00** [comment]
Is it possible for the build process to incorporate the version from `/resources/VERSION.md`?

**Comment by mcdurdin** [comment]
@darcywong00 wrote:

> Is it possible for the build process to incorporate the version from `/resources/VERSION.md`?

I concur. As far as possible, we are trying to avoid hard-coding version strings. It may require a preprocessor step or perhaps xcodebuild can take a parameter to update plist entries?

**Comment by rfaramir** [comment]
I'd like to not lose this conversation, but my branch that corresponds to the reworked solution is in a different branch. Can I change the branch this PR refers to, or must I make a new PR for the new branch?

**Comment by mcdurdin** [comment]
You can cherry-pick the commits from the new branch into this one and then push.

**Comment by mcdurdin** [comment]
Replaced by #1583

**Pull request closed without merging**
