### PR TITLE
Use api.keyman.com instead of r.keymanweb.com on KeymanWeb

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Comment by mcdurdin** [comment]
The underlying issue should now be fixed (the api call succeeds now) so can go ahead and re-check.

**Comment by jahorton** [comment]
We still have one small problem with the API.  The returned `keyboard` entry in the main object is now an array of length 1, where that one element is the array of keyboards.  Somehow, we nested the keyboards array and that's breaking KMW's `register` function.

**Comment by mcdurdin** [comment]
It looks like it's returning the correct structure (although the schema documentation doesn't allow for arrays, which is a separate issue I am now addressing); it may be related to BCP 47 instead of ISO639-3 language codes?

**Comment by jahorton** [comment]
Right, my mistake.  There's definitely issues when it goes to match the input/specified language code (Example: 'heb') against the returned BCP-47 tag (here, 'he').

**Pull request merged**
