### PR TITLE
chore(linux): Fix bugs, add dependency and update documentation

### PR DESCRIPTION
**Pull request by ermshiperete**
- Fix crash if error is not set and we can't access the system service
- Check existence of `services` directory
- Update readme for ibus-keyman tests
- Make ibus-keyman depend on keyman-system-service (needed for integration tests)
- Fix meson version in keyman-system-service

@keymanapp-test-bot skip

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
> Fix bug and update documentation

Could you come up with a more descriptive title please? 😁

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.178-alpha](https://keyman.com/downloads/releases/alpha/17.0.178)

**Comment by mcdurdin** [comment]
Hmm, 'fix bugs' is still not clear! Would be better to state which bugs this PR is fixing

**Pull request merged**
