### PR TITLE
chore(ios): Set transparent background on "more" icons

### LINKED ISSUE #6414: bug(ios): the three dot menu icon has white background against the yellow background of the app itself
**Describe the bug**

**Expected behavior**

The icon's background should have been transparent, not white as it is now.

---

**Keyman for iPhone:**
 - Device: iPhone 11 simulator
 - OS: iOS 15.4
 - Keyman version 15.0.220-beta-test
 - Target application: Keyman

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #6414 
This sets the background of the 3-dot "more" icon transparent.

## User Testing
Setup to match configuration in the reported issue
Device: iPhone 11 simulator
OS: iOS 15.4
Install PR build of "Keyman for iPhone and iPad"

* **TEST_NORMAL** - Test the appearance in normal mode (not dark mode)
1. Start Keyman
2. Observe the icons in the menu bar
3. Verify the 3-dot "more" icon appears and the background matches the toolbar color

* **TEST_DARK_MODE** - Test the appearance in dark mode
1. Set the device to dark mode
2. Start Keyman
3. Observe the icons in the menu bar
4. Verify the 3-dot "more" icon appears and the background matches the toolbar color

### CODE REVIEW

**Comment by sgschantz** [comment]
When running in the simulator I'm still seeing the white background:
image

**Comment by darcywong00** [comment]
Aha, there were two copies of the file. Copied the png with the transparent background over.

**Comment by MakaraSok** [comment]
It looks transparent to me before and after tapping on it, while tapping and hold its background is white:

Tap and hold:
image

No tap and hold:
image

**Comment by darcywong00** [comment]
OK, I've set the more-selected.png images to have a transparent background.

**Review by rc-swag — APPROVED** [review]
lgtm

**Review by sgschantz — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_NORMAL (PASSED):** No issue found. It looks good.
Tap and hold
image

No tap, no hold
image

* **TEST_DARK_MODE (PASSED):** No issue found. It looks good.
Tap and hold
image


No tap, no hold
image

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.246-beta](https://keyman.com/downloads/releases/beta/15.0.246)

**Pull request merged**
