### PR TITLE
fix(android/engine): Skip final globe key action

### LINKED ISSUE #10452: bug(android): keyboard picker use triggers an extra keyboard swap
Discovered on the current `master` / 17.0.247:

Using the keyboard picker to swap keyboards, the keyboard will be swapped to the target keyboard _and then, immediately_ to the keyboard _after_ it:

double-swap

Simple taps on the globe key will only swap keyboard once, operating as expected.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #10452 
The Keyman for Android globe key handling has a bug in the scenario
| globe variable | value |
|-----------------------|----------|
globeKeyState | GLOBE_KEY_STATE_UP 
globeKeyDown | false

globeKeyState ultimate arbitrates between globe key long presses and short presses to determine the action.
This was triggering a spurious globeKeyAction to be processed.

This is fixed by ignoring that combo.

## User Testing
**Setup** - Install the PR build of Keyman for Android on an Android emulator/device

* **TEST_SHORT_PRESS** - Verifies globe key short press action
1. Launch Keyman for Android and dismiss the "Get Started" menu
2. Short-press and release the globe key
3. Verify the Keyman keyboard picker is displayed
4. Select the current keyboard to dismiss the keyboard picker
5. From Keyman settings, install a second keyboard (e.g. khmer_angkor) from keyman.com 
6. In the Keyman app, verify the installed keyboard is selected.
7. Short-press and release the globe key
8. Verify the in-app keyboard switches to the next keyboard
9. Short-press and release the globe key
10. Verify the in-app keyboard switches to the next keyboard

* **TEST_LONG_PRESS** - Verifies globe key long press action
1. Launch Keyman for Android and dismiss the "Get Started" menu
2. Long-press and release the globe key
3. Verify the Keyman keyboard picker is displayed
4. Select the current keyboard to dismiss the keyboard picker
5. From Keyman settings, install a second keyboard (e.g. khmer_angkor) from keyman.com 
6. In the Keyman app, verify the installed keyboard is selected.
7. Long-press and release the globe key
8. Verify the Keyman keyboard picker is displayed
9. From the keyboard picker, select a keyboard
10. Verify the selected keyboard is selected and displayed
11. Long-press and release the globe key
12. Verify the Keyman keyboard picker is displayed
13. From the keyboard picker, select another keyboard
14. Verify the selected keyboard is selected and displayed

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_SHORT_PRESS (FAILED):** Keyman app crashes after installing Keyman Alpha-test-10465. Seems to be an issue. 

   

* **TEST_LONG_PRESS (FAILED):** Keyman app crashes after installing Keyman Alpha-test-10465. Seems to be an issue.

**Comment by darcywong00** [comment]
@bharanidharanj - do you remember what version of Android you used in your test? I've merged master into this branch in case it was Android 14 (API 34).

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
> @bharanidharanj - do you remember what version of Android you used in your test? I've merged master into this branch in case it was Android 14 (API 34).
> 
> @keymanapp-test-bot retest

@darcywong00 Tested with the Android Mobile device (Samsung Galaxy A23 5g - Android 13) and I was getting the above mentioned crash.

**Comment by darcywong00** [comment]
I see your [crashes in Sentry](https://keyman.sentry.io/issues/4907080816/?environment=test&project=5983520&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) but I'm confused how it would be expecting khmer_angkor updates on a clean installation.

Did you uninstall and try retesting?

**Comment by bharanidharanj** [comment]
> I see your [crashes in Sentry](https://keyman.sentry.io/issues/4907080816/?environment=test&project=5983520&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) but I'm confused how it would be expecting khmer_angkor updates on a clean installation.
> 
> Did you uninstall and try retesting?

@darcywong00 Okay.

**Comment by bharanidharanj** [comment]
@darcywong00  Retested with the Android Mobile (Samsung Galaxy A23 5g - Android 13) device and here is my observation: 1. Getting the same crash while trying to open the keyman app. 2. Cleared the Cache files. 3. Uninstalled the app. 4. Reinstalled it. 5. Successfully opened the Keyman in-app.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_SHORT_PRESS (PASSED):** Retested with Keyman 17.0.250-alpha-test-10465 in the Android mobile device (ver 13) and here is my observation : 1. Opened the Keyman In-App. 2. Dismissed the "Get Started" menu. 3. Verified that the Keyman keyboard picker is displayed after short-pressing the globe key. 4. Selected the current keyboard to dismiss the keyboard picker. 5. Installed another keyboard eg., "khmer_angkor" from keyman.com. 6. Verified the installed keyboard is selected in the Keyman app. 7. Verified that the in-app keyboard switched to the next keyboard (ie., from khmer_angkor to sil_eurolatin) after short-pressing the globe key. Seems to be working as expected.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_LONG_PRESS (PASSED):** Retested with Keyman 17.0.250-alpha-test-10465 in the Android mobile device (ver 13) and here is my observation: 1. Opened the Keyman In-App. 2. Dismissed the "Get Started" menu. 3. Long-pressed then released the globe key. Verified that the Keyman picker menu was displayed. 4. Clicked the current keyboard to dismiss the keyboard picker. 5. Installed the second keyboard (eg., khmer_angkor) from keyman.com. 6. Verified that the installed keyboard was selected in the Keyman app. 7. Long pressed then released the globe key to open the Keyboard picker menu. 8. Verified that I was able to select any keyboard from the keyboard picker menu and the keyboard was selected and displayed in the keyman in-app. Seems to be working fine.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.250-alpha](https://keyman.com/downloads/releases/alpha/17.0.250)

**Pull request merged**
