### PR TITLE
fix(web): unbreak some ts paths

### PR DESCRIPTION
**Pull request by srl295**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
ideally there'd be an eslint to catch this?

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.233-alpha](https://keyman.com/downloads/releases/alpha/17.0.233)

**Comment by mcdurdin** [comment]
> ideally there'd be an eslint to catch this?

It feels like it should be caught at build time. It's kinda weird how it works in some build states but not others. Not sure how best to fix.

**Comment by mcdurdin** [comment]
https://github.com/microsoft/vscode/issues/137446#issuecomment-973563410 is relevant

**Pull request merged**
