### PR TITLE
chore(common): Merge beta to master for Sprint B17S6 (part 2)

### PR DESCRIPTION
**Pull request by darcywong00**
Follows #11291 in merging beta to master for end of Sprint B17S6

@keymanapp-test-bot skip

### CODE REVIEW

**Review by jahorton — COMMENTED** [review]
A couple more things got merged in this morning; would it be a bit late for those to slip in, too?

Granted, I guess we haven't enacted a code-freeze 🧊 🥶 yet, so I guess they could land in a follow-up.

**Comment by darcywong00** [comment]
yeah, we got time to throw those in too...

**Review by jahorton — APPROVED** [review]
History looks good; glad there weren't blank entries left by the automation this time.  Unless there were, in which case... glad you caught 'em.

LGTM.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.23-alpha](https://keyman.com/downloads/releases/alpha/18.0.23)

**Pull request merged**
