### PR TITLE
fix(mac): make Download Keyboard dialog content visible in macOS Monterey

### PR DESCRIPTION
**Pull request by sgschantz**
Instead of seeing a completely blank dialog when clicking the Download Keyboard... button, ensure that it always displays correctly.

Fixes: #12130 

This issue was caused by the URL being not being percent-encoded when the version (which is included in the the query string of the URL) contained spaces. The version had to be encoded so that each space was represented with '%20'.

Both Sonoma and Monterey loaded the content successfuly with a version that did not contain spaces:
`https://keyman.com/go/macos/14.0/download-keyboards/?version=18.0.86`

Only Sonoma loaded the content successfuly with a version that did contain unencoded spaces, and Monterey produced a blank page:
`https://keyman.com/go/macos/14.0/download-keyboards/?version=Keyman 18.0.86 for macOS`

This fix encodes the spaces and results in successfully loaded content for both Sonoma and Monterey:
`https://keyman.com/go/macos/14.0/download-keyboards/?version=Keyman%2018.0.86%20for%20macOS`

It is not clear why this issue was dependent on the version of macOS.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
That version string seems wrong? Should just be the dotted triplet

**Comment by sgschantz** [comment]
> That version string seems wrong? Should just be the dotted triplet

That's right, it's pulling CFBundleShortVersionString from the plist. So the root cause must be due to the version not being written correctly. At least this helps it to handle that better and not block keyboards from downloading. Are there other things that might break from the version not being in the correct format?

**Comment by jahorton** [comment]
We were able to determine that the erroneous version string we're seeing... is because that's what's in the base, _non-overwritten_ version of the projects' PLISTs.

_engine_
https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/KeymanEngine4Mac/KeymanEngine4Mac/Info.plist#L19-L20

_app_
https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/Keyman4MacIM/Keyman4MacIM/Info.plist#L38-L39

We have build.sh code that _should_ be overwriting this... and it does appear to be executing.  My best guess is that it's somehow operating on "the wrong" Plist, and the version that actually gets bundled into the installer is unaffected despite our intentions.

Start of the shell function used to update Plist files:

https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/build.sh#L147-L150

One such use: 

https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/build.sh#L169-L175

On the surface of things, that "looks" like a correct path, but perhaps it isn't actually the right one?

https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/build.sh#L177-L185

The same thing would need to apply here.

**Comment by mcdurdin** [comment]
> _engine_
> 
> https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/KeymanEngine4Mac/KeymanEngine4Mac/Info.plist#L19-L20
> 
> _app_
> 
> https://github.com/keymanapp/keyman/blob/37aeec6ddd3214845ad526ebbb9a46316dc91475/mac/Keyman4MacIM/Keyman4MacIM/Info.plist#L38-L39

Would a simpler fix just be to update these two to be:

```
 <key>CFBundleShortVersionString</key> 
 <string>$(PRODUCT_VERSION)</string> 
```

and avoid the rewriting altogether?

**Review by mcdurdin — CHANGES_REQUESTED** [review]
I think we should fix the underlying issue here, so marking this as request-changes

**Comment by sgschantz** [comment]
> I think we should fix the underlying issue here, so marking this as request-changes

I created a separate issue #12197 for this. Would it be good to take care of that as a separate fix?

**Comment by sgschantz** [comment]
Changed back to draft as PR #12233 addresses the root cause which is the invalid version string.

**Comment by sgschantz** [comment]
Closing, a more appropriate fix was provided with #12233

**Pull request closed without merging**
