### PR TITLE
chore(common): Add crowdin strings for Czech 🍒

### PR DESCRIPTION
**Pull request by darcywong00**
🍒 pick of #8070 from master to 16.0 beta

Using localized name `čeština` from https://github.com/unicode-org/cldr/blob/a88558301989b98d5bedb13e9123ec6d12f82416/common/main/cs.xml#L142

## User Testing
This adds the crowdin strings for Czech locale cs-CZ

## User Testing
Load the PR build for each platform and set the UI / Locale to "čeština" (Czech)

* **TEST_ANDROID** 
1. Load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display Language --> čeština (Czech)
3. Return to the Keyman app 
4. Verify the UI is in Czech (prompt, Settings strings, etc.).
czech android

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Czech
3. Return to the Keyman app
4. Verify the UI is in  Czech

* **TEST_LINUX**
1. Start Keyman configuration with: LANGUAGE=cs_CZ km-config
2. Verify Keyman UI is in Czech

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Czech
3. Verify the Keyman UI is in Czech

* **TEST_WINDOWS**
1. Load the PR build of Keyman for Windows
2. Set the UI to čeština (Czech)
3. Verify the Keyman UI is in Czech

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

**Comment by bharanidharanj** [comment]
* **TEST_WINDOWS (PASSED):** Tested with the attached PR build (keyman 16.0.135-beta-test-8095) in Windows 11 OS (VM) and I am able to use the Czech UI in the Keyman application. 

..Czech UI 1:

   

..Czech UI 2:

   

..Czech UI 3:

**Comment by bharanidharanj** [comment]
* **TEST_ANDROID (PASSED):** Tested with the attached PR build (keyman 16.0.135-beta-test-8095) in Android 11 / API 30 emulator and I am able to use the Czech UI without having any problem. 

..Czech UI1:

   


..Czech UI2:

   


..Czech UI3:

**Comment by bharanidharanj** [comment]
* **TEST_LINUX (PASSED):** Tested with the attached PR build (keyman 16.0.135-beta (package version 16.0.135-1~PR-8095+focal2)) in Ubuntu 20.04 Focal Linux OS (VM) and I am able to use the Czech UI without having any problem. 

..Czech UI1:

   

..Czech UI2:

**Comment by bharanidharanj** [comment]
* **TEST_IOS (FAILED):** Tested with the attached PR build (16.0.135-beta-test-8095) build in iPhone 12 Pro Max Simulator (iOS 15.0) and I am getting crash while trying to open the Keyman App. I have also attached the Crash text file (KeymanCrashiOS.txt)  for your reference. 

..Crash Keyman :


   

[KeymanCrashiOS.txt](https://github.com/keymanapp/keyman/files/10520013/KeymanCrashiOS.txt)

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_MACOS (PASSED):** Tested with the attached PR build in macMini Monterey 12.6 OS and I am able to change the Czech UI in Keyman App. 

..Czech UI1:

   

..Czech UI2:

   

..Czech UI3:

   

..Czech UI4:

**Comment by mcdurdin** [comment]
iOS failure is tracked in #8118.

**Comment by mcdurdin** [comment]
Re-running iOS build to get updated sil_euro_latin.kmp to address crash.

@keymanapp-test-bot retest TEST_IOS

**Comment by mcdurdin** [comment]
I manually triggered a new iOS test build which should pull in the fixed sil_euro_latin.kmp 2.0.3.

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_IOS (PASSED):**  "Done" is found to still be in English (1 and 2) and "Keyboard" is also seen in English under the menu for keyboard caption (3). PASSED for now as it doesn't prove to be a blocking issue that prevent users from accessing the app.

| (1) | (2) | (3) |
| --- | --- | --- |
| image | image | image |

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.136-beta](https://keyman.com/downloads/releases/beta/16.0.136)

**Pull request merged**
