### PR TITLE
docs(linux): Add reference help pages 🍒 

### PR DESCRIPTION
**Pull request by darcywong00**
Addresses the missing links to Keyman for Linux reference help for 14.0 in keymanapp/help.keyman.com#450

🍒 picks of a39bc95 and copies the 15.0 reference help files (instead of introducing 15.0 scripts to auto-generate reference help)

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by ermshiperete** [comment]
I'm not sure all command line parameters are the same, so we'd have to re-generate the .md files for stable-14.0. 

But the other question is why the Linux reference .php files got deleted when building 14.0.282 (see [commit](https://github.com/keymanapp/help.keyman.com/commit/7184e926049302d4d663cadf5589ef4c27325f95#diff-b191b3fb77b70d872b237b2aa3c1f8923f3a4839aaac00b5ee7674de6c00f588), [TC build](https://build.palaso.org/buildConfiguration/KeymanLinux_Master/291450?buildTab=log&focusLine=7147&linesState=7147)).

**Comment by mcdurdin** [comment]
> But the other question is why the Linux reference .php files got deleted when building 14.0.282 (see [commit](https://github.com/keymanapp/help.keyman.com/commit/7184e926049302d4d663cadf5589ef4c27325f95#diff-b191b3fb77b70d872b237b2aa3c1f8923f3a4839aaac00b5ee7674de6c00f588), [TC build](https://build.palaso.org/buildConfiguration/KeymanLinux_Master/291450?buildTab=log&focusLine=7147&linesState=7147)).

We no longer generate .php in 14.0, do we?

**Comment by ermshiperete** [comment]
> > But the other question is why the Linux reference .php files got deleted when building 14.0.282 (see [commit](https://github.com/keymanapp/help.keyman.com/commit/7184e926049302d4d663cadf5589ef4c27325f95#diff-b191b3fb77b70d872b237b2aa3c1f8923f3a4839aaac00b5ee7674de6c00f588), [TC build](https://build.palaso.org/buildConfiguration/KeymanLinux_Master/291450?buildTab=log&focusLine=7147&linesState=7147)).
> 
> We no longer generate .php in 14.0, do we?

no, but this didn't change between .281 and .282, did it? And the files only got removed with the .282 build.

**Comment by mcdurdin** [comment]
> no, but this didn't change between .281 and .282, did it? And the files only got removed with the .282 build.

Yes, due to #5751 -- dud files left lying around causing issues elsewhere :grin:

**Review by mcdurdin — APPROVED** [review]

**Comment by darcywong00** [comment]
Replaced by #5764

**Pull request closed without merging**
