### PR TITLE
feat(web): `&newLayer` and `&oldLayer`

### LINKED ISSUE #6112: bug(ios): in-app keyboard does not work correctly with start-of-sentence
Pulling this out of the pull request #5963 as it is a very limited scope issue, impacting only in-app keyboard, not system keyboard, on iOS.

I have reproduced this issue myself.

## Test start-of-sentence detection
- **IOS: FAILED** _Tested with iOS 15.0. mostly_
  * In-app
    - It should set the keyboard to the Shift layer at the start of a text field, after full stop (`.`), exclamation (`!`) or question mark (`?`) and one or spaces (e.g. `. `).

      > Not working! In iOS 15.0, there are two tabs audibly heard right after opening the Keyman app before the "Get Started" window appears. Click on "Done" to close the window to see the default layer of the keyboard instead of the shift layer. See the screenshot below.

      

      The shift layer appears only after tapping in the text area.

      

      Here is a screen recording for a better visual.
      
      https://user-images.githubusercontent.com/28331388/145767663-35ebaf40-76bf-4782-9067-092b6a45bb23.mov

      In iOS 13.7, still hear the two taps, but no "Get Started" page is shown. The keyboard layout does show the shift layer right off.

      
       
    - It should keep the keyboard in the numeric layer after typing a digit, but move back to base layer for all other symbols.

      > Not working! Pressing any key on the numeric layer moves the keyboard back to the default layer.
      
    - It should keep the keyboard in the shift layer after typing two capital letters (note that this is a temporary testing behaviour until we support a CAPS layer in an upcoming PR).

      > Not working! The keyboard doesn't stay on shift layer after typing two capital letters in a row.

      

    _Note that the default layer is shown when the Keyman app is opened from standby. It is expected to have shift layer shown instead._
    
    https://user-images.githubusercontent.com/28331388/145761077-d2fc57ed-2912-4244-8d8c-9825a70cad33.mov
      
    _After a line break (pressing Enter key), the shift layer should be shown, but it still stays in the default layer. Please consider adding this as a new functionality._

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/5963#issuecomment-992171268_

### LINKED ISSUE #6364: feat(web): tweak meaning of `&layerChanged` store to reflect name of new layer
This is a proposal to change the meaning of the `&layerChanged` system store so that instead of just being a boolean value, it returns the name of the new layer selected. Given the `&layerChanged` store is only available during the `postKeystroke` processing, this should have no impact on existing keyboards. The `&layerChanged` store is new in Keyman 15.0 and this change would need to be applied in the 15.0 beta cycle (as of writing we are at 15.0.211-beta).

The store could have three possible values, set in the following circumstances:
* If no layer change occurs with a given keystroke, then the store value would be an empty string.
* If the user touches a key which has a `next layer` property that is not `(none)`, then the value of `&layerChanged` would be the name of that next layer -- even if the next layer is _the same layer_. See discussion below.
* If any rule is matched that includes a `layer` statement in the output, the last `layer` statement fired in the rule processing for that keystroke would determine the value in `&layerChanged` -- even if the next layer is _the same layer_.

About the value of `&layerChanged` when the next layer is set to _the same layer_: this gives us the ability to easily say that a given key, e.g. on the shift layer, should not trigger a layer change, i.e. the opposite of the default action for that layer. It is still possible to do this, by matching on the output of that key and skipping the layer reset in the `postKeystroke` processing, but that is more indirect. This is also new behaviour -- the original implementation would have returned `0` in this case.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6364.
Fixes #6112. (I think).

Removes `&layerChanged` and adds `&newLayer` and `&oldLayer` system stores with the additional nuances around values as described in #6364.

# User Testing

## Setup 

Android/IOS: Run these tests with the obolo_chwerty_6351 keyboard available in the Test-14.0 (Keyman - Windows (Desktop/Developer)) artifacts.

Web: The obolo_chwerty_6351 keyboard for these tests is available under **English.../obolo_chwerty_6351** in the globe menu.

1. touch **English...** first:

   image

2. Then **obolo_chwerty_6351** should be available in the submenu that appears:

   image

## Base Configurations

These tests should be run on Android, iOS and Web.

**GROUP_ANDROID:** Run the Keyman app, either in Android emulator or real device. Version of Android is not important. Test the System keyboard and In-App keyboard.
**GROUP_IOS:** Run the Keyman app, either in iPhone simulator or real device. Version of iOS is not important. Test the System keyboard and In-App keyboard.
**GROUP_WEB:** Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator. The obolo_chwerty_6351 keyboard for this test is available under English.../obolo_chwerty_6351 in the globe menu.

## Tests

* **TEST_STARTS_WITH_SHIFT:** Make sure that the initial shift layer is working correctly.
 
  1. Verify that the initial layer when the keyboard is activated in an empty text area is Shift.
  2. Press an alphabet key on the shift layer to verify that the output is correctly shifted.
  3. Verify that the layer switches to the base layer.
  4. Press another alphabet key, verify that the output is lower case.
  
* **TEST_CAPS:** Verify behaviour of Caps Lock

  1. Double-tap on the Shift key to activate Caps Lock.
  2. Verify that the next alphabet key pressed generates capitalised output.
  3. Verify that the layer remains the Caps Lock layer.
  4. Press the <kbd>CH</kbd> key and verify that it is also capitalised.
  5. Press Shift again to return to the base layer.
  6. Verify that the next alphabet key pressed generates lower case output.

# SUITE_SOS_IOS

* **TEST_6112:** Please retest the scenario in #6112.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Review by ermshiperete — APPROVED** [review]
It's a shame that we have to re-define `TSS_NEWLAYER` and `TSS_OLDLAYER` over and over again...

**Comment by mcdurdin** [comment]
> It's a shame that we have to re-define `TSS_NEWLAYER` and `TSS_OLDLAYER` over and over again...

Definitely. I think in the future the list in Compiler.h should be able to instead use kmx_file.h, and the KMBinaryFileFormat.h header should disappear completely.

**Comment by bharanidharanj** [comment]
### GROUP_WEB: Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator.

* **TEST_STARTS_WITH_SHIFT (FAILED):** Tested this on Keyman Web Test Home page along with Mobile emulator (in Chrome desktop) and noticed that the Switching to Base layer is not happening.

 

* **TEST_CAPS (FAILED):** Double tap on the Shift Key is not activating the Caps Lock.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: Run the Keyman app, either in Android emulator or real device. Version of Android is not important. Test the System keyboard and In-App keyboard.

* **TEST_STARTS_WITH_SHIFT (FAILED):** Tested this on Android emulator (API 29 - Version 10.0) and the Switching is not working. 

 

* **TEST_CAPS (FAILED):** Tested this on Android emulator (API 29 - Version 10.0) and double clicking on the Shift Key is not activating to CapsLock.

**Comment by bharanidharanj** [comment]
### GROUP_IOS: Run the Keyman app, either in iPhone simulator or real device. Version of iOS is not important. Test the System keyboard and In-App keyboard.

* **TEST_STARTS_WITH_SHIFT (FAILED):** Tested this on iPhone 13 Pro Simulator and the Shift key is not working as expected. 

In-App - with Shift

 

In-App - Caps

System Keyboard - with Shift

System Keyboard - Caps

* **TEST_CAPS (FAILED):** notes

In-App - with Shift

**Comment by mcdurdin** [comment]
Thank you for running these tests @bharanidharanj. I am sorry that they didn't pass!

## GROUP_WEB

One note: I note that the GROUP_WEB test wasn't run with the mobile emulation mode. To run mobile emulation mode in Chrome:

1. Press F12

2. Click the mobile emulation button at the top of the Developer Tools window:

    image

4. Back in the page, select the appropriate device from the dropdown at top (e.g. iPhone 12):

    image

5. Reload the page to reset the environment for KeymanWeb to mobile device.

## GROUP_IOS and GROUP_ANDROID

However ... there is more to this! The keyboard attached in this build looks like it was not correct. I have made a couple of fixes, and the obolo_chwerty_6351.kmp package that will be available from the Test Keyboards link in the User Test Results should now be the correct one. Make sure you install that keyboard (uninstall old ones first) before testing.

@keymanapp-test-bot retest all

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.214-beta](https://keyman.com/downloads/releases/beta/15.0.214)

**Comment by bharanidharanj** [comment]
> Thank you for running these tests @bharanidharanj. I am sorry that they didn't pass!
> 
> ## GROUP_WEB
> One note: I note that the GROUP_WEB test wasn't run with the mobile emulation mode. To run mobile emulation mode in Chrome:
> 
> 1. Press F12
> 2. Click the mobile emulation button at the top of the Developer Tools window:
>    image
> 3. Back in the page, select the appropriate device from the dropdown at top (e.g. iPhone 12):
>    image
> 4. Reload the page to reset the environment for KeymanWeb to mobile device.
> 
> ## GROUP_IOS and GROUP_ANDROID
> However ... there is more to this! The keyboard attached in this build looks like it was not correct. I have made a couple of fixes, and the obolo_chwerty_6351.kmp package that will be available from the Test Keyboards link in the User Test Results should now be the correct one. Make sure you install that keyboard (uninstall old ones first) before testing.
> 
> @keymanapp-test-bot retest all

@mcdurdin Okay, Thanks Marc. I will re-test as per your suggestion.

**Comment by bharanidharanj** [comment]
### GROUP_WEB: Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator.

* **TEST_STARTS_WITH_SHIFT (FAILED):** Tested this on mobile emulator (in Chrome desktop) and it is failed since the Shift Key is not changing to the base layer after the output is correctly shifted to Caps.
 

* **TEST_CAPS (FAILED):** Double clicking on the Shift Key is not activating the Caps.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: Run the Keyman app, either in Android emulator or real device. Version of Android is not important. Test the System keyboard and In-App keyboard.

* **TEST_STARTS_WITH_SHIFT (PASSED):** Tested this on Android Emulator API 29 and it is working as expected.


* **TEST_CAPS (PASSED):** Tested this on Android Emulator API 29 and it working as expected.

**Comment by bharanidharanj** [comment]
### GROUP_IOS: Run the Keyman app, either in iPhone simulator or real device. Version of iOS is not important. Test the System keyboard and In-App keyboard.

* **TEST_STARTS_WITH_SHIFT (PASSED):** Tested this on iPhone 13 Pro simulator and it is working as expected in both System Keyboard and In-App keyboard. 
 



* **TEST_CAPS (FAILED):** Tested this on iPhone 13 Pro simulator and it is failed in (In-App keyboard) the 3rd Step (Verify that the layer remains the Caps Lock layer) as it mentioned in the Test Steps.

**Comment by mcdurdin** [comment]
> GROUP_WEB: Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator.

I have updated the test keyboard for KeymanWeb; please retest this one. The keyboard is now called obolo_chwerty_6351.

@keymanapp-test-bot retest GROUP_WEB

**Comment by mcdurdin** [comment]
> * **TEST_CAPS (FAILED)**: Tested this on iPhone 13 Pro simulator and it is failed in (In-App keyboard) the 3rd Step (Verify that the layer remains the Caps Lock layer) as it mentioned in the Test Steps.

Good catch! I have addressed this now in the latest update. What was happening was that the host app was resetting the edit context with each keystroke, returning us to a default state.

Given this change, I think we should re-run both the iOS tests. Thanks :grin:

@keymanapp-test-bot retest GROUP_IOS

**Comment by bharanidharanj** [comment]
> > * **TEST_CAPS (FAILED)**: Tested this on iPhone 13 Pro simulator and it is failed in (In-App keyboard) the 3rd Step (Verify that the layer remains the Caps Lock layer) as it mentioned in the Test Steps.
> 
> Good catch! I have addressed this now in the latest update. What was happening was that the host app was resetting the edit context with each keystroke, returning us to a default state.
> 
> Given this change, I think we should re-run both the iOS tests. Thanks 😁
> 
> @keymanapp-test-bot retest GROUP_IOS TEST_STARTS_WITH_SHIFT TEST_CAPS

@mcdurdin Okay, Thanks.

**Comment by bharanidharanj** [comment]
* **TEST_STARTS_WITH_SHIFT (PASSED):** Re-tested this on iPhone 13 Pro Simulator and it is working as expected.

In-App Keyboard


System Keyboard



* **TEST_CAPS (PASSED):** Re-tested this on iPhone 13 Pro Simulator and it is passed. I found a glitch at Step v (Press Shift again to return to the base layer.). Here, the Shift Key Color changes from light blue to dark blue after clicking the Shifty key. (In-App 1.png) However, clicking on any letter key would show the lower case letter on the Screen. (In-App2.png)

In-App 1


In-App2


System Keyboard

**Comment by bharanidharanj** [comment]
### GROUP_WEB: Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator.

* **TEST_STARTS_WITH_SHIFT (FAILED):** Tested this on mobile emulator in Chrome desktop and Shift key is not enabled (for the first time) when I was in the text area. 



* **TEST_CAPS (FAILED):** Tested this on mobile emulator in Chrome desktop and double clicking on the Shift key is not working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SOS_IOS: 

* **TEST_6112 (FAILED) :** Tested this on iOS 15.2 (iPhone 13 Pro Simulator) and the Shift Key is not activated after I clicking on the text area.  ie., it is still showing the default layer.

**Comment by mcdurdin** [comment]
> GROUP_WEB: Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator.
> TEST_STARTS_WITH_SHIFT (FAILED)

Sorry, my mistake. The instructions should have been clearer on this -- the keyboard to test is already available under English.../obolo_chwerty_6351 in the globe menu for KeymanWeb. I have updated the instructions!

@keymanapp-test-bot retest GROUP_WEB TEST_STARTS_WITH_SHIFT TEST_CAPS

**Comment by mcdurdin** [comment]
> ## SUITE_SOS_IOS:
> * **TEST_6112 (FAILED):** Tested this on iOS 15.2 (iPhone 13 Pro Simulator) and the Shift Key is not activated after I clicking on the text area.  ie., it is still showing the default layer.

Okay, I believe I've fixed this now -- I've retested locally and it appears to be correct.

@keymanapp-test-bot SUITE_SOS_IOS TEST_6112 retest

**Comment by mcdurdin** [comment]
> * **GROUP_IOS ... TEST_CAPS (FAILED):** Re-tested this on iPhone 13 Pro Simulator and it is passed. I found an issue at Step v (Press Shift again to return to the base layer.). Here, the Shift Key Color changes from light blue to dark blue after clicking the Shifty key. (In-App 1.png) However, clicking on any letter key would show the lower case letter on the Screen. (In-App2.png)

I haven't been able to reproduce this. The dark blue colour normally appears as the 'down' touch action and then is replaced with a lighter blue to indicate that Shift is selected (or grey to indicate that Shift is _not_ selected) once the user releases the touch. Can you try this again? If this continues to go wrong, we might list it as a separate issue to resolve.

@keymanapp-test-bot GROUP_IOS TEST_CAPS retest

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_IOS: Run the Keyman app, either in iPhone simulator or real device. Version of iOS is not important. Test the System keyboard and In-App keyboard.

* **TEST_STARTS_WITH_SHIFT (FAILED):** The keyboard doesn't show Shift layer when the keyboard is activated, i.e. switch from a different keyboard to bolo_chwerty; unless tapping in the text area where the cursor is blinking. See the screen recording below. 

https://user-images.githubusercontent.com/28331388/159405946-473b4c84-7727-4b18-a527-1860ee76ea37.mov


* **TEST_CAPS (PASSED):** works as indicated in the instructions.

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_WEB: Run testing/unminified, either in Chrome desktop, with mobile emulation, or mobile device/emulator. The obolo_chwerty_6351 keyboard for this test is available under English.../obolo_chwerty_6351 in the globe menu.

* **TEST_STARTS_WITH_SHIFT (BLOCKED):** The obolo_chwerty_6351 cannot be found per instructions.
* **TEST_CAPS (BLOCKED):** The obolo_chwerty_6351 cannot be found per instructions.

Link used: [id: 312043](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/312043:id/samples/unminified.html)

Chrome desktop with mobile emulation:
image

Mobile device:
image

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_SOS_IOS: 

* **TEST_6112 (FAILED):** In-app, the keyboard doesn't show right off with the Shift layer in-app (while system does), however the basic function of having a letter capitalized after a <kbd>.</kbd>, <kbd>!</kbd> or <kbd>?<>/kbd> and a space is working well. 

One main problem is that if adding more than two spaces after any of the three punctuations above, the keyboard shows the lower case layer instead.

In-app:

https://user-images.githubusercontent.com/28331388/159434972-5dd83948-8d99-40b0-8acf-162743bb5136.mov


System:

https://user-images.githubusercontent.com/28331388/159435156-9a76cee6-39d2-41dc-b763-309c52c00df4.mov

**Note:** A good to have feature - the keyboard should stay on Shift layer when pressing the `return` key after the ".!? + spaces". Currently, it switches to small caps in both in-app and system keyboard.

in-app (same for system):


https://user-images.githubusercontent.com/28331388/159436154-9538c1ba-c8d0-4705-b755-f829df3dadb0.mov

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_WEB: Run [testing/unminified](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/312043:id/testing/unminified.html), either in Chrome desktop, with mobile emulation, or mobile device/emulator. The obolo_chwerty_6351 keyboard for this test is available under English.../obolo_chwerty_6351 in the globe menu.

* **TEST_STARTS_WITH_SHIFT (PASSED):** The initial layer on an empty text field is indeed Shift.




* **TEST_CAPS (PASSED):** Double tap on the Shift key does enable Caps Lock. Tap on the Shift key again does disable the Caps Lock.

**Comment by mcdurdin** [comment]
I've revisited the context reset code and found a couple of inconsistencies. I think this addresses the starting shift state in iOS more cleanly. @MakaraSok can you retest with the new build?

@keymanapp-test-bot retest GROUP_IOS TEST_STARTS_WITH_SHIFT, SUITE_SOS_IOS TEST_6112

**Comment by mcdurdin** [comment]
@keymanapp-test-bot retest SUITE_SOS_IOS TEST_6112

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_IOS: Run the Keyman app, either in iPhone simulator or real device. Version of iOS is not important. Test the System keyboard and In-App keyboard.

* **TEST_STARTS_WITH_SHIFT (FAILED):** 
  
**in-app:** 👎 

The keyboard still doesn't show the Shift layer right off. Plus the predictive banner in particular is pushed up and cropped off. The keyboard itself seems to be pushed up leaving a huge empty gab at the bottom of the keyboard.



**system:** 👍 

The keyboard shows Shift layer right off after switching to the keyboard. The banner looks good, no cropped off like that of  the in-app.

image

Clicking in the text area doesn't enable the Shift layer either. Note also

https://user-images.githubusercontent.com/28331388/159616240-e171c65c-50cf-43b4-9e5b-c144e4a7e85c.mov

## SUITE_SOS_IOS: 

* **TEST_6112 (FAILED):** notes

**in-app:** 👎 

The keyboard doesn't switch to the Shift layer at the start of a text field; however, it does after full stop (.), exclamation (!) or question mark (?) and one or two spaces (e.g. . ). _Three spaces and a return key after one of the three punctuations doesn't keep the keyboard on the Shifter layer either, it actually is expected though to have the keyboard stay on the Shift layer._

**system:** 👍 
The keyboard does switch to the Shift layer at the start of a text field; however, it does after full stop (.), exclamation (!) or question mark (?) and one or two spaces (e.g. . ). _Three spaces and a return key after one of the three punctuations doesn't keep the keyboard on the Shifter layer either, it actually is expected though to have the keyboard stay on the Shift layer._

**Comment by mcdurdin** [comment]
I have isolated the primary remaining issue (which is minor) into #6416 as we want to get this in front of beta users. Merging.

**Pull request merged**
