### PR TITLE
chore: merge master into windows-upgrades 📲

### PR DESCRIPTION
**Pull request by keyman-server**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
Build failure:

```
14:02:35   File has wrong company name: "c:\buildagent\work\7ac43416c45637e9\keyman\windows\bin\engine\keyman32.dll","Signed","3:00 AM 10/13/2023","n/a","n/a","n/a","n/a","n/a"
14:02:35   File has wrong company name: "c:\buildagent\work\7ac43416c45637e9\keyman\windows\bin\engine\keyman64.dll","Signed","3:01 AM 10/13/2023","n/a","n/a","n/a","n/a","n/a"
```

https://build.palaso.org/buildConfiguration/KeymanDesktop_TestPullRequests/414481?buildTab=log&focusLine=7890&linesState=349&logView=flowAware

**Comment by MayuraVerma** [comment]
Just curious, Will this provide word suggestion for Windows?

**Comment by mcdurdin** [comment]
> Just curious, Will this provide word suggestion for Windows?

No, this is administrative. Predictive text for desktop platforms is on the roadmap but not for 17.0, 18.0, or even 19.0 at this stage.

**Comment by MayuraVerma** [comment]
Ok

**Review by mcdurdin — APPROVED** [review]
rslgtm

**Pull request merged**
