### PR TITLE
fix(common): publish @keymanapp/developer-utils as npm module

### LINKED ISSUE #10111: bug(developer): kmc 17.0.220-alpha crashes with error on start
with this Dockerfile

```dockerfile
FROM --platform=amd64 ubuntu:22.04
USER root
RUN apt-get -q -y update &&  \
  apt-get -q -y upgrade
RUN apt-get install -y -qq curl
# Install Node - yes, with a 60s delay
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash && \
  apt-get -q -y install nodejs
```

i get a failure

```
$ npm i -g @keymanapp/kmc@alpha
$ npm ls -g -a
(error messages)
$ kmc
(blows up)
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/usr/lib/node_modules/@keymanapp/kmc/node_modules/@keymanapp/keyman-version/' imported from /usr/lib/node_modules/@keymanapp/kmc/build/src/kmc.js
    at new NodeError (node:internal/errors:405:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:233:9)
    at packageResolve (node:internal/modules/esm/resolve:874:14)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.17.1
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10111.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
looks ok, does developer-utils have docs around it that it's more of an implementation detail?

**Comment by mcdurdin** [comment]
> developer-utils have docs around it that it's more of an implementation detail?

Added a basic README.md.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.222-alpha](https://keyman.com/downloads/releases/alpha/17.0.222)

**Comment by srl295** [comment]
Didn't get to test but lgtm. 

Want a CI test for it?

**Comment by mcdurdin** [comment]
> Want a CI test for it?

That's a bit of infrastructure work I think? How would you foresee that working?

**Comment by srl295** [comment]
> > Want a CI test for it?
> 
> That's a bit of infrastructure work I think? How would you foresee that working?

I'd think the Dockerfile as a GitHub action in https://github.com/keymanapp/keyman/issues/10111#issue-2019695874 could be run whenever a new release https://github.com/keymanapp/keyman/tags is created, and simply attempt an npm install and run against that tag.

**Comment by mcdurdin** [comment]
OK, we don't have Docker on most of our build agents at present, so there's a chunk of work to set this up -- don't want to dive into adding extra infrastructure without consideration. Not that this isn't a good idea, but... even adding the GHA for Linux has been multiple weeks of effort to get it stable.

Do you want to open it as a separate issue?

**Comment by srl295** [comment]
i'll prototype on my own GHA

**Pull request merged**
