### PR TITLE
refactor(web): transcription cache needed for multitaps, no longer prediction-only 🐵

### PR DESCRIPTION
**Pull request by jahorton**
Prep work needed for #9740.  Fortunately, it's pretty simple to spin off like this as a separate PR.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by jahorton** [comment]
Looks like I may need to update a few unit tests.

**Review by mcdurdin — APPROVED** [review]

**Comment by jahorton** [comment]
Build failure:  BrowserStack's macOS Monterrey - Safari agent didn't connect.  So, external flakiness.

**Comment by mcdurdin** [comment]
> Build failure: BrowserStack's macOS Monterrey - Safari agent didn't connect. So, external flakiness.

Is it possible for us to detect this specific flakiness and retry automatically a couple of times, given usually it works on a rebuild?

Noting also that Language Modeling Layer has failed twice now.

**Comment by jahorton** [comment]
> > Build failure: BrowserStack's macOS Monterrey - Safari agent didn't connect. So, external flakiness.
> 
> Is it possible for us to detect this specific flakiness and retry automatically a couple of times, given usually it works on a rebuild?

While detecting it directly isn't particularly possible...

```
07:24:15 
    24 10 2023 20:24:15.125:WARN [launcher.browserstack]: safari 15.3 (OS X Monterey) has not captured in 120000 ms, killing.

07:24:15 
    24 10 2023 20:24:15.126:DEBUG [launcher.browserstack]: Killing safari 15.3 (OS X Monterey) (worker 121721204).

07:24:17 
    24 10 2023 20:24:16.619:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) (worker 121721204) successfully killed.

07:24:17 
    24 10 2023 20:24:16.619:DEBUG [launcher]: FINISHED -> FINISHED

07:24:18 
    24 10 2023 20:24:17.566:INFO [launcher.browserstack]: safari 15.3 (OS X Monterey) session at https://automate.browserstack.com/builds/1218da60e34f269fba6924ec1fc5aa07c8764834/sessions/62d2a17dddfbfa5658d130da85864a79ad8ce5d3

07:24:18 
    24 10 2023 20:24:17.567:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) job with id 121721229 in queue.

07:24:24 
    24 10 2023 20:24:23.380:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) job started with id 121721229

07:26:24 
    24 10 2023 20:26:23.392:WARN [launcher.browserstack]: safari 15.3 (OS X Monterey) has not captured in 120000 ms, killing.

07:26:24 
    24 10 2023 20:26:23.393:DEBUG [launcher.browserstack]: Killing safari 15.3 (OS X Monterey) (worker 121721229).

07:26:25 
    24 10 2023 20:26:24.823:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) (worker 121721229) successfully killed.

07:26:25 
    24 10 2023 20:26:24.823:DEBUG [launcher]: FINISHED -> FINISHED

07:26:26 
    24 10 2023 20:26:26.105:INFO [launcher.browserstack]: safari 15.3 (OS X Monterey) session at https://automate.browserstack.com/builds/1218da60e34f269fba6924ec1fc5aa07c8764834/sessions/ef5a226bf3036f04808a75d94e42201d02ab8389

07:26:26 
    24 10 2023 20:26:26.105:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) job with id 121721244 in queue.

07:26:33 
    24 10 2023 20:26:33.099:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) job started with id 121721244

07:28:33 
    24 10 2023 20:28:33.105:WARN [launcher.browserstack]: safari 15.3 (OS X Monterey) has not captured in 120000 ms, killing.

07:28:33 
    24 10 2023 20:28:33.106:DEBUG [launcher.browserstack]: Killing safari 15.3 (OS X Monterey) (worker 121721244).

07:28:35 
    24 10 2023 20:28:34.566:DEBUG [launcher.browserstack]: safari 15.3 (OS X Monterey) (worker 121721244) successfully killed.
```

We already _are_ retrying a couple of times.  That count, at least, is configurable - we could increase it.  But... there are some times where that specific "worker", on their end, seems to be down entirely.

**Pull request merged**
