### PR TITLE
fix(developer): search-term quote replacement was not global

### PR DESCRIPTION
**Pull request by jahorton**
Noted this one while working on https://github.com/keymanapp/lexical-models/pull/244.

Should a single word contain multiple directional quotes and/or apostrophes, all should be corrected - not just the first.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
This requires a rebuild of affected models, right? Which would then mean a version bump for them?

LGTM

**Comment by jahorton** [comment]
> This requires a rebuild of affected models, right? Which would then mean a version bump for them?
> 
> LGTM

To take effect, yes.  This mostly covers a niche scenario, so it's not exactly a high priority item... but at the same time, should the addressed issue be signficant for someone... it'd be easy to forget that this fix was "just waiting" if we took a particularly "lazy" approach to updating them.

**Comment by mcdurdin** [comment]
OK. I don't want to bump the versions of all the models so we'll take the lazy approach.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.283-beta](https://keyman.com/downloads/releases/beta/17.0.283)

**Pull request merged**
