### PR TITLE
fix(windows): invalid character in text content opening help

### LINKED ISSUE #4205: bug(windows): invalid character in text content
**Describe the bug**

This happens when trying to open help page of the keyboard from the icon on the Windows taskbar.

image

**To Reproduce**

1. Go to 'Configuration' and install 'el_dinka' keyboard
2. Click on Keyman icon on the Windows taskbar
3. Click on 'Help...'

**Expected behavior**

A link to the help page (see below) should be shown.
image

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.215-beta
 - Target Application: self

**Additional context**

https://github.com/keymanapp/keyman/issues/4057

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4205.

Avoids encoding UTF-8 in the URL which has patchy support in some of our libraries.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.229-beta](https://keyman.com/downloads/releases/beta/14.0.229)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.230-beta](https://keyman.com/downloads/releases/beta/14.0.230)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
