### PR TITLE
feat(android): Use build-download-resources.sh for KMApro and FV apps

### PR DESCRIPTION
**Pull request by darcywong00**
Follow-on to #3300

* Update the FV Android app to use the same build script to download its default keyboard package. (`fv_all.kmp`)
    * This means downloading `fv_all.kmp` is the only valid option for the build (remove option to copy/rebuild keyboards)
* Reduce the number of exports in the Bash scripts
* Also removes `sil_euro_latin.kmp` since the app will fallback to `fv_all/sil_euro_latin` (in a future PR)

### CODE REVIEW

**Comment by darcywong00** [comment]
> We're going to need to add the nrc.str.sencoten model as well I think?

Along with nrc.str.sencoten?

**Comment by mcdurdin** [comment]
> Along with nrc.str.sencoten?

Confused by this question 😕

**Comment by darcywong00** [comment]
Should the the FV app also include the nrc.str.sencoten model to use with the fv_sencoten keyboard?

**Comment by mcdurdin** [comment]
Yes, that's why I wrote:

> We're going to need to add the nrc.str.sencoten model as well I think?

:-)

**Comment by darcywong00** [comment]
/facepalm  

Since this PR involved sil_euro_latin, I saw `nrc...` and the autocomplete in my brain 🧠  assumed you wanted to add the nrc.en.mtnt model.

**Comment by mcdurdin** [comment]
> ... add the nrc.en.mtnt model.

Of course, that's a very good idea.

**Pull request merged**
