### PR TITLE
fix(common): create GitHub comments serially

### PR DESCRIPTION
**Pull request by mcdurdin**
This is a suggested approach for addressing the rate limit issues we were experiencing. We'll try it and see.

Have I got the `promise` mechanism correct here? It looks right to me but hard to test...

### CODE REVIEW

**Review by jahorton — APPROVED** [review]
LGTM.

To be safe, I jerry-rigged a local test for this, adding the following code (temporarily) to web's unminified.html test page:

```
<script>
  let result = Promise.resolve();
  let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  arr.forEach(num => {
    result = result.then(() => (console.log("#" + num + " start")))
                   .then(() => new Promise(resolve => setTimeout(resolve, 10000)))
                   .then(() => (console.log("#" + num + " complete")));
  })
</script>
```

Results were as expected:

Screen Shot 2021-02-11 at 11 57 31 AM

There's a nice, 10-second delay after each 'start' statement.  (I captured this screenshot before the final timeout completed.)

**Comment by mcdurdin** [comment]
> To be safe, I jerry-rigged a local test for this, adding the following code (temporarily) to web's unminified.html test page:

That's almost exactly what I did (although I pasted pretty much the same thing into the dev console instead!) 🤣

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.242-beta](https://keyman.com/downloads/releases/beta/14.0.242)

**Pull request merged**
