### PR TITLE
fix(mac): limit short bundle version string to x.y.z format in info.plist

### PR DESCRIPTION
**Pull request by sgschantz**
In the info.plist for both the Keyman Engine and Input Method, remove the framing text so that CFBundleShortVersionString just contains the version string, x.y.z where x, y and z are numeric values.

Fixes: #12197
Fixes: #12130

For background, see discussion in PR #12156 which was addressing the side effect rather than the root cause.

# User Testing

## TEST_DOWNLOAD_KEYBOARD_VISIBLE_MONTEREY

1. With a mac running macOS Monterey, select the Configuration... command from the Keyman menu
2. In the Keyboards pane, click the Download Keyboard... button
3. Confirm that the Download Keyboard dialog should appear as shown:
image

## TEST_DOWNLOAD_KEYBOARD_VISIBLE_OTHER_OS

1. With a mac running a macOS version other than Monterey, select the Configuration... command from the Keyman menu
2. In the Keyboards pane, click the Download Keyboard... button
3. Confirm that the Download Keyboard dialog appears as shown above.

## TEST_DOWNLOAD_AND_INSTALL_KEYBOARD

1. Download and install a new keyboard after invoking the Configuration... command 
2. Confirm that the downloaded keyboard is installed successfully and can be used

### CODE REVIEW

**Comment by dinakaranr** [comment]
# Test Results

I tested this issue with the attached "Keyman 18.0.94-alpha-test" build on the MacOS  
Here is my observation.

* **TEST_DOWNLOAD_KEYBOARD_VISIBLE_MONTEREY (passed):**
1. Installed the MacOS Monterey version 12.0.1.
2. Installed the "Keyman-18.0.94.dmg" file. 
3. Open the "Keyman Configuration" dialog by clicking the keyman icon.
4. "Keyman: Download Keyboard" dialog by clicking the "Download Keyboard" button.
Verified that the "Download keyboard" dialog appeared.

* **TEST_DOWNLOAD_KEYBOARD_VISIBLE_OTHER_OS (passed):**
1. Installed the "Keyman-18.0.94.dmg" file in the macOS sonoma 14 version.
2. Open the "Keyman Configuration" dialog by clicking the keyman icon.
3. "Keyman: Download Keyboard" dialog by clicking the "Download Keyboard" button.
Verified that the "Download keyboard" dialog appeared.

* **TEST_DOWNLOAD_AND_INSTALL_KEYBOARD (passed):**
1. Open the "Keyman Configuration" dialog by clicking the keyman icon.
2. "Keyman: Download Keyboard" dialog by clicking the "Download Keyboard" button.
3. Downloaded and installed three languages(EuroLatin, Khmer Angkor, and Amharic) keyboard. 
4. Open the sticky notes and then type some text using the installed keyboards.
It works great for me. Thank you.

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
This needs a cherry-pick to stable-17.0, I think.

**Comment by sgschantz** [comment]
> This needs a cherry-pick to stable-17.0, I think.

The version string looks good in stable-17.0, so I think we're good to make this change for 18 only.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.98-alpha](https://keyman.com/downloads/releases/alpha/18.0.98)

**Pull request merged**
