### PR TITLE
feat(windows): Don't install desktop shortcut for Keyman for windows on installation

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes: #7862

### CODE REVIEW

**Comment by rc-swag** [comment]
# User Testing

## TEST_NO_KEYMAN_DESKTOP_ICON

This test ensures the Keyman desktop icon is not installed when installing Keyman.
1. Make sure Keyman is not installed
2. Install the Keyman for Windows linked in this PR.
Expected result
3. Observe that there is no Keyman Shortcut on the desktop.
4. As an extra check, ensure there is no Keyman shortcut in the Desktop folder using Windows Explorer.

**Comment by rc-swag** [comment]
@mcdurdin   I did have a look into offering a check box to enable installing the Desktop shortcut. It seemed due to the way Keyman Installation is done this would be in the "setup.exe" project and not with just WiX tool set. An Install option would be added and a parameter used in `TRunTools.ConfigFirstRun`  this would then I guess create the shortcut.
Before I went down that path I wanted to give that option, or just don't install it at all. Thoughts?

**Comment by mcdurdin** [comment]
I don't think we need a setup option for the desktop shortcut for Keyman in this day and age -- that's a stack of extra engineering for minimal benefit, and comes at the cost of more options in the Setup dialog.

I think we'd want the default setting to be "don't create desktop shortcut", but the only people who would need the option would be those who would never look in the Setup Options dialog anyway, so that would make it pointless.

But we should make sure we update documentation (if there is anything that refers to the desktop shortcut) to point people to the Start Menu to search for Keyman to start it.

**Comment by dinakaranr** [comment]
# Test Results
* **TEST_NO_KEYMAN_DESKTOP_ICON (PASSED):** I tested this issue with the attached "Keyman 18.0.32-alpha-test-11401" build on an Window 10 & 11 OS environment: Here is my observation.
1. Uninstalled the previous Keyman application(Removed keyboards from system, cleared temp folder and rebooted)
2. Installed the "Keyman 18.0.32.apk" file and gave all permissions to the application.
3. Click the "Start Keyman" button on the startup window.
4. Keyman icon added in the tray.
There is no Keyman's shortcut appearing on the desktop. There is no Keyman icon available in the desktop folder.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.34-alpha](https://keyman.com/downloads/releases/alpha/18.0.34)

**Pull request merged**
