### PR TITLE
change(web): adjusts minimum distance needed for quick-display of subkeys

### LINKED ISSUE #6646: bug(web): character on the subkey got output when fast typing
**Describe the bug**

When typing very quickly on iPad, the character on the neighboring keys get output. Try and type the word "you" very quickly and you'll somehow get something totally not what you expect. Please see the screen recording below.

https://user-images.githubusercontent.com/28331388/169770520-aee5f11c-71b2-4684-ad0c-64c38f9e0eff.mov

**Expected behavior**

This issue seems to occur only in iOS. I was not able to repro it on Android running Keyman 15.0.250-beta.

---

**Keyman for iPad:**
 - Device: iPad mini 6
 - OS: iOS 15.5
 - Keyman version: 15.0.249-beta-test-6633 (TestFlight: 0.6633.6275)
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.6
 - Language name: English

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6646.

## User Testing

GROUP_IN_APP:  Test using the main Keyman app on a physical iPhone or iPad.
GROUP_IN_MOBILE_BROWSER:  Using a physical iPhone or iPad, use Safari and navigate to the "Prediction - robust testing" manual test page through the "KeymanWeb Test Home" link below.

For both, select the "EuroLatin" keyboard.  (It has lots of subkeys.)  In app, this is the default keyboard.

TEST_QUICK_YOU_TYPING:  Rapidly type `you ` at least 10 times in a row.  Fail if a subkey is emitted more than once for every ten tries.
- Do try to be a bit precise, but the focus _is_ on rapidly typing.

TEST_LONGPRESS_FLICK: 

1. Press and hold the `i` key and _quickly_ move your finger in an upward motion.  Select a subkey.
2. Press and hold the `i` key, keeping your finger still.
    - The subkey menu should display earlier for step 1 than for step 2.

### CODE REVIEW

**Comment by jahorton** [comment]
@MakaraSok Could you check whether or not this potential fix helps with the issue?  Thanks.

**Comment by jahorton** [comment]
Preliminary testing shows that this change appears to cut down on the number of misinputs, even if it doesn't eliminate them fully.

Worth note:  in 14.0, the subkey quick-display shortcut was broken; longpresses would only result from waiting out the longpress timer.  This was fixed during 15.0.

I believe what is happening is the result of a lack of precision with the input; an upward-sliding finger can easily trigger the quick-display shortcut, with the top row's subkeys displaying directly under the touch-point due to their number.  We can obviously "fix" this by re-disabling the quick-display shortcut... but that's likely less than ideal.  Note that there are a few other, non-subkey-based typos in the original issue's video - I believe any remaining instances of this are likely due to a relative lack of precision while rapid-typing.

**Comment by MakaraSok** [comment]
I've tried the iOS build on the iPod touch 7th gen. Generally speaking its quite challenging to be not sloppy while fast-typing. A smaller form factor enables better control and be more precise on key presses than on bigger one like iPad. However the issue arises every once in a while outputting something totally unexpected (from the subkeys).

https://user-images.githubusercontent.com/28331388/172307174-17178027-5895-47c2-be5e-d31bd6331555.mp4

**Comment by MakaraSok** [comment]
I would suggest that someone test this on a real device to avoid subjective sloppiness while typing. 💯

**Review by ermshiperete — APPROVED** [review]

**Comment by mcdurdin** [comment]
> I've tried the iOS build on the iPod touch 7th gen.

Simulator or real device?

I do wonder about the threshold that you've selected @jahorton -- is it sufficient to avoid accidental flicks? We should probably test on a variety of devices. One thing I wonder is if the level of movement is really relative to the size of the key, or if we should be using a fixed physical distance?

**Comment by jahorton** [comment]
> One thing I wonder is if the level of movement is really relative to the size of the key, or if we should be using a fixed physical distance?

Decent question.  That said, do note that all adjustments here are _more restrictive_ than before.  It's not much work to alter the threshold again.

I also did look into `devicePixelRatio` stuff, but that's auto-handled on iOS devices;  it's already accounted for.

**Comment by MakaraSok** [comment]
# Test Results

All tests done on iPod 7th gen.

### GROUP_IN_APP: Test using the main Keyman app on a physical iPhone or iPad.

* **TEST_QUICK_YOU_TYPING (PASSED):** It's harder to get it to misbehave now. See the clip below:

https://user-images.githubusercontent.com/28331388/172807524-0d87d059-8b44-4d6e-9620-588eea2dc326.mp4


* **TEST_LONGPRESS_FLICK (PASSED):** Flicking does show the sub keys quicker than longpressing.

### GROUP_IN_MOBILE_BROWSER: Using a physical iPhone or iPad, use Safari and navigate to the "Prediction - robust testing" manual test page through the "KeymanWeb Test Home" link below.

* **TEST_QUICK_YOU_TYPING (PASSED):** No strange character gets output when trying to fast type.
* **TEST_LONGPRESS_FLICK (PASSED):** Flicking does show the sub keys quicker than longpressing.

**Comment by jahorton** [comment]
Wait... so it's easier to get it to misbehave in the app than it is outside of the app?  Did I infer that correctly?

**Comment by jahorton** [comment]
> Wait... so it's easier to get it to misbehave in the app than it is outside of the app? Did I infer that correctly?

From a separate channel:

> Yes, it failed once in-app, and not at all on web.
>
> By failed, I meant some unexpected character got output instead.

With it being _just once_ vs never, I'm not too concerned about the difference.  I was worried that the difference would be more pronounced.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.259-beta](https://keyman.com/downloads/releases/beta/15.0.259)

**Pull request merged**
