### PR TITLE
[Web, Android, iOS] Null suggestion banner bug

### PR DESCRIPTION
**Pull request by jahorton**
Fixes the following issue:

- Selecting a 'blank' suggestion element was erroneously triggering predictive state management.
  - Most significantly, this tended to temporarily break the BKSP key.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/151153:id/kvk/index.html)

**Comment by darcywong00** [comment]
I'm also seeing weird interaction with `<keep>` and backspace:
Using default EuroLatin (SIL) keyboard

1. From a blank context, click `<keep>` which inserts a space
2. Click "backspace" which inserts another space

**Comment by darcywong00** [comment]
Clicking on a blank suggestion also seems to kill the spacebar. 
If I type a letter, the spacebar starts to work again.

**Comment by jahorton** [comment]
> Clicking on a blank suggestion also seems to kill the spacebar.
> If I type a letter, the spacebar starts to work again.

That's literally the bug this PR addresses.  Are you seeing that on this PR's branch as well, meaning it's not adequately fixed?

**Comment by jahorton** [comment]
> Clicking on a blank suggestion also seems to kill the spacebar.
> If I type a letter, the spacebar starts to work again.

Huh.  Does that also happen on this PR's branch?  I hadn't heard about the spacebar issue 'til now, but I'd expect it to be fixed by this, too.

**Comment by darcywong00** [comment]
Right, I'm on this PR's branch.
"Backspace" and "enter" work after clicking a blank suggestion.
Spacebar doesn't work.

> If I type a letter, the spacebar starts to work again.

To clarify, I have to do stuff to change the context ( `<keep>`, "enter', or type enough letters to prompt new suggestions). After that, the spacebar works

**Comment by jahorton** [comment]
OK, the spacebar thing should be handled properly now.  I do see some funkiness with `<keep>` after entering a space on iOS, but not the same way as you described earlier.  (Both are probably their own bugs, so I won't push for 'em in this PR.)

> I'm also seeing weird interaction in the Android app with `<keep>` and backspace:
> Using default EuroLatin (SIL) keyboard
> 
>     1. From a blank context, click `<keep>` which inserts a space
> 
>     2. Click "backspace" which inserts another space

I should probably mention that between this and other similar issues I've recently handled for iOS, there were issues with the app's recognized text field desynchronizing from what the embedded KMW had available for its local context.  There's a chance that such a desync might cause the behavior you describe.

**Comment by rfaramir** [comment]
This works now, for me, too.

**Pull request merged**
