### PR TITLE
feat(developer): LDML Keyboard Test Window 🌱

### LINKED ISSUE #10420: feat(developer): need a way to test an LDML keyboard internally
While we don't need step-by-step debugging at this stage, it would be good to at least be able to load an LDML keyboard and test it in Developer.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10420.

Implements a basic LDML keyboard test window. Press F5 or Keyboard/Test to start test. Shows a character grid for each character in the text.

Does not yet support display of markers (#10458). Does not support interactive debugging, nor any more detailed status information.

# User Testing

* **TEST_DEBUGGER**: Create a new LDML Keyboard Project. Open the keyboard and press F5 to start testing. Verify that pressing <kbd>a</kbd> generates `Hello World!` and that basic text editing functions work as expected. Press Shift+F5 or the stop button in the debug toolbar to stop testing.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (FAILED):** Tested with the attached PR build (Keyman Developer 17.0.247-alpha-test-10459) on Windows 11 OS (VM) and here is my observation: 1. Created an LDML project. 2. Created a keyboard. 3. Compiled it. 4. Pressed F5 to start the Debugger. In the Debugger mode, pressed 'a' key and I noticed that there was no output "Hello World!" appearing on the pane.

**Comment by mcdurdin** [comment]
Hi @bharanidharanj, that's a Keyman keyboard project, not an LDML keyboard project. To create an LDML keyboard project, you need to select Project / New Project / LDML Keyboard. Can you retest please? Thanks!

@keymanapp-test-bot retest all

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (FAILED):** 1. Created an LDML keyboard project by Clicking Project / New Project / LDML keyboard options. 2. Opened the Keyboard window. 3. Pressing F5 to open the Debugger window. 4. Noticed that pressing the letter 'a' did not output the "Hello World!" text. Seems to be an issue. Or did I miss out on any steps?

**Comment by bharanidharanj** [comment]
@mcdurdin I noticed that there was an error message that appeared in 'Node' widow which is running behind the Keyman Developer application.

**Comment by mcdurdin** [comment]
@bharanidharanj (I think the node error is unrelated)

Can you follow the steps in the video to run your test keyboard (note, once you have selected Test Keyboard, then you'll need to press <kbd>a</kbd> as per the instructions above; my example does not have that final step)

@keymanapp-test-bot skip

https://github.com/keymanapp/keyman/assets/4498365/8fb8c10f-6a8f-4355-ac27-c6545baff47d

**Comment by srl295** [comment]
> @mcdurdin Followed the steps as mentioned in the video and I got an error message after clicking the 'Test Keyboard' option.
> 
> 

sounds like some kind of install issue.  I'll dig into it a bit more.

I also noticed a minor typo in the error message you got, filed #10484 to fix.

**Comment by mcdurdin** [comment]
> sounds like some kind of install issue. I'll dig into it a bit more.

The issue is the techpreview files are not included in the Keyman Developer msi. I am looking at how best to solve.

**Comment by srl295** [comment]
@mcdurdin should there be some kind of sanity checking at start-up? to make sure the schemas and data all arrived ok?

**Comment by mcdurdin** [comment]
> @mcdurdin should there be some kind of sanity checking at start-up? to make sure the schemas and data all arrived ok?

Doesn't really help us. It would still fail so the user is still stuck. Need to have the files present in the installer, see #10485 and a cascade of following issues.

**Comment by mcdurdin** [comment]
Note: schemas are bundled in the .mjs but imports are not.

**Comment by mcdurdin** [comment]
Fix is blocked until #10489, #10492 are merged into this branch, will merge those up to the epic once they pass and then update this branch; will then retest.

**Comment by mcdurdin** [comment]
@bharanidharanj the underlying issues have now been addressed, hopefully! Please retest :grin:
@keymanapp-test-bot retest

**Review by rc-swag — APPROVED** [review]
Seeing all the if `ActiveLdmlKeyboardEditor` else if `ActiveLdmlKeyboardEditor` feels like some aggregation or maybe even inheritance could have been used for a `ActiveKeyboardEditor`.   Otherwise 
LGTM

**Comment by mcdurdin** [comment]
> Seeing all the if `ActiveLdmlKeyboardEditor` else if `ActiveLdmlKeyboardEditor` feels like some aggregation or maybe even inheritance could have been used for a `ActiveKeyboardEditor`

Agree. Certainly would be a nice refactor. For now, given the code is deprecated before it even lands, leaving it as is. The ActiveLdmlKeyboardEditor is likely to be completely rewritten in 18.0 as a web component.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER (PASSED):** Retested with the updated PR build (Keyman Developer 17.0.248-alpha-test-10459) on Windows 11 OS (VM) and here is my observation: 1. Created an LDML keyboard project. 2. Opened the project. 3. Clicked Keyboard / Test Keyboard option from the Keyboard menu. Verified that the project doesn't throw any error messages. 4. Pressing 'a' key shows 'Hello World!'  on the pane. Seems to be working fine. Thanks.

**Pull request merged**
