### PR TITLE
[Web, LMLayer] Dependency updates

### PR DESCRIPTION
**Pull request by jahorton**
We've had a major jump in the number of detected vulnerabilities that Node's reporting, so even though they're all focused on the development/testing environment, it's probably wise to get them updated.

Most of the reports require semantic-version updates, so `dependabot` seems to prefer we handle those ourselves... hence this PR.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/157141:id/kvk/index.html)

**Comment by jahorton** [comment]
The KeymanWeb failures here are entirely due to lack of a CORS setup for testing IFrames.

**Comment by jahorton** [comment]
Or so I thought... testing today is turning up different stuff.  Either way, I added some error logging to the general area of the code to facilitate debugging the issue further, along with a self-adjusting timeout on the attachment itself in case it's a matter of load event timings.

**Comment by jahorton** [comment]
> LGTM. I am not a fan of random magic timeout durations but they'll do for now :)

Well, that's why we `.skip()`'ed those tests, right?

**Pull request merged**
