### PR TITLE
chore(common): Check in crowdin strings for Fulfulde Nigeria

### PR DESCRIPTION
**Pull request by darcywong00**
These use the locale `ff-NG` in contrast to the existing Pulaar-Fulfulde locale `ff-ZA`.

## User Testing
For all the platforms, load the PR build, set the UI to "Ɗemngal Fulfulde" (sometimes listed as Fulfulde Nigeria), and verify the UI is in Fulfulde

* **TEST_ANDROID** - Tests Ɗemngal Fulfulde UI for Android
1. Load the PR build in an Android 5.0 emulator (SDK 21)
2. In the Keyman app, go to Settings --> Display Language --> Ɗemngal Fulfulde
3. Verify the UI is in Ɗemngal Fulfulde

* **TEST_IOS** - Tests Ɗemngal Fulfulde UI for iOS
1. Start the app
2. Under Settings - General - Language & Region, set the Language to Pulaar Fula and the Region to Nigeria
3. Verify the app refreshes with the Fulah Nigeria, or 'ff-NG' strings

* **TEST_WINDOWS** - Tests Ɗemngal Fulfulde UI for Windows

* **TEST_LINUX** - Tests Ɗemngal Fulfulde UI for Linux
1.  start Keyman configuration with: `LANGUAGE=ff_NG km-config`

### CODE REVIEW

**Comment by darcywong00** [comment]
@sgschantz - Is the ff-NG locale available in XCode?

**Comment by sgschantz** [comment]
I see ff-ng under Fulah in Xcode. I see Fulah as already supported in Keyman, and I'm assuming that must be ff-za. I need to confirm in the project file sas Xcode's UI only shows the language name "Fulah" for supported languages, without locale info.

**Review by mcdurdin — APPROVED** [review]

**Comment by MakaraSok** [comment]
* **TEST_ANDROID: PASSED** The UI does switch and show in the language.
* **TEST_IOS: PASSED** The UI does switch and show in the language.
* **TEST_WINDOWS: PASSED** The UI does switch and show in the language.
* **TEST_LINUX: BLOCKED** The language cannot be found in Linux. Running `LANGUAGE=ff_NG km-config` does switch the UI to the language. Mark as "BLOCKED" for now as the language cannot be switched from within the "Region & Language" settings.

**Comment by MakaraSok** [comment]
> * **TEST_LINUX: BLOCKED** The language cannot be found in Linux. Running `LANGUAGE=ff_NG km-config` does switch the UI to the language. Mark as "BLOCKED" for now as the language cannot be switched from within the "Region & Language" settings.

Fulfulde cannot be found in the list of available languages.

**Comment by darcywong00** [comment]
> Fulfulde cannot be found in the list of available languages.

Per standup, we'll proceed with merging this since Keyman for Linux doesn't have a language picker.
It'll be similar to the iOS platform

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.149-alpha](https://keyman.com/downloads/releases/alpha/15.0.149)

**Pull request merged**
