### PR TITLE
chore(common): beta to master B15S6

### PR DESCRIPTION
**Pull request by mcdurdin**
@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
Not to address on this PR, but I would have expected the github-actions bot to apply more platform labels besides android and common

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
> Not to address on this PR, but I would have expected the github-actions bot to apply more platform labels besides android and common

Smells like it might have hit a limit (9 labels?). I checked the action log at https://github.com/keymanapp/keyman/runs/5809901597?check_suite_focus=true#step:2:2 and there were no errors reported.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.5-alpha](https://keyman.com/downloads/releases/alpha/16.0.5)

**Pull request merged**
