### PR TITLE
fix(developer): data was lost when editing ansi keyboards

### LINKED ISSUE #2380: [Developer] Data loss can occur if ANSI file has Unicode chars added
**Describe the bug**

Load an .kmn file in Keyman Developer which has characters >0x80 in it (but not UTF-8, to ensure it loads as 'ANSI'). Add some Unicode chars and then save, then the Unicode chars are lost without warning.

--

**Keyman Developer**:
 - OS: Windows
 - Keyman Developer version: 12.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #2380. If the user loads a keyboard that was an ANSI file, and adds Unicode content, the Unicode content was silently lost on save.

### CODE REVIEW

**Comment by mcdurdin** [comment]
# User Test:

Test 'yes' case:
1. Create a new keyboard project and load the keyboard file.
2. Change the file format to ANSI, save and close the keyboard.
3. Reopen the keyboard, add any other script character to a field in the source file.
4. Press Save. You should be presented with a prompt warning you.
5. Choose Yes. The file should be converted to UTF-8. 

Test 'no' case:
1. Follow steps 1-4 above.
2. Choose No. The file will not be converted and the Unicode content will be lost (probably converted to `?`).

Test 'cancel' case:
1. Follow steps 1-4 above.
2. Choose Cancel. The keyboard will not be saved.

**Comment by MakaraSok** [comment]
Errors occur when installing the Keyman Desktop and Keyman Developer of this PR:

image

image

However, they seem to get installed and be usable.

When following the steps above, at #4 there was no warning message popped up. The file got save normally and silently without any warning.

The following code block was used to test:

```
begin ANSI > use(main)


group(main) using keys

"a" + "a" > "â"
"i" + "i" > "î"
"u" + "u" > "û"

"n" + "n" > "ñ"
```

**Comment by mcdurdin** [comment]
The codes you have chosen are all available in the ANSI code page 😄 Perhaps add Khmer characters or something non-Latin to validate.

**Comment by MakaraSok** [comment]
I am not able to find the files necessary for the test here: 

https://build.palaso.org/viewLog.html?buildId=173105&buildTypeId=Keyman_ValidateHistoryMd&tab=artifacts&showAll=true

Am I looking at the right place?

**Comment by mcdurdin** [comment]
> I am not able to find the files necessary for the test here:
> 
> https://build.palaso.org/viewLog.html?buildId=173105&buildTypeId=Keyman_ValidateHistoryMd&tab=artifacts&showAll=true
> 
> Am I looking at the right place?

Not quite! Look at the build associated with "Test: Pull Requests (Keyman Desktop and Keyman Developer)" check (e.g. https://build.palaso.org/viewLog.html?buildId=173099&buildTypeId=KeymanDesktop_TestPullRequests&tab=artifacts). However, this build has expired so I am triggering a new one which will hopefully be available when you wake up!

**Comment by mcdurdin** [comment]
@MakaraSok can you retest? Build should be available in next hour; look at the build associated with "Test: Pull Requests (Keyman Desktop and Keyman Developer)" check.

**Comment by MakaraSok** [comment]
> Not quite! Look at the build associated with "Test: Pull Requests (Keyman Desktop and Keyman Developer)" check (e.g. https://build.palaso.org/viewLog.html?buildId=173099&buildTypeId=KeymanDesktop_TestPullRequests&tab=artifacts). However, this build has expired so I am triggering a new one which will hopefully be available when you wake up!

The link does not work.
image

The installation files were obtained them from here instead: https://build.palaso.org/viewLog.html?buildId=177910&buildTypeId=KeymanDesktop_TestPullRequests&tab=artifacts&branch_KeymanDesktop=2416#%2Frelease

Upon installation, error 404s occurred for both Desktop and Dev. Here is the diagnostic report which may help telling what was happening.
[error404.zip](https://github.com/keymanapp/keyman/files/4084199/error404.zip)

Despite the errors, the programs seems to work just fine though.​​ I then proceeded to testing, instruction #1 to #4 have been followed, but when clicking on "Save," nothing happened. No dialogue box appeared.

Here is the test keyboard.
[test.zip](https://github.com/keymanapp/keyman/files/4084243/test.zip).

**Comment by MakaraSok** [comment]
@mcdurdin 

> Test 'yes' case:
> 
> 1. Create a new keyboard project and load the keyboard file.
> 2. Change the file format to ANSI, save and close the keyboard.
> 3. Reopen the keyboard, add any other script character to a field in the source file.
> 4. Press Save. You should be presented with a prompt warning you.
> 5. Choose Yes. The file should be converted to UTF-8.
> 

The file has been converted to UTF-8 without losing any data.

> Test 'no' case:
> 
> 1. Follow steps 1-4 above.
> 2. Choose No. The file will not be converted and the Unicode content will be lost (probably converted to `?`).

The file was not converted and the Unicode content is not lost nor converted to `?`.

> 
> Test 'cancel' case:
> 
> 1. Follow steps 1-4 above.
> 2. Choose Cancel. The keyboard will not be saved.

Works as expected.

**Comment by mcdurdin** [comment]
> > Test 'no' case:
...
> The file was not converted and the Unicode content is not lost nor converted to `?`.

Did you reopen the file to see if the content was lost?

**Comment by MakaraSok** [comment]
> > > Test 'no' case:
> > > ...
> > > The file was not converted and the Unicode content is not lost nor converted to `?`.
> 
> Did you reopen the file to see if the content was lost?

I didn't. I was looking for changes right after clicking "no". 

Tested it again, and yes the file was not converted and the Unicode character turned to ?.
image

**Pull request merged**
