### PR TITLE
fix(android/engine): Activate menu on globe longpress before release

### PR DESCRIPTION
**Pull request by darcywong00**
Addresses #6267 for 15.0 beta.

This updates the globekey longpress logic to trigger the keyboard picker menu before the globe key is released.
We still want to block the keybard picker menu for system keyboard on lock screen.

~Question: Should we make `KMManager.doGlobeKeyLongpressAction()` a public API?~
I ended up making `KMManager.handleGlobeKeyAction()` a public API

## User testing
Setup 
1. On an Android device or emulator, install PR build of Keyman
2. From the Android settings menu, also set a simple password (e.g. `1234` as password, not PIN). If using a physical device, I 
recommend adding a second unlock like fingerprint
3. From Keyman, install another Keyman keyboard (e.g. Khmer Angkor)

* **TEST_GLOBE_SHORTPRESS**
1. In the Keyman app, short press the globe key and release
2. Verify Keyman quickly switches to the next Keyman keyboard

* **TEST_GLOBE_LONGPRESS**
1. In the Keyman app, longpress the globe key and hold it down
2. After a while, verify the Keyman keyboard picker menu appears
3. Select a Keyman keyboard and verify Keyman switches to the selected keyboard
4. From the Keyman "Settings" menu, enable Keyman as a default system keyboard
5. Lock the device
6. Attempt to unlock the device with the Keyman keyboard, but don't enter the password yet
7. Longpress on the globe key and release
8. Verify instead of the keyboard picker menu, Keyman switches to another keyboard (still on lock screen). The next keyboard can be either Keyman or system keyboard. Depending on the lock screen timing, it could cycle through all the Keyman keyboards before getting to a system keyboard.
9. While still on the lock screen (you may need to hit the power button again if the lock screen times out), short press on the globe and release
10. Enter the password to unlock the device.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Not sure if this is related but some display artifacts on keyboard menu:



Also, keyboard should not be dismissed when the switch screen is shown -- it is slow, and then the user has to touch in the edit box again to show the keyboard again.

**Comment by darcywong00** [comment]
> Also, keyboard should not be dismissed when the switch screen is shown -- it is slow, and then the user has to touch in the edit box again to show the keyboard again.

Yeah, that's been reported as #4476

**Comment by bharanidharanj** [comment]
* **TEST_GLOBE_SHORTPRESS (PASSED):** Tested this in API 30 Android 11 emulator and the Short Press on the Globe Key Switches to next keyman keyboard successfully.

**Comment by bharanidharanj** [comment]
* **TEST_GLOBE_LONGPRESS (FAILED):** Tested this issue with API 30 (Version 11) and I am seeing two different results. First time it working fine. Second time, when I repeat the same steps, that is Long press the globe key on the OSK, the keyboard has been changed to System Keyboard. Seems to be an issue. Attached the Screenshot for reference.

**Comment by darcywong00** [comment]
> Second time, when I repeat the same steps, that is Long press the globe key on the OSK, the keyboard has been changed to System Keyboard.

@bharanidharanj - multiple uses of the globe key on the lock screen will eventually cycle to the system keyboard. I'll tweak step 8

> 8. Verify instead of the keyboard picker menu, Keyman switches to another Keyman keyboard (still on lock screen)

to accommodate that case.

@keymanapp-test-bot retest TEST_GLOBE_LONGPRESS

**Review by rc-swag — APPROVED** [review]
LGTM

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_GLOBE_LONGPRESS (PASSED):** globe key works as indicated.

**Comment by bharanidharanj** [comment]
> > Second time, when I repeat the same steps, that is Long press the globe key on the OSK, the keyboard has been changed to System Keyboard.
> 
> @bharanidharanj - multiple uses of the globe key on the lock screen will eventually cycle to the system keyboard. I'll tweak step 8
> 
> > 8. Verify instead of the keyboard picker menu, Keyman switches to another Keyman keyboard (still on lock screen)
> 
> to accommodate that case.
> 
> @keymanapp-test-bot retest TEST_GLOBE_LONGPRESS

@darcywong00 Okay, Thanks.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.213-beta](https://keyman.com/downloads/releases/beta/15.0.213)

**Pull request merged**
