### PR TITLE
[Android] Allow user to switch keyboard  on lock screen

### PR DESCRIPTION
**Pull request by darcywong00**
@MakaraSok got into a scenario where his Android device was locked, and the current system keyboard was a non-Latin Keyman keyboard. If it weren't for his fingerprint access, he would have been locked out and unable to enter his password.

(edited to describe behavior in review comment below)
This PR overrides the globe button if the screen is locked:
1. Switch to next Keyman keyboard (w/o menu)
2. When all Keyman keyboards have been cycled through, advance to next system input.

**Caution:** If testing on a physical device, make sure there's a fallback to fingerprint access.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148911:id/kvk/index.html)

**Comment by darcywong00** [comment]
Question: Maybe it's better on the lock screen to have the globe button switch to the default "SIL Euro Latin" keyboard?

**Comment by mcdurdin** [comment]
There are numerous scenarios here which are difficult. Which keyboard has the user used to enter their password? What if they uninstall Keyman after setting their password with Keyman? It's impossible for us to cover all the bases, so I think the appropriate action for the globe key would be: switch to next Keyman keyboard, until all Keyman keyboards have been selected, then advance to next input mode.

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/154728:id/kvk/index.html)

**Pull request merged**
