### PR TITLE
fix(web): add null guard for missing debug info when reporting to Sentry

### LINKED ISSUE #11548: bug(web): sentry-reporting error occurs if top-level `keyman` object unavailable
Sentry Issue: [KEYMAN-WEB-K7](https://keyman.sentry.io/issues/5389324925/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'window["keyman"]["getDebugInfo"]')
  at None (/private/var/mobile/Containers/Shared/AppGroup/EA683373-DC57-4C37-97F6-4B783F7799DC/keyman/keyman-sentry.js:73:49)
  at None (/private/var/mobile/Containers/Shared/AppGroup/EA683373-DC57-4C37-97F6-4B783F7799DC/keyman/keyman-sentry.js:93:31)
  at None (/private/var/mobile/Containers/Shared/AppGroup/EA683373-DC57-4C37-97F6-4B783F7799DC/keyman/keyman-sentry.js:118:30)
  at None (/private/var/mobile/Containers/Shared/AppGroup/EA683373-DC57-4C37-97F6-4B783F7799DC/keyman/sentry.min.js:2:37552)
  at onfulfilled (/private/var/mobile/Containers/Shared/AppGroup/EA683373-DC57-4C37-97F6-4B783F7799DC/keyman/sentry.min.js:2:18507)
...
(28 additional frame(s) were not displayed)
```

A couple of simple optional-chaining guards should allow the error to pass through.  It's pretty clear this is blocking _some other_ sort of error that's occurring very early during the keyboard-initialization process within one or both of our mobile apps.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11548.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

**Pull request merged**
