### PR TITLE
chore(oem/fv): Update versions in keyboards.csv 🏠

### PR DESCRIPTION
**Pull request by darcywong00**
Cherrypick of #10606 to stable-16.0

Several users reported the latest FV app (16.0.145) is listing old keyboard versions (which still come from keyboards.csv).

This updates the keyboard versions in keyboards.csv (already updated in 17.0)

## User Testing

**Setup** - Install the PR build of FirstVoices for Android

* **TEST_NSILXCEN_Hul̓q̓umin̓um̓** - Verifies keyboard versions updated and can be enabled
1. Launch FirstVoices
2. On the Setup menu -->  Select keyboards --> BC Interior --> Nsilxcən
3. On the *Nsilxcən Settings* page, verify keyboard version is 9.2
4. Enable Nsilxcən and return to the FV main menu
5. On the FV main menu --> Select keyboards --> BC Coast --> Hul̓q̓umin̓um̓ --> Enable
6. Return to the FV main menu and Setup --> Enable FirstVoices and choose as current input method
7. Launch Chrome and select a text area
8. Select FirstVoices keyboard
9. Verify you can use Nsilxcən and Hul̓q̓umin̓um̓ FV keyboards (globe key to alternate)

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
@darcywong00 you may need to touch a file in /android in order to get a build here

**Comment by darcywong00** [comment]
Ah, I manually triggered a test build. Hopefully it'll show up

**Comment by mcdurdin** [comment]
FV APK: https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/441734:id/release/FirstVoices/app-debug.apk

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NSILXCEN_Hul (PASSED):** Tested with the attached PR build (ver 16.0.146-test-10638) in the Android 12 (API 31) emulator and here is my observation: 1. Launched FirstVoices keyboard. 2. Set  Nsilxcən as the system keyboard. Verified the keyboard version is 9.2. 3. Enabled  Nsilxcən and Hul̓q̓umin̓um̓ keyboards. 4 Opened Chrome and clicked the Search bar text field. 5. Verified that the Nsilxcən and Hul̓q̓umin̓um̓ FV keyboards appear (while using the globe key). Seems to be working fine. 

..Nsilxcən keyboard

   


..two firstvoices keyboards as system keyboard

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.146](https://keyman.com/downloads/releases/stable/16.0.146)

**Pull request merged**
