### PR TITLE
fix(developer): enforce presence of Version field when FollowKeyboardVersion is not set, in package compiler 🍒 🏠

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes: #12193
Cherry-pick-of: #12205

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by darcywong00** [comment]
Will this need a :cherries: pick of 1cbd061c05b7a64cf3c688a8a0399bcb06ee90b5 ?

**Comment by mcdurdin** [comment]
> Will this need a 🍒 pick of [1cbd061](https://github.com/keymanapp/keyman/commit/1cbd061c05b7a64cf3c688a8a0399bcb06ee90b5) ?

No, because that piece of code never made it to 17.0-stable.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.329](https://keyman.com/downloads/releases/stable/17.0.329)

**Pull request merged**
