### PR TITLE
change(web): conversion to standard filesystem layout:  testing -> src/test/manual, unit_tests -> src/test/auto 📜

### PR DESCRIPTION
**Pull request by jahorton**
This 📜 PR set is for some long-needed maintenance:  the Web project's files are being reorganized into a format more consistent with the other Keyman projects.  There's no new functionality; the end-goal is for everything to be stable and working as before (at the end of the 📜 PR chain).

Continuing from #7513, this PR moves all test-related files into the `src/test` folder, each going to an appropriate subdirectory based on its role.

This also moves the former `unit_tests/test.sh` script up to the top-level `web/` folder, rather than bury the main unit-test script underneath multiple subdirectories.

Note that CI configurations should be updated to grab `web/src/test/manual` rather than `web/testing`.

### Other notes

As-of-yet unhandled reorg tasks, for future PRs to handle:

- `web/bulk_renderer` is technically an automated testing tool; it should be placed with the rest of the automated testing tools.
- `web/tools/sourcemap-root` is _not_ an automated-testing tool - it's a _build_ tool.  It should be placed separately from the others.
- To accomplish these two goals in accordance with our filesystem organization goals, we'll probably want the following sort of solution:
    - web/src/tools/building (holds `sourcemap-root`)
    - web/src/tools/testing (holds the others)

@keymanapp-test-bot skip

Unit tests have been delegated to #7831.

### CODE REVIEW

**Comment by jahorton** [comment]
- [ ] Just realized - the old `testing/regression-tests` should be handled better.
    - The tool may not be a formalized 'unit test', but I believe it is a form of automated test and should be placed appropriately.
    - I kinda blindly moved it under `src/test/manual/web/` along with the rest of the folder.

**Comment by mcdurdin** [comment]
> * I kinda blindly moved it under `src/test/manual/web/` along with the rest of the folder.

It may be a good step to do this on the way to automation, given it needs manual management at present.

**Comment by jahorton** [comment]
- [ ] I just noticed that `src/tsconfig.json` should be safe to eliminate; each app/ and engine/ directory has its own tsconfig.json based on `src/tsconfig.base.json`.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.41-alpha](https://keyman.com/downloads/releases/alpha/17.0.41)

**Pull request merged**
