### PR TITLE
feat(core): ldml backspace transform 🙀

### PR DESCRIPTION
**Pull request by srl295**
- includes some subroutine refactoring

For: #9450

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
I'm refactoring this some

**Comment by mcdurdin** [comment]
Hope you don't mind, will return this to draft while we wait for parent branch to stabilize and builds to pass, so it exits the review queue.

**Comment by srl295** [comment]
rebased

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.215-alpha](https://keyman.com/downloads/releases/alpha/17.0.215)

**Pull request merged**
