### PR TITLE
[Android] Update dependencies

### PR DESCRIPTION
**Pull request by darcywong00**
Since we're early in the alpha development, it's a good time to update as many dependencies as we can.

### High level summary of changes
* Update compile/target SDK version from 27 to 28
* Migrate appcompat namespace (See https://developer.android.com/jetpack/androidx/migrate)
* Add a null check in JSONParser.java (unit test was failing)

I still need to sort out how Google is consolidating Fabric / Crashlytics into Firebase, so that's for a future PR
References:
http://fabric.io/blog/the-future-of-fabric/

### CODE REVIEW

**Comment by darcywong00** [comment]
Will likely need to update SDKs on the build agents...

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/143445:id/kvk/index.html)

**Comment by jahorton** [comment]
Not sure what's going on, but the Robolectric tests are falling over hard on my development machine.  Was there anything extra you had to do outside of standard code changes to get things working?

**Comment by darcywong00** [comment]
From the command line, `./build.sh` ran tests for me with no changes.

From Android Studio, when running unit tests from the KMEA project, the tests that involved `test_resources` were finicky.
I'd have to manually "Run" -> "Edit configurations", and change the "Working directory" from `$MODULE_DIR$` to the path of my KMEA folder.

**Comment by darcywong00** [comment]
@rfaramir , can you try to build this branch from your machine and see if you run into unit test issues?

**Comment by darcywong00** [comment]
My configuration:

Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by darcywong00** [comment]
So on a fresh 18.04 Ubuntu install
I'm able to build and run tests from the command line.

```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by rfaramir** [comment]
> @rfaramir , can you try to build this branch from your machine and see if you run into unit test issues?

Looks like KMEA built fine, but KMAPro didn't:

Build KMEA and KMAPro:
Build KMEA

DO_BUILD: true
DO_COPY: true
NO_DAEMON: false
...

Welcome to Gradle 4.10.1!
...

BUILD SUCCESSFUL in 48s
1 actionable task: 1 executed
...

BUILD SUCCESSFUL in 22s
23 actionable tasks: 23 executed
...

BUILD SUCCESSFUL in 48s
49 actionable tasks: 36 executed, 13 up-to-date

Copying Keyman Engine for Android to KMAPro, Sample apps, and Tests
Build KMAPro

NO_DAEMON: false
ONLY_DEBUG: false

> Configure project :kMAPro
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :kMAPro:processDebugGoogleServices
Parsing json file: /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/src/debug/google-services.json

> Task :kMAPro:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :kMAPro:processReleaseGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kMAPro:processReleaseGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/src/nullnull/release/google-services.json
  /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/src/release/nullnull/google-services.json
  /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/src/nullnull/google-services.json
  /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/src/release/google-services.json
  /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/src/nullnullRelease/google-services.json
  /Users/rboring/Dev/Keyman/darcy-keyman/android/KMAPro/kMAPro/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
38 actionable tasks: 38 executed

ERROR: KMAPro/build.sh failed

**Comment by darcywong00** [comment]
@rfaramir you need to build the debug variant (google-services.json is on the build agents for release variants)

`./build.sh -debug`

**Comment by rfaramir** [comment]
> @rfaramir you need to build the debug variant (google-services.json is on the build agents for release variants)
> 
> `./build.sh -debug`

That did it!
BUILD SUCCESSFUL in 7s
29 actionable tasks: 28 executed, 1 up-to-date

Building afterwards without -debug failed, so it's not a once-and-done kind of thing. Is that expected? Developers always build debug? Does only the CI build for 'real'?

**Comment by darcywong00** [comment]
Yeah, from the /Android/README.md

> Firebase Crashlytics is used for crash reporting, and it depends on a configured google-services.json file. For this reason, only the Debug variant of KMAPro is intended to be built on a Developer machine

**Pull request merged**
