### PR TITLE
fix(oem/fv): Update keyboard versions and names for fv_all.kmp 🏠

### PR DESCRIPTION
**Pull request by darcywong00**
🍒 pick of #12461 to stable-17.0

This updates keyboard versions and names in keyboards.csv to match the latest fv_all.kmp file.

## User Testing
**Setup** Install the PR build of FirstVoices for Android on device/emulator

* **TEST_VERSION_NAMES** - Verify keyboard versions and names updated
1. Launch FirstVoices app and go to "Select keyboards" menu
2. For the regions below, verify keyboard versions and names match the table below
* BC Coast

| Keyboard Name | Keyboard Version |
|-------------------------|---------------------------|
| Haíɫzaqvḷa            | 10.0                       |
| Sḵwx̱wú7mesh  (snichim) | 10.0        |
| X̄aʼislak̓ala          | 10.0                         |
| Éy7á7juuthem    | 10.2                        |
| ’Wuìk̓ala                | 9.4                         |

* BC Interior

| Keyboard Name | Keyboard Version | 
|-------------------------|----------------------------|
| Nsyilxcən             |  10.0.1                     |
| Tāłtān                   | 9.2                            |

* Western Subarctic

| Keyboard Name | Keyboard Version |
|-------------------------|---------------------------|
| Danezāgéʼ           |  11.0.1                     |
|Dene Zhatıé         |  10.2.1                    |
| Dënesųłıné          | 10.0.1                     |
| Dɛnɛsųłįnɛ           | 10.0.2                    |

### CODE REVIEW

**Comment by darcywong00** [comment]
Build artifact for [FirstVoices apk](https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/498818:id/release/FirstVoices/firstvoices-17.0.331.apk)

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "Keyman-17.0.331-test-12504.apk and firstvoices-17.0.331.apk" build on the Android 14 mobile & emulator. I'm sharing my observation here.

* **TEST_VERSION_NAMES (Passed):** 
1. Installed the "Keyman-17.0.331.apk" file from the PR build. and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" on the settings page. Checked the "Set Keyman as default keyboard".
3. Installed the "firstvoices-17.0.331.apk" file from the PR build.
4. Go to the "Select Keyboards" menu.
- Select the "BC Coast" menu
- Verified keyboard name & version matched.
- Haíɫzaqvḷa 10.0, Sḵwx̱wú7mesh (snichim) 10.0, X̄aʼislak̓ala 10.0, Éy7á7juuthem 10.2, ’Wuìk̓ala 9.4
- Select the BC Interior
- Verified keyboard name & version matched.
- Nsyilxcən 10.0.1, Tāłtān 9.2
- Select the Western Subarctic
- Verified keyboard name & version matched.
- Danezāgéʼ 11.0.1, Dene Zhatıé 10.2.1, Dënesųłıné 10.0.1, Dɛnɛsųłįnɛ 10.0.2
It works well, Thank you.

**Review by mcdurdin — APPROVED** [review]
RSLGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.331](https://keyman.com/downloads/releases/stable/17.0.331)

**Pull request merged**
