### PR TITLE
chore(common): Check in crowdin files for km (Khmer)

### PR DESCRIPTION
**Pull request by darcywong00**
Since the Khmer translation progress is between 90%-100% complete, this PR manually checks in the crowdin files for km.
```bash
crowdin.bat download -b master -l km
```

Sample screenshots of the Keyman for Android app using the Khmer language:
@MakaraSok - please proofread

### App
android app

### Get Started
get started

### Menu options
menu

### Settings
settings

### Install
install

------

We can either:
1. Have team members rebuild for their platforms and verify Khmer locale
2. Only check in the Android files for now

### CODE REVIEW

**Comment by darcywong00** [comment]
Also note, (at least for Android), while we later on will have translations available from translate.keyman.com, we may be limited to the list of languages provided by the ROM on the device.

For example, I can find "amharic", but not "nko" or "obolo" 😞

**Comment by MakaraSok** [comment]
Proofread - all screenshot look good. :)

**Comment by mcdurdin** [comment]
> We can either:
> 
> 1. Have team members rebuild for their platforms and verify Khmer locale
> 2. Only check in the Android files for now

Can I add an option 3?

3. Check in files for all platforms and then allow the localizer to test the subsequent beta release

It isn't feasible to provide screenshots for all or even most potential strings for all platforms, and the localizer or checker can open issues for other problems that are detected such as missing strings or mistranslations.

**Review by mcdurdin — APPROVED** [review]
LGTM. @MakaraSok can you validate against the beta build when it is ready?

**Comment by darcywong00** [comment]
Follow-on notes for the other languages on translate.keyman.com

1. When a translation is ready (~90% complete), we'll manually check those files in (1 language per PR)
2. Give the beta build link for reviewers to test

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.222-beta](https://keyman.com/downloads/releases/beta/14.0.222)

**Comment by MakaraSok** [comment]
@darcywong00 How can I change the UI language to Khmer on Keyman for Android?

**Comment by MakaraSok** [comment]
> LGTM. @MakaraSok can you validate against the beta build when it is ready?

@mcdurdin Checked and some bugs and feat can be found here: https://github.com/keymanapp/keyman/issues?q=is%3Aissue+is%3Aopen+label%3Al10n.

**Comment by darcywong00** [comment]
> How can I change the UI language to Khmer on Keyman for Android?

For now, change your device language to Khmer (Android Settings). Then restart Keyman for Android and it should be in Khmer.
#4261 adds a menu option to select different display languages (not merged yet)

**Comment by MakaraSok** [comment]
@darcywong00 That works for some versions of android, but 5.1.1 does not have KM in the "Language and Input". So, there was not way for me to check them in that older version.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)

**Pull request merged**
