### PR TITLE
fix(linux): JSON File missing after installation

### LINKED ISSUE #8017: bug(linux): JSON File missing after installation
After installing a keyboard (via the "Download" or "Install" button on the GUI or `km-package-install -f` (`km-package-install -p` works fine)) the file {keyboardName}.json is missing from the installation folder and thus when selecting the keyboard and clicking the "About" button no package description is shown (because the description is in that file).
Once you click the "Download" button again however, the file gets added to the installation folder and everything works fine.
image
no description here because of the missing file

### PR DESCRIPTION
**Pull request by TheSchlunz**
This change fixes a bug where a JSON file containing the package description was missing after initial installation.
For that it disposes of the `online` argument in `install_kmp`. 

Fixes #8017

# User Testing
## Preparations
  - delete all files in `~/.cache/keyman/` (especially `keyman_cache.sqlite`)
  - download "EuroLatin" (SIL) package into `~/.cache/keyman/` (https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
  - don't have "khmer_angkor" or "sil_euro_latin" keyboard installed
 
## Tests

**TEST_DOWNLOAD**: JSON file gets downloaded and package description is shown
  - start `km-config`
  - click "Download" button
  - search for "khmer" and click on the "khmer_angkor" keyboard
  - click "Install keyboard" button
  - click "Install" button
  - click "OK" on the message dialog
  - select "Khmer Angkor" keyboard and click "About" button
  - verify that a package description is shown
  - verify that in `~/.local/share/keyman/khmer_angkor` the file `khmer_angkor.json` exists

**TEST_DOWNLOAD_NO_INTERNET**: Installation still works w/o internet connection
  - start `km-config`
  - click "Download" button
  - search for "khmer" and click on the "khmer_angkor" keyboard
  - click "Install keyboard" button
  - turn off internet connection
  - click "Install" button
  - click "OK" on the message dialog
  - verify that the installation works

**TEST_INSTALL**: JSON file gets downloaded and package description is shown
  - start `km-config`
  - click "Install" button
  - select `sil_euro_latin.kmp` from `~/.cache/keyman/`
  - click "Install" button
  - click "OK" on the message dialog
  - select "EuroLatin (SIL)" keyboard and click "About" button
  - verify that a package description is shown
  - verify that in `~/.local/share/keyman/sil_euro_latin` the file `sil_euro_latin.json` exists

**TEST_INSTALL_NO_INTERNET**: Installation still works w/o internet connection
  - start `km-config`
  - turn off internet connection
  - click "Install" button
  - select `sil_euro_latin.kmp` from `~/.cache/keyman/`
  - click "Install" button
  - click "OK" on the message dialog
  - verify that the installation works

**TEST_CL_FILE_INSTALL**: JSON file gets downloaded and package description is shown
  - open terminal
  - change directory to `keyman/linux/keyman-config`
  - run `./km-package-install -f ~/.cache/keyman/sil_euro_latin.kmp`
  - start `km-config`
  - select "EuroLatin (SIL)" keyboard and click "About" button
  - verify that a package description is shown
  - verify that in `~/.local/share/keyman/sil_euro_latin` the file `sil_euro_latin.json` exists

**TEST_CL_FILE_INSTALL_NO_INTERNET**: Installation still works w/o internet connection
  - open terminal
  - turn off internet connection
  - change directory to `keyman/linux/keyman-config`
  - run `./km-package-install -f ~/.cache/keyman/sil_euro_latin.kmp`
  - start `km-config`
  - verify that the installation worked

**TEST_CL_PACKAGE_INSTALL**: JSON file gets downloaded and package description is shown
  - open terminal
  - change directory to `keyman/linux/keyman-config`
  - run `./km-package-install -p sil_euro_latin`
  - start `km-config`
  - select "EuroLatin (SIL)" keyboard and click "About" button
  - verify that a package description is shown
  - verify that in `~/.local/share/keyman/sil_euro_latin` the file `sil_euro_latin.json` exists

**TEST_CL_PACKAGE_INSTALL_NO_INTERNET**: Downloading package fails
  - open terminal
  - turn off internet connection
  - change directory to `keyman/linux/keyman-config`
  - run `./km-package-install -p sil_euro_latin`
  - verify that `ERROR:km-package-install: error: Could not download keyboard data for sil_euro_latin` is shown

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by mcdurdin — APPROVED** [review]

**Review by ermshiperete — APPROVED** [review]

**Comment by ermshiperete** [comment]
@TheSchlunz Looks like you have to adjust the tests. Try running them locally.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by ermshiperete — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.32-alpha](https://keyman.com/downloads/releases/alpha/17.0.32)

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DOWNLOAD (PASSED):** Tested with the attached PR build (Keyman 17.0.32-alpha (package version 17.0.32-1~PR-8040+focal6) in Ubuntu 20.04 Focal Linux OS (VM) and it is showing the package description in the About page. Also, shows the .jason file in the corresponding khmer_angkor folder.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DOWNLOAD_NO_INTERNET (PASSED):** Turned off internet connection. Verified the installation works after clicking the OK button.

**Comment by bharanidharanj** [comment]
* **TEST_INSTALL (PASSED):** notes

**Comment by bharanidharanj** [comment]
* **TEST_INSTALL_NO_INTERNET (PASSED):** Tested this as per the instructions and I was able to install sil_euro_latin keyboard without the internet connection.

**Comment by bharanidharanj** [comment]
* **TEST_CL_FILE_INSTALL (PASSED):** Verified that the package description is shown and the sil_euro_latin.json file is in the corresponding (sil_euro_latin) file folder.

**Comment by bharanidharanj** [comment]
* **TEST_CL_FILE_INSTALL_NO_INTERNET (PASSED):** Tested this as per the instructions and I was able to install the keyboard without internet connection.

**Comment by bharanidharanj** [comment]
* **TEST_CL_PACKAGE_INSTALL (PASSED):** Run the command in the terminal as the instructions and I was able to install the sil euro latin package without having any problem.

**Comment by bharanidharanj** [comment]
* **TEST_CL_PACKAGE_INSTALL_NO_INTERNET (PASSED):** Tested this as per the instructions and verified that an error message appears in the terminal window after run the mentioned command in the test steps.

**Pull request merged**
