### PR TITLE
[iOS] #1166-Use try-catch block to trap and ignore reachability error

### PR DESCRIPTION
**Pull request by tombogle**
Since I can't reproduce the crash, I can't see whether this fixes it (or causes other problems). Not sure if we want to try to put this into master (alpha) first or apply it directly to stable.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Do you have a link to the crash report?

**Comment by tombogle** [comment]
If there is a way to see (or link to) the crash reports on-line, I haven't been able to find it. Logically, it seems like it ought to be possible, but the only way I've found them is through the Organizer in Xcode, and it doesn't appear to have a way to export the crashes. Pretty sad.

**Comment by tombogle** [comment]
And to answer your question from last night, these crash reports do not appear to say what the actual exception was. Bizarre!

**Comment by tombogle** [comment]
We realized that this error is probably happening as a result of a timeout while attempting to determine reachability. So catching and ignoring the exception won't help at all. Instead, we need to determine whether the reachability stuff is needed. If not, we'll remove it. If so, perhaps it can be done asynchronously or postponed.

**Pull request closed without merging**
