### PR TITLE
chore(mac): update to SIL logo with glyph in About window

### PR DESCRIPTION
**Pull request by sgschantz**
Change About window from this:

image

to this:

image

Note that the new logo used is Andika v1 from: https://sites.google.com/sil.org/brand-resource-center/branding/visual-brand/logos
 
Fixes: #12159

# User Testing

* **TEST_ABOUT_WITH_SIL_LOGO**: verify new SIL logo appearance

1. Install and run the Keyman build associated with this PR
1. Verify that the About window displays the updated SIL logo with accompanying glyph

### CODE REVIEW

**Comment by mcdurdin** [comment]
> to this:
> 
> image

The stripes are supposed to be a thin band -- see keyman.com, and the logo is supposed to be on a white background, otherwise it is lost against the orange. See the design guide on the Google drive: https://drive.google.com/file/d/11Hqm9EeEnY6EEOxALTRbSLz5poLc6FRH/view?usp=drive_link

**Comment by sgschantz** [comment]
Now updated to so that the three-color stripe is a thin band 7 points in height.
It was apparently incorrect when running under Sonoma or later due to the Sonoma change in macOS where the default setting in UIView for (the formerly internal value) clipsToBounds changed from true to false.

Here is the updated appearance:

Pasted Graphic

**Comment by mcdurdin** [comment]
> Here is the updated appearance:

That looks great, thanks!

**Review by SabineSIL — APPROVED** [review]

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "Keyman 18.0.151-alpha-local" build on macOS Sonoma 14.5. 

* **TEST_ABOUT_WITH_SIL_LOGO (Passed):**
1. Install the "Keyman 18.0.151-alpha-local" build.
2. Installed the "Khmer" & "Tamil99" keyboards.(e.g., IPA SIL)
3. Select the "Khmer" keyboard.
4. Open the "About" window by clicking the keyman icon.
5. Verified the keyman logo appears as per the design doc. 
6. Verified the Keyman logo has a white background on the header. 
7. Verified the keyman links and buttons work on the About window.
It works well. Thank you.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.154-alpha](https://keyman.com/downloads/releases/alpha/18.0.154)

**Pull request merged**
