### PR TITLE
refactor(linux): Comment unused methods

### LINKED ISSUE #7297: bug(linux): wrong logic in ibus_keyman_engine_set_surrounding_text()
`ibus_keyman_engine_set_surrounding_text()` gets called by ibus in response to a call to `ibus_engine_get_surrounding_text()` to set the context. However, our implementation of `ibus_keyman_engine_set_surrounding_text()` doesn't do anything with the passed in text but instead calls `reset_context()` which in turn calls `ibus_engine_get_surrounding_text()`.

### PR DESCRIPTION
**Pull request by ermshiperete**
Closes #7297.

@keymanapp-test-bot skip

### CODE REVIEW

**Review by jahorton — COMMENTED** [review]
In my experience, we usually outright-delete code rather than comment it out.  Worst-case, it'll still live on in commit history.

**Comment by ermshiperete** [comment]
In general I agree, however in this case I find it helpful to have them commented: the documentation of ibus isn't that great, and having them helps when debugging since it allows to quickly uncomment them.

**Review by mcdurdin — APPROVED** [review]
Generally I think we should delete unused code, but I think @ermshiperete's reasoning is solid here, so lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.88-alpha](https://keyman.com/downloads/releases/alpha/16.0.88)

**Pull request merged**
