### PR TITLE
chore(oem/fv): Add keyboard version and languages

### PR DESCRIPTION
**Pull request by darcywong00**
This updates the keyboards.csv file used by the FirstVoices oem app to generate a keyboard list sorted by Regions.
The following columns are added: Keyboard Version, Language ID, and Language Name (each keyboard only has 1 associated language per kmp.json). These fields will be used by the upcoming feature of adding dictionary support for FV on Android 

The following Bash script generated the columns

```bash
##
## Parses kmp.json from fv_all.kmp and add the keyboard version and the 
## first associated language ID/name for each keyboard in the existing keyboards.csv
## Writes out to the target keyboards.csv
##
function updateLanguages {
  local KMP_FILE="kmp.json"
  if [ ! -f "$KMP_FILE" ]; then
    echo "ERROR: kmp.json not extracted"
    exit 1
  fi

  if [ -f $KEYBOARDS_CSV_TARGET ]; then
    echo "Cleaning existing keyboards.csv target"
    rm -f "${KEYBOARDS_CSV_TARGET}"
  fi

  echo "Parsing language info to add to keyboards.csv"

  # Existing column headers
  while IFS="," read -r SHORTNAME ID NAME REGION WEB_KEYBOARD_9_0
  do
    if [ "$SHORTNAME" != "Shortname" ]; then
      # Find first matching language info for each keyboard
      local KEYBOARD_INFO=$(cat "${KMP_FILE}" | "$JQ" -r ".keyboards[] | select(.id==\"$ID\")")
      local KEYBOARD_VERSION=$(echo ${KEYBOARD_INFO} | "$JQ" -r ".version")
      local LANGUAGE_INFO=$(echo ${KEYBOARD_INFO} | "$JQ" -r ".languages[0]")
      local LANGUAGE_ID=$(echo ${LANGUAGE_INFO} | "$JQ" -r ".id")
      local LANGUAGE_NAME=$(echo ${LANGUAGE_INFO} | "$JQ" -r ".name")

      # trim newline from WEB_KEYBOARD_9_0
      WEB_KEYBOARD_9_0=${WEB_KEYBOARD_9_0%$'\n'}
      WEB_KEYBOARD_9_0=${WEB_KEYBOARD_9_0%$'\r'}

      # Write out keyboard info
      echo "${SHORTNAME},${ID},${NAME},${REGION},${WEB_KEYBOARD_9_0},${KEYBOARD_VERSION},${LANGUAGE_ID},${LANGUAGE_NAME}" >> $KEYBOARDS_CSV_TARGET
    else
      # Copy header line to target
      echo "Shortname,ID,Name,Region,9.0 Web Keyboard,Version,Language ID,Language Name" >> $KEYBOARDS_CSV_TARGET
    fi
  done < $KEYBOARDS_CSV

  echo "Language info added to ${KEYBOARDS_CSV_TARGET}"
}
```

Tagging @madebybridget

## User Testing
* **TEST_ANDROID** 
1. Load the PR build of the OEM FirstVoices app for Android
2. On the Setup page, select a region --> any keyboard --> check the box
3. Back out until you're back at the Setup page
4. Enable FirstVoices as a System Keyboard
5. Launch a separate app (e.g. Chrome browser) and click in a text field
6. With the FirstVoices keyboard as a system keyboard, verify it appears and types

* **TEST_IOS**
1. Repeat the same test with the PR build of the OEM FirstVoices app for iOS

### CODE REVIEW

**Comment by mcdurdin** [comment]
Can we add the bash script to the repo, along with documentation on when it should be used? I guess it can't be added to the build because of some manual steps required?

**Review by mcdurdin — APPROVED** [review]
Changes LGTM

**Comment by darcywong00** [comment]
> Can we add the bash script to the repo, along with documentation on when it should be used? I guess it can't be added to the build because of some manual steps required?

OK. I also considered replacing `oem/firstvoices/common/build_keyboards.sh`, but FV iOS still uses it.

**Comment by darcywong00** [comment]
I've committed the Bash script in `build_csv_languages.sh`. It's manually run, and self-contained.

imho it's documented in the comments 😄

**Comment by MakaraSok** [comment]
> Load the OEM FirstVoices app for Android

Should the latest stable of FV be used to test this PR?

**Comment by darcywong00** [comment]
> Should the latest stable of FV be used to test this PR?

No, use the test build that uses this updated keyboards.csv and verify it functions the same

**Comment by bharanidharanj** [comment]
* **TEST_ANDROID: FAILED** First Voice Keyboard missing while clicking on the text field (in Chrome browser)

**Comment by darcywong00** [comment]
> First Voice Keyboard missing while clicking on the text field (in Chrome browser)

@bharanidharanj  What Region and Language did you select in the FirstVoices keyboard? ("Select keyboards" button in the setup). Can you use the device's keyboard selector to select "First Voices" and see if that shows?

**Comment by MakaraSok** [comment]
I've retested this with the new build triggered today and the results are:

* **TEST_ANDROID: PASSED** The FV keyboard does show up when clicking in the text field.

**Comment by MakaraSok** [comment]
* **TEST_IOS: BLOCKED** The FV keyboards don't show up as expected. Euro Latin keyboard is shown instead.

image

Two languages were selected from within the FV app, but it doesn't show up as a system keyboard.
image

Note that the behavior above is observed on in the Simulator for both the build off of this PR and the stable version of FV.
When installing the stable version of the FV on a physical device, things are working as expected.

@bharanidharanj Can you try the build from this PR on your simulator?

**Comment by darcywong00** [comment]
iOS is blocked by #6281 - I'm going to go ahead and merge this to continue FV development.

**Comment by sgschantz** [comment]
@MakaraSok @mcdurdin FV iOS works as expected for me -- no problems switching between FV keyboards. I tested with using master post-merge. This was tested on iOS 15.2 with simulator Version 13.2 (972.2) included with the latest Xcode 13.2.1.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.202-alpha](https://keyman.com/downloads/releases/alpha/15.0.202)

**Pull request merged**
