### PR TITLE
fix(windows): Ignore Access Denied error creating task

### LINKED ISSUE #4116: bug(windows): EOleException(80070005): Failed to create task: Access is denied
**Describe the bug**

Continuing on from #3994.
Sentry Issue: [KEYMAN-WINDOWS-5T](https://sentry.keyman.com/organizations/keyman/issues/1479/?referrer=github_integration)

This issue is not resolved by #4033. We are still getting "Access is denied" for some users. The error is silently handled but results in a reduction of functionality, as Keyman will not be able to start automatically when the task is not available to trigger it. Given it's a silent error and has a reasonably low impact in day-to-day use (workaround: start Keyman yourself, just like in previous versions of Keyman), I propose to resolve this during beta rather than treating this as a beta launch blocking issue.

```
  kmshell             0x2c9387b3   Keyman.System.KeymanSentryClient.TKeymanSentryClient.ReportHandledException (Keyman.System.KeymanSentryClient.pas:201)
  kmshell             0x2c939b03   Keyman.System.KeymanStartTask.TKeymanStartTask.CreateTask (Keyman.System.KeymanStartTask.pas:135)
  kmshell             0x2c93a40e   Keyman.System.KeymanStartTask.TKeymanStartTask.RecreateTask (Keyman.System.KeymanStartTask.pas:202)
  kmshell             0x2c970ed8   initprog.RunKMCOM (initprog.pas:379)
  kmshell             0x2c970cbd   initprog.Run (initprog.pas:331)
  kmshell             0x2c984c9a   kmshell.kmshell
  KERNEL32.DLL        0x75516358   BaseThreadInitThunk
  ntdll               0x77708943   __RtlUserThreadStart
  ntdll               0x77708913   _RtlUserThreadStart
```

We may need to collect some more detail on this issue to be able to figure out under which circumstances access is denied. The issue is frequent so we should be able to find a reproduction of it.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows (unknown version?) 
 - Keyman version: 14.0.203-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4116.
Fixes KEYMAN-WINDOWS-5T.

If we get an 'access denied' error, we won't report it to Sentry. This error is of minor consequence as it arises in normal configurations only if the task was already present, created by an elevated instance of kmshell under the same user name. In that situation, the task works fine; it just cannot be updated by a non-elevated instance of kmshell. If there are other reasons for receiving access denied, we won't be able to distinguish them anyway, so the best response is to suppress this message.

An alternative would have been to either (a) avoid creating the task as an elevated user, or (b) only ever create the task as an elevated user. However, this adds extra unnecessary complexity and means that the task may not always be present when we want it to be.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.232-beta](https://keyman.com/downloads/releases/beta/14.0.232)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.98-alpha](https://keyman.com/downloads/releases/alpha/15.0.98)

**Pull request merged**
