### PR TITLE
fix(web): Maintain separate Caps Lock states for touch and physical

### LINKED ISSUE #6799: bug(web): caps lock state needs to be maintained separately for physical and touch layouts at the same time
**Describe the bug**

As of 15.0, the changes I introduced for the Caps Lock layer in KeymanWeb interact with the ` this.stateKeys['K_CAPS']` variable to ensure that key events generated from the `caps` layer are given the right modifier state when doing rule processing.

However, in a brief re-analysis today, I think there is a logical issue and loss of state. We need to ensure that `this.stateKeys['K_CAPS']` is set to the state of the hardware keyboard caps lock key, kept in sync with the hardware keyboard state, except when the user generates a touch event on the caps layer.

The hardware Caps Lock key must not affect the output from the touch keyboard, and changing the caps state on the touch keyboard must not affect the value of `this.stateKeys['K_CAPS']` when pressing keys on the hardware keyboard.

This is also mixed up with `_UpdateVKShift` which was originally designed to make sure the On Screen Keyboard for desktop matched the modifier states of the hardware keyboard (so holding Shift on the hardware keyboard would show the shifted layer on the desktop On Screen Keyboard). This function is now overloaded with touch layout logic as well, and we have multiple state variables for modifiers, so it's really hard to trace:

* `this.stateKeys['K_CAPS']`
* `Lkc.Lstates`
* `Lkc.Lmodifiers`
* And the mysterious link between layer and modifier as shown in `this.getLayerId(keyShiftState)`

Note that the hardware keyboard modifier keys currently affect the visible layer of the touch keyboard, which is probably wrong, particularly for Caps Lock which is not transient -- hardware modifier state should only affect the modifier state of the desktop osk (which is supposed to mirror the state of the hardware keyboard, unlike the touch keyboard).

Yes, there is a hard problem of pressing Caps Lock on the desktop osk, which AFAIK cannot cancel the Caps Lock state of the hardware keyboard on current browsers. Separate problem really but one to consider when detangling this.

---

**KeymanWeb:**
 - KeymanWeb Version: 15.0.260

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6799.

Caps Lock state management for touch layouts was not quite right -- it touched the base Caps state variables rather than just the event Lstates property. This meant that it was impossible to track the physical Caps Lock key separately to the touch layout layer, and that the two states would interfere with each other.

This PR changes that behaviour and separates the physical caps lock and touch caps lock states. The physical caps lock state is tracked in the `this.stateKeys['K_CAPS']` variable, but is completely ignored for touch layouts. Rules use the Caps Lock state replicated in the `Levent.Lstates` property, which was already being set correctly for the touch layout in the `ActiveKey.constructBaseKeyEvent` function:

https://github.com/keymanapp/keyman/blob/4f36c3c2df0b14ec2d5fac36714c4e8bda54961c/common/web/keyboard-processor/src/keyboards/activeLayout.ts#L177-L182

https://github.com/keymanapp/keyman/blob/aa905e1c61c9743e54ce8c7c0c5a4fae0734fcff/common/web/keyboard-processor/src/text/keyboardProcessor.ts#L378-L392

## Unanswered Questions/Issues

- [ ] There is still a question in my mind around the `NCAPS` state which is never set. Do we need to be tracking this also? The compiler avoids ambiguity now around unspecified Caps Lock state but I am not clear if we are covering all the bases here and if behaviour is consistent -- should we be setting `NCAPS` if not on the `caps` layer? Note that on touch we don't combine Caps Lock with other modifiers, unlike on physical keyboards or desktop OSK.
- [ ] On a desktop device, clicking the Caps Lock key on the OSK results in desync between hardware and OSK. This is unavoidable, as we cannot set the physical Caps Lock state. The current behaviour *seems* okay -- the Caps Lock state is in effect for OSK keys until the user touches the physical keyboard, and physical Caps Lock is reflected in the OSK. Nonetheless, there is a difference in physical Caps Lock state and OSK-initiated Caps Lock state, and I wonder if we need to be able to tell the difference?
- [ ] The desktop OSK does not show a 'Caps Lock' layer. This is definitely not ideal but matches the current Windows behaviour. This is something we need to improve on -- but does require changes to .kvk in order to work properly.

# User Testing

## SUITE_CAPS_ON_TOUCH - Test using the new sil_euro_latin keyboard with Caps Lock support

Use the keyboard ~~[sil_euro_latin.zip](https://github.com/keymanapp/keyman/files/8985670/sil_euro_latin.zip)~~ [sil_euro_latin.zip](https://github.com/keymanapp/keyman/files/9018791/sil_euro_latin.zip) for testing.

### GROUP_WEB_DEBUGGER: Perform tests in the Keyman Developer web debugger:

1. Install Keyman Developer from the artifacts in this PR.
2. Unzip and load this .kpj into Keyman Developer.
3. Open sil_euro_latin.kmn
4. In the Build tab, click Compile Keyboard, then click Test Keyboard on web.
5. Select 'http://localhost:8008/' from the list of web addresses and click Open in browser.
6. In the web debugger, select sil_euro_latin from the list of keyboards.
7. Select 'iPhone 5S' from the list of devices.

### GROUP_ANDROID: Perform these tests in the Android emulator, in-app or system keyboard, after installing the compiled sil_euro_latin.kmp from the above link.

* **TEST_CAPS_LAYER**: on the touch keyboard on screen, double-click on the Shift key to activate the `caps` layer. Verify that:
  1. the `caps` layer is activated
  2. clicking keys on the `caps` layer generate capital letters, including long-presses.
  3. clicking letter keys does not drop back to the default layer.
 
* **TEST_CAPS_LAYER_RESET**: on the touch keyboard on screen, double-click on the Shift key to activate the `caps` layer. Click a few letter keys. Then click the Shift key again. Verify that:
  1. the `default` layer is activated
  2. clicking keys on the `default` layer generates lower case letters, including long-presses.
  3. typing a few letters generates lower case letters.

* **TEST_CAPS_ON_HARDWARE**: verify that Caps Lock is working correctly on hardware keyboard and that hardware caps does not affect the touch keyboard.
  1. On the hardware keyboard (your computer keyboard if using emulator/simulator), ensure Caps Lock is off, and type a few letters on the hardware keyboard. Verify that they are lower case.
  2. Press Caps Lock on your hardware keyboard. Type a few letters on the hardware keyboard. Verify that they are UPPER CASE.
  3. Type a few letters on the touch keyboard. Verify that they are lower case

## SUITE_DESKTOP

For these tests, use the KeymanWeb unminified test page, without any mobile emulation, on a desktop computer.

### GROUP_OBOLO_CHWERTY: Use the `obolo_chwerty_6351` keyboard that is in the keyboard menu. Ensure that you press the Q (ch/Ch/CH key) in the tests to confirm the Caps vs NCaps vs Shift state.

* **TEST_PHYSICAL_CAPS**: Verify that the Caps Lock key on the hardware keyboard affects both hardware keystrokes and OSK keystrokes:
  1. Verify that Caps Lock is off, type a few letters on the hardware keyboard and then a few on the OSK to verify that letters are lower case.
  4. Press Caps Lock on the hardware keyboard. Type a few letters on the hardware keyboard, and then a few on the OSK to verify that letters are now upper case. Verify that the Caps Lock key is highlighted on the OSK (note that the letters will not show upper case on the OSK, this is not a failure.)
  5. Press Caps Lock again. Type a few letters on the hardware keyboard and then a few on the OSK to verify that letters are again lower case.

* **TEST_OSK_CAPS**: Verify that the Caps Lock key on the OSK affects only OSK keystrokes:
  1. Verify that Caps Lock is off, type a few letters on the hardware keyboard and then a few on the OSK to verify that letters are lower case.
  2. Press Caps Lock on the OSK. Type a few letters on the OSK to verify that letters are now upper case. Verify that the Caps Lock key is highlighted on the OSK (note that the letters will not show upper case on the OSK, this is not a failure.)
  3. Press Caps Lock on the OSK again. Type a few letters on the OSK to verify that letters are again lower case.

* **TEST_OSK_CAPS_INTERACTIONS**: Verify that pressing any key on the hardware keyboard cancels the OSK Caps Lock key:
  1. Verify that Caps Lock is off, type a few letters on the hardware keyboard and then a few on the OSK to verify that letters are lower case.
  2. Press Caps Lock on the OSK. Type a few letters on the OSK to verify that letters are now upper case. Verify that the Caps Lock key is highlighted on the OSK (note that the letters will not show upper case on the OSK, this is not a failure.)
  3. Press a letter key on the _hardware keyboard_. Type a few letters on the OSK to verify that letters are again lower case. Type a few letters on the hardware keyboard to verify that they are lower case.

### CODE REVIEW

**Comment by jahorton** [comment]
This PR needs additional user tests beyond those specified here.

In particular, we need to test against a keyboard with [CAPS] and [NCAPS]-based rules, not just a touch keyboard that happens to utilize a caps layer.  It does seem that the "Obolo Chwerty" keyboard has such rules, at least.  We'd need some tests against a few different use cases:

The most important edge-like case to be sure we have covered:  typing with the OSK when the hardware keyboard's CAPS key is enabled.  Consider that this can happen for Android devices with external keyboards!

**Comment by jahorton** [comment]
> Caps Lock state management for touch layouts was not quite right -- it touched the base Caps state variables rather than just the event Lstates property. This meant that it was impossible to track the physical Caps Lock key separately to the touch layout layer, and that the two states would interfere with each other.

I see that someone made a significant amount of changes to the relevant area while I was away, so this may no longer hold, but...

The original design for state-key management was that they **_shouldn't_** be tracked separately.  On desktop devices, at least, _any_ keystroke typed while CAPS is active will have that noted as part of its modifier state - see the following block:

https://github.com/keymanapp/keyman/blob/bcfd822baacee15d75b18f4c5ccb4baabdb72ead/web/source/dom/preProcessor.ts#L97-L103

Therefore, there's **_literally_** no need to "track" physical-keystroke modifier state - assuming that mobile devices follow suit as well when an external keyboard is used on them.  Or is there something I'm missing here?

Under the assumption that my logic until now in this comment is correct, we only need to _track_ the OSK's modeled state for CAPS.   The second a physical keystroke comes in, we then instantly reset the OSK's modeled state to match that of the incoming keystroke.  (As this is an inherent part of physical-keystroke KeyEvents, we don't even need to reset the tracked-state first!)  Until a physical keystroke comes in, any OSK-based changes to the state take priority.

So...

> This meant that it was impossible to track the physical Caps Lock key separately to the touch layout layer, and that the two states would interfere with each other.

How would they interfere with each other?

**Comment by mcdurdin** [comment]
I think your assessment is pretty much right. 

Except I think that we need to be careful on touch devices:

> assuming that mobile devices follow suit as well when an external keyboard is used on them

I don't think it makes all that much sense for physical keyboard modifiers to reflect on the touch keyboard. The `shift` layer (if it even exists, see khmer_angkor for example!) does not completely match the physical keyboard's Shift modifier, etc. So I think it's just cleaner to avoid *any* cross-interactions between hardware modifiers and touch layers.

> How would they interfere with each other? The one thing I can think of where it could possibly matter: changing context while CAPS is active. But even then, we still return to the default layer if SHIFT is held while context is changed, so at least the current behavior would match.

The code as I had it was breaking this -- by setting `this.stateKeys['K_CAPS']` based on the active layer. Like you say, this should be maintained in the event properties. That's what this PR is trying to do.

**Comment by jahorton** [comment]
> I don't think it makes all that much sense for physical keyboard modifiers to reflect on the touch keyboard. The `shift` layer (if it even exists, see khmer_angkor for example!) does not completely match the physical keyboard's Shift modifier, etc. So I think it's just cleaner to avoid _any_ cross-interactions between hardware modifiers and touch layers.

I can see and understand your position here.  Just keep in mind that this would be a break from long-standing KMW behavior - this pattern has been in place since _at least_ version 10.0.  I'm positive this was already in place before #300.

**Comment by bharanidharanj** [comment]
## SUITE_CAPS_ON_TOUCH: - Test using the new sil_euro_latin keyboard with Caps Lock support

### GROUP_WEB_DEBUGGER: Perform tests in the Keyman Developer web debugger:

* **TEST_CAPS_LAYER (BLOCKED):** Got an error message while trying to open the browser using Keyman Developer 16.0.20. Not able to do further testing. 

 

* **TEST_CAPS_LAYER_RESET (BLOCKED):** Got an error message while trying to open the browser using Keyman Developer 16.0.20. Not able to do further testing.

**Comment by mcdurdin** [comment]
I've rebased this off the Developer refactor branch so that we can move forward on this without being impacted by all the changes on the refactor branch which has not yet undergone final review or testing.

I think the blocking issues in test were due to the previous base, so hopefully this test will work, apologies to @bharanidharanj!

@keymanapp-test-bot retest

**Comment by mcdurdin** [comment]
> I can see and understand your position here. Just keep in mind that this would be a break from long-standing KMW behavior - this pattern has been in place since _at least_ version 10.0. I'm positive this was already in place before #300.

Yes, I think the touch layout design just inherited this flawed behaviour from KMW 1.0, probably before we had a really good understanding of the interactions between touch and hardware keyboards. I don't think it works well so I think we should change this.

**Comment by mcdurdin** [comment]
@jahorton wrote:
> In particular, we need to test against a keyboard with [CAPS] and [NCAPS]-based rules, not just a touch keyboard that happens to utilize a caps layer. It does seem that the "Obolo Chwerty" keyboard has such rules, at least. We'd need some tests against a few different use cases.
> 
> The most important edge-like case to be sure we have covered: typing with the OSK when the hardware keyboard's CAPS key is enabled.

Tests added.

I've tried to add tests that match what you are asking for. If there are any others you think important, can you draft a test requirement?


* SUITE_CAPS_ON_TOUCH
  * GROUP_IPHONE
    * **TEST_CAPS_ON_HARDWARE (SKIPPED):** Hardware keyboard not supported on iOS

**Comment by jahorton** [comment]
> I've rebased this off the Developer refactor branch so that we can move forward on this without being impacted by all the changes on the refactor branch which has not yet undergone final review or testing.
> 
> I think the blocking issues in test were due to the previous base, so hopefully this test will work, apologies to @bharanidharanj!
> 
> @keymanapp-test-bot retest

Uh... won't that have a rather drastic effect on our ability to cherry-pick the PR once we're done?  I assume we do plan to have a 🍒 for stable-15.0, right?

**Comment by mcdurdin** [comment]
By 'rebased off' I mean, 'rebased away from' -- sorry for ambiguity. It's based on `master` now. Easy to cherry-pick (I hope!)

Mind you, the changes are simple so should be easy to hand pick if necessary.

**Review by jahorton — APPROVED** [review]

**Comment by mcdurdin** [comment]
The rebase story here has been painful and messy. I have now rebased back onto the 🎢 branch as it turns out the fix in #6860 is required in order to test this in Keyman Developer Server. Still just the one commit here for review.

**Comment by MakaraSok** [comment]
@mcdurdin 
The same error like that of what Bharani has seen is seen when "Open in browser" after successfully building the keyboard.

Should I do the trick on `dist` provided in Slack earlier today and proceed with testing?

**Comment by mcdurdin** [comment]
Yes please.

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_CAPS_ON_TOUCH: - Test using the new sil_euro_latin keyboard with Caps Lock support

### GROUP_WEB_DEBUGGER: Perform tests in the Keyman Developer web debugger:

* **TEST_CAPS_LAYER (PASSED):** CAPS was successfully activated, all keys generate capital letters including subkeys. The keyboard doesn't drop back to default layer. All is well.
* **TEST_CAPS_LAYER_RESET (PASSED):** Click on the Shift key switches to the default layer and all keys output small letter including the subkeys.
* **TEST_CAPS_ON_HARDWARE (PASSED):** The Caps Lock on the hardware keyboard doesn't affect the touch keyboard. With Caps Lock on triggered from the hardware keyboard, typing on the touch keyboard output small cap.

### GROUP_IPHONE: Perform these tests in the iPhone simulator, in-app or system keyboard, after installing the compiled sil_euro_latin.kmp from the above link.

* **TEST_CAPS_LAYER (FAILED):** `caps` layer doesn't get activated when double tapping on the Shift key.

https://user-images.githubusercontent.com/28331388/176632805-70c1e2c0-67f9-4452-8518-2c4ea92a09f6.mov


* **TEST_CAPS_LAYER_RESET (BLOCKED):** The `caps` layer doesn't get enabled in the first place, hence not able to test this as a result.

### GROUP_ANDROID: Perform these tests in the Android emulator, in-app or system keyboard, after installing the compiled sil_euro_latin.kmp from the above link.

* **TEST_CAPS_LAYER (FAILED):** Double tapping on the Shift key doesn't enable `caps` layer.

https://user-images.githubusercontent.com/28331388/176634599-7bc75bca-44f0-4708-9390-7cc3c7ebde5d.mov


* **TEST_CAPS_LAYER_RESET (BLOCKED):** `caps` layer doesn't get activated, hence this test can't be run.
* **TEST_CAPS_ON_HARDWARE (PASSED):** The Caps Lock on the hardware keyboard doesn't affect the touch keyboard. With Caps Lock on triggered from the hardware keyboard, typing on the touch keyboard output small cap.

## SUITE_DESKTOP: 

### GROUP_BASIC_KBDUS: Add the `basic_kbdus` keyboard in the "Add a keyboard by keyboard name" box, then select English - US Basic from keyboard menu.

* **TEST_PHYSICAL_CAPS (PASSED):** The Caps Lock key doesn't affect the output triggered on the OSK, and the OSK itself doesn't show characters in capital letters as indicated. All is well.

* **TEST_OSK_CAPS (PASSED):** All work as indicated.
* **TEST_OSK_CAPS_INTERACTIONS (PASSED):** All work as indicated.

### GROUP_OBOLO_CHWERTY: Use the `obolo_chwerty_6351` keyboard that is in the keyboard menu. Ensure that you press the Q (ch/Ch/CH key) in the tests to confirm the Caps vs NCaps vs Shift state.

* **TEST_PHYSICAL_CAPS (PASSED):** All work as indicated. 
* **TEST_OSK_CAPS (PASSED):** All work as indicated.
* **TEST_OSK_CAPS_INTERACTIONS (PASSED):** All work as indicated.

**Comment by bharanidharanj** [comment]
## SUITE_CAPS_ON_TOUCH: - Test using the new sil_euro_latin keyboard with Caps Lock support

### GROUP_IPHONE: Perform these tests in the iPhone simulator, in-app or system keyboard, after installing the compiled sil_euro_latin.kmp from the above link.

* **TEST_CAPS_LAYER (PASSED):** Tested this as per the instructions in iOS 14.4 / iPhone 12 Simulator and it is working as expected. However, I noticed that the Caps layer is already activated after installing the sil_euro_latin Keyboard. 
* **TEST_CAPS_LAYER_RESET (PASSED):** Tested this as per the instructions in iOS 14.4 / iPhone 12 Simulator and it is working as expected.

**Comment by mcdurdin** [comment]
Thank you for the tests @bharanidharanj!

> * However, I noticed that the Caps layer is already activated after installing the sil_euro_latin Keyboard.

This is correct and by design -- it's treated as the start of a sentence so the Shift layer (not quite the Caps layer) will be activated for the first letter.

**Comment by jahorton** [comment]
So... I find it interesting that the 🍒 got merged before the real deal.

And, unfortunately... we've got live Sentry error reports coming in from this.  Like, a considerable amount:

https://sentry.io/share/issue/f9a9f864dad84b1ba48291a13f403a7b/

**Review by jahorton — CHANGES_REQUESTED** [review]
Please see my most recent comments; this PR, as is, will cause a bug to surface.

**Comment by mcdurdin** [comment]
Going ahead and merging this. Don't see any point in delaying any further; already merged in the PR which fixed @jahorton's requested change.

**Pull request merged**
