### PR TITLE
fix(windows): Enter and Spacebar handling in Configuration

### LINKED ISSUE #4183: bug(windows): enter and esc actions cause diag dialog in kmshell
**Describe the bug**

If you press <kbd>Enter</kbd> or <kbd>Esc</kbd> in Keyman Configuration, it triggers `keyman:footer_ok` or `keyman:footer_cancel` respectively. These actions are no longer relevant and show a diagnostic dialog.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 20H2 x64 
 - Keyman version: 14.0.210-alpha

### LINKED ISSUE #4186: bug(windows): enter or spacebar in km config can cause error
Sentry Issue: [KEYMAN-WINDOWS-6Y](https://sentry.keyman.com/organizations/keyman/issues/2305/?referrer=github_integration)

I think this arose when I pressed Enter or Spacebar when no keyboard was highlighted?

```
TypeError: Cannot read property 'checked' of null
  at keyboard_checkclick (/app/config.js:298:29)
  at HTMLDocument.menuframe_keydown (/app/menu-frame.js:111:19)
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4186.
Fixes #4183.
Fixes [KEYMAN-WINDOWS-7X](https://sentry.keyman.com/organizations/keyman/issues/2802/?referrer=github_integration).
Fixes [KEYMAN-WINDOWS-6Y](https://sentry.keyman.com/organizations/keyman/issues/2305/?referrer=github_integration).

The Enter and Spacebar key handlers had not been updated for the new layout and so threw errors in use.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.233-beta](https://keyman.com/downloads/releases/beta/14.0.233)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)

**Pull request merged**
