### PR TITLE
fix(developer): publish developer-utils package during build

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes: #12426

@keymanapp-test-bot skip

### CODE REVIEW

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
Glad it was easy

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.118-alpha](https://keyman.com/downloads/releases/alpha/18.0.118)

**Comment by srl295** [comment]
@mcdurdin does this need a release note? that `@keymanapp/kmc@alpha` is no longer broken?

**Comment by srl295** [comment]
```
fixed!

$ docker run --rm -it node npx '@keymanapp/kmc@18.0.117-alpha'
Need to install the following packages:
@keymanapp/kmc@18.0.117-alpha
Ok to proceed? (y) 

npm error code ETARGET
npm error notarget No matching version found for @keymanapp/developer-utils@18.0.117-alpha.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-09-27T04_28_39_808Z-debug-0.log
(1) Ísrl295@abeja:~/src/keyman ⬡ null [git⫢master]
$ docker run --rm -it node npx -y '@keymanapp/kmc@18.0.118-alpha'
Usage: kmc [options] [command]

Keyman Developer Command Line Interface

Options:
  -V, --version                    output the version number
  --no-error-reporting             Disable error reporting to keyman.com (overriding user settings)
  --error-reporting                Enable error reporting to keyman.com (overriding user settings)
  -h, --help                       display help for command

Commands:
  build [options]
  analyze
  message [options] [messages...]  Describe one or more compiler messages. Note: Markdown format is always written to files on disk.
  help [command]                   display help for command
```

**Comment by mcdurdin** [comment]
No release note needed for alpha -- it is expected to be broken. We still have the history.md with every PR

**Pull request merged**
