### PR TITLE
docs(android): Update installing-keyboards.md

### PR DESCRIPTION
**Pull request by bravogeorge**
Went off directions from @jahorton From step 5 I rewrote the sentence after "once the download is complete..." to make the wording less awkward and instructions more concrete. then "A" I rewrote to make it less jarring and more clearer transition to "B". Part "C" was rewritten with the same intention. Less jarring and more clarity.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by mcdurdin — APPROVED** [review]
Looks good to me (LGTM). Thank you for your contribution!

**Comment by mcdurdin** [comment]
@darcywong00 do we want to cherry-pick this to stable-14.0?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.27-alpha](https://keyman.com/downloads/releases/alpha/15.0.27)

**Pull request merged**
