### PR TITLE
chore(common): Update crowdin strings for Amharic 📜

### PR DESCRIPTION
**Pull request by darcywong00**
This adds Amharic localization for macOS.

Also updates Amharic strings for Android and iOS.

## User Testing
Only testing macOS platform, since other platforms are just updating strings

* **TEST_MAC** - Tests Amharic localization on Keyman for macOS
1. Load the macOS PR build
2. Set the system language to Amharic
3. Launch Keyman for macOS
4. Verify strings are in Amharic.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by MakaraSok** [comment]
* **TEST_MAC: FAILED** It can't be switch to Amharic, but Khmer does work though.

Catalina: the language doesn't switch to Amharic, even after a restart.
image

When the language is set to "Khmer," the UI language for Keyman does switch to Khmer though.
image


Big Sur: the language doesn't switch to Amharic, even after a restart.
image

Monterey: the same behaviors.

**Comment by darcywong00** [comment]
@sgschantz - Does the macOS project also need to be run through XCode to add the Amharic locale?

**Comment by sgschantz** [comment]
Yes, I need to specify it as a supported localization in the project, just like we need to do for iOS.

**Comment by darcywong00** [comment]
@keymanapp-test-bot retest TEST_MAC

**Comment by sgschantz** [comment]
>

**Comment by MakaraSok** [comment]
- **TEST_MAC: PASSED** but some strings are still in English. See the screenshot below.

The UI does switch to the language, but all strings in the keyboard info page stay in English.

Catalina
image

BigSur
image

**Comment by sgschantz** [comment]
@MakaraSok When I did the internationalization for the Mac, I missed all the strings in this view because it is a webview, and I didn't notice the labels coded in HTML. So these must still appear in English for the Khmer localization, too. 

I'm not sure how I missed that -- I might have assumed they had a different source like the help pages. I'll need to externalize the keyboard info strings so they can be localized.

**Comment by MakaraSok** [comment]
@sgschantz Let me know when/if this needs to be retested.

**Comment by sgschantz** [comment]
I think we need a new issue to track this because it is not related to language. You should see the same results for Khmer. After adding i18n support for this window, then we can go back and get the corresponding Amharic strings from crowdin.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.173-alpha](https://keyman.com/downloads/releases/alpha/15.0.173)

**Pull request merged**
