### PR TITLE
chore(common): Add crowdin for Swedish

### PR DESCRIPTION
**Pull request by darcywong00**
Adds crowdin strings for Swedish for locale sv-SE
Using localized name `svenska` from https://github.com/unicode-org/cldr/blob/a88558301989b98d5bedb13e9123ec6d12f82416/common/main/sv.xml#L577

## User Testing
This adds the crowdin strings for Swedish locale sv-SE

TODO for @sgschantz 
- [x] Run XCode for iOS
- [x] Run XCode for macOS

## User Testing
Load the PR build for each platform and set the UI / Locale to "svenska" (Swedish)

* **TEST_ANDROID** 
1. Load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display Language --> svenska (Swedish)
3. Return to the Keyman app 
4. Verify the UI is in Swedish (prompt, Settings strings, etc.).

* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Swedish
3. Return to the Keyman app
4. Verify the UI is in  Swedish

* **TEST_LINUX**
1. Start Keyman configuration with: LANGUAGE=sv_SE km-config
2. Verify Keyman UI is in Swedish

* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the locale to Swedish
3. Verify the Keyman UI is in Swedish

* **TEST_WINDOWS**
1. Load the PR build of Keyman for Windows
2. Set the UI to svenska (Swedish)
3. Verify the Keyman UI is in Swedish

### CODE REVIEW

**Review by rc-swag — APPROVED** [review]
lgtm

**Review by jahorton — APPROVED** [review]
Huh, this one seems to have a slightly lower line count than the other crowdin PRs available at the moment.  Any idea why that is?  Looks like the same files are in place, at least...

**Comment by darcywong00** [comment]
Curious - most of these are 95% complete (including Swedish).

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ANDROID (PASSED):** Tested with the attached PR build (keyman 16.0.134-beta-test-8071) in Android 12 / API 31 emulator and I am able to use the Swedish UI as the Keyman UI language.

**Comment by bharanidharanj** [comment]
* **TEST_IOS (FAILED):** Tested with the attached PR build (keyman 16.0.134-beta-test-8071) in iPhone 12 Pro Max Simulator (iOS 15.0) and I noticed that the the Keyman crashes If I try to open the Keyman App. #8108

**Comment by bharanidharanj** [comment]
* **TEST_LINUX (PASSED):** Tested with the attached PR build (6.0.134-beta (package version 16.0.134-1~PR-8071+focal6) in Ubuntu 20.04 focal Linux OS (VM) I am able to use the Swedish UI as the Keyman UI language in Keyman Configuration. 

..Swedish UI 1:

   


..Swedish UI 2:

**Comment by bharanidharanj** [comment]
* **TEST_WINDOWS (PASSED):** Tested with the attached PR build (16.0.134-beta-test-8071) in Windows 11 OS (VM) and I am able to use the Swedish UI as the Keyman UI language. 

..Swedish UI 1:

   


..Swedish UI 2:

   


..Swedish UI 3:

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_MACOS (PASSED):** Tested with the attached PR build and it is working as expected. 

..Swedish UI1:

   

..Swedish UI2:

   


..Swedish UI3:

**Comment by darcywong00** [comment]
@sgschantz are you able to run the iOS build locally? Are the build agents updated for Xcode?

**Comment by sgschantz** [comment]
> @sgschantz are you able to run the iOS build locally? Are the build agents updated for Xcode?

I tested the Swedish localization in the simulator before committing the code. The plan is to update the build agents to Xcode 14.2 later. Everything should still be running with 13.4 now.

**Comment by sgschantz** [comment]
I will check this again locally for iOS and use a similar device and os version to @bharanidharanj .

**Comment by mcdurdin** [comment]
iOS test failure is in #8118.

**Comment by darcywong00** [comment]
> iOS test failure is in #8118.

I manually triggered a new iOS test build which should pull in the fixed sil_euro_latin.kmp.

@keymanapp-test-bot retest TEST_IOS

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS (FAILED):** Retested with the attached PR build in iOS 15.0 /  iPhone 12 Pro Max Simulator and I was able to reproduce the following crash.

**Comment by mcdurdin** [comment]
I manually triggered a new iOS test build which should pull in the fixed sil_euro_latin.kmp 2.0.3.

@keymanapp-test-bot retest TEST_IOS

**Comment by MakaraSok** [comment]
# Test Results

* **TEST_IOS (FAILED):** Everything seems to be shown in Swedish except two words: (1) Done and (2) Keyboard. PASSED this if they are intentional or system-related strings.

(1)
image

(2)
image

**Comment by mcdurdin** [comment]
TEST_IOS: PASSED -- assuming those two strings are among the 5%? that did not get translated.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.136-beta](https://keyman.com/downloads/releases/beta/16.0.136)

**Pull request merged**
