### PR TITLE
chore(ios/engine): dead code removal + deprecations

### PR DESCRIPTION
**Pull request by jahorton**
Time to retire some of the old installation infrastructure.

Actually, I wanted to retire even _more_ of it, but since there's no actual equivalent to `APIKeyboardRepository`, it doesn't feel right to straight-up obsolete the class; deprecation will have to do for now.

### CODE REVIEW

**Comment by jahorton** [comment]
My main worry there was that, on the off-chance that _someone_ was using it directly, there is no replacement for it.

I can totally nix it if you think it's fine, though.

**Comment by mcdurdin** [comment]
I think nix it. It keeps a long term dependency on a completely deprecated model of handling keyboards ... we want app developers moving to 14.0 to be thinking only about packages 😄 . Unless I am misunderstanding what `APIKeyboardRepository` is all about?

**Comment by jahorton** [comment]
> I think nix it. It keeps a long term dependency on a completely deprecated model of handling keyboards ... we want app developers moving to 14.0 to be thinking only about packages 😄 . Unless I am misunderstanding what `APIKeyboardRepository` is all about?

True, `APIKeyboardRepository` is designed for JS resources, so forcing devs to "move to 14.0" would be wise.

----

The one thing of note:  KeymanEngine currently has no "keyboard query" of any sort.  Keyboard search exists, but requires user interaction.  There's no reasonable way for a framework user to try automating it.

_If_ someone wanted to perform a keyboard query without user interaction, the info provided by `APIKeyboardRepository` is sufficient to act as a "pseudo-query" of sorts in a pinch.  Definitely not its original purpose, of course; this relies on the fact that keyboards are distributed in packages with matching IDs.

If we already had `Queries.Keyboards` as a Swift endpoint for https://help.keyman.com/developer/cloud/search/1.0/, we wouldn't be having this conversation.  But it's not implemented yet, and it isn't really on our roadmap so far as I can tell.

I suppose I could include that URL in the obsoletion message?  It may not be implemented in Swift, but at least that'd give developers a way forward.

**Comment by mcdurdin** [comment]
There's nothing to stop framework users accessing the cloud endpoints via REST themselves, of course.

Given `APIKeyboardRepository` references the legacy endpoints, offering it is actually worse than not offering it -- it will give results inconsistent with the new package endpoints which would lead to weird edge cases etc.

I think we need to have a focused design discussion on REST API wrappers before we attempt to provide consistent access to the REST endpoints via Keyman Engine. This would need to be done for iOS, Android, Windows, Linux, macOS and possibly even web. It's not a small job and I don't think it adds a lot of value to add it just to iOS, just for search. I am placing a low priority on this.

**Pull request merged**
