### PR TITLE
feat(developer): turn on developer side normalization 🙀

### PR DESCRIPTION
**Pull request by srl295**
- turn on normalization on the developer side
- add tests
- also, change this.X to Class.X for statics

For: #10317

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by srl295** [comment]
remaining basic.txt issue..

**Review by mcdurdin — APPROVED** [review]
LGTM

Does this handle the settings normalization=goawayanddontmesswithmycodepoints flag?

**Comment by srl295** [comment]
> LGTM
> 
> Does this handle the settings normalization=goawayanddontmesswithmycodepoints flag?

nope that's TODO as discussed-

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.256-alpha](https://keyman.com/downloads/releases/alpha/17.0.256)

**Pull request merged**
